export const DESKTOP_SEARCH_MESSAGE_IDS = [
    "search.asset.file_match",
    "search.asset.metadata_match",
    "search.failed",
    "search.group.assets",
    "search.group.current_global",
    "search.group.current_project",
    "search.group.navigation",
    "search.group.other",
    "search.group.projects",
    "search.input_label",
    "search.keyboard_hint",
    "search.loading",
    "search.current_failed",
    "search.current_limited",
    "search.match.display_description",
    "search.match.display_name",
    "search.match.kind",
    "search.match.scope_path",
    "search.match.type_metadata",
    "search.navigation.global",
    "search.navigation.global_detail",
    "search.navigation.projects",
    "search.navigation.projects_detail",
    "search.navigation.settings",
    "search.navigation.settings_detail",
    "search.no_results",
    "search.open",
    "search.partial",
    "search.placeholder",
    "search.project.retained",
    "search.title",
] as const;

export type DesktopSearchMessageId = (typeof DESKTOP_SEARCH_MESSAGE_IDS)[number];
type DesktopSearchMessages = Readonly<Record<DesktopSearchMessageId, string>>;

export const ENGLISH_DESKTOP_SEARCH_MESSAGES = {
    "search.asset.file_match": "{kind} · matched file {path}",
    "search.asset.metadata_match": "{kind} · matched {field}",
    "search.failed": "Search could not be completed. Try again.",
    "search.group.assets": "Assets",
    "search.group.current_global": "Current Global assets",
    "search.group.current_project": "Current Project",
    "search.group.navigation": "Go to",
    "search.group.other": "Other results",
    "search.group.projects": "Projects",
    "search.input_label": "Search OAAM",
    "search.keyboard_hint": "Use ↑ and ↓ to move, Enter to open, and Esc to close.",
    "search.loading": "Searching the current catalog…",
    "search.current_failed": "Current-page results could not be loaded. Other results are still available.",
    "search.current_limited": "Showing the first {count} matches in the current view.",
    "search.match.display_description": "description",
    "search.match.display_name": "name",
    "search.match.kind": "Asset kind",
    "search.match.scope_path": "scope path",
    "search.match.type_metadata": "type metadata",
    "search.navigation.global": "Global library",
    "search.navigation.global_detail": "Browse Assets that are not owned by one Project.",
    "search.navigation.projects": "Projects",
    "search.navigation.projects_detail": "Browse and manage registered Projects.",
    "search.navigation.settings": "Settings",
    "search.navigation.settings_detail": "Open OAAM preferences and maintenance.",
    "search.no_results": "No current Project, Asset, or destination matches this search.",
    "search.open": "Search OAAM",
    "search.partial": "Some catalog sources were unavailable. Results below are incomplete.",
    "search.placeholder": "Search Projects, Assets, and destinations",
    "search.project.retained": "Retained Project · {path}",
    "search.title": "Search OAAM",
} as const satisfies DesktopSearchMessages;

export const GERMAN_DESKTOP_SEARCH_MESSAGES = {
    "search.asset.file_match": "{kind} · passende Datei {path}",
    "search.asset.metadata_match": "{kind} · Treffer in {field}",
    "search.failed": "Die Suche konnte nicht abgeschlossen werden. Versuchen Sie es erneut.",
    "search.group.assets": "Assets",
    "search.group.current_global": "Aktuelle globale Assets",
    "search.group.current_project": "Aktuelles Projekt",
    "search.group.navigation": "Öffnen",
    "search.group.other": "Weitere Ergebnisse",
    "search.group.projects": "Projekte",
    "search.input_label": "OAAM durchsuchen",
    "search.keyboard_hint": "Mit ↑ und ↓ bewegen, mit Eingabetaste öffnen und mit Esc schließen.",
    "search.loading": "Der aktuelle Katalog wird durchsucht…",
    "search.current_failed":
        "Ergebnisse der aktuellen Ansicht konnten nicht geladen werden. Weitere Ergebnisse sind weiterhin verfügbar.",
    "search.current_limited": "Die ersten {count} Treffer der aktuellen Ansicht werden angezeigt.",
    "search.match.display_description": "Beschreibung",
    "search.match.display_name": "Name",
    "search.match.kind": "Asset-Typ",
    "search.match.scope_path": "Bereichspfad",
    "search.match.type_metadata": "Typmetadaten",
    "search.navigation.global": "Globale Bibliothek",
    "search.navigation.global_detail": "Assets durchsuchen, die keinem einzelnen Projekt gehören.",
    "search.navigation.projects": "Projekte",
    "search.navigation.projects_detail": "Registrierte Projekte durchsuchen und verwalten.",
    "search.navigation.settings": "Einstellungen",
    "search.navigation.settings_detail": "OAAM-Einstellungen und Wartung öffnen.",
    "search.no_results": "Kein aktuelles Projekt, Asset oder Ziel entspricht dieser Suche.",
    "search.open": "OAAM durchsuchen",
    "search.partial": "Einige Katalogquellen waren nicht verfügbar. Die Ergebnisse sind unvollständig.",
    "search.placeholder": "Projekte, Assets und Ziele durchsuchen",
    "search.project.retained": "Beibehaltenes Projekt · {path}",
    "search.title": "OAAM durchsuchen",
} as const satisfies DesktopSearchMessages;

export const JAPANESE_DESKTOP_SEARCH_MESSAGES = {
    "search.asset.file_match": "{kind} · 一致したファイル {path}",
    "search.asset.metadata_match": "{kind} · {field} に一致",
    "search.failed": "検索を完了できませんでした。もう一度お試しください。",
    "search.group.assets": "Assets",
    "search.group.current_global": "現在のグローバルアセット",
    "search.group.current_project": "現在のプロジェクト",
    "search.group.navigation": "移動先",
    "search.group.other": "その他の結果",
    "search.group.projects": "Projects",
    "search.input_label": "OAAM を検索",
    "search.keyboard_hint": "↑ と ↓ で移動し、Enter で開き、Esc で閉じます。",
    "search.loading": "現在のカタログを検索しています…",
    "search.current_failed": "現在の画面の結果を読み込めませんでした。その他の結果は引き続き利用できます。",
    "search.current_limited": "現在の画面の最初の {count} 件を表示しています。",
    "search.match.display_description": "説明",
    "search.match.display_name": "名前",
    "search.match.kind": "Asset 種類",
    "search.match.scope_path": "スコープパス",
    "search.match.type_metadata": "種類メタデータ",
    "search.navigation.global": "Global ライブラリ",
    "search.navigation.global_detail": "1 つの Project に属さない Asset を参照します。",
    "search.navigation.projects": "Projects",
    "search.navigation.projects_detail": "登録済み Project を参照して管理します。",
    "search.navigation.settings": "設定",
    "search.navigation.settings_detail": "OAAM の設定とメンテナンスを開きます。",
    "search.no_results": "現在の Project、Asset、移動先に一致するものはありません。",
    "search.open": "OAAM を検索",
    "search.partial": "一部のカタログソースが利用できません。結果は不完全です。",
    "search.placeholder": "Project、Asset、移動先を検索",
    "search.project.retained": "保持された Project · {path}",
    "search.title": "OAAM を検索",
} as const satisfies DesktopSearchMessages;

export const SIMPLIFIED_CHINESE_DESKTOP_SEARCH_MESSAGES = {
    "search.asset.file_match": "{kind} · 匹配文件 {path}",
    "search.asset.metadata_match": "{kind} · 匹配{field}",
    "search.failed": "无法完成搜索，请重试。",
    "search.group.assets": "资产",
    "search.group.current_global": "当前全局资产",
    "search.group.current_project": "当前项目",
    "search.group.navigation": "前往",
    "search.group.other": "其他结果",
    "search.group.projects": "项目",
    "search.input_label": "搜索 OAAM",
    "search.keyboard_hint": "使用 ↑ 和 ↓ 移动，按 Enter 打开，按 Esc 关闭。",
    "search.loading": "正在搜索当前资产库…",
    "search.current_failed": "无法读取当前页面的结果，仍可查看其他结果。",
    "search.current_limited": "当前页面只显示前 {count} 个匹配项。",
    "search.match.display_description": "描述",
    "search.match.display_name": "名称",
    "search.match.kind": "资产类型",
    "search.match.scope_path": "归属路径",
    "search.match.type_metadata": "类型元数据",
    "search.navigation.global": "全局资产库",
    "search.navigation.global_detail": "浏览可供多个项目使用的资产。",
    "search.navigation.projects": "项目",
    "search.navigation.projects_detail": "浏览和管理已添加的项目。",
    "search.navigation.settings": "设置",
    "search.navigation.settings_detail": "打开 OAAM 偏好设置与维护功能。",
    "search.no_results": "当前项目、资产和页面中没有匹配项。",
    "search.open": "搜索 OAAM",
    "search.partial": "部分资产库来源不可用，以下结果并不完整。",
    "search.placeholder": "搜索项目、资产和页面",
    "search.project.retained": "已保留的项目 · {path}",
    "search.title": "搜索 OAAM",
} as const satisfies DesktopSearchMessages;
