// Complete Desktop locale catalog; exact type and runtime tests defend key and placeholder parity.

import { JAPANESE_DESKTOP_ASSET_ACTION_MESSAGES } from "./catalog-asset-actions";
import { JAPANESE_DESKTOP_ASSET_INSPECTOR_MESSAGES } from "./catalog-asset-inspector";
import { JAPANESE_DESKTOP_ASSET_AUTHORIZATION_MESSAGES } from "./catalog-asset-authorizations";
import { JAPANESE_DESKTOP_DEPLOYMENT_PRODUCT_LANGUAGE_MESSAGES } from "./catalog-deployment-product-language";
import { JAPANESE_DESKTOP_DIAGNOSTICS_MESSAGES } from "./catalog-diagnostics";
import { JAPANESE_DESKTOP_DIRECTORY_PREVIEW_MESSAGES } from "./catalog-directory-preview";
import { JAPANESE_DESKTOP_DISCOVERY_RESULT_MESSAGES } from "./catalog-discovery-results";
import type { DesktopMessageId } from "./catalog-en";
import { JAPANESE_DESKTOP_GUIDED_IMPORT_MESSAGES } from "./catalog-guided-import";
import { JAPANESE_DESKTOP_IMPORT_PREVIEW_MESSAGES } from "./catalog-import-preview";
import { JAPANESE_DESKTOP_LIBRARY_SOURCE_MESSAGES } from "./catalog-library-sources";
import { JAPANESE_DESKTOP_MAINTENANCE_MESSAGES } from "./catalog-maintenance";
import { JAPANESE_DESKTOP_PRESENTATION_MESSAGES } from "./catalog-presentation";
import { JAPANESE_DESKTOP_PROJECT_LIFECYCLE_MESSAGES } from "./catalog-project-lifecycle";
import { JAPANESE_DESKTOP_SEARCH_MESSAGES } from "./catalog-search";

export const JAPANESE_DESKTOP_MESSAGES = {
    "app.brand.subtitle": "エージェントアセットマネージャー",
    "app.client_unavailable.eyebrow": "クライアントが使用不可",
    "app.client_unavailable.message": "OAAM は起動しましたが、ローカルワークスペースに接続できません。",
    "app.client_unavailable.title": "OAAM はローカル ワークスペースを開けませんでした。",
    "app.failed.eyebrow": "OAAM を利用できません",
    "app.failed.reason": "失敗コード:",
    "app.failed.title": "OAAM の起動を完了できませんでした。",
    "app.host.running": "実行中",
    "app.navigation.catalog": "カタログ化と導入",
    "app.navigation.import": "インポートレビュー",
    "app.navigation.label": "ワークスペースのナビゲーション",
    "app.navigation.overview": "概要",
    "app.navigation.sources": "情報源",
    "app.navigation.workspace": "ワークスペース",
    "app.ready": "準備完了",
    "app.reconnecting.title": "OAAM を再接続しています",
    "app.saved_assets.many": "{count} 保存されたアセット",
    "app.saved_assets.one": "{count} 保存されたアセット",
    "app.starting.eyebrow": "Open Agent Asset Manager",
    "app.starting.title": "OAAM を起動中",
    "app.toolbar.assets": "エージェント資産",
    "app.toolbar.workspace": "ローカルワークスペース",
    "app.workspace.label": "OAAMワークスペース",
    "common.cancel": "キャンセル",
    "common.close": "閉じる",
    "common.retry": "再試行",
    "common.save": "保存",
    "discovery.complete_with_warnings": "スキャンは完了しましたが、確認できなかった場所があります。",
    "discovery.enable_provider_first": "スキャンする前に、利用可能な AI コーディングツールを 1 つ以上選択してください。",
    "discovery.interrupted": "スキャンが中断されました。現在の結果を取得するには、もう一度実行してください。",
    "discovery.loading": "スキャンの選択内容を読み込んでいます…",
    "discovery.loading_failed": "OAAM はスキャンの選択内容を読み込めませんでした。",
    "discovery.no_environment": "スキャンする前に、利用可能な場所を 1 つ以上選択してください。",
    "discovery.provider.save_failed": "ツールの選択内容を保存できませんでした。更新してから再試行してください。",
    "discovery.provider.saved": "ツールの選択内容を保存しました。現在のローカル Asset を確認するには再スキャンしてください。",
    "discovery.provider.saving": "ツールの選択内容を保存しています…",
    "discovery.scanning": "選択したツールと場所をスキャンしています…",
    "discovery.settings_unavailable": "スキャンの選択内容を利用できません。",
    "discovery.snapshot_refreshed": "スキャン結果は最新です。",
    "discovery.snapshot_untrustworthy": "信頼できる結果を得る前にスキャンが終了しました。",
    "discovery.ui.copy":
        "無効化されたプロバイダーは表示されますが、明示的な選択を保存するまでプローブ、読み取り、レンダリング、または検査することはできません。",
    "discovery.ui.discovery_copy":
        "利用可能な場所 {environments} 件 · 保存済みの場所選択 {watched} 件。スキャンだけでファイルがインポートされることはありません。",
    "discovery.ui.discovery_copy_one_environment":
        "利用可能な場所 {environments} 件 · 保存済みの場所選択 {watched} 件。スキャンだけでファイルがインポートされることはありません。",
    "discovery.ui.discovery_copy_one_source":
        "利用可能な場所 {environments} 件 · 保存済みの場所選択 {watched} 件。スキャンだけでファイルがインポートされることはありません。",
    "discovery.ui.discovery_copy_one_each":
        "利用可能な場所 {environments} 件 · 保存済みの場所選択 {watched} 件。スキャンだけでファイルがインポートされることはありません。",
    "discovery.ui.eyebrow": "ローカル Asset スキャン",
    "discovery.ui.environment.current_process": "続行するまで、このコンピューターはスキャンされません。",
    "discovery.ui.environment.legend": "スキャンする場所",
    "discovery.ui.environment.windows_default": "この Windows コンピューターは既定で選択されています。",
    "discovery.ui.environment.wsl_opt_in":
        "この WSL ディストリビューションにも agent Asset を保存している場合だけ選択してください。",
    ...JAPANESE_DESKTOP_DISCOVERY_RESULT_MESSAGES,
    ...JAPANESE_DESKTOP_GUIDED_IMPORT_MESSAGES,
    ...JAPANESE_DESKTOP_IMPORT_PREVIEW_MESSAGES,
    ...JAPANESE_DESKTOP_ASSET_ACTION_MESSAGES,
    ...JAPANESE_DESKTOP_ASSET_INSPECTOR_MESSAGES,
    ...JAPANESE_DESKTOP_ASSET_AUTHORIZATION_MESSAGES,
    ...JAPANESE_DESKTOP_DEPLOYMENT_PRODUCT_LANGUAGE_MESSAGES,
    "discovery.ui.environment_result_providers": "プロバイダー: {providers}",
    "discovery.ui.environment_results": "場所ごとのスキャン結果",
    "discovery.ui.loading_providers": "AI コーディングツールを読み込んでいます",
    "discovery.ui.no_runtime_relationship": "エージェントとランタイムの関係は報告されていません",
    "discovery.ui.no_snapshot": "スキャン結果はまだありません。",
    "discovery.ui.no_sources": "選択したツールのローカル Asset 保存場所は見つかりませんでした。",
    "discovery.ui.unchecked_project_environment_reference":
        "{runtime} は {environment} 内のプロジェクトを参照しています。まだ確認されていません。{environment} を選択して確認を続けてください。",
    "discovery.ui.picker.choose_source_button": "このソースフォルダーを使用してください",
    "discovery.ui.picker.choose_source_title": "外部ソースフォルダーを選択してください",
    "discovery.ui.provider.copy":
        "無効化されたプロバイダーは表示されますが、明示的な選択を保存するまでプローブ、読み取り、レンダリング、または検査することはできません。",
    "discovery.ui.provider.disabled": "無効",
    "discovery.ui.provider.disabled_after_save": "保存後に無効化",
    "discovery.ui.provider.enabled": "有効",
    "discovery.ui.provider.enabled_after_save": "保存後に有効化",
    "discovery.ui.provider.entries.many": "{count} ランタイム エントリ",
    "discovery.ui.provider.entries.one": "{count} ランタイム エントリ",
    "discovery.ui.provider.eyebrow": "スキャン設定",
    "discovery.ui.provider.save": "プロバイダーアクセスを保存する",
    "discovery.ui.provider.saving": "保存中…",
    "discovery.ui.provider.title": "OAAM が実行できるアダプターを選択する",
    "discovery.ui.provider.unavailable": "以前に保存したこのツールは、現在の OAAM では利用できません。",
    "discovery.ui.probe_status.complete": "完了",
    "discovery.ui.probe_status.failed": "失敗しました",
    "discovery.ui.probe_status.partial": "部分的",
    "discovery.ui.refresh_settings": "選択内容を更新",
    "discovery.ui.review_sources": "選択した場所を確認",
    "discovery.ui.retry_discovery": "もう一度スキャン",
    "discovery.ui.run": "今すぐスキャン",
    "discovery.ui.save_and_run": "選択を保存してスキャン",
    "discovery.ui.save_before_scan": "スキャンを始める前に、更新したツールの選択内容を保存します。",
    "discovery.ui.scanning": "スキャン中…",
    "discovery.ui.select_import_source": "インポートレビュー用に {path} を選択してください",
    "discovery.ui.select_source": "{path} を選択します",
    "discovery.ui.source.eyebrow": "ローカル Asset",
    "discovery.ui.source.moved_from": "以前: {path}",
    "discovery.ui.source.title": "Asset の場所を検索して確認",
    "discovery.ui.status.current": "現在",
    "discovery.ui.status.missing": "行方不明",
    "discovery.ui.status.moved": "移転しました",
    "discovery.ui.status.new": "新しい",
    "discovery.ui.status.not_checked": "未チェック",
    "discovery.ui.warnings": "検出警告",
    "discovery.ui.watch.do_not_watch": "今後のスキャンには含めないでください",
    "discovery.ui.watch.global": "グローバルソースとして視聴",
    "discovery.ui.watch.label": "今後のスキャン",
    "discovery.ui.watch.project": "プロジェクトを監視します: {project}",
    "discovery.ui.watch.project_unavailable": "使用できないプロジェクト バインディングを保持します: {project}",
    "discovery.ui.watch.save": "今後のスキャンの選択を保存する",
    "discovery.ui.watch.saving": "今後のスキャンの選択を保存しています…",
    "discovery.ui.watch.source_label": "{path} の今後のスキャンの選択",
    "discovery.ui.watch.unavailable": "このソースには安定した監視 ID がありません。",
    "discovery.watch.saved": "場所の選択内容を保存しました。次回も実際のパスを再確認します。",
    "discovery.watch.save_failed": "場所の選択内容を保存できませんでした。スキャン結果を更新してから再試行してください。",
    "discovery.watch.saving": "場所の選択内容を保存しています…",
    "discovery.watch.selection_invalid": "場所の選択内容が古くなっています。最新のスキャン結果を確認してください。",
    "import.accepting": "選択した Asset をインポートしています…",
    "import.batch.complete": "インポートが完了しました。以下の各 Asset を確認してください。",
    "import.batch.failed": "選択した Asset をインポートできませんでした。",
    "import.batch.partial": "一部の Asset はインポートされ、一部はされませんでした。各結果を確認してください。",
    "import.cancel.failed": "この Asset 確認を閉じられませんでした。",
    "import.cancel.interrupted": "Asset 確認を閉じる処理が中断されました。",
    "import.cancelled": "Asset 確認を閉じました。再確認するにはソースをもう一度選択してください。",
    "import.cancelling": "Asset 確認を閉じています…",
    "import.choose_candidates": "保存する Asset を選択してください。確認するまでは何もインポートされません。",
    "import.choose_compatible_asset": "同じ種類の資産で、削除されていない現在の資産を選択します。",
    "import.choose_compatible_candidate": "この関連を満たせる別の選択済み Asset を選んでください。",
    "import.choose_existing_version": "互換性のあるアセットの種類を持つ現在の既存のバージョンを選択します。",
    "import.connection_ended": "OAAM がインポート結果を報告する前に接続が終了しました。再試行前にライブラリを更新してください。",
    "import.detail.interrupted": "ファイル詳細の読み込みが中断されました。",
    "import.detail.unavailable": "選択したファイル詳細は利用できません。",
    "import.idle": "戻ってソースを選択するか、インポートせずに続けます。",
    "import.interrupted": "信頼できる結果が得られる前に Asset 確認が中断されました。",
    "import.no_candidates": "選択したソースには確認できる Asset がありません。",
    "import.catalog.failed": "Asset ライブラリを読み込めませんでした。再試行してから変更の保存先を選択してください。",
    "import.preview.failed": "Asset 確認を準備できませんでした。",
    "import.previewing": "Asset 確認を準備しています…",
    "import.read.failed": "選択されたソースを読み取ることができませんでした。",
    "import.read.attention": "選択した場所の一部を確認する必要があります。",
    "import.reading": "選択したソースを読んでいます…",
    "import.ui.action.cancel": "Asset 確認を閉じる",
    "import.ui.action.cancelling": "キャンセル中…",
    "import.ui.action.import": "選択した Asset をインポート",
    "import.ui.action.importing": "インポート中…",
    "import.ui.binary_copy": "このバイナリファイルは表示しません。正確な種類、サイズ、ハッシュは技術詳細で確認できます。",
    "import.ui.binding.choose_exact": "関連する Asset を選択",
    "import.ui.binding.existing_versions": "ライブラリ内の Asset",
    "import.ui.binding.leave_unbound": "Asset を関連付けない",
    "import.ui.binding.optional": "{target} の任意の関連 Asset",
    "import.ui.binding.required": "{target} に必要な関連 Asset",
    "import.ui.binding.selected_candidates": "この確認で選択した Asset",
    "import.ui.binding.target_label": "{candidate} の関連 Asset：{target}",
    "import.ui.candidate.file_count.many": "{count} ファイル",
    "import.ui.candidate.file_count.one": "{count} ファイル",
    "import.ui.candidate.select": "{candidate} を選択",
    "import.ui.asset.scope.global": "グローバルライブラリ",
    "import.ui.asset.scope.project": "現在のプロジェクト",
    "import.ui.asset.status.blocked": "インポート不可",
    "import.ui.asset.status.duplicate": "対応する Asset があります",
    "import.ui.asset.status.incomplete": "まだインポートできません",
    "import.ui.asset.status.ready": "準備完了",
    "import.ui.asset.status.requires_refresh": "再スキャンが必要",
    "import.ui.asset.status.stale": "ソースが変更されました",
    "import.ui.asset.status.unknown": "ソース状態が不明",
    "import.ui.diagnostics.attribution": "Asset 確認",
    "onboarding.completion.eyebrow": "無事完了",
    "onboarding.completion.failed": "OAAM はオンボーディングの完了を保存できませんでした。何もデプロイされませんでした。",
    "onboarding.completion.finish_without_import": "インポートせずに終了する",
    "onboarding.completion.imported_copy":
        "選択した Asset は OAAM ライブラリに保存されました。AI コーディングツールのファイルは変更されていません。",
    "onboarding.completion.imported_title": "安全なインポートが完了しました",
    "onboarding.completion.open_workspace": "オープンなワークスペース",
    "onboarding.completion.safe_copy":
        "新しいスキャンの後、インポートせずに終了できます。スキャンや今後の確認場所の保存では、ファイルをデプロイしません。",
    "onboarding.completion.safe_title": "ソーススナップショットが正しく表示されたら終了します",
    "onboarding.completion.saving": "ワークスペースを開いています…",
    "onboarding.copy": "OAAM が確認する場所を選び、見つかった内容を確認して、保存する Asset を決めます。",
    "onboarding.eyebrow": "最初の実行",
    "onboarding.steps.label": "初回実行時の進捗状況",
    "onboarding.title": "AI コーディングツールのファイルを変更せずに OAAM を設定",
    "import.ui.copy": "必要に応じてファイルを確認し、OAAM に保存する Asset だけを選択してください。",
    "import.ui.dependencies_too_many": "この Asset は {count} 個の関連 Asset を参照しており、ここでは安全に確認できません。",
    "import.ui.destination.add_version": "{asset} リビジョン {revision} の後にバージョンを追加",
    "import.ui.destination.create_asset": "新しいOAAMアセットを作成する",
    "import.ui.destination.label": "{candidate} の保存方法",
    "import.ui.destination.save_as": "名前を付けて保存",
    "import.ui.detail.binary_label": "確認したファイルの詳細",
    "import.ui.detail.first_file": "最初のファイル",
    "import.ui.detail.loading": "ファイル詳細を読み込んでいます…",
    "import.ui.detail.text_truncated": "このテキストは切り詰められています。ハッシュはファイル全体をカバーします。",
    "import.ui.detail.view": "{path} を表示する",
    "import.ui.detail.view_first": "最初のファイルを表示する",
    "import.ui.eyebrow": "インポートレビュー",
    "import.ui.failed.refresh_title": "新たな発見が必要",
    "import.ui.failed.title": "インポートレビューは利用できません",
    "import.ui.files_omitted": "この Asset にはほかのファイルもあります。必要に応じて利用可能なファイルを確認してください。",
    "import.ui.no_candidates": "選択したソースにはインポートできる Asset がありません。",
    "import.ui.no_preview": "確認する Asset が選択されていません",
    "import.ui.preparing": "Asset 確認を準備中",
    "import.ui.reading": "選択したソースを読む",
    "import.ui.read_attention.action_copy":
        "詳細を確認してから再試行してください。ソースの場所を変更するには、場所の選択に戻ってください。",
    "import.ui.read_attention.continue": "読み取れた場所だけで続行",
    "import.ui.read_attention.copy":
        "OAAM は不完全な読み取り結果を Asset の確認に渡していません。該当する場所の Asset はインポートされません。",
    "import.ui.read_attention.eyebrow": "ファイルアクセス",
    "import.ui.read_attention.status.failed": "この場所を読み取れませんでした",
    "import.ui.read_attention.status.not_found": "この場所は利用できなくなりました",
    "import.ui.read_attention.status.partial": "この場所の一部だけを読み取りました",
    "import.ui.read_attention.status.unreported": "この場所から信頼できる結果を取得できませんでした",
    "import.ui.read_attention.title": "完全に読み取れなかった場所があります",
    "import.ui.refresh_required": "ソースファイルが変更されたか、この確認の期限が切れました。再スキャンしてください。",
    "import.ui.return_to_sources": "スキャン場所を確認",
    "import.ui.result.batch_outcomes": "インポート結果",
    "import.ui.result.copy": "{message} 失敗した Asset があっても、成功したインポートは取り消されません。",
    "import.ui.result.no_tool_changes": "プロジェクト ファイルとツールの設定は変更されていません。",
    "import.ui.result.retry_failed":
        "失敗した Asset を再度インポートするには、ソースに戻ってそれらの Asset だけを選択してください。",
    "import.ui.result.dependency_failed": "必要な Asset をインポートできませんでした",
    "import.ui.result.failed": "失敗しました",
    "import.ui.result.failed_dependencies": "インポートできなかった必要な Asset：{assets}",
    "import.ui.result.imported": "インポート済み",
    "import.ui.result.asset_saved": "新しい Asset を OAAM ライブラリに保存しました",
    "import.ui.result.version_saved": "既存の Asset に新しい Version を保存しました",
    "import.ui.result.open": "Asset を開く",
    "import.ui.result.open_failed": "Asset は保存されましたが、開けませんでした。再試行するか、ライブラリから探してください。",
    "import.ui.result.title": "インポート結果",
    "import.ui.result.unknown_asset": "名前のない Asset",
    "import.ui.safe_import_copy":
        "選択した各 Asset は、新しい Asset を作成するか、互換性のある Asset に Version を追加します。AI コーディングツールやプロジェクトのファイルは変更しません。",
    "import.ui.technical.asset_id": "Asset ID：{assetId}",
    "import.ui.technical.byte_length": "バイト数：{byteLength}",
    "import.ui.technical.candidate_id": "確認項目 ID：{candidateId}",
    "import.ui.technical.content_hash": "完全なファイルのハッシュ：{contentHash}",
    "import.ui.technical.media_type": "メディアタイプ：{mediaType}",
    "import.ui.technical.version_id": "Version ID：{versionId}",
    "import.ui.technical_details": "技術詳細",
    "import.ui.title": "Asset と必要な関連 Asset を選択",
    "import.validation.binding_duplicate": "同じ関連 Asset が複数回選択されています。",
    "import.validation.binding_existing_stale": "選択した既存 Version は最新ではないか、互換性がありません。",
    "import.validation.binding_stale": "関連 Asset は利用できない、未選択、または互換性がありません。",
    "import.validation.candidate_dependencies_truncated":
        "{candidate} が参照する関連 Asset が多すぎるため、この確認画面では安全に表示できません。",
    "import.validation.candidate_not_importable": "{candidate} はこの Asset 確認からインポートできません。",
    "import.validation.candidate_refresh": "{candidate} は再スキャンが必要です。",
    "import.validation.destination_choose": "{candidate} が新しいアセットを作成するか新しいバージョンを作成するかを選択します。",
    "import.validation.destination_duplicate": "1 つの Asset に複数の保存先が選択されています。",
    "import.validation.destination_incompatible": "{candidate} には、古いか互換性のない既存のアセットの宛先があります。",
    "import.validation.destination_missing": "選択した保存先は、この Asset 確認では利用できなくなりました。",
    "import.validation.destination_stale": "保存先が古い、または未選択の Asset に属しています。",
    "import.validation.missing_binding": "{candidate} には {target} の関連 Asset が必要です。",
    "import.validation.no_selection": "インポートできる Asset を少なくとも 1 つ選択してください。",
    "import.validation.preview_membership": "選択した Asset は、この Asset 確認に属さなくなりました。",
    "import.validation.user_action": "OAAM はこの操作を確認できません。Asset 確認を閉じて開き直してください。",
    "catalog.activity.analyze": "レンダリング オプションの分析",
    "catalog.version_update.action": "選択中のバージョンを更新",
    "catalog.version_update.title": "この場所で使うバージョンを更新",
    "catalog.version_update.copy":
        "この場所では別のバージョンが選択されています。新しいバージョンを選び、ファイルの差分を確認してから適用してください。",
    "catalog.version_update.choose": "リビジョン {revision} を選択して確認",
    "catalog.version_update.selected": "以前の選択バージョン：{version}",
    "catalog.version_update.next": "新しいバージョン：{version}",
    "catalog.version_update.pending": "選択内容の確認が必要です",
    "catalog.version_update.changed": "Asset または使用場所が変更されました。再読み込みしてから更新を確認してください。",
    "catalog.version_update.failed": "選択中のバージョンを更新できませんでした。",
    "catalog.activity.create": "ツール設定を保存中",
    "catalog.activity.deploy": "選択したレンダーを展開しています",
    "catalog.activity.preview": "正確なターゲットのプレビューを準備する",
    "catalog.activity.inspect": "配置済みファイルの変更を確認する",
    "catalog.activity.recover": "ツールファイルの状態を回復中",
    "catalog.activity.register": "プロジェクトの登録",
    "catalog.activity.repair": "OAAM管理ファイルの修復",
    "catalog.activity.reverse_cancel": "準備したレビューをキャンセルする",
    "catalog.activity.reverse_commit": "レビューした変更を保存する",
    "catalog.activity.reverse_refresh": "保存したバージョンと適用先を更新しています",
    "catalog.activity.reverse_prepare": "レビューした変更を準備する",
    "catalog.activity.scan": "デプロイされたファイルのスキャン",
    "catalog.asset.detail_interrupted": "アセット詳細のロードが中断されました。",
    "catalog.asset.detail_unavailable": "資産の詳細は利用できません。",
    "catalog.asset.missing": "選択したアセットまたは現在のバージョンは存在しません。",
    "catalog.authority_changed":
        "このページを開いている間にライブラリが変更されました。古い選択を適用しないよう操作を一時停止しています。更新して現在の状態を確認してください。",
    "catalog.empty": "ライブラリが空です。AI コーディングツールを選ぶ前に Asset をインポートして確認してください。",
    "catalog.deployment.created": "ツール設定を保存しました。書き込む前にファイル変更を確認してください。",
    "catalog.deployment.creation_failed": "ツール設定を保存できませんでした。",
    "catalog.inspection.conflict": "ファイルの競合には、明示的な復元またはレビューした変更を保存する選択が必要です。",
    "catalog.inspection.current": "検査は現状です。修理する前に個々の詳細を確認してください。",
    "catalog.inspection.detail_interrupted": "検査の詳細が中断されました。",
    "catalog.inspection.detail_unavailable": "検査の詳細は入手できません。",
    "catalog.inspection.interrupted": "検査は中断されました。",
    "catalog.inspection.lost_channel": "インスペクションは端末チャネルを失いました。再度検査して新たな証拠を入手します。",
    "catalog.inspection.retained_expired":
        "保持されている検査の有効期限が切れたか、交換されました。修復または上書きする前にもう一度検査してください。",
    "catalog.load.failed": "OAAM カタログをロードできませんでした。",
    "catalog.load.interrupted": "OAAM カタログのロードが中断されました。",
    "catalog.loading": "OAAMカタログをロード中…",
    "catalog.operation.failed": "{operation} が失敗しました。",
    "catalog.operation.finished": "操作が完了しました。現在の状態：{stage}。",
    "catalog.operation.interrupted": "{operation} は、信頼できる結果が得られる前に中断されました。",
    "catalog.operation.lost_terminal":
        "{operation} は最終結果を失いました。やみくもに再試行せず、最新の保存状態を読み込み、必要に応じて回復してください。",
    "catalog.project.registered": "{project} を登録しました。",
    "catalog.project.registration_failed": "選択したプロジェクトを登録できませんでした。",
    "catalog.preview.failed": "正確なターゲットのプレビューを準備できませんでした。",
    "catalog.preview.interrupted": "信頼できる結果が得られる前に、ターゲットのプレビューが中断されました。",
    "catalog.preview.lost_channel":
        "ターゲット プレビューのターミナル チャネルが失われました。書き込む前に新しいプレビューを準備します。",
    "catalog.preview.ready": "正確な現在および望ましい目標状態をレビューする準備ができています。",
    "catalog.preview.retained_expired":
        "保持されているターゲット プレビューの有効期限が切れたか、置き換えられました。新しいプレビューを準備します。",
    "catalog.render.analysis_failed": "レンダリング解析に失敗しました。",
    "catalog.render.choose_strategies": "セマンティック入力ごとに 1 つの戦略を選択します。必要な分解は未承認のままです。",
    "catalog.render.interrupted": "レンダリング解析が中断されました。",
    "catalog.render.lost_channel":
        "レンダリング解析によりターミナル チャネルが失われました。これは読み取り専用であり、更新後に再度実行できます。",
    "catalog.reverse.cancel_failed": "準備したレビューをキャンセルできませんでした。",
    "catalog.reverse.cancelled": "Asset を変更せずに準備したレビューをキャンセルしました。",
    "catalog.reverse.commit_failed": "レビューした変更を保存できませんでした。",
    "catalog.reverse.not_prepared": "これらの変更を安全にレビューできる状態に準備できませんでした。",
    "catalog.reverse.prepare_failed": "OAAM は正確に検査した変更を準備できませんでした。",
    "catalog.reverse.prepared": "検査した変更を新しい Asset Version として確認してください。",
    "catalog.reverse.promotion_confirmation_required": "保存する前に、この正確な新しい Version を確認してください。",
    "catalog.reverse.result.committed": "新しい Asset Version が公開され、このツール設定で選択されました。",
    "catalog.reverse.result.not_published": "新しいアセット バージョンは公開されていません。",
    "catalog.reverse.result.outcome_unavailable":
        "OAAM は変更が保存されたかを証明できません。最新の保存状態を読み込んでください。",
    "catalog.reverse.result.published_not_selected":
        "新しい Asset Version が公開されましたが、このツール設定では以前の Version が選択されたままです。",
    "catalog.reverse.result.recovery_required": "別の書き込みを試す前に、この保存を回復する必要があります。",
    "catalog.target.inspection_failed": "配置済みファイルの検査に失敗しました。",
    "catalog.ui.action.analyze": "変更予定を確認",
    "catalog.ui.action.apply": "変更を適用",
    "catalog.ui.action.create": "この設定を保存",
    "catalog.ui.action.inspect": "外部変更を確認",
    "catalog.ui.action.overwrite": "選択した OAAM バージョンを適用",
    "catalog.ui.action.preview": "適用前にファイルを確認",
    "catalog.ui.action.recover": "復旧",
    "catalog.ui.action.repair": "この正確な検査による修理",
    "catalog.ui.action.replace_unmanaged": "既存のファイルを置き換える",
    "catalog.ui.action.reverse_cancel": "保存せずにキャンセル",
    "catalog.ui.action.reverse_commit": "新しいライブラリ版として保存",
    "catalog.ui.action.reverse_prepare": "ツールでの変更を確認",
    "catalog.ui.action.scan": "ファイルの状態を確認",
    "catalog.ui.asset.bytes": "{count} バイト",
    "catalog.ui.asset.catalog_eyebrow": "アセットとバージョンのカタログ",
    "catalog.ui.asset.catalog_title": "正確に保存されたバージョンを選択してください",
    "catalog.ui.asset.current_version": "現在のアセットのバージョン",
    "catalog.ui.asset.empty": "アセットはまだ保存されていません。まず上記のインポートレビューを完了してください。",
    "catalog.ui.asset.loading_detail": "正確なバージョンのメタデータをロードしています…",
    "catalog.ui.asset.refresh": "カタログを更新する",
    "catalog.ui.asset.revision_version": "リビジョン {revision} · バージョン {versionId}",
    "catalog.ui.asset.view_version": "現在のバージョンを表示",
    "catalog.ui.catalog_eyebrow": "ライブラリとツールでの利用",
    "catalog.ui.catalog_loading": "OAAMカタログをロードしています",
    "catalog.ui.catalog_unavailable": "カタログが利用できません",
    "catalog.ui.catalog_warnings": "ライブラリとツールファイルのお知らせ",
    "catalog.ui.create.add_folder": "プロジェクトフォルダーを追加",
    "catalog.ui.create.allow_incomplete": "この不完全なバージョンを明示的に許可します",
    "catalog.ui.create.asset_revision": "{asset} · バージョン {revision}",
    "catalog.ui.create.assets_legend": "正確な現在の資産バージョン",
    "catalog.ui.create.consumer_legend": "この場所で使うツールエントリ",
    "catalog.ui.create.copy": "Asset、ツール、場所を選びます。OAAM は変更を先に表示し、もう一度確認した後だけ書き込みます。",
    "catalog.ui.create.eyebrow": "ステップ 3",
    "catalog.ui.create.fresh_target": "ツールの場所",
    "catalog.ui.create.no_ready_runtime": "このツールは選択した場所を使用できません。",
    "catalog.ui.create.not_ready": "ここでは利用できません: {agentRuntimeIds}",
    "catalog.ui.create.project": "OAAMプロジェクト",
    "catalog.ui.create.project_choose": "プロジェクトを選択してください",
    "catalog.ui.create.subject_global": "Global ライブラリの Asset を使用します。",
    "catalog.ui.create.subject_project": "この Project と Global ライブラリの Asset を使用します。",
    "catalog.ui.create.target_choose": "見つかったツールの場所を選択",
    "catalog.ui.create.title": "追加先を確認",
    "catalog.ui.deployment.asset_count.many": "ライブラリ項目 {count} 件",
    "catalog.ui.deployment.asset_count.one": "ライブラリ項目 {count} 件",
    "catalog.ui.deployment.empty": "ツール設定はまだ保存されていません。",
    "catalog.ui.deployment.eyebrow": "設定済みのツール",
    "catalog.ui.deployment.select": "確認または更新するツール設定を選択してください。",
    "catalog.ui.deployment.title": "ツールファイルを確認して更新",
    "catalog.ui.freshness.complete": "最終チェック日 {time}",
    "catalog.ui.freshness.failed": "前回のチェックは失敗しました {attempt} · 最後に完了しました {lastComplete}",
    "catalog.ui.freshness.in_progress": "{attempt} · 最後に完了した {lastComplete} 以降をチェックしています",
    "catalog.ui.freshness.never": "まだチェックされていません",
    "catalog.ui.freshness.no_complete": "まだ完成していない",
    "catalog.ui.freshness.partial": "前回のチェックは部分的でした {attempt} · 最後に完了した {lastComplete}",
    "catalog.ui.inspection.change_count.many": "{count} の変更",
    "catalog.ui.inspection.change_count.one": "{count} の変更",
    "catalog.ui.inspection.conflict_count.many": "{count} の競合",
    "catalog.ui.inspection.conflict_count.one": "{count} 競合",
    "catalog.ui.inspection.detail_loading": "制限付き検査の詳細を読み込み中…",
    "catalog.ui.inspection.details_omitted": "追加の検査セレクターは、この限定された概要から省略されました。",
    "catalog.ui.inspection.inspecting": "配置済みファイルの変更を確認しています…",
    "catalog.ui.inspection.title": "検査",
    "catalog.ui.inspection.file_detail": "ファイルの帰属",
    "catalog.ui.inspection.change_detail": "内容の変更",
    "discovery.ui.choose_environments": "環境を選ぶ",
    "catalog.ui.picker.cancelled": "プロジェクトの選択がキャンセルされました。",
    "catalog.ui.picker.choose_button": "このプロジェクトフォルダーを使用します",
    "catalog.ui.picker.choose_title": "OAAMプロジェクトフォルダーを選択してください",
    "catalog.ui.picker.failed": "ネイティブ プロジェクト フォルダーの選択に失敗しました。",
    "catalog.ui.picker.opening": "ネイティブのプロジェクト フォルダー ピッカーを開いています…",
    "catalog.ui.picker.registering": "{path} を登録中…",
    "catalog.ui.preview.action.blocked_managed_conflict":
        "管理対象の内容が変更されています。このバージョンを確認し、置き換えを確定してください。",
    "catalog.ui.preview.action.ready_apply": "正確なターゲット状態により、通常の適用が可能になります。",
    "catalog.ui.preview.action.requires_unmanaged_replacement":
        "対象の場所には異なる内容が存在します。ファイルの変更を確認してから、今回の置き換えを確定してください。",
    "catalog.ui.preview.change.create": "新しいファイルを作成する",
    "catalog.ui.preview.change.establish_baseline": "同一のコンテンツを維持し、OAAM ベースラインを確立する",
    "catalog.ui.preview.change.managed_conflict": "管理対象ターゲットがOAAMベースラインと異なる",
    "catalog.ui.preview.change.remove_managed": "OAAM管理ファイルの削除",
    "catalog.ui.preview.change.replace_unmanaged": "内容が異なる既存のファイルを置き換える",
    "catalog.ui.preview.change.remove_unmanaged": "確認した既存ファイルを削除",
    "catalog.ui.preview.change.unchanged": "管理ファイルを変更しないでください",
    "catalog.ui.preview.change.update_managed": "管理されているファイルを更新する",
    ...JAPANESE_DESKTOP_DIRECTORY_PREVIEW_MESSAGES,
    "catalog.ui.preview.confirm_managed_overwrite": "外部ファイルの変更を確認し、正確な OAAM 出力を今回だけ復元します。",
    "catalog.ui.preview.confirm_unmanaged": "既存の内容を確認し、今回のみ置き換えることに同意します",
    "catalog.ui.preview.current_tab": "現在",
    "catalog.ui.preview.desired_tab": "希望",
    "catalog.ui.preview.current_text": "現在のターゲットテキスト",
    "catalog.ui.preview.desired_text": "希望するターゲットテキスト",
    "catalog.ui.preview.review_tab": "ファイルの変更",
    "catalog.ui.preview.open_current": "現在のファイルをタブで開く",
    "catalog.ui.preview.open_desired": "適用予定のファイルをタブで開く",
    "catalog.ui.preview.snapshot_copy": "このプレビューの作成時に取得したファイル内容を表示しています。",
    "catalog.ui.preview.bounded_diff": "差分が多いため、変更を範囲単位で表示しています。各ファイルを開くと全文を確認できます。",
    "catalog.ui.reconciliation_required":
        "OAAM は変更の最終結果を失いました。最新の保存状態を読み込み、操作をやみくもに繰り返さないでください。",
    "catalog.ui.reverse.finish_recovery":
        "この操作を完了するには「復旧」を選んでください。OAAM は次の変更の前に保存済みの結果を確認します。",
    "catalog.ui.reverse.confirm_promotion": "このツール設定で、この新しい Asset Version を選択できるようにします",
    "catalog.ui.reverse.expires": "この準備は {time} で期限切れになります。",
    "catalog.ui.reverse.preparing": "正確に検査した変更をレビュー用に準備しています…",
    "catalog.ui.reverse.result_title": "保存結果",
    "catalog.ui.reverse.title": "ツールでの変更を確認",
    "catalog.ui.reverse.whole_file_adoption":
        "ファイル全体の採用を必要とする変更は、通常のソースの読み取りとインポートのレビュー フローに属します。",
    "catalog.ui.render.approve_degraded": "この劣化したレンダリングを一度承認します",
    "catalog.ui.render.approval.reverse_extract_unsupported": "このツールで今後行われる編集を安全に取り込むことはできません",
    "catalog.ui.render.approval.semantic_degradation": "一部のソース動作が失われます",
    "catalog.ui.render.blocked": "この部分は安全にレンダリングできません。",
    "catalog.ui.render.degradation.folder_asset_flattened": "フォルダーアセットはフラット化されます",
    "catalog.ui.render.degradation.memory_semantics_lost": "記憶動作がプレーンな内容になる",
    "catalog.ui.render.degradation.permission_or_tool_boundary_lost": "権限またはツールの境界が失われます",
    "catalog.ui.render.degradation.reverse_extract_pollution_risk":
        "後で逆抽出すると、生成されたコンテンツが含まれる可能性があります",
    "catalog.ui.render.degradation.runtime_specific_metadata_lost": "ツール固有のメタデータは失われます",
    "catalog.ui.render.degradation.target_runtime_missing_asset_kind":
        "この AI コーディングツールには、この Asset 種別のネイティブ形式がありません",
    "catalog.ui.render.degradation.trigger_or_loading_level_lost": "元のトリガーまたは読み込みレベルは失われます",
    "catalog.ui.render.degradation.workflow_permission_lost": "ワークフロー権限の動作が失われます",
    "catalog.ui.render.degradation.workflow_runtime_lost": "ワークフローの実行動作が失われます",
    "catalog.ui.render.degradation.workflow_trigger_lost": "ワークフロートリガーの動作は失われます",
    "catalog.ui.render.degradation.workflow_variable_lost": "ワークフロー変数の動作が失われます",
    "catalog.ui.render.degradations": "行動の変化",
    "catalog.ui.render.executable_suffix": "· 実行可能ファイル",
    "catalog.ui.render.managed_directory": "管理ディレクトリ: {path}",
    "catalog.ui.render.no_target_file": "このセマンティクスは、直接ファイル要求を追加しません。",
    "catalog.ui.render.output_binary": "{path} · バイナリ{executable}",
    "catalog.ui.render.output_text": "{path} · テキスト{executable}",
    "catalog.ui.render.output_counts": "{count} ファイル · テキスト {text} · バイナリ {binary} · 実行可能 {executable}",
    "catalog.ui.render.directory_count": "管理対象ディレクトリ {count} 個",
    "catalog.ui.render.preview_required":
        "アイテムごとに完全なレンダリング オプションを 1 つ選択します。 OAAM は、書き込みの前に、最新の正確なターゲットのプレビューを表示します。",
    "catalog.ui.render.reverse.can_reconcile": "今後の編集内容を帰属させてレビューすることができます",
    "catalog.ui.render.reverse.ignore_generated_wrapper": "変更が戻されると、生成されたラッパー テキストは無視されます",
    "catalog.ui.render.reverse.unsupported": "今後の編集内容を安全に戻すことはできません",
    "catalog.ui.render.reverse_label": "今後の編集処理: {policy}",
    "catalog.ui.render.runtime": "AI コーディングツール: {runtime}",
    "catalog.ui.render.semantic.asset_file_inventory": "含まれるファイル",
    "catalog.ui.render.semantic.guidance_base_context": "プロジェクトのコンテキスト",
    "catalog.ui.render.semantic.guidance_content": "指示",
    "catalog.ui.render.semantic.memory_content": "記憶内容",
    "catalog.ui.render.semantic.memory_support": "メモリのサポート",
    "catalog.ui.render.semantic.rule_activation": "ルールのアクティブ化",
    "catalog.ui.render.semantic.rule_content": "ルールの内容",
    "catalog.ui.render.semantic.skill_body": "スキルの説明",
    "catalog.ui.render.semantic.skill_discovery_metadata": "スキルディスカバリーメタデータ",
    "catalog.ui.render.semantic.skill_resource": "スキルリソース",
    "catalog.ui.render.semantic.subagent_delegation_metadata": "サブエージェント委任メタデータ",
    "catalog.ui.render.semantic.subagent_invoked_context": "サブエージェントが呼び出すコンテキスト",
    "catalog.ui.render.semantic.subagent_model_hint": "サブエージェントモデルのヒント",
    "catalog.ui.render.semantic.subagent_resource": "サブエージェントリソース",
    "catalog.ui.render.semantic.subagent_tool_boundary": "サブエージェントツールの境界",
    "catalog.ui.render.semantic.workflow_activation": "ワークフローのアクティブ化",
    "catalog.ui.render.semantic.workflow_content": "ワークフローの内容",
    "catalog.ui.render.semantic.workflow_reference": "ワークフローリファレンス",
    "catalog.ui.render.strategy.inline": "インラインコンテンツ",
    "catalog.ui.render.strategy.native_directory": "ネイティブディレクトリ",
    "catalog.ui.render.strategy.native_graph": "ネイティブファイルグラフ",
    "catalog.ui.render.strategy.native_file": "ネイティブファイル",
    "catalog.ui.render.strategy.native_import": "ネイティブインポート",
    "catalog.ui.render.strategy.reference_with_intro": "簡単な紹介付きのリファレンス",
    "catalog.ui.support_required":
        "OAAM はこのツールファイル設定を自動で回復できません。確認結果を保存し、サポートに連絡してください。",
    "catalog.ui.render.subject": "{asset} · {semantic}",
    "catalog.ui.render.title": "ツールでのファイルの表示方法を選択",
    "catalog.ui.render.waiting": "レンダリング解析を待っています…",
    "catalog.ui.status.external_changes": "外部の変更が見つかりました",
    "catalog.ui.status.first_deployment": "最初のデプロイを利用できます",
    "catalog.ui.status.needs_checking": "ステータスの確認が必要",
    "catalog.ui.status.paused_for_safety": "安全のため一時停止中",
    "catalog.ui.status.repair_available": "一部の管理ファイルは復元可能",
    "catalog.ui.status.review_required": "このツール設定は確認が必要です",
    "catalog.ui.status.support_required": "サポートが必要です",
    "catalog.ui.status.up_to_date": "最新の状態",
    "catalog.ui.target.choose_project": "ツールを確認",
    "catalog.ui.target.copy":
        "この Project で確認するツールとシステム環境を選びます。Asset の取得元ツールは使用先を制限しません。この確認ではファイルを変更しません。",
    "catalog.ui.target.discover_global": "ツールを確認",
    "catalog.ui.target.environments": "確認するシステム環境",
    "catalog.ui.target.eyebrow": "ツールと場所",
    "catalog.ui.target.loading": "ツールとシステム環境を読み込み中",
    "catalog.ui.target.no_provider": "選択した AI コーディングツールを利用できません。",
    "catalog.ui.target.probing": "ツールを確認中…",
    "catalog.ui.target.providers": "使用するツール",
    "catalog.ui.target.select_all": "すべて選択",
    "catalog.ui.target.clear_all": "選択を解除",
    "catalog.ui.target.title": "利用できるツールを探す",
    "catalog.ui.target.unavailable": "現在、利用できるツールを確認できません",
    "catalog.ui.workspace.back": "ライブラリに戻る",
    "catalog.ui.workspace.eyebrow": "ツールの場所",
    "catalog.ui.workspace.global": "Global Asset を使う",
    "catalog.ui.workspace.project": "Project Asset を使う",
    "catalog.validation.asset_duplicate": "同じツール設定に同じ Asset を 2 回含めることはできません。",
    "catalog.validation.asset_incomplete": "{asset} は不完全です。そのバージョンを明示的に許可するか、削除します。",
    "catalog.validation.asset_missing": "選択したアセットは現在のカタログに存在しません。",
    "catalog.validation.asset_version_changed": "{asset} の現在のバージョンは異なります。確認して再度選択します。",
    "catalog.validation.choose_asset": "ツールに渡す Asset を少なくとも 1 つ選択してください。",
    "catalog.validation.choose_project": "現在の OAAM プロジェクトを選択します。",
    "catalog.validation.choose_runtime": "この正確な場所で利用できる AI コーディングツールを 1 つ以上選択してください。",
    "catalog.validation.choose_target": "現在の検出結果から対象を選択してください。",
    "catalog.validation.render_approval": "劣化を伴うオプション「{strategy}」を明示的に承認するか、別の方法を選択してください。",
    "catalog.validation.render_approval_evidence": "承認にはユーザーのアクションの証拠はありません。",
    "catalog.validation.render_duplicate": "1 つのセマンティック入力に複数のレンダリング方法が選択されています。",
    "catalog.validation.render_incomplete":
        "OAAM ではファイル変更の確認を最後まで検証できませんでした。続行する前に更新してください。",
    "catalog.validation.render_missing": "各セマンティック入力について、レンダリング方法を 1 つだけ選択してください。",
    "catalog.validation.render_none": "この解析には適用できるレンダリング方法がありません。",
    "session.catalog_unavailable": "OAAM カタログは使用できません。",
    "session.connecting": "OAAM に接続中…",
    "session.connection_closed": "OAAM との接続が切断されました。",
    "session.host_recovering": "OAAM の準備が整わなかったため、1 回だけクリーンに再試行しています…",
    "session.host_startup_failed": "OAAM を起動できませんでした。バックグラウンドで再試行を繰り返しません。",
    "session.host_startup_timeout": "30 秒経過しても OAAM を利用できません。明示的に再試行できます。",
    "session.initialization_failed": "OAAM のローカルデータを準備できませんでした。",
    "session.restart_failed": "OAAM を再起動できませんでした。",
    "session.restarting": "OAAM を再起動中…",
    "session.starting": "OAAM を開始しています…",
    "workspace.catalog.assets.many": "{count} アセット",
    "workspace.catalog.assets.none": "アセットはまだインポートされていません",
    "workspace.catalog.label": "カタログ概要",
    "workspace.host.ready": "ホストの準備完了",
    "workspace.host.warnings.many": "{count} 起動警告",
    "workspace.host.warnings.one": "{count} 起動警告",
    "workspace.overview.copy": "ローカルのソースを発見し、正確な候補を確認して、明示的な選択のみを行ってデプロイします。",
    "workspace.overview.eyebrow": "ワークスペースの概要",
    "workspace.overview.title": "ポータブルエージェント資産の管理",
    "library.asset_detail_interrupted": "アセットのメタデータの読み込みが中断されました。",
    "library.asset_detail_unavailable": "選択した Asset の詳細を読み込めませんでした。",
    "library.asset_missing": "選択したアセットまたは現在のバージョンは利用できなくなりました。",
    "library.assets.count": "{count} アセット",
    "library.assets.deleted": "削除済み",
    "library.assets.empty": "このコレクションにはアセットがありません。",
    "library.assets.empty_global_copy":
        "AI コーディングツールからアセットをインポートして、再利用できるグローバルライブラリを作成します。",
    "library.assets.empty_global_title": "グローバルアセットライブラリは空です",
    "library.assets.empty_project_copy":
        "AI コーディングツール内のこのプロジェクトの場所を確認し、インポートする Asset を選びます。",
    "library.assets.empty_project_title": "{project} にアセットはありません",
    "library.assets.eyebrow": "アセットライブラリ",
    "library.assets.global_copy": "グローバルライブラリに保存された Asset。",
    "library.assets.global_title": "グローバルライブラリ",
    "library.assets.incomplete": "不完全",
    "library.assets.include_deleted": "OAAM のごみ箱にあるアセットを表示します。完全には削除されておらず、復元できます。",
    "library.assets.loading": "アセットを読み込んでいます…",
    "library.assets.loading_page": "最大 50 件の Asset を読み込んでいます…",
    "library.assets.no_description": "説明なし",
    "library.assets.no_match": "この検索に一致するロードされたアセットはありません。",
    "library.assets.project_copy": "この正確なプロジェクトに関連付けられたアセット。",
    "library.assets.project_title": "プロジェクト資産",
    "library.assets.revision": "バージョン {revision}",
    "library.assets.search": "ロードされたアセットを検索する",
    "library.assets.search_placeholder": "この読み込まれたライブラリを検索します",
    "library.assets.shared_copy":
        "グローバル アセットは後で選択できますが、ターゲットの互換性についてはレンダリングのレビューが必要です。",
    "library.assets.shared_title": "このプロジェクトで利用可能なグローバル アセット",
    "library.assets.show_more": "{count} をさらに表示 {kind} アセット",
    "library.assets.title": "保存されたアセットを参照する",
    "library.authority_changed": "カタログが変わりました。このビューに依存する前にリフレッシュしてください。",
    "library.catalog.warnings": "カタログの警告: {count} 件",
    "library.environments.filter": "監視環境フィルター",
    "library.environments.sources": "{count} が監視したソース",
    "library.environments.title": "このビューで監視されている環境",
    "library.export.action": "OAAM Version パッケージをエクスポート",
    "library.export.choose_button": "パッケージをエクスポート",
    "library.export.choose_title": "この Version の OAAM Version パッケージを保存",
    "library.export.complete": "{bytes} バイトの OAAM Version パッケージをエクスポートしました。",
    "library.export.failed": "OAAM Version パッケージをエクスポートできませんでした。",
    "library.export.running": "OAAM Version パッケージを作成しています…",
    "library.failed_title": "ライブラリをロードできませんでした",
    "library.file_preview_failed": "選択したファイルを安全に読み取れませんでした。",
    "library.files.descendants": "下位ファイル {count} 件",
    "library.files.more": "さらに 50 件読み込む",
    "library.files.up": "1 つ上のフォルダーへ",
    "library.global.navigation": "グローバルライブラリ",
    "library.global.navigation_copy": "1 つのプロジェクトに所有されていないアセットおよび監視ソースを参照します。",
    "library.global.title": "グローバルライブラリ",
    "library.host.warnings": "{count} 起動警告",
    "library.inspector.bytes": "{count} バイト",
    "library.inspector.close": "アセットインスペクタを閉じる",
    "library.inspector.created": "作成されました",
    "library.inspector.current_version": "現在のバージョン {revision}",
    "library.inspector.executable": "実行可能ファイル",
    "library.inspector.eyebrow": "資産検査官",
    "library.inspector.files": "ファイル",
    "library.inspector.fingerprint": "指紋",
    "library.inspector.incomplete": "この現在のバージョンは不完全であり、完全には展開可能ではありません。",
    "library.inspector.kind": "種類",
    "library.inspector.label": "選択されたアセットのメタデータ",
    "library.inspector.loading": "アセットの詳細を読み込んでいます…",
    "library.inspector.more_versions": "さらに 50 Version を読み込む",
    "library.inspector.no_files": "このバージョンにはファイルが含まれていません。",
    "library.inspector.overview": "概要",
    "library.inspector.project": "プロジェクト",
    "library.inspector.scope": "範囲",
    "library.inspector.scope_path": "スコープパス",
    "library.inspector.status": "ステータス",
    "library.inspector.title": "資産の詳細",
    "library.inspector.updated": "更新されました",
    "library.inspector.version_id": "バージョンID",
    "library.inspector.version_select": "正確な Version",
    "library.inspector.versions": "バージョン",
    "library.compare.action": "正確な Version を比較",
    "library.compare.base": "比較対象",
    "library.compare.file_graph": "ファイルの変更",
    "library.compare.folded": "未変更の {count} 行を折りたたみ",
    "library.compare.layout": "Diff レイアウト",
    "library.compare.metadata_only": "ファイル構成は変更されていますが、表示できるテキスト Diff はありません。",
    "library.compare.no_text_changes": "選択したテキストは両方の Version で同一です。",
    "library.compare.progress": "{stage}: {completed}/{total}",
    "library.compare.selected_file": "選択したファイル",
    "library.compare.show_more_files": "ファイルをさらに表示（{shown}/{total}）",
    "library.compare.show_more_lines": "Diff 行をさらに表示（{shown}/{total}）",
    "library.compare.side_by_side": "左右比較",
    "library.compare.title": "Version 比較",
    "library.compare.unified": "統合表示",
    "library.compare_failed": "正確な Version 比較が完了しませんでした。",
    "library.preview.binary": "このファイルはバイナリ形式のため、プレビューできません。",
    "library.preview.loading": "選択したファイルを安全に読み込んでいます…",
    "library.preview.more": "次のテキストページを読み込む",
    "library.preview.range": "{total} バイト中 {start}–{end} バイト",
    "library.preview.title": "ファイルプレビュー",
    "library.layout.cards": "カード",
    "library.layout.label": "アセットのレイアウト",
    "library.layout.list": "リスト",
    "library.load_failed": "必要な Project または Asset の情報を読み込めませんでした。",
    "library.load_interrupted": "信頼できるビューが利用可能になる前に、ライブラリ接続が終了しました。",
    "library.loading": "現在のプロジェクトとアセットのメタデータをロードしています…",
    "library.loading_title": "OAAMライブラリのロード",
    "library.operation_unavailable": "このバージョンの OAAM では、必要な Project と Asset を一覧表示できません。",
    "library.deployments.manage": "ツールの使用場所を管理",
    "library.deployments.start": "使用場所を選択",
    "library.preference_not_saved": "このセッションでは選択はアクティブのままですが、デスクトップ設定は保存されませんでした。",
    "library.project_register_failed": "選択したフォルダーをプロジェクトとして登録できませんでした。",
    "library.project_register_interrupted": "信頼できる結果が返される前に、プロジェクトの登録が中断されました。",
    "library.project_registered": "{project} を登録しました。",
    "library.projects.add": "プロジェクトの追加",
    "library.projects.empty_copy": "最初のプロジェクトフォルダーを追加するか、使用中のツールからアセットをインポートします。",
    "library.projects.empty_eyebrow": "管理対象プロジェクトがありません",
    "library.projects.empty_title": "プロジェクトから始める",
    "library.projects.search": "ロードされたプロジェクトを検索する",
    "library.projects.search_placeholder": "現在のプロジェクトを検索",
    "library.projects.open_guided_import": "ガイド付きインポートを開く",
    "library.projects.title": "プロジェクト",
    "library.refresh": "リフレッシュ",
    "library.refresh_required": "変更されたデータを更新する",
    "library.subject.global": "グローバル",
    "library.subject.label": "図書館の主題",
    "library.subject.projects": "プロジェクト",
    "library.summary.assets": "プロジェクト資産",
    "library.summary.global_assets": "グローバル資産",
    "library.summary.label": "現在のライブラリの概要",
    "library.summary.watched_environments": "監視されている環境が表示される",
    "library.workspace.label": "プロジェクトファーストのアセットワークスペース",
    ...JAPANESE_DESKTOP_LIBRARY_SOURCE_MESSAGES,
    ...JAPANESE_DESKTOP_PROJECT_LIFECYCLE_MESSAGES,
    "common.back": "戻る",
    "onboarding.discovery.continue_without_import": "インポートせずに続行する",
    "onboarding.navigation.label": "オンボーディングナビゲーション",
    "onboarding.welcome.choose": "各ステップで、場所、ツール、ソース、Asset を選択します。",
    "onboarding.welcome.copy": "OAAM は、選択した場所で再利用できる手順や設定を探せます。開始するまでは何もスキャンしません。",
    "onboarding.welcome.eyebrow": "スキャンの前",
    "onboarding.welcome.inspect": "OAAM は、明示的に選択した場所だけを読み取ります。",
    "onboarding.welcome.later": "後で設定する",
    "onboarding.welcome.no_write": "スキャンとインポートでは、AI コーディングツールのファイルは変更されません。",
    "onboarding.welcome.start": "ガイド付きセットアップを開始する",
    "onboarding.welcome.title": "OAAM がコンピュータを検査する時期を選択します",
    "state_resilience.backup.copy":
        "完全で変更不可能な復旧アーカイブを作成します。ほかのバックアップアーカイブや AI コーディングツールが使用するファイルは含みません。",
    "state_resilience.backup.create": "検証済みバックアップを作成",
    "state_resilience.backup.create_failed": "バックアップは作成されませんでした。",
    "state_resilience.backup.create_interrupted": "バックアップ処理が中断されました。",
    "state_resilience.backup.created": "検証済みバックアップを作成しました。",
    "state_resilience.backup.inspect": "バックアップを確認",
    "state_resilience.backup.inspect_failed": "バックアップを確認できませんでした。",
    "state_resilience.backup.inspect_interrupted": "バックアップの確認が中断されました。",
    "state_resilience.backup.output": "{path} に作成しました",
    "state_resilience.backup.review_ready": "アーカイブを作成する前に、正確なソースサイズと保存先を確認してください。",
    "state_resilience.backup.review_title": "バックアップの確認",
    "state_resilience.backup.title": "OAAM の状態をバックアップ",
    "state_resilience.copy": "OAAM ライブラリ、管理先の記録、復元用ファイル、画面設定をバックアップおよび復元します。",
    "state_resilience.destination.choose": "別のフォルダーを選択…",
    "state_resilience.destination.choose_button": "このバックアップフォルダーを使用",
    "state_resilience.destination.choose_failed": "バックアップフォルダーを選択できませんでした。",
    "state_resilience.destination.choose_title": "バックアップフォルダーを選択",
    "state_resilience.destination.custom": "選択したカスタムフォルダー",
    "state_resilience.destination.default": "OAAM 既定のバックアップフォルダー",
    "state_resilience.destination.label": "保存先",
    "state_resilience.destination.remembered": "前回成功したカスタムフォルダー：{path}",
    "state_resilience.destination.remembered_unavailable":
        "記憶したフォルダーは利用できません。別のフォルダーを選ぶか、OAAM の既定を使用してください。",
    "state_resilience.destination.use_remembered": "前回のカスタムフォルダーを使用",
    "state_resilience.encryption.compatible": "互換パスワード（弱い ZipCrypto）",
    "state_resilience.encryption.compatible_warning":
        "互換モードは弱い方式です。別のコンピューターで OAAM なしに ZIP を開く必要がある場合に限り使用してください。",
    "state_resilience.encryption.label": "アーカイブ暗号化",
    "state_resilience.encryption.none": "パスワードなし",
    "state_resilience.encryption.none_warning":
        "通常の ZIP には非公開の Agent アセットが含まれる場合があります。ファイルを持つ人は誰でも読めます。",
    "state_resilience.encryption.short.compatible_password": "互換パスワード",
    "state_resilience.encryption.short.none": "パスワードなし",
    "state_resilience.encryption.short.strong_password": "AES-256 パスワード",
    "state_resilience.encryption.strong": "強力なパスワード（AES-256）",
    "state_resilience.file.action_failed": "ファイルマネージャーの操作に失敗しました。",
    "state_resilience.file.confirm_trash": "このバックアップをゴミ箱へ移動",
    "state_resilience.file.copied": "バックアップのパスをコピーしました。",
    "state_resilience.file.copy": "パスをコピー",
    "state_resilience.file.copy_failed": "バックアップのパスをコピーできませんでした。",
    "state_resilience.file.reveal": "フォルダーに表示",
    "state_resilience.file.reveal_failed": "ファイルマネージャーで表示できませんでした。代わりにパスをコピーできます。",
    "state_resilience.file.revealed": "ファイルマネージャーにバックアップを表示しました。",
    "state_resilience.file.trash": "削除…",
    "state_resilience.file.trash_failed":
        "OAAM は最終的なゴミ箱の状態を確認できませんでした。一覧を更新してください。完全削除への切り替えは行っていません。",
    "state_resilience.file.trashed": "バックアップをゴミ箱へ移動しました。",
    "state_resilience.inventory.empty": "登録済みのバックアップはまだありません。",
    "state_resilience.inventory.summary": "登録済み {count} 件 · 現在利用可能 {bytes}",
    "state_resilience.inventory.title": "バックアップ一覧",
    "state_resilience.load_attention": "注意が必要な可能性のある詳細とともに、バックアップ情報を読み込みました。",
    "state_resilience.load_failed": "バックアップと復元の状態を読み込めませんでした。",
    "state_resilience.observation.available": "利用可能",
    "state_resilience.observation.missing": "見つかりません",
    "state_resilience.observation.replaced": "置換されています",
    "state_resilience.password.confirm": "パスワードの確認",
    "state_resilience.password.label": "パスワード",
    "state_resilience.password_invalid": "同じ空でないパスワードを 2 回入力してください。",
    "state_resilience.policy.ask": "毎回確認",
    "state_resilience.policy.back_up_first": "先にバックアップ",
    "state_resilience.policy.continue": "バックアップ確認なしで続行",
    "state_resilience.policy.copy": "Project の管理状態の変更や Asset の完全削除前に表示するバックアップの確認を選びます。",
    "state_resilience.policy.future_scope":
        "この設定で破壊的操作自体の正確な確認が省略されることはありません。既存の Deployment 上書きと修復は従来の確認を維持します。",
    "state_resilience.policy.label": "破壊的操作前のバックアップ確認",
    "state_resilience.policy.latest": "最新の利用可能なバックアップ：{time} · {path}",
    "state_resilience.policy.no_backup": "利用可能なバックアップは登録されていません。",
    "state_resilience.policy.save": "確認設定を保存",
    "state_resilience.policy.save_failed": "確認設定を保存できませんでした。更新してから再試行してください。",
    "state_resilience.policy.saved": "バックアップ確認設定を保存しました。",
    "state_resilience.policy.title": "破壊的なライフサイクル操作の前",
    "state_resilience.progress": "{stage}：{completed}/{total}",
    "state_resilience.refresh": "更新",
    "state_resilience.restore.activate": "この完全なバックアップを復元",
    "state_resilience.restore.activate_failed":
        "バックアップを有効化できませんでした。復元する前に、バックアップを選び直して再検査してください。",
    "state_resilience.restore.activate_interrupted":
        "結果が確定する前に復元接続が終了しました。OAAM を開き直して復旧状態を確認してください。",
    "state_resilience.restore.activated": "バックアップを有効化しました。OAAM は復元したデータで開き直します。",
    "state_resilience.restore.choose": "別の ZIP を選択…",
    "state_resilience.restore.choose_button": "このバックアップを確認",
    "state_resilience.restore.choose_failed": "バックアップアーカイブを選択できませんでした。",
    "state_resilience.restore.choose_title": "OAAM バックアップ ZIP を選択",
    "state_resilience.restore.confirm": "この完全なバックアップを確認し、現在の OAAM 状態が移動・保持されることを理解しました。",
    "state_resilience.restore.copy":
        "完全で検証済みのバックアップを 1 単位で復元します。テーブル、Asset、Deployment の選択的復元には対応しません。",
    "state_resilience.restore.inspect": "バックアップを検査",
    "state_resilience.restore.inspect_failed": "選択したアーカイブは有効で完全な OAAM バックアップではありません。",
    "state_resilience.restore.inspect_interrupted": "バックアップの検査が中断されました。",
    "state_resilience.restore.no_displaced": "以前の OAAM 状態はありません",
    "state_resilience.restore.no_source": "登録済みバックアップまたは別の OAAM バックアップ ZIP を選択してください。",
    "state_resilience.restore.password": "必要な場合はアーカイブのパスワード",
    "state_resilience.restore.restarting": "復元しました。以前の状態：{path}。OAAM を再起動しています。",
    "state_resilience.restore.review_ready": "完全なバックアップは有効です。有効化する前に内容を確認してください。",
    "state_resilience.restore.review_title": "復元の確認",
    "state_resilience.restore.title": "OAAM の状態を復元",
    "state_resilience.restore.use": "復元…",
    "state_resilience.restore.warning":
        "復元は OAAM の完全な状態単位を置き換えます。現在の状態は移動先の復旧ディレクトリに保持されます。",
    "state_resilience.review.available": "利用可能容量",
    "state_resilience.review.created": "作成日時",
    "state_resilience.review.desktop_preferences": "デスクトップ設定",
    "state_resilience.review.destination": "保存先",
    "state_resilience.review.destination_existing": "既存フォルダー: {path}",
    "state_resilience.review.destination_planned": "作成予定のフォルダー: {path}",
    "state_resilience.review.files": "ファイル数",
    "state_resilience.review.included": "含まれます",
    "state_resilience.review.logical_size": "論理サイズ",
    "state_resilience.review.not_included": "含まれません",
    "state_resilience.stage.activation": "有効化中",
    "state_resilience.stage.commit": "確定中",
    "state_resilience.stage.encryption": "暗号化中",
    "state_resilience.stage.inspection": "検査中",
    "state_resilience.stage.inventory": "一覧作成中",
    "state_resilience.stage.packing": "圧縮中",
    "state_resilience.stage.quiescence": "実行中の作業を停止中",
    "state_resilience.stage.restart_required": "再起動が必要",
    "state_resilience.stage.verification": "検証中",
    "state_resilience.title": "データ保護",
    "state_resilience.recovery.eyebrow": "復元が必要です",
    "state_resilience.recovery.title": "OAAM の状態を復元",
    "state_resilience.recovery.reason.missing_database":
        "既存の OAAM プロファイルに State データベースがありません。通常の操作は引き続きブロックされます。",
    "state_resilience.recovery.reason.corrupt_database":
        "OAAM State データベースが破損しているか読み取れません。通常の操作は引き続きブロックされます。",
    "state_resilience.recovery.reason.incompatible_database":
        "OAAM State データベースはこのビルドと互換性がありません。通常の操作は引き続きブロックされます。",
    "state_resilience.recovery.reason.restore_reconciliation":
        "中断された State 復元を照合するまで、通常の操作を再開できません。",
    "state_resilience.recovery_only":
        "復旧モードでは、選択した完全なバックアップの確認と復元だけを行えます。復元を承認するまで通常の OAAM データは変更されません。",
    "state_resilience.unavailable": "現在の OAAM セッションではバックアップと復元を利用できません。",
    "settings.close": "設定を閉じる",
    "settings.back_to_app": "アプリに戻る",
    "settings.eyebrow": "アプリケーション設定",
    "settings.general.copy": "これらの設定は、デスクトップ アプリの外観と操作方法だけを変更します。",
    "settings.general.title": "一般",
    "settings.project_management.copy": "OAAM で再び管理する場合は、停止した Project をここで復元できます。",
    "settings.project_management.empty": "管理を停止した Project はありません。",
    "settings.project_management.title": "Project 管理",
    ...JAPANESE_DESKTOP_DIAGNOSTICS_MESSAGES,
    ...JAPANESE_DESKTOP_MAINTENANCE_MESSAGES,
    ...JAPANESE_DESKTOP_PRESENTATION_MESSAGES,
    ...JAPANESE_DESKTOP_SEARCH_MESSAGES,
    "settings.open": "設定",
    "settings.privacy.copy": "OAAM は、許可された場所だけを確認します。",
    "settings.privacy.no_session": "OAAM は、チャット内容、認証情報、拡張機能、一時的な会話データをアセットとして収集しません。",
    "settings.privacy.no_write": "スキャンとインポートでは、AI コーディングツールが使用するファイルを変更しません。",
    "settings.privacy.read": "OAAM は、選択した場所または継続確認を依頼した場所だけを読み取ります。",
    "settings.privacy.title": "プライバシーとデータアクセス",
    "settings.runtime.copy":
        "設定から実行するスキャンの既定範囲と保存済みの場所を管理します。Asset のインポートは別のガイド付きインポートから開始します。",
    "settings.runtime.guided_setup": "インポートを開始",
    "settings.runtime.title": "場所と AI コーディングツール",
    "tray.host.failed": "OAAM：利用不可",
    "tray.host.ready": "OAAM：実行中",
    "tray.host.recovering": "OAAM：復旧中",
    "tray.host.starting": "OAAM：起動中",
    "tray.quit": "OAAM を終了",
    "tray.show": "OAAM を表示",
    "tray.tooltip": "Open Agent Asset Manager を開く",
    "settings.title": "設定",
    "settings.search": "設定を検索",
    "settings.search_no_results": "一致する設定はありません。",
    "window.about.detail": "バージョン {version}。 OAAM は、明示的な制御下でエージェント資産のポータブル性を維持します。",
    "window.about.title": "OAAMについて",
    "window.action.failed": "ウィンドウコマンドを完了できませんでした。",
    "window.chrome.title": "Open Agent Asset Manager",
    "window.menu.edit": "編集",
    "window.menu.edit.copy": "コピー",
    "window.menu.edit.cut": "カット",
    "window.menu.edit.delete": "削除",
    "window.menu.edit.paste": "ペースト",
    "window.menu.edit.redo": "やり直し",
    "window.menu.edit.select_all": "すべて選択",
    "window.menu.edit.settings": "設定…",
    "window.menu.edit.undo": "元に戻す",
    "window.menu.file": "ファイル",
    "window.menu.file.add_project": "プロジェクトを追加…",
    "window.menu.file.exit": "終了",
    "window.menu.file.hide_to_tray": "トレイに隠す",
    "window.menu.help": "ヘルプ",
    "window.menu.help.about": "OAAMについて",
    "window.menu.view": "表示",
    "window.menu.view.back": "戻る",
    "window.menu.view.forward": "進む",
    "window.menu.view.full_screen": "全画面表示の切り替え",
    "window.menu.view.inspector": "詳細パネルの切り替え",
    "window.menu.view.sidebar": "サイドバーの切り替え",
    "window.menu.view.zoom_in": "ズームイン",
    "window.menu.view.zoom_out": "ズームアウト",
    "window.menu.view.zoom_reset": "実際のサイズ",
    "window.navigation.back": "戻る",
    "window.navigation.forward": "進む",
    "window.inspector.toggle": "Asset 詳細パネルの切り替え",
    "window.sidebar.toggle": "サイドバーの切り替え",
} as const satisfies Readonly<Record<DesktopMessageId, string>>;
