export const DESKTOP_DIAGNOSTICS_MESSAGE_IDS = [
    "diagnostics.copy",
    "diagnostics.health.copy",
    "diagnostics.health.degraded",
    "diagnostics.health.healthy",
    "diagnostics.health.host",
    "diagnostics.health.lifecycle.draining",
    "diagnostics.health.lifecycle.failed",
    "diagnostics.health.lifecycle.ready",
    "diagnostics.health.lifecycle.starting",
    "diagnostics.health.lifecycle.stopped",
    "diagnostics.health.loading",
    "diagnostics.health.log",
    "diagnostics.health.log_reason.cleanup_failed",
    "diagnostics.health.log_reason.unsafe_storage",
    "diagnostics.health.log_reason.write_failed",
    "diagnostics.health.log_state.active",
    "diagnostics.health.log_state.disabled",
    "diagnostics.health.log_state.suspended",
    "diagnostics.health.retained",
    "diagnostics.health.startup",
    "diagnostics.health.startup_mode.normal",
    "diagnostics.health.startup_mode.state_recovery",
    "diagnostics.health.title",
    "diagnostics.health.unhealthy",
    "diagnostics.load_attention",
    "diagnostics.load_failed",
    "diagnostics.log.active",
    "diagnostics.log.clear",
    "diagnostics.log.clear_confirm",
    "diagnostics.log.clear_failed",
    "diagnostics.log.cleared",
    "diagnostics.log.copy",
    "diagnostics.log.disabled",
    "diagnostics.log.enabled",
    "diagnostics.log.invalid",
    "diagnostics.log.maximum_mib",
    "diagnostics.log.retention_days",
    "diagnostics.log.save",
    "diagnostics.log.save_failed",
    "diagnostics.log.saved",
    "diagnostics.log.title",
    "diagnostics.performance.confirm",
    "diagnostics.performance.copy",
    "diagnostics.performance.discard",
    "diagnostics.performance.discard_failed",
    "diagnostics.performance.failure.cleanup_failed",
    "diagnostics.performance.failure.initialization_failed",
    "diagnostics.performance.failure.start_failed",
    "diagnostics.performance.failure.stop_failed",
    "diagnostics.performance.failure.trace_too_large",
    "diagnostics.performance.ready",
    "diagnostics.performance.recording",
    "diagnostics.performance.remaining",
    "diagnostics.performance.retry_stop",
    "diagnostics.performance.save",
    "diagnostics.performance.save.choose_button",
    "diagnostics.performance.save.choose_title",
    "diagnostics.performance.save_failed",
    "diagnostics.performance.saved",
    "diagnostics.performance.start",
    "diagnostics.performance.start_failed",
    "diagnostics.performance.stop",
    "diagnostics.performance.stop_failed",
    "diagnostics.performance.title",
    "diagnostics.performance.unavailable",
    "diagnostics.performance.warning",
    "diagnostics.recovery.copy",
    "diagnostics.recovery.maintenance",
    "diagnostics.recovery.state",
    "diagnostics.recovery.title",
    "diagnostics.refresh",
    "diagnostics.reindex.action",
    "diagnostics.reindex.complete",
    "diagnostics.reindex.copy",
    "diagnostics.reindex.failed",
    "diagnostics.reindex.title",
    "diagnostics.support.archive_hash",
    "diagnostics.support.hash_copy",
    "diagnostics.support.hash_copied",
    "diagnostics.support.hash_copy_failed",
    "diagnostics.support.category.adapter_capabilities",
    "diagnostics.support.category.documentation",
    "diagnostics.support.category.health",
    "diagnostics.support.category.local_paths",
    "diagnostics.support.category.manifest",
    "diagnostics.support.category.ordinary_log",
    "diagnostics.support.category.product",
    "diagnostics.support.copy",
    "diagnostics.support.export",
    "diagnostics.support.export.choose_button",
    "diagnostics.support.export.choose_title",
    "diagnostics.support.export_failed",
    "diagnostics.support.exported",
    "diagnostics.support.extended",
    "diagnostics.support.inspect",
    "diagnostics.support.inspect_failed",
    "diagnostics.support.log_full",
    "diagnostics.support.log_summary",
    "diagnostics.support.log_truncated",
    "diagnostics.support.mode",
    "diagnostics.support.review",
    "diagnostics.support.entry_size",
    "diagnostics.support.review_ready",
    "diagnostics.support.standard",
    "diagnostics.support.title",
    "diagnostics.title",
    "diagnostics.unavailable",
] as const;

export type DesktopDiagnosticsMessageId = (typeof DESKTOP_DIAGNOSTICS_MESSAGE_IDS)[number];
type DesktopDiagnosticsMessages = Readonly<Record<DesktopDiagnosticsMessageId, string>>;

export const ENGLISH_DESKTOP_DIAGNOSTICS_MESSAGES = {
    "diagnostics.copy":
        "Inspect operational health, bounded logs, support evidence, performance traces, and repair entry points.",
    "diagnostics.health.copy": "Current OAAM readiness and ordinary operational-log status.",
    "diagnostics.health.degraded": "Degraded",
    "diagnostics.health.healthy": "Healthy",
    "diagnostics.health.host": "OAAM readiness",
    "diagnostics.health.lifecycle.draining": "Finishing active work",
    "diagnostics.health.lifecycle.failed": "Failed",
    "diagnostics.health.lifecycle.ready": "Ready",
    "diagnostics.health.lifecycle.starting": "Starting",
    "diagnostics.health.lifecycle.stopped": "Stopped",
    "diagnostics.health.loading": "Loading current health…",
    "diagnostics.health.log": "Ordinary log",
    "diagnostics.health.log_reason.cleanup_failed": "OAAM could not clean up the ordinary log within its limits.",
    "diagnostics.health.log_reason.unsafe_storage": "The local log location did not pass its safety check.",
    "diagnostics.health.log_reason.write_failed": "OAAM could not write the ordinary log.",
    "diagnostics.health.log_state.active": "Logging active",
    "diagnostics.health.log_state.disabled": "Disabled by your setting",
    "diagnostics.health.log_state.suspended": "Paused",
    "diagnostics.health.retained": "Retained log size",
    "diagnostics.health.startup": "Startup mode",
    "diagnostics.health.startup_mode.normal": "Normal startup",
    "diagnostics.health.startup_mode.state_recovery": "Recovery mode",
    "diagnostics.health.title": "Operational health",
    "diagnostics.health.unhealthy": "Unhealthy",
    "diagnostics.load_attention": "Diagnostics loaded with details that may need attention.",
    "diagnostics.load_failed": "Diagnostics could not be loaded.",
    "diagnostics.log.active": "Ordinary logging is active.",
    "diagnostics.log.clear": "Permanently clear log",
    "diagnostics.log.clear_confirm": "I understand that retained ordinary log segments will be permanently removed.",
    "diagnostics.log.clear_failed": "The ordinary log could not be cleared.",
    "diagnostics.log.cleared": "Removed {count} log segments ({size}).",
    "diagnostics.log.copy": "Configure the bounded, local operational log. It is not a chat transcript.",
    "diagnostics.log.disabled": "Ordinary logging is disabled.",
    "diagnostics.log.enabled": "Enable ordinary logging",
    "diagnostics.log.invalid": "Retention must be 1–14 days and size must be 0.0625–50 MiB.",
    "diagnostics.log.maximum_mib": "Maximum size (MiB)",
    "diagnostics.log.retention_days": "Retention (days)",
    "diagnostics.log.save": "Save log settings",
    "diagnostics.log.save_failed": "The ordinary-log settings could not be saved.",
    "diagnostics.log.saved": "Ordinary-log settings were saved.",
    "diagnostics.log.title": "Ordinary operational log",
    "diagnostics.performance.confirm":
        "I understand this trace may include function names, file paths, and personal information.",
    "diagnostics.performance.copy": "Record a bounded Electron performance trace only when troubleshooting this window.",
    "diagnostics.performance.discard": "Discard",
    "diagnostics.performance.discard_failed": "The trace could not be discarded.",
    "diagnostics.performance.failure.cleanup_failed": "The owned temporary trace could not be cleaned up.",
    "diagnostics.performance.failure.initialization_failed": "The protected trace workspace could not be initialized.",
    "diagnostics.performance.failure.start_failed": "Performance recording could not start.",
    "diagnostics.performance.failure.stop_failed": "Performance recording could not be stopped cleanly.",
    "diagnostics.performance.failure.trace_too_large": "The finalized trace exceeded the 128 MiB safety limit and was discarded.",
    "diagnostics.performance.ready": "Trace ready: {size}. It expires in {seconds} seconds.",
    "diagnostics.performance.recording": "Recording",
    "diagnostics.performance.remaining": "Stops automatically in {seconds} seconds.",
    "diagnostics.performance.retry_stop": "Retry stopping before starting another trace.",
    "diagnostics.performance.save": "Save trace…",
    "diagnostics.performance.save.choose_button": "Save trace",
    "diagnostics.performance.save.choose_title": "Save OAAM performance trace",
    "diagnostics.performance.save_failed": "The performance trace could not be saved.",
    "diagnostics.performance.saved": "The performance trace was saved to {path}.",
    "diagnostics.performance.start": "Start recording",
    "diagnostics.performance.start_failed": "Performance recording could not start.",
    "diagnostics.performance.stop": "Stop recording",
    "diagnostics.performance.stop_failed": "Performance recording could not be stopped.",
    "diagnostics.performance.title": "Performance recording",
    "diagnostics.performance.unavailable": "Performance-recording state is unavailable.",
    "diagnostics.performance.warning":
        "Recording is off by default, requires fresh confirmation, stops after 120 seconds, and is never uploaded automatically.",
    "diagnostics.recovery.copy": "Open the existing owners for backup/restore or local application maintenance.",
    "diagnostics.recovery.maintenance": "Open local maintenance",
    "diagnostics.recovery.state": "Open backup and restore",
    "diagnostics.recovery.title": "Recovery and maintenance",
    "diagnostics.refresh": "Refresh",
    "diagnostics.reindex.action": "Rebuild Asset index",
    "diagnostics.reindex.complete": "Reindexed {indexed} Assets; skipped {skipped}.",
    "diagnostics.reindex.copy": "Rebuild the database index from authoritative Asset and Version manifests.",
    "diagnostics.reindex.failed": "The Asset index could not be rebuilt.",
    "diagnostics.reindex.title": "Asset reindex",
    "diagnostics.support.copy": "Review the exact redacted inventory before choosing where to save a local ZIP.",
    "diagnostics.support.category.adapter_capabilities": "Declared tool capabilities",
    "diagnostics.support.category.documentation": "Bundle documentation",
    "diagnostics.support.category.health": "OAAM health",
    "diagnostics.support.category.local_paths": "Local path labels",
    "diagnostics.support.category.manifest": "Bundle manifest",
    "diagnostics.support.category.ordinary_log": "Ordinary log",
    "diagnostics.support.category.product": "Product information",
    "diagnostics.support.export": "Export reviewed bundle…",
    "diagnostics.support.export.choose_button": "Export bundle",
    "diagnostics.support.export.choose_title": "Export OAAM support bundle",
    "diagnostics.support.export_failed": "The reviewed support bundle could not be exported.",
    "diagnostics.support.exported": "The support bundle was exported to {path}.",
    "diagnostics.support.extended": "Extended (includes local path labels)",
    "diagnostics.support.inspect": "Review bundle",
    "diagnostics.support.inspect_failed": "The support bundle could not be inspected. Choose Review bundle to try again.",
    "diagnostics.support.mode": "Bundle detail",
    "diagnostics.support.archive_hash": "Archive SHA-256",
    "diagnostics.support.hash_copy": "Copy archive hash",
    "diagnostics.support.hash_copied": "Archive hash copied",
    "diagnostics.support.hash_copy_failed": "Archive hash could not be copied",
    "diagnostics.support.log_full": "The complete retained log is included.",
    "diagnostics.support.log_summary":
        "Included {includedSegments} of {retainedSegments} segments ({includedSize} of {retainedSize}).",
    "diagnostics.support.log_truncated": "The retained log was truncated for this bundle.",
    "diagnostics.support.review": "{count} reviewed files · compressed ZIP {size}",
    "diagnostics.support.entry_size": "{size} uncompressed",
    "diagnostics.support.review_ready": "The support-bundle inventory is ready for review.",
    "diagnostics.support.standard": "Standard",
    "diagnostics.support.title": "Support bundle",
    "diagnostics.title": "Diagnostics and support",
    "diagnostics.unavailable": "This OAAM session does not provide this diagnostic action.",
} as const satisfies DesktopDiagnosticsMessages;

export const GERMAN_DESKTOP_DIAGNOSTICS_MESSAGES = {
    "diagnostics.copy":
        "Betriebszustand, begrenzte Protokolle, Support-Nachweise, Leistungsspuren und Reparatureinstiege prüfen.",
    "diagnostics.health.copy": "Aktuelle OAAM-Bereitschaft und Status des normalen Betriebsprotokolls.",
    "diagnostics.health.degraded": "Beeinträchtigt",
    "diagnostics.health.healthy": "Fehlerfrei",
    "diagnostics.health.host": "OAAM-Bereitschaft",
    "diagnostics.health.lifecycle.draining": "Aktive Arbeit wird beendet",
    "diagnostics.health.lifecycle.failed": "Fehlgeschlagen",
    "diagnostics.health.lifecycle.ready": "Bereit",
    "diagnostics.health.lifecycle.starting": "Wird gestartet",
    "diagnostics.health.lifecycle.stopped": "Beendet",
    "diagnostics.health.loading": "Aktueller Zustand wird geladen…",
    "diagnostics.health.log": "Normales Protokoll",
    "diagnostics.health.log_reason.cleanup_failed":
        "OAAM konnte das normale Protokoll nicht innerhalb seiner Grenzen bereinigen.",
    "diagnostics.health.log_reason.unsafe_storage": "Der lokale Protokollspeicher hat die Sicherheitsprüfung nicht bestanden.",
    "diagnostics.health.log_reason.write_failed": "OAAM konnte das normale Protokoll nicht schreiben.",
    "diagnostics.health.log_state.active": "Protokollierung aktiv",
    "diagnostics.health.log_state.disabled": "Durch Ihre Einstellung deaktiviert",
    "diagnostics.health.log_state.suspended": "Angehalten",
    "diagnostics.health.retained": "Beibehaltene Protokollgröße",
    "diagnostics.health.startup": "Startmodus",
    "diagnostics.health.startup_mode.normal": "Normaler Start",
    "diagnostics.health.startup_mode.state_recovery": "Wiederherstellungsmodus",
    "diagnostics.health.title": "Betriebszustand",
    "diagnostics.health.unhealthy": "Fehlerhaft",
    "diagnostics.load_attention": "Diagnosedaten wurden mit möglicherweise relevanten Details geladen.",
    "diagnostics.load_failed": "Diagnosedaten konnten nicht geladen werden.",
    "diagnostics.log.active": "Das normale Protokoll ist aktiv.",
    "diagnostics.log.clear": "Protokoll endgültig löschen",
    "diagnostics.log.clear_confirm": "Ich verstehe, dass gespeicherte normale Protokollsegmente endgültig gelöscht werden.",
    "diagnostics.log.clear_failed": "Das normale Protokoll konnte nicht gelöscht werden.",
    "diagnostics.log.cleared": "{count} Protokollsegmente ({size}) wurden gelöscht.",
    "diagnostics.log.copy": "Konfigurieren Sie das begrenzte lokale Betriebsprotokoll. Es ist kein Chat-Transkript.",
    "diagnostics.log.disabled": "Das normale Protokoll ist deaktiviert.",
    "diagnostics.log.enabled": "Normales Protokoll aktivieren",
    "diagnostics.log.invalid": "Aufbewahrung: 1–14 Tage; Größe: 0,0625–50 MiB.",
    "diagnostics.log.maximum_mib": "Maximale Größe (MiB)",
    "diagnostics.log.retention_days": "Aufbewahrung (Tage)",
    "diagnostics.log.save": "Protokolleinstellungen speichern",
    "diagnostics.log.save_failed": "Die Protokolleinstellungen konnten nicht gespeichert werden.",
    "diagnostics.log.saved": "Die Protokolleinstellungen wurden gespeichert.",
    "diagnostics.log.title": "Normales Betriebsprotokoll",
    "diagnostics.performance.confirm":
        "Mir ist bewusst, dass die Spur Funktionsnamen, Dateipfade und persönliche Daten enthalten kann.",
    "diagnostics.performance.copy": "Zeichnet nur zur Fehleranalyse dieses Fensters eine begrenzte Electron-Leistungsspur auf.",
    "diagnostics.performance.discard": "Verwerfen",
    "diagnostics.performance.discard_failed": "Die Spur konnte nicht verworfen werden.",
    "diagnostics.performance.failure.cleanup_failed": "Die eigene temporäre Spur konnte nicht bereinigt werden.",
    "diagnostics.performance.failure.initialization_failed":
        "Der geschützte Spur-Arbeitsbereich konnte nicht initialisiert werden.",
    "diagnostics.performance.failure.start_failed": "Die Leistungsaufzeichnung konnte nicht gestartet werden.",
    "diagnostics.performance.failure.stop_failed": "Die Leistungsaufzeichnung konnte nicht sauber beendet werden.",
    "diagnostics.performance.failure.trace_too_large": "Die Spur überschritt 128 MiB und wurde verworfen.",
    "diagnostics.performance.ready": "Spur bereit: {size}. Ablauf in {seconds} Sekunden.",
    "diagnostics.performance.recording": "Aufzeichnung",
    "diagnostics.performance.remaining": "Automatischer Stopp in {seconds} Sekunden.",
    "diagnostics.performance.retry_stop": "Beenden Sie die Aufzeichnung erneut, bevor Sie eine neue starten.",
    "diagnostics.performance.save": "Spur speichern…",
    "diagnostics.performance.save.choose_button": "Spur speichern",
    "diagnostics.performance.save.choose_title": "OAAM-Leistungsspur speichern",
    "diagnostics.performance.save_failed": "Die Leistungsspur konnte nicht gespeichert werden.",
    "diagnostics.performance.saved": "Die Leistungsspur wurde unter {path} gespeichert.",
    "diagnostics.performance.start": "Aufzeichnung starten",
    "diagnostics.performance.start_failed": "Die Leistungsaufzeichnung konnte nicht gestartet werden.",
    "diagnostics.performance.stop": "Aufzeichnung beenden",
    "diagnostics.performance.stop_failed": "Die Leistungsaufzeichnung konnte nicht beendet werden.",
    "diagnostics.performance.title": "Leistungsaufzeichnung",
    "diagnostics.performance.unavailable": "Der Status der Leistungsaufzeichnung ist nicht verfügbar.",
    "diagnostics.performance.warning":
        "Standardmäßig aus; jede Aufnahme erfordert eine neue Bestätigung, endet nach 120 Sekunden und wird nie automatisch hochgeladen.",
    "diagnostics.recovery.copy": "Öffnen Sie die vorhandenen Bereiche für Sicherung/Wiederherstellung oder lokale Wartung.",
    "diagnostics.recovery.maintenance": "Lokale Wartung öffnen",
    "diagnostics.recovery.state": "Sicherung und Wiederherstellung öffnen",
    "diagnostics.recovery.title": "Wiederherstellung und Wartung",
    "diagnostics.refresh": "Aktualisieren",
    "diagnostics.reindex.action": "Asset-Index neu aufbauen",
    "diagnostics.reindex.complete": "{indexed} Assets indiziert; {skipped} übersprungen.",
    "diagnostics.reindex.copy": "Baut den Datenbankindex aus maßgeblichen Asset- und Versionsmanifesten neu auf.",
    "diagnostics.reindex.failed": "Der Asset-Index konnte nicht neu aufgebaut werden.",
    "diagnostics.reindex.title": "Asset-Neuindizierung",
    "diagnostics.support.copy": "Prüfen Sie den genauen bereinigten Inhalt, bevor Sie eine lokale ZIP-Datei speichern.",
    "diagnostics.support.category.adapter_capabilities": "Deklarierte Tool-Funktionen",
    "diagnostics.support.category.documentation": "Paketdokumentation",
    "diagnostics.support.category.health": "OAAM-Zustand",
    "diagnostics.support.category.local_paths": "Lokale Pfadbezeichnungen",
    "diagnostics.support.category.manifest": "Paketmanifest",
    "diagnostics.support.category.ordinary_log": "Normales Betriebsprotokoll",
    "diagnostics.support.category.product": "Produktinformationen",
    "diagnostics.support.export": "Geprüftes Paket exportieren…",
    "diagnostics.support.export.choose_button": "Paket exportieren",
    "diagnostics.support.export.choose_title": "OAAM-Supportpaket exportieren",
    "diagnostics.support.export_failed": "Das geprüfte Supportpaket konnte nicht exportiert werden.",
    "diagnostics.support.exported": "Das Supportpaket wurde nach {path} exportiert.",
    "diagnostics.support.extended": "Erweitert (mit lokalen Pfadbezeichnungen)",
    "diagnostics.support.inspect": "Paket prüfen",
    "diagnostics.support.inspect_failed":
        "Das Supportpaket konnte nicht geprüft werden. Wählen Sie „Paket prüfen“, um es erneut zu versuchen.",
    "diagnostics.support.mode": "Paketdetail",
    "diagnostics.support.archive_hash": "Archiv-SHA-256",
    "diagnostics.support.hash_copy": "Archiv-Hash kopieren",
    "diagnostics.support.hash_copied": "Archiv-Hash kopiert",
    "diagnostics.support.hash_copy_failed": "Archiv-Hash konnte nicht kopiert werden",
    "diagnostics.support.log_full": "Das vollständige aufbewahrte Protokoll ist enthalten.",
    "diagnostics.support.log_summary":
        "{includedSegments} von {retainedSegments} Segmenten enthalten ({includedSize} von {retainedSize}).",
    "diagnostics.support.log_truncated": "Das aufbewahrte Protokoll wurde für dieses Paket gekürzt.",
    "diagnostics.support.review": "{count} geprüfte Dateien · komprimierte ZIP {size}",
    "diagnostics.support.entry_size": "{size} unkomprimiert",
    "diagnostics.support.review_ready": "Der Inhalt des Supportpakets kann geprüft werden.",
    "diagnostics.support.standard": "Standard",
    "diagnostics.support.title": "Supportpaket",
    "diagnostics.title": "Diagnose und Support",
    "diagnostics.unavailable": "Diese OAAM-Sitzung stellt diese Diagnoseaktion nicht bereit.",
} as const satisfies DesktopDiagnosticsMessages;

export const JAPANESE_DESKTOP_DIAGNOSTICS_MESSAGES = {
    "diagnostics.copy": "稼働状態、限定ログ、サポート証拠、性能トレース、修復入口を確認します。",
    "diagnostics.health.copy": "OAAM の現在の準備状態と通常運用ログの状態です。",
    "diagnostics.health.degraded": "低下",
    "diagnostics.health.healthy": "正常",
    "diagnostics.health.host": "OAAM の準備状態",
    "diagnostics.health.lifecycle.draining": "実行中の処理を終了中",
    "diagnostics.health.lifecycle.failed": "失敗",
    "diagnostics.health.lifecycle.ready": "準備完了",
    "diagnostics.health.lifecycle.starting": "起動中",
    "diagnostics.health.lifecycle.stopped": "停止",
    "diagnostics.health.loading": "現在の状態を読み込み中…",
    "diagnostics.health.log": "通常ログ",
    "diagnostics.health.log_reason.cleanup_failed": "通常ログを制限内に整理できませんでした。",
    "diagnostics.health.log_reason.unsafe_storage": "ローカルログの保存先が安全性チェックを通過しませんでした。",
    "diagnostics.health.log_reason.write_failed": "通常ログを書き込めませんでした。",
    "diagnostics.health.log_state.active": "ログ記録中",
    "diagnostics.health.log_state.disabled": "設定により無効",
    "diagnostics.health.log_state.suspended": "一時停止",
    "diagnostics.health.retained": "保持ログサイズ",
    "diagnostics.health.startup": "起動モード",
    "diagnostics.health.startup_mode.normal": "通常起動",
    "diagnostics.health.startup_mode.state_recovery": "復旧モード",
    "diagnostics.health.title": "稼働状態",
    "diagnostics.health.unhealthy": "異常",
    "diagnostics.load_attention": "注意が必要な可能性のある詳細とともに、診断情報を読み込みました。",
    "diagnostics.load_failed": "診断情報を読み込めませんでした。",
    "diagnostics.log.active": "通常ログは有効です。",
    "diagnostics.log.clear": "ログを完全に消去",
    "diagnostics.log.clear_confirm": "保持された通常ログセグメントが完全に削除されることを理解しました。",
    "diagnostics.log.clear_failed": "通常ログを消去できませんでした。",
    "diagnostics.log.cleared": "{count} 個のログセグメント（{size}）を削除しました。",
    "diagnostics.log.copy": "限定されたローカル運用ログを設定します。チャットの transcript ではありません。",
    "diagnostics.log.disabled": "通常ログは無効です。",
    "diagnostics.log.enabled": "通常ログを有効化",
    "diagnostics.log.invalid": "保持期間は 1～14 日、サイズは 0.0625～50 MiB にしてください。",
    "diagnostics.log.maximum_mib": "最大サイズ（MiB）",
    "diagnostics.log.retention_days": "保持期間（日）",
    "diagnostics.log.save": "ログ設定を保存",
    "diagnostics.log.save_failed": "通常ログ設定を保存できませんでした。",
    "diagnostics.log.saved": "通常ログ設定を保存しました。",
    "diagnostics.log.title": "通常運用ログ",
    "diagnostics.performance.confirm": "トレースに関数名、ファイルパス、個人情報が含まれる可能性を理解しました。",
    "diagnostics.performance.copy": "このウィンドウの問題調査時だけ、限定された Electron 性能トレースを記録します。",
    "diagnostics.performance.discard": "破棄",
    "diagnostics.performance.discard_failed": "トレースを破棄できませんでした。",
    "diagnostics.performance.failure.cleanup_failed": "OAAM 所有の一時トレースを消去できませんでした。",
    "diagnostics.performance.failure.initialization_failed": "保護されたトレース領域を初期化できませんでした。",
    "diagnostics.performance.failure.start_failed": "性能記録を開始できませんでした。",
    "diagnostics.performance.failure.stop_failed": "性能記録を正常に停止できませんでした。",
    "diagnostics.performance.failure.trace_too_large": "完成したトレースが 128 MiB を超えたため破棄しました。",
    "diagnostics.performance.ready": "トレース準備完了：{size}。{seconds} 秒後に期限切れになります。",
    "diagnostics.performance.recording": "記録中",
    "diagnostics.performance.remaining": "{seconds} 秒後に自動停止します。",
    "diagnostics.performance.retry_stop": "新しい記録の前に停止を再試行してください。",
    "diagnostics.performance.save": "トレースを保存…",
    "diagnostics.performance.save.choose_button": "トレースを保存",
    "diagnostics.performance.save.choose_title": "OAAM 性能トレースを保存",
    "diagnostics.performance.save_failed": "性能トレースを保存できませんでした。",
    "diagnostics.performance.saved": "性能トレースを {path} に保存しました。",
    "diagnostics.performance.start": "記録を開始",
    "diagnostics.performance.start_failed": "性能記録を開始できませんでした。",
    "diagnostics.performance.stop": "記録を停止",
    "diagnostics.performance.stop_failed": "性能記録を停止できませんでした。",
    "diagnostics.performance.title": "性能記録",
    "diagnostics.performance.unavailable": "性能記録の状態を取得できません。",
    "diagnostics.performance.warning": "既定では無効です。毎回確認が必要で、120 秒後に停止し、自動アップロードは行いません。",
    "diagnostics.recovery.copy": "バックアップ／復元またはローカル保守の既存画面を開きます。",
    "diagnostics.recovery.maintenance": "ローカル保守を開く",
    "diagnostics.recovery.state": "バックアップと復元を開く",
    "diagnostics.recovery.title": "復元と保守",
    "diagnostics.refresh": "更新",
    "diagnostics.reindex.action": "Asset インデックスを再構築",
    "diagnostics.reindex.complete": "{indexed} 件を再インデックス化し、{skipped} 件をスキップしました。",
    "diagnostics.reindex.copy": "正規の Asset および Version manifest からデータベースインデックスを再構築します。",
    "diagnostics.reindex.failed": "Asset インデックスを再構築できませんでした。",
    "diagnostics.reindex.title": "Asset 再インデックス",
    "diagnostics.support.copy": "ローカル ZIP の保存場所を選ぶ前に、秘匿化された正確な内容を確認します。",
    "diagnostics.support.category.adapter_capabilities": "ツールの宣言済み機能",
    "diagnostics.support.category.documentation": "Bundle の説明",
    "diagnostics.support.category.health": "OAAM の状態",
    "diagnostics.support.category.local_paths": "ローカルパスのラベル",
    "diagnostics.support.category.manifest": "Bundle manifest",
    "diagnostics.support.category.ordinary_log": "通常ログ",
    "diagnostics.support.category.product": "製品情報",
    "diagnostics.support.export": "確認済み bundle を出力…",
    "diagnostics.support.export.choose_button": "Bundle を出力",
    "diagnostics.support.export.choose_title": "OAAM support bundle を出力",
    "diagnostics.support.export_failed": "確認済み support bundle を出力できませんでした。",
    "diagnostics.support.exported": "Support bundle を {path} に出力しました。",
    "diagnostics.support.extended": "拡張（ローカルパスのラベルを含む）",
    "diagnostics.support.inspect": "Bundle を確認",
    "diagnostics.support.inspect_failed": "Support bundle を確認できませんでした。「Bundle を確認」でやり直してください。",
    "diagnostics.support.mode": "Bundle の詳細",
    "diagnostics.support.archive_hash": "Archive SHA-256",
    "diagnostics.support.hash_copy": "Archive hash をコピー",
    "diagnostics.support.hash_copied": "Archive hash をコピーしました",
    "diagnostics.support.hash_copy_failed": "Archive hash をコピーできませんでした",
    "diagnostics.support.log_full": "保持されているログをすべて含みます。",
    "diagnostics.support.log_summary":
        "{retainedSegments} セグメント中 {includedSegments} 件を含みます（{retainedSize} 中 {includedSize}）。",
    "diagnostics.support.log_truncated": "この bundle では保持ログが切り詰められています。",
    "diagnostics.support.review": "確認済み {count} ファイル · 圧縮 ZIP {size}",
    "diagnostics.support.entry_size": "{size}（圧縮前）",
    "diagnostics.support.review_ready": "Support bundle の内容を確認できます。",
    "diagnostics.support.standard": "標準",
    "diagnostics.support.title": "サポート資料",
    "diagnostics.title": "診断とサポート",
    "diagnostics.unavailable": "この OAAM セッションでは、この診断操作を利用できません。",
} as const satisfies DesktopDiagnosticsMessages;

export const SIMPLIFIED_CHINESE_DESKTOP_DIAGNOSTICS_MESSAGES = {
    "diagnostics.copy": "检查运行健康、有限日志、支持证据、性能追踪与修复入口。",
    "diagnostics.health.copy": "OAAM 当前的就绪状态和普通运行日志状态。",
    "diagnostics.health.degraded": "已降级",
    "diagnostics.health.healthy": "健康",
    "diagnostics.health.host": "OAAM 就绪状态",
    "diagnostics.health.lifecycle.draining": "正在结束现有工作",
    "diagnostics.health.lifecycle.failed": "已失败",
    "diagnostics.health.lifecycle.ready": "已就绪",
    "diagnostics.health.lifecycle.starting": "正在启动",
    "diagnostics.health.lifecycle.stopped": "已停止",
    "diagnostics.health.loading": "正在加载当前状态…",
    "diagnostics.health.log": "普通日志",
    "diagnostics.health.log_reason.cleanup_failed": "OAAM 无法在容量与期限限制内清理普通日志。",
    "diagnostics.health.log_reason.unsafe_storage": "本地日志位置未通过安全检查。",
    "diagnostics.health.log_reason.write_failed": "OAAM 无法写入普通日志。",
    "diagnostics.health.log_state.active": "正在记录",
    "diagnostics.health.log_state.disabled": "已按你的设置停用",
    "diagnostics.health.log_state.suspended": "已暂停",
    "diagnostics.health.retained": "已保留日志大小",
    "diagnostics.health.startup": "启动模式",
    "diagnostics.health.startup_mode.normal": "正常启动",
    "diagnostics.health.startup_mode.state_recovery": "恢复模式",
    "diagnostics.health.title": "运行健康",
    "diagnostics.health.unhealthy": "不健康",
    "diagnostics.load_attention": "诊断信息已加载，其中有一些可能需要注意的详情。",
    "diagnostics.load_failed": "无法加载诊断信息。",
    "diagnostics.log.active": "普通日志已启用。",
    "diagnostics.log.clear": "永久清除日志",
    "diagnostics.log.clear_confirm": "我知道已保留的普通日志片段会被永久删除。",
    "diagnostics.log.clear_failed": "无法清除普通日志。",
    "diagnostics.log.cleared": "已删除 {count} 个日志片段（{size}）。",
    "diagnostics.log.copy": "配置有容量与期限限制的本地运行日志。它不是聊天 transcript。",
    "diagnostics.log.disabled": "普通日志已禁用。",
    "diagnostics.log.enabled": "启用普通日志",
    "diagnostics.log.invalid": "保留期限必须为 1–14 天，大小必须为 0.0625–50 MiB。",
    "diagnostics.log.maximum_mib": "最大大小（MiB）",
    "diagnostics.log.retention_days": "保留期限（天）",
    "diagnostics.log.save": "保存日志设置",
    "diagnostics.log.save_failed": "无法保存普通日志设置。",
    "diagnostics.log.saved": "普通日志设置已保存。",
    "diagnostics.log.title": "普通运行日志",
    "diagnostics.performance.confirm": "我知道追踪可能包含函数名、文件路径和个人信息。",
    "diagnostics.performance.copy": "仅在排查当前窗口性能问题时录制有界 Electron 性能追踪。",
    "diagnostics.performance.discard": "丢弃",
    "diagnostics.performance.discard_failed": "无法丢弃性能追踪。",
    "diagnostics.performance.failure.cleanup_failed": "无法清理 OAAM 自有的临时追踪。",
    "diagnostics.performance.failure.initialization_failed": "无法初始化受保护的追踪工作区。",
    "diagnostics.performance.failure.start_failed": "无法开始性能录制。",
    "diagnostics.performance.failure.stop_failed": "无法干净地停止性能录制。",
    "diagnostics.performance.failure.trace_too_large": "最终追踪超过 128 MiB 安全上限，已被丢弃。",
    "diagnostics.performance.ready": "追踪已就绪：{size}；将在 {seconds} 秒后过期。",
    "diagnostics.performance.recording": "正在录制",
    "diagnostics.performance.remaining": "将在 {seconds} 秒后自动停止。",
    "diagnostics.performance.retry_stop": "开始下一次追踪前，请重试停止操作。",
    "diagnostics.performance.save": "保存追踪…",
    "diagnostics.performance.save.choose_button": "保存追踪",
    "diagnostics.performance.save.choose_title": "保存 OAAM 性能追踪",
    "diagnostics.performance.save_failed": "无法保存性能追踪。",
    "diagnostics.performance.saved": "性能追踪已保存到 {path}。",
    "diagnostics.performance.start": "开始录制",
    "diagnostics.performance.start_failed": "无法开始性能录制。",
    "diagnostics.performance.stop": "停止录制",
    "diagnostics.performance.stop_failed": "无法停止性能录制。",
    "diagnostics.performance.title": "性能录制",
    "diagnostics.performance.unavailable": "性能录制状态不可用。",
    "diagnostics.performance.warning": "默认关闭；每次启动都要重新确认，120 秒后自动停止，并且绝不会自动上传。",
    "diagnostics.recovery.copy": "打开已有的备份/恢复或本地应用维护功能。",
    "diagnostics.recovery.maintenance": "打开本地维护",
    "diagnostics.recovery.state": "打开备份与恢复",
    "diagnostics.recovery.title": "恢复与维护",
    "diagnostics.refresh": "刷新",
    "diagnostics.reindex.action": "重建 Asset 索引",
    "diagnostics.reindex.complete": "已重新索引 {indexed} 个 Asset；跳过 {skipped} 个。",
    "diagnostics.reindex.copy": "依据权威 Asset 与 Version manifest 重建数据库索引。",
    "diagnostics.reindex.failed": "无法重建 Asset 索引。",
    "diagnostics.reindex.title": "Asset 重索引",
    "diagnostics.support.copy": "选择本地 ZIP 保存位置前，先检查经过脱敏的精确内容清单。",
    "diagnostics.support.category.adapter_capabilities": "工具声明的能力",
    "diagnostics.support.category.documentation": "支持包说明",
    "diagnostics.support.category.health": "OAAM 健康状态",
    "diagnostics.support.category.local_paths": "本地路径标签",
    "diagnostics.support.category.manifest": "支持包清单",
    "diagnostics.support.category.ordinary_log": "普通运行日志",
    "diagnostics.support.category.product": "产品信息",
    "diagnostics.support.export": "导出已检查的支持包…",
    "diagnostics.support.export.choose_button": "导出支持包",
    "diagnostics.support.export.choose_title": "导出 OAAM 支持包",
    "diagnostics.support.export_failed": "无法导出已检查的支持包。",
    "diagnostics.support.exported": "支持包已导出到 {path}。",
    "diagnostics.support.extended": "扩展（包含本地路径标签）",
    "diagnostics.support.inspect": "检查支持包",
    "diagnostics.support.inspect_failed": "无法检查支持包。请点击“检查支持包”重试。",
    "diagnostics.support.mode": "支持包详细程度",
    "diagnostics.support.archive_hash": "归档 SHA-256",
    "diagnostics.support.hash_copy": "复制归档哈希",
    "diagnostics.support.hash_copied": "归档哈希已复制",
    "diagnostics.support.hash_copy_failed": "未能复制归档哈希",
    "diagnostics.support.log_full": "已包含全部保留日志。",
    "diagnostics.support.log_summary": "已包含 {includedSegments}/{retainedSegments} 个分段（{includedSize}/{retainedSize}）。",
    "diagnostics.support.log_truncated": "此支持包中的保留日志已截断。",
    "diagnostics.support.review": "已检查 {count} 个文件 · ZIP 压缩后 {size}",
    "diagnostics.support.entry_size": "压缩前 {size}",
    "diagnostics.support.review_ready": "支持包内容清单已可以检查。",
    "diagnostics.support.standard": "标准",
    "diagnostics.support.title": "支持包",
    "diagnostics.title": "诊断与支持",
    "diagnostics.unavailable": "当前 OAAM 会话未提供这项诊断操作。",
} as const satisfies DesktopDiagnosticsMessages;
