export const DESKTOP_ASSET_INSPECTOR_MESSAGE_IDS = [
    "library.compare.direction",
    "library.compare.change.added",
    "library.compare.change.removed",
    "library.compare.change.modified",
    "library.compare.change.unchanged",
    "library.compare.stage.diffing",
    "library.compare.stage.inventory",
    "library.compare.stage.loading",
    "library.compare.stage.starting",
    "library.files.kind.binary",
    "library.files.kind.text",
    "library.inspector.fingerprint_value",
    "library.inspector.metadata",
    "library.inspector.project_id",
    "library.inspector.project_unavailable",
    "library.inspector.views",
] as const;

export type DesktopAssetInspectorMessageId = (typeof DESKTOP_ASSET_INSPECTOR_MESSAGE_IDS)[number];
type DesktopAssetInspectorMessages = Readonly<Record<DesktopAssetInspectorMessageId, string>>;

export const ENGLISH_DESKTOP_ASSET_INSPECTOR_MESSAGES = {
    "library.compare.direction": "Reference: {left} → selected: {right}",
    "library.compare.change.added": "Added",
    "library.compare.change.removed": "Removed",
    "library.compare.change.modified": "Modified",
    "library.compare.change.unchanged": "Unchanged",
    "library.compare.stage.diffing": "Comparing content",
    "library.compare.stage.inventory": "Comparing file lists",
    "library.compare.stage.loading": "Loading selected files",
    "library.compare.stage.starting": "Starting comparison",
    "library.files.kind.binary": "Binary file",
    "library.files.kind.text": "Text file",
    "library.inspector.fingerprint_value": "Version fingerprint: {fingerprint}",
    "library.inspector.metadata": "Metadata",
    "library.inspector.project_id": "Project ID: {projectId}",
    "library.inspector.project_unavailable": "Project details unavailable",
    "library.inspector.views": "Asset detail views",
} as const satisfies DesktopAssetInspectorMessages;

export const GERMAN_DESKTOP_ASSET_INSPECTOR_MESSAGES = {
    "library.compare.direction": "Vergleich: {left} → ausgewählt: {right}",
    "library.compare.change.added": "Hinzugefügt",
    "library.compare.change.removed": "Entfernt",
    "library.compare.change.modified": "Geändert",
    "library.compare.change.unchanged": "Unverändert",
    "library.compare.stage.diffing": "Inhalte werden verglichen",
    "library.compare.stage.inventory": "Dateilisten werden verglichen",
    "library.compare.stage.loading": "Ausgewählte Dateien werden geladen",
    "library.compare.stage.starting": "Vergleich wird gestartet",
    "library.files.kind.binary": "Binärdatei",
    "library.files.kind.text": "Textdatei",
    "library.inspector.fingerprint_value": "Versionsfingerabdruck: {fingerprint}",
    "library.inspector.metadata": "Metadaten",
    "library.inspector.project_id": "Projekt-ID: {projectId}",
    "library.inspector.project_unavailable": "Projektdetails nicht verfügbar",
    "library.inspector.views": "Asset-Detailansichten",
} as const satisfies DesktopAssetInspectorMessages;

export const JAPANESE_DESKTOP_ASSET_INSPECTOR_MESSAGES = {
    "library.compare.direction": "比較元：{left} → 選択：{right}",
    "library.compare.change.added": "追加",
    "library.compare.change.removed": "削除",
    "library.compare.change.modified": "変更",
    "library.compare.change.unchanged": "変更なし",
    "library.compare.stage.diffing": "内容を比較しています",
    "library.compare.stage.inventory": "ファイル一覧を比較しています",
    "library.compare.stage.loading": "選択したファイルを読み込んでいます",
    "library.compare.stage.starting": "比較を開始しています",
    "library.files.kind.binary": "バイナリファイル",
    "library.files.kind.text": "テキストファイル",
    "library.inspector.fingerprint_value": "Version の指紋：{fingerprint}",
    "library.inspector.metadata": "メタデータ",
    "library.inspector.project_id": "Project ID：{projectId}",
    "library.inspector.project_unavailable": "Project の詳細を利用できません",
    "library.inspector.views": "Asset 詳細の表示",
} as const satisfies DesktopAssetInspectorMessages;

export const SIMPLIFIED_CHINESE_DESKTOP_ASSET_INSPECTOR_MESSAGES = {
    "library.compare.direction": "对照：{left} → 已选：{right}",
    "library.compare.change.added": "新增",
    "library.compare.change.removed": "移除",
    "library.compare.change.modified": "修改",
    "library.compare.change.unchanged": "未变化",
    "library.compare.stage.diffing": "正在比较内容",
    "library.compare.stage.inventory": "正在比较文件列表",
    "library.compare.stage.loading": "正在读取选中文件",
    "library.compare.stage.starting": "正在开始比较",
    "library.files.kind.binary": "二进制文件",
    "library.files.kind.text": "文本文件",
    "library.inspector.fingerprint_value": "版本指纹：{fingerprint}",
    "library.inspector.metadata": "元数据",
    "library.inspector.project_id": "Project ID：{projectId}",
    "library.inspector.project_unavailable": "Project 详情不可用",
    "library.inspector.views": "资产详情视图",
} as const satisfies DesktopAssetInspectorMessages;
