// Complete Desktop locale catalog; exact type and runtime tests defend key and placeholder parity.

import { GERMAN_DESKTOP_ASSET_ACTION_MESSAGES } from "./catalog-asset-actions";
import { GERMAN_DESKTOP_ASSET_INSPECTOR_MESSAGES } from "./catalog-asset-inspector";
import { GERMAN_DESKTOP_ASSET_AUTHORIZATION_MESSAGES } from "./catalog-asset-authorizations";
import { GERMAN_DESKTOP_DEPLOYMENT_PRODUCT_LANGUAGE_MESSAGES } from "./catalog-deployment-product-language";
import { GERMAN_DESKTOP_DIAGNOSTICS_MESSAGES } from "./catalog-diagnostics";
import { GERMAN_DESKTOP_DIRECTORY_PREVIEW_MESSAGES } from "./catalog-directory-preview";
import { GERMAN_DESKTOP_DISCOVERY_RESULT_MESSAGES } from "./catalog-discovery-results";
import type { DesktopMessageId } from "./catalog-en";
import { GERMAN_DESKTOP_GUIDED_IMPORT_MESSAGES } from "./catalog-guided-import";
import { GERMAN_DESKTOP_IMPORT_PREVIEW_MESSAGES } from "./catalog-import-preview";
import { GERMAN_DESKTOP_LIBRARY_SOURCE_MESSAGES } from "./catalog-library-sources";
import { GERMAN_DESKTOP_MAINTENANCE_MESSAGES } from "./catalog-maintenance";
import { GERMAN_DESKTOP_PRESENTATION_MESSAGES } from "./catalog-presentation";
import { GERMAN_DESKTOP_PROJECT_LIFECYCLE_MESSAGES } from "./catalog-project-lifecycle";
import { GERMAN_DESKTOP_SEARCH_MESSAGES } from "./catalog-search";

export const GERMAN_DESKTOP_MESSAGES = {
    "app.brand.subtitle": "Agent Asset Manager",
    "app.client_unavailable.eyebrow": "Kunde nicht verfügbar",
    "app.client_unavailable.message": "OAAM wurde gestartet, aber die Verbindung zum lokalen Arbeitsbereich fehlt.",
    "app.client_unavailable.title": "OAAM konnte den lokalen Arbeitsbereich nicht öffnen.",
    "app.failed.eyebrow": "OAAM nicht verfügbar",
    "app.failed.reason": "Fehlercode:",
    "app.failed.title": "OAAM konnte den Start nicht beenden.",
    "app.host.running": "Aktiv",
    "app.navigation.catalog": "Katalogisieren und bereitstellen",
    "app.navigation.import": "Rezension importieren",
    "app.navigation.label": "Arbeitsbereichsnavigation",
    "app.navigation.overview": "Übersicht",
    "app.navigation.sources": "Quellen",
    "app.navigation.workspace": "Arbeitsbereich",
    "app.ready": "Bereit",
    "app.reconnecting.title": "OAAM wird neu verbunden",
    "app.saved_assets.many": "{count} gespeicherte Vermögenswerte",
    "app.saved_assets.one": "{count} gespeichertes Asset",
    "app.starting.eyebrow": "Open Agent Asset Manager",
    "app.starting.title": "OAAM wird gestartet",
    "app.toolbar.assets": "Agentenvermögen",
    "app.toolbar.workspace": "Lokaler Arbeitsbereich",
    "app.workspace.label": "OAAM-Arbeitsbereich",
    "common.cancel": "Abbrechen",
    "common.close": "Schließen",
    "common.retry": "Erneut versuchen",
    "common.save": "Speichern",
    "discovery.complete_with_warnings": "Der Scan ist abgeschlossen, einige Speicherorte konnten jedoch nicht geprüft werden.",
    "discovery.enable_provider_first": "Wählen Sie vor dem Scannen mindestens ein verfügbares KI-Coding-Tool aus.",
    "discovery.interrupted": "Der Scan wurde unterbrochen. Versuchen Sie es erneut, um aktuelle Ergebnisse zu erhalten.",
    "discovery.loading": "Scanauswahl wird geladen…",
    "discovery.loading_failed": "OAAM konnte Ihre Scanauswahl nicht laden.",
    "discovery.no_environment": "Wählen Sie vor dem Scannen mindestens einen verfügbaren Speicherort aus.",
    "discovery.provider.save_failed": "Ihre Toolauswahl wurde nicht gespeichert. Aktualisieren Sie sie vor einem neuen Versuch.",
    "discovery.provider.saved": "Ihre Toolauswahl wurde gespeichert. Scannen Sie erneut nach aktuellen lokalen Assets.",
    "discovery.provider.saving": "Toolauswahl wird gespeichert…",
    "discovery.scanning": "Ausgewählte Tools und Speicherorte werden gescannt…",
    "discovery.settings_unavailable": "Die Scanauswahl ist nicht verfügbar.",
    "discovery.snapshot_refreshed": "Die Scanergebnisse sind aktuell.",
    "discovery.snapshot_untrustworthy": "Der Scan wurde nicht mit vertrauenswürdigen Ergebnissen abgeschlossen.",
    "discovery.ui.copy":
        "Deaktivierte Anbieter sind sichtbar, können aber erst dann prüfen, lesen, rendern oder inspizieren, wenn Sie eine explizite Auswahl speichern.",
    "discovery.ui.discovery_copy":
        "{environments} verfügbare Speicherorte · {watched} gespeicherte Speicherortauswahlen. Ein Scan importiert nie selbstständig Dateien.",
    "discovery.ui.discovery_copy_one_environment":
        "{environments} verfügbarer Speicherort · {watched} gespeicherte Speicherortauswahlen. Ein Scan importiert nie selbstständig Dateien.",
    "discovery.ui.discovery_copy_one_source":
        "{environments} verfügbare Speicherorte · {watched} gespeicherte Speicherortauswahl. Ein Scan importiert nie selbstständig Dateien.",
    "discovery.ui.discovery_copy_one_each":
        "{environments} verfügbarer Speicherort · {watched} gespeicherte Speicherortauswahl. Ein Scan importiert nie selbstständig Dateien.",
    "discovery.ui.eyebrow": "Lokaler Asset-Scan",
    "discovery.ui.environment.current_process": "OAAM scannt diesen Computer erst, nachdem Sie fortfahren.",
    "discovery.ui.environment.legend": "Zu scannende Speicherorte",
    "discovery.ui.environment.windows_default": "Dieser Windows-Computer ist standardmäßig ausgewählt.",
    "discovery.ui.environment.wsl_opt_in":
        "Wählen Sie diese WSL-Distribution nur aus, wenn Sie dort ebenfalls Agent-Assets speichern.",
    ...GERMAN_DESKTOP_DISCOVERY_RESULT_MESSAGES,
    ...GERMAN_DESKTOP_GUIDED_IMPORT_MESSAGES,
    ...GERMAN_DESKTOP_IMPORT_PREVIEW_MESSAGES,
    ...GERMAN_DESKTOP_ASSET_ACTION_MESSAGES,
    ...GERMAN_DESKTOP_ASSET_INSPECTOR_MESSAGES,
    ...GERMAN_DESKTOP_ASSET_AUTHORIZATION_MESSAGES,
    ...GERMAN_DESKTOP_DEPLOYMENT_PRODUCT_LANGUAGE_MESSAGES,
    "discovery.ui.environment_result_providers": "Anbieter: {providers}",
    "discovery.ui.environment_results": "Scanergebnisse nach Speicherort",
    "discovery.ui.loading_providers": "KI-Coding-Tools werden geladen",
    "discovery.ui.no_runtime_relationship": "Es wurde keine Agent-Laufzeit-Beziehung gemeldet",
    "discovery.ui.no_snapshot": "Noch keine Scanergebnisse.",
    "discovery.ui.no_sources": "Für die ausgewählten Tools wurden keine lokalen Asset-Speicherorte gefunden.",
    "discovery.ui.unchecked_project_environment_reference":
        "{runtime} verweist auf ein Projekt in {environment}. Es wurde noch nicht geprüft. Wählen Sie {environment} aus und fahren Sie mit der Prüfung fort.",
    "discovery.ui.picker.choose_source_button": "Verwenden Sie diesen Quellordner",
    "discovery.ui.picker.choose_source_title": "Wählen Sie einen externen Quellordner",
    "discovery.ui.provider.copy":
        "Deaktivierte Anbieter sind sichtbar, können aber erst dann prüfen, lesen, rendern oder inspizieren, wenn Sie eine explizite Auswahl speichern.",
    "discovery.ui.provider.disabled": "Deaktiviert",
    "discovery.ui.provider.disabled_after_save": "Nach dem Speichern deaktiviert",
    "discovery.ui.provider.enabled": "Aktiviert",
    "discovery.ui.provider.enabled_after_save": "Nach dem Speichern aktiviert",
    "discovery.ui.provider.entries.many": "{count} Laufzeiteinträge",
    "discovery.ui.provider.entries.one": "{count} Laufzeiteintrag",
    "discovery.ui.provider.eyebrow": "Scaneinrichtung",
    "discovery.ui.provider.save": "Providerzugang speichern",
    "discovery.ui.provider.saving": "Sparen…",
    "discovery.ui.provider.title": "Wählen Sie aus, welche Adapter OAAM ausführen darf",
    "discovery.ui.provider.unavailable": "Dieses zuvor gespeicherte Tool ist in dieser OAAM-Version nicht verfügbar.",
    "discovery.ui.probe_status.complete": "Komplett",
    "discovery.ui.probe_status.failed": "Fehlgeschlagen",
    "discovery.ui.probe_status.partial": "Teilweise",
    "discovery.ui.refresh_settings": "Auswahl aktualisieren",
    "discovery.ui.review_sources": "Ausgewählte Speicherorte prüfen",
    "discovery.ui.retry_discovery": "Scan erneut versuchen",
    "discovery.ui.run": "Jetzt scannen",
    "discovery.ui.save_and_run": "Auswahl speichern und scannen",
    "discovery.ui.save_before_scan": "Ihre aktualisierte Toolauswahl wird vor dem Scan gespeichert.",
    "discovery.ui.scanning": "Scannen…",
    "discovery.ui.select_import_source": "Wählen Sie {path} zur Importüberprüfung aus",
    "discovery.ui.select_source": "Wählen Sie {path}",
    "discovery.ui.source.eyebrow": "Lokale Assets",
    "discovery.ui.source.moved_from": "Bisher: {path}",
    "discovery.ui.source.title": "Asset-Speicherorte finden und prüfen",
    "discovery.ui.status.current": "Aktuell",
    "discovery.ui.status.missing": "Fehlt",
    "discovery.ui.status.moved": "Verschoben",
    "discovery.ui.status.new": "Neu",
    "discovery.ui.status.not_checked": "Nicht überprüft",
    "discovery.ui.warnings": "Entdeckungswarnungen",
    "discovery.ui.watch.do_not_watch": "Nicht in zukünftige Scans einbeziehen",
    "discovery.ui.watch.global": "Beobachten Sie als globale Quelle",
    "discovery.ui.watch.label": "Zukünftige Scans",
    "discovery.ui.watch.project": "Achten Sie auf das Projekt: {project}",
    "discovery.ui.watch.project_unavailable": "Nicht verfügbare Projektbindung beibehalten: {project}",
    "discovery.ui.watch.save": "Speichern Sie zukünftige Scan-Auswahlmöglichkeiten",
    "discovery.ui.watch.saving": "Speichern zukünftiger Scan-Optionen…",
    "discovery.ui.watch.source_label": "Zukünftige Scan-Auswahl für {path}",
    "discovery.ui.watch.unavailable": "Diese Quelle hat keine stabile Uhrenidentität.",
    "discovery.watch.saved": "Speicherortauswahl gespeichert. OAAM prüft die echten Pfade beim nächsten Mal erneut.",
    "discovery.watch.save_failed": "Speicherortauswahl wurde nicht gespeichert. Aktualisieren Sie zuerst die Scanergebnisse.",
    "discovery.watch.saving": "Speicherortauswahl wird gespeichert…",
    "discovery.watch.selection_invalid": "Eine Speicherortauswahl ist veraltet. Prüfen Sie die neuesten Scanergebnisse.",
    "import.accepting": "Ausgewählte Assets werden importiert…",
    "import.batch.complete": "Der Import ist abgeschlossen. Prüfen Sie jedes Asset unten.",
    "import.batch.failed": "Die ausgewählten Assets wurden nicht importiert.",
    "import.batch.partial": "Einige Assets wurden importiert, andere nicht. Prüfen Sie jedes Ergebnis unten.",
    "import.cancel.failed": "Diese Asset-Prüfung konnte nicht geschlossen werden.",
    "import.cancel.interrupted": "Das Schließen der Asset-Prüfung wurde unterbrochen.",
    "import.cancelled": "Asset-Prüfung geschlossen. Wählen Sie Quellen erneut aus, um eine neue Prüfung vorzubereiten.",
    "import.cancelling": "Asset-Prüfung wird geschlossen…",
    "import.choose_candidates": "Wählen Sie die Assets, die OAAM speichern soll. Vor Ihrer Bestätigung wird nichts importiert.",
    "import.choose_compatible_asset": "Wählen Sie ein aktuelles, nicht gelöschtes Asset mit derselben Asset-Art.",
    "import.choose_compatible_candidate": "Wählen Sie ein anderes ausgewähltes Asset, das diese Beziehung erfüllen kann.",
    "import.choose_existing_version": "Wählen Sie eine aktuell vorhandene Version mit einem kompatiblen Asset-Typ.",
    "import.connection_ended":
        "Die Verbindung wurde beendet, bevor OAAM das Importergebnis melden konnte. Aktualisieren Sie vor einem erneuten Versuch die Bibliothek.",
    "import.detail.interrupted": "Das Laden der Dateidetails wurde unterbrochen.",
    "import.detail.unavailable": "Das ausgewählte Dateidetail ist nicht verfügbar.",
    "import.idle": "Gehen Sie zurück und wählen Sie eine Quelle oder fahren Sie ohne Import fort.",
    "import.interrupted": "Die Asset-Prüfung wurde unterbrochen, bevor verlässliche Ergebnisse verfügbar waren.",
    "import.no_candidates": "Die ausgewählten Quellen enthalten keine Assets, die geprüft werden können.",
    "import.catalog.failed":
        "Die Asset-Bibliothek konnte nicht geladen werden. Versuchen Sie es erneut, bevor Sie das Ziel für diese Änderungen wählen.",
    "import.preview.failed": "Die Asset-Prüfung konnte nicht vorbereitet werden.",
    "import.previewing": "Asset-Prüfung wird vorbereitet…",
    "import.read.failed": "Die ausgewählten Quellen konnten nicht gelesen werden.",
    "import.read.attention": "Einige ausgewählte Orte erfordern Ihre Aufmerksamkeit.",
    "import.reading": "Ausgewählte Quellen lesen…",
    "import.ui.action.cancel": "Asset-Prüfung schließen",
    "import.ui.action.cancelling": "Stornieren…",
    "import.ui.action.import": "Ausgewählte Assets importieren",
    "import.ui.action.importing": "Importieren…",
    "import.ui.binary_copy":
        "Diese Binärdatei wird nicht angezeigt. Typ, Größe und Hash bleiben in den technischen Details verfügbar.",
    "import.ui.binding.choose_exact": "Zugehöriges Asset auswählen",
    "import.ui.binding.existing_versions": "Assets in der Bibliothek",
    "import.ui.binding.leave_unbound": "Kein Asset verknüpfen",
    "import.ui.binding.optional": "Optionales zugehöriges Asset für {target}",
    "import.ui.binding.required": "Erforderliches zugehöriges Asset für {target}",
    "import.ui.binding.selected_candidates": "In dieser Prüfung ausgewählte Assets",
    "import.ui.binding.target_label": "Zugehöriges Asset für {candidate}: {target}",
    "import.ui.candidate.file_count.many": "{count} Dateien",
    "import.ui.candidate.file_count.one": "{count}-Datei",
    "import.ui.candidate.select": "{candidate} auswählen",
    "import.ui.asset.scope.global": "Globale Bibliothek",
    "import.ui.asset.scope.project": "Aktuelles Projekt",
    "import.ui.asset.status.blocked": "Nicht importierbar",
    "import.ui.asset.status.duplicate": "Bereits vorhanden",
    "import.ui.asset.status.incomplete": "Noch nicht importierbar",
    "import.ui.asset.status.ready": "Bereit",
    "import.ui.asset.status.requires_refresh": "Erneut scannen",
    "import.ui.asset.status.stale": "Quelle wurde geändert",
    "import.ui.asset.status.unknown": "Quellstatus unbekannt",
    "import.ui.diagnostics.attribution": "Asset-Prüfung",
    "onboarding.completion.eyebrow": "Sicherer Abschluss",
    "onboarding.completion.failed": "OAAM konnte den Onboarding-Abschluss nicht speichern. Es wurde nichts eingesetzt.",
    "onboarding.completion.finish_without_import": "Beenden Sie den Vorgang, ohne zu importieren",
    "onboarding.completion.imported_copy":
        "Die ausgewählten Assets befinden sich in der OAAM-Bibliothek. Dateien von KI-Programmierwerkzeugen wurden nicht geändert.",
    "onboarding.completion.imported_title": "Sicherer Import abgeschlossen",
    "onboarding.completion.open_workspace": "Arbeitsbereich öffnen",
    "onboarding.completion.safe_copy":
        "Sie können nach einem neuen Scan ohne Import abschließen. Scannen und das Merken eines Ortes für spätere Prüfungen stellen keine Dateien bereit.",
    "onboarding.completion.safe_title": "Beenden Sie den Vorgang, wenn der Quell-Snapshot richtig aussieht",
    "onboarding.completion.saving": "Arbeitsbereich wird geöffnet…",
    "onboarding.copy": "Wählen Sie, wo OAAM suchen darf, prüfen Sie die Funde und entscheiden Sie, welche Assets Sie behalten.",
    "onboarding.eyebrow": "Erster Lauf",
    "onboarding.steps.label": "Fortschritt beim ersten Durchlauf",
    "onboarding.title": "OAAM einrichten, ohne Dateien Ihrer KI-Programmierwerkzeuge zu ändern",
    "import.ui.copy": "Prüfen Sie bei Bedarf die Dateien und wählen Sie nur Assets aus, die OAAM speichern soll.",
    "import.ui.dependencies_too_many":
        "Dieses Asset verweist auf {count} zugehörige Assets. Das sind zu viele für eine sichere Prüfung hier.",
    "import.ui.destination.add_version": "Version nach {asset} Revision {revision} hinzufügen",
    "import.ui.destination.create_asset": "Erstellen Sie ein neues OAAM-Asset",
    "import.ui.destination.label": "{candidate} speichern als",
    "import.ui.destination.save_as": "Speichern unter",
    "import.ui.detail.binary_label": "Details der geprüften Datei",
    "import.ui.detail.first_file": "Erste Datei",
    "import.ui.detail.loading": "Dateidetails werden geladen…",
    "import.ui.detail.text_truncated": "Dieser Text ist gekürzt; der Hash deckt die komplette Datei ab.",
    "import.ui.detail.view": "{path} anzeigen",
    "import.ui.detail.view_first": "Erste Datei anzeigen",
    "import.ui.eyebrow": "Importprüfung",
    "import.ui.failed.refresh_title": "Neue Entdeckung erforderlich",
    "import.ui.failed.title": "Importprüfung nicht verfügbar",
    "import.ui.files_omitted": "Weitere Dateien gehören zu diesem Asset. Prüfen Sie bei Bedarf die verfügbaren Dateien.",
    "import.ui.no_candidates": "Die ausgewählten Quellen enthalten keine importierbaren Assets.",
    "import.ui.no_preview": "Keine Assets zur Prüfung ausgewählt",
    "import.ui.preparing": "Asset-Prüfung wird vorbereitet",
    "import.ui.reading": "Ausgewählte Quellen lesen",
    "import.ui.read_attention.action_copy":
        "Prüfen Sie die Details und versuchen Sie es erneut. Um die Quellen zu ändern, kehren Sie zur Ortsauswahl zurück.",
    "import.ui.read_attention.continue": "Mit lesbaren Orten fortfahren",
    "import.ui.read_attention.copy":
        "OAAM hat kein unvollständiges Leseergebnis an die Asset-Prüfung weitergegeben. Aus den betroffenen Orten werden keine Assets importiert.",
    "import.ui.read_attention.eyebrow": "Dateizugriff",
    "import.ui.read_attention.status.failed": "Dieser Ort konnte nicht gelesen werden",
    "import.ui.read_attention.status.not_found": "Dieser Ort ist nicht mehr verfügbar",
    "import.ui.read_attention.status.partial": "Dieser Ort konnte nur teilweise gelesen werden",
    "import.ui.read_attention.status.unreported": "Dieser Ort lieferte kein vertrauenswürdiges Ergebnis",
    "import.ui.read_attention.title": "Einige Orte konnten nicht vollständig gelesen werden",
    "import.ui.refresh_required": "Die Quelldateien wurden geändert oder die Prüfung ist abgelaufen. Scannen Sie erneut.",
    "import.ui.return_to_sources": "Scanorte prüfen",
    "import.ui.result.batch_outcomes": "Importergebnisse",
    "import.ui.result.copy": "{message} Ein fehlgeschlagenes Asset macht erfolgreich importierte Assets nicht rückgängig.",
    "import.ui.result.no_tool_changes": "Projektdateien und Werkzeugkonfiguration wurden nicht geändert.",
    "import.ui.result.retry_failed":
        "Um fehlgeschlagene Assets erneut zu importieren, kehren Sie zu den Quellen zurück und wählen Sie nur diese Assets aus.",
    "import.ui.result.dependency_failed": "Erforderliches Asset wurde nicht importiert",
    "import.ui.result.failed": "Fehlgeschlagen",
    "import.ui.result.failed_dependencies": "Nicht importierte erforderliche Assets: {assets}",
    "import.ui.result.imported": "Importiert",
    "import.ui.result.asset_saved": "Neues Asset in der OAAM-Bibliothek gespeichert",
    "import.ui.result.version_saved": "Neue Version im bestehenden Asset gespeichert",
    "import.ui.result.open": "Asset öffnen",
    "import.ui.result.open_failed":
        "Das Asset wurde gespeichert, konnte aber nicht geöffnet werden. Versuchen Sie es erneut oder suchen Sie es in der Bibliothek.",
    "import.ui.result.title": "Importergebnis",
    "import.ui.result.unknown_asset": "Unbenanntes Asset",
    "import.ui.safe_import_copy":
        "Jedes ausgewählte Asset erstellt ein neues Asset oder ergänzt ein kompatibles Asset um eine Version. Der Import ändert keine Dateien eines KI-Programmierwerkzeugs oder Projekts.",
    "import.ui.technical.asset_id": "Asset-ID: {assetId}",
    "import.ui.technical.byte_length": "Größe in Bytes: {byteLength}",
    "import.ui.technical.candidate_id": "Prüfelement-ID: {candidateId}",
    "import.ui.technical.content_hash": "Hash der vollständigen Datei: {contentHash}",
    "import.ui.technical.media_type": "Medientyp: {mediaType}",
    "import.ui.technical.version_id": "Versions-ID: {versionId}",
    "import.ui.technical_details": "Technische Details",
    "import.ui.title": "Assets und erforderliche zugehörige Assets auswählen",
    "import.validation.binding_duplicate": "Eine Auswahl für ein zugehöriges Asset wurde mehrfach getroffen.",
    "import.validation.binding_existing_stale": "Eine ausgewählte vorhandene Version ist nicht mehr aktuell oder kompatibel.",
    "import.validation.binding_stale": "Ein zugehöriges Asset ist nicht mehr verfügbar, ausgewählt oder kompatibel.",
    "import.validation.candidate_dependencies_truncated":
        "{candidate} verweist auf mehr zugehörige Assets, als diese Prüfung sicher anzeigen kann.",
    "import.validation.candidate_not_importable": "{candidate} kann aus dieser Asset-Prüfung nicht importiert werden.",
    "import.validation.candidate_refresh": "{candidate} muss erneut gescannt werden.",
    "import.validation.destination_choose": "Wählen Sie, ob {candidate} ein neues Asset oder eine neue Version erstellt.",
    "import.validation.destination_duplicate": "Für ein Asset wurden mehrere Speicherziele ausgewählt.",
    "import.validation.destination_incompatible": "{candidate} hat ein veraltetes oder inkompatibles vorhandenes Asset-Ziel.",
    "import.validation.destination_missing": "Ein ausgewähltes Speicherziel ist in dieser Asset-Prüfung nicht mehr verfügbar.",
    "import.validation.destination_stale": "Ein Speicherziel gehört zu einem veralteten oder nicht ausgewählten Asset.",
    "import.validation.missing_binding": "{candidate} benötigt noch ein zugehöriges Asset für {target}.",
    "import.validation.no_selection": "Wählen Sie mindestens ein importbereites Asset aus.",
    "import.validation.preview_membership": "Die ausgewählten Assets gehören nicht mehr zu dieser Asset-Prüfung.",
    "import.validation.user_action":
        "OAAM konnte diese Aktion nicht bestätigen. Schließen und öffnen Sie die Asset-Prüfung erneut.",
    "catalog.activity.analyze": "Renderoptionen analysieren",
    "catalog.version_update.action": "Ausgewählte Version aktualisieren",
    "catalog.version_update.title": "Hier verwendete Version aktualisieren",
    "catalog.version_update.copy":
        "An diesem Ort ist eine andere Version ausgewählt. Wählen Sie die neue Version, prüfen Sie die Dateiänderungen und wenden Sie sie anschließend an.",
    "catalog.version_update.choose": "Revision {revision} auswählen und prüfen",
    "catalog.version_update.selected": "Bisher ausgewählte Version: {version}",
    "catalog.version_update.next": "Neue Version: {version}",
    "catalog.version_update.pending": "Ausgewählte Inhalte müssen geprüft werden",
    "catalog.version_update.changed": "Das Asset oder der Ort wurde geändert. Laden Sie den aktuellen Stand vor der Prüfung neu.",
    "catalog.version_update.failed": "Die ausgewählte Version konnte nicht aktualisiert werden.",
    "catalog.activity.create": "Werkzeugeinstellung speichern",
    "catalog.activity.deploy": "Ausgewähltes Rendering bereitstellen",
    "catalog.activity.preview": "Genaue Zielvorschau vorbereiten",
    "catalog.activity.inspect": "Änderungen an bereitgestellten Dateien prüfen",
    "catalog.activity.recover": "Status der Werkzeugdateien wird wiederhergestellt",
    "catalog.activity.register": "Projekt registrieren",
    "catalog.activity.repair": "Reparieren von OAAM-verwalteten Dateien",
    "catalog.activity.reverse_cancel": "Vorbereitete Überprüfung abbrechen",
    "catalog.activity.reverse_commit": "Überprüfte Änderungen speichern",
    "catalog.activity.reverse_refresh": "Gespeicherte Version und verwalteten Speicherort aktualisieren",
    "catalog.activity.reverse_prepare": "Überprüfte Änderungen vorbereiten",
    "catalog.activity.scan": "Scannen bereitgestellter Dateien",
    "catalog.asset.detail_interrupted": "Das Laden der Asset-Details wurde unterbrochen.",
    "catalog.asset.detail_unavailable": "Asset-Details sind nicht verfügbar.",
    "catalog.asset.missing": "Das ausgewählte Asset oder die aktuelle Version existiert nicht mehr.",
    "catalog.authority_changed": "Die Bibliothek wurde geändert. Aktualisieren Sie die Seite und prüfen Sie den aktuellen Stand.",
    "catalog.empty": "Die Bibliothek ist leer. Importieren und prüfen Sie Assets, bevor Sie Werkzeuge auswählen.",
    "catalog.deployment.created": "Diese Werkzeugeinstellung wurde gespeichert. Prüfen Sie Änderungen vor dem Schreiben.",
    "catalog.deployment.creation_failed": "Diese Werkzeugeinstellung konnte nicht gespeichert werden.",
    "catalog.inspection.conflict":
        "Dateikonflikte erfordern eine explizite Wiederherstellung oder die Entscheidung, die geprüften Änderungen zu speichern.",
    "catalog.inspection.current": "Die Inspektion ist aktuell. Überprüfen Sie vor der Reparatur die einzelnen Details.",
    "catalog.inspection.detail_interrupted": "Inspektionsdetail wurde unterbrochen.",
    "catalog.inspection.detail_unavailable": "Inspektionsdetails sind nicht verfügbar.",
    "catalog.inspection.interrupted": "Die Inspektion wurde unterbrochen.",
    "catalog.inspection.lost_channel":
        "Die Inspektion hat ihren Endkanal verloren. Überprüfen Sie es erneut, um neue Beweise zu erhalten.",
    "catalog.inspection.retained_expired":
        "Die beibehaltene Inspektion ist abgelaufen oder wurde ersetzt. Überprüfen Sie es erneut, bevor Sie es reparieren oder überschreiben.",
    "catalog.load.failed": "Der OAAM-Katalog konnte nicht geladen werden.",
    "catalog.load.interrupted": "Das Laden des OAAM-Katalogs wurde unterbrochen.",
    "catalog.loading": "OAAM-Katalog wird geladen…",
    "catalog.operation.failed": "{operation} fehlgeschlagen.",
    "catalog.operation.finished": "Der Vorgang ist abgeschlossen. Aktueller Status: {stage}.",
    "catalog.operation.interrupted": "{operation} wurde unterbrochen, bevor ein vertrauenswürdiges Ergebnis verfügbar war.",
    "catalog.operation.lost_terminal":
        "{operation} hat sein Endergebnis verloren. Versuchen Sie es nicht blind noch einmal. Laden Sie den zuletzt gespeicherten Zustand und stellen Sie ihn bei Bedarf wieder her.",
    "catalog.project.registered": "Registriert {project}.",
    "catalog.project.registration_failed": "Das ausgewählte Projekt konnte nicht registriert werden.",
    "catalog.preview.failed": "Die genaue Zielvorschau konnte nicht erstellt werden.",
    "catalog.preview.interrupted": "Die Zielvorschau wurde unterbrochen, bevor ein vertrauenswürdiges Ergebnis verfügbar war.",
    "catalog.preview.lost_channel":
        "Die Zielvorschau hat ihren Endkanal verloren. Bereiten Sie vor dem Schreiben eine neue Vorschau vor.",
    "catalog.preview.ready": "Exakte Ist- und Soll-Zustände stehen zur Überprüfung bereit.",
    "catalog.preview.retained_expired":
        "Die beibehaltene Zielvorschau ist abgelaufen oder wurde ersetzt. Bereiten Sie eine neue Vorschau vor.",
    "catalog.render.analysis_failed": "Die Renderanalyse ist fehlgeschlagen.",
    "catalog.render.choose_strategies":
        "Wählen Sie für jede semantische Eingabe eine Strategie. Geforderte Degradierung bleibt ungenehmigt.",
    "catalog.render.interrupted": "Die Renderanalyse wurde unterbrochen.",
    "catalog.render.lost_channel":
        "Die Renderanalyse hat ihren Endkanal verloren. Es ist schreibgeschützt und kann nach der Aktualisierung erneut ausgeführt werden.",
    "catalog.reverse.cancel_failed": "Die vorbereitete Überprüfung konnte nicht abgebrochen werden.",
    "catalog.reverse.cancelled": "Die vorbereitete Überprüfung wurde abgebrochen, ohne das Asset zu ändern.",
    "catalog.reverse.commit_failed": "Die überprüften Änderungen wurden nicht gespeichert.",
    "catalog.reverse.not_prepared": "Diese Änderungen konnten nicht sicher zur Überprüfung vorbereitet werden.",
    "catalog.reverse.prepare_failed": "OAAM konnte die exakt geprüften Änderungen nicht vorbereiten.",
    "catalog.reverse.prepared": "Prüfen Sie, wie die Änderungen zu einer Asset-Version würden.",
    "catalog.reverse.promotion_confirmation_required": "Bestätigen Sie diese genaue neue Version, bevor Sie sie speichern.",
    "catalog.reverse.result.committed":
        "Die neue Asset-Version wurde veröffentlicht und von dieser Werkzeugeinstellung ausgewählt.",
    "catalog.reverse.result.not_published": "Es wurde keine neue Asset-Version veröffentlicht.",
    "catalog.reverse.result.outcome_unavailable":
        "OAAM kann nicht beweisen, ob die Änderungen gespeichert wurden. Laden Sie den zuletzt gespeicherten Zustand.",
    "catalog.reverse.result.published_not_selected":
        "Die neue Asset-Version wurde veröffentlicht, diese Werkzeugeinstellung verwendet jedoch weiterhin die vorherige Version.",
    "catalog.reverse.result.recovery_required":
        "Dieser Speichervorgang muss wiederhergestellt werden, bevor erneut geschrieben werden kann.",
    "catalog.target.inspection_failed": "Die Überprüfung der bereitgestellten Dateien ist fehlgeschlagen.",
    "catalog.ui.action.analyze": "Dateiänderungen prüfen",
    "catalog.ui.action.apply": "Änderungen anwenden",
    "catalog.ui.action.create": "Diese Einstellung speichern",
    "catalog.ui.action.inspect": "Externe Änderungen prüfen",
    "catalog.ui.action.overwrite": "Ausgewählte OAAM-Version anwenden",
    "catalog.ui.action.preview": "Dateien vor dem Anwenden prüfen",
    "catalog.ui.action.recover": "Wiederherstellen",
    "catalog.ui.action.repair": "Reparatur anhand dieser genauen Inspektion",
    "catalog.ui.action.replace_unmanaged": "Vorhandene Dateien ersetzen",
    "catalog.ui.action.reverse_cancel": "Abbrechen, ohne zu speichern",
    "catalog.ui.action.reverse_commit": "Als neue Bibliotheksversion behalten",
    "catalog.ui.action.reverse_prepare": "Änderungen aus dem Werkzeug prüfen",
    "catalog.ui.action.scan": "Dateistatus prüfen",
    "catalog.ui.asset.bytes": "{count} Bytes",
    "catalog.ui.asset.catalog_eyebrow": "Asset- und Versionskatalog",
    "catalog.ui.asset.catalog_title": "Wählen Sie genau gespeicherte Versionen",
    "catalog.ui.asset.current_version": "Aktuelle Asset-Version",
    "catalog.ui.asset.empty": "Es sind noch keine Assets gespeichert. Füllen Sie zunächst die obige Importprüfung aus.",
    "catalog.ui.asset.loading_detail": "Genaue Versionsmetadaten werden geladen…",
    "catalog.ui.asset.refresh": "Katalog aktualisieren",
    "catalog.ui.asset.revision_version": "Revision {revision} · Version {versionId}",
    "catalog.ui.asset.view_version": "Aktuelle Version anzeigen",
    "catalog.ui.catalog_eyebrow": "Bibliothek und Werkzeugnutzung",
    "catalog.ui.catalog_loading": "OAAM-Katalog wird geladen",
    "catalog.ui.catalog_unavailable": "Katalog nicht verfügbar",
    "catalog.ui.catalog_warnings": "Hinweise zu Bibliothek und Werkzeugdateien",
    "catalog.ui.create.add_folder": "Projektordner hinzufügen",
    "catalog.ui.create.allow_incomplete": "Erlauben Sie ausdrücklich diese unvollständige Version",
    "catalog.ui.create.asset_revision": "{asset} · Version {revision}",
    "catalog.ui.create.assets_legend": "Genaue aktuelle Asset-Versionen",
    "catalog.ui.create.consumer_legend": "Werkzeugeintrag für diesen Ort",
    "catalog.ui.create.copy":
        "Wählen Sie Assets, Werkzeuge und Ort. OAAM zeigt Änderungen zuerst und schreibt erst nach weiterer Bestätigung.",
    "catalog.ui.create.eyebrow": "Schritt 3",
    "catalog.ui.create.fresh_target": "Werkzeugort",
    "catalog.ui.create.no_ready_runtime": "Dieses Werkzeug kann den ausgewählten Ort nicht verwenden.",
    "catalog.ui.create.not_ready": "Hier nicht verfügbar: {agentRuntimeIds}",
    "catalog.ui.create.project": "OAAM-Projekt",
    "catalog.ui.create.project_choose": "Wählen Sie ein Projekt",
    "catalog.ui.create.subject_global": "Assets stammen aus der globalen Bibliothek.",
    "catalog.ui.create.subject_project": "Assets stammen aus diesem Projekt und der globalen Bibliothek.",
    "catalog.ui.create.target_choose": "Gefundenen Werkzeugort auswählen",
    "catalog.ui.create.title": "Zielort bestätigen",
    "catalog.ui.deployment.asset_count.many": "{count} Bibliothekseinträge",
    "catalog.ui.deployment.asset_count.one": "{count} Bibliothekseintrag",
    "catalog.ui.deployment.empty": "Es wurde noch keine Werkzeugeinstellung gespeichert.",
    "catalog.ui.deployment.eyebrow": "Eingerichtete Werkzeuge",
    "catalog.ui.deployment.select": "Wählen Sie eine Werkzeugeinstellung vor der Prüfung oder Aktualisierung.",
    "catalog.ui.deployment.title": "Werkzeugdateien prüfen und aktualisieren",
    "catalog.ui.freshness.complete": "Zuletzt überprüft {time}",
    "catalog.ui.freshness.failed": "Letzte Prüfung fehlgeschlagen {attempt} · letzte vollständige Prüfung {lastComplete}",
    "catalog.ui.freshness.in_progress": "Überprüfung seit {attempt} · letzter Abschluss {lastComplete}",
    "catalog.ui.freshness.never": "Noch nicht überprüft",
    "catalog.ui.freshness.no_complete": "noch nicht abgeschlossen",
    "catalog.ui.freshness.partial": "Letzte Prüfung war teilweise {attempt} · letzte vollständige Prüfung {lastComplete}",
    "catalog.ui.inspection.change_count.many": "{count} Änderungen",
    "catalog.ui.inspection.change_count.one": "{count} ändern",
    "catalog.ui.inspection.conflict_count.many": "{count} Konflikte",
    "catalog.ui.inspection.conflict_count.one": "{count} Konflikt",
    "catalog.ui.inspection.detail_loading": "Begrenzte Inspektionsdetails werden geladen…",
    "catalog.ui.inspection.details_omitted":
        "Zusätzliche Inspektionsselektoren wurden in dieser begrenzten Zusammenfassung weggelassen.",
    "catalog.ui.inspection.inspecting": "Änderungen an bereitgestellten Dateien prüfen…",
    "catalog.ui.inspection.title": "Inspektion",
    "catalog.ui.inspection.file_detail": "Dateizuordnung",
    "catalog.ui.inspection.change_detail": "Inhaltsänderung",
    "discovery.ui.choose_environments": "Umgebungen auswählen",
    "catalog.ui.picker.cancelled": "Projektauswahl abgebrochen.",
    "catalog.ui.picker.choose_button": "Verwenden Sie diesen Projektordner",
    "catalog.ui.picker.choose_title": "Wählen Sie einen OAAM-Projektordner",
    "catalog.ui.picker.failed": "Die Auswahl des nativen Projektordners ist fehlgeschlagen.",
    "catalog.ui.picker.opening": "Öffnen der nativen Projektordnerauswahl…",
    "catalog.ui.picker.registering": "Registrieren von {path}…",
    "catalog.ui.preview.action.blocked_managed_conflict":
        "Verwaltete Inhalte wurden geändert. Prüfen Sie diese Version und bestätigen Sie das Ersetzen.",
    "catalog.ui.preview.action.ready_apply": "Der genaue Zielzustand ermöglicht eine gewöhnliche Anwendung.",
    "catalog.ui.preview.action.requires_unmanaged_replacement":
        "Am Ziel sind bereits andere Inhalte vorhanden. Prüfen Sie die Dateiänderungen und bestätigen Sie dann das Ersetzen.",
    "catalog.ui.preview.change.create": "Erstellen Sie eine neue Datei",
    "catalog.ui.preview.change.establish_baseline": "Behalten Sie identische Inhalte bei und etablieren Sie eine OAAM-Grundlinie",
    "catalog.ui.preview.change.managed_conflict": "Das verwaltete Ziel unterscheidet sich von seiner OAAM-Basislinie",
    "catalog.ui.preview.change.remove_managed": "Entfernen Sie eine von OAAM verwaltete Datei",
    "catalog.ui.preview.change.replace_unmanaged": "Abweichende vorhandene Inhalte ersetzen",
    "catalog.ui.preview.change.remove_unmanaged": "Diese geprüfte vorhandene Datei entfernen",
    "catalog.ui.preview.change.unchanged": "Lassen Sie die verwaltete Datei unverändert",
    "catalog.ui.preview.change.update_managed": "Aktualisieren Sie die verwaltete Datei",
    ...GERMAN_DESKTOP_DIRECTORY_PREVIEW_MESSAGES,
    "catalog.ui.preview.confirm_managed_overwrite":
        "Ich habe die externen Dateiänderungen geprüft und stelle die genaue OAAM-Ausgabe einmal wieder her",
    "catalog.ui.preview.confirm_unmanaged": "Ich habe die vorhandenen Inhalte geprüft und stimme dem einmaligen Ersetzen zu",
    "catalog.ui.preview.current_tab": "Aktuell",
    "catalog.ui.preview.desired_tab": "Gewünscht",
    "catalog.ui.preview.current_text": "Aktueller Zieltext",
    "catalog.ui.preview.desired_text": "Gewünschter Zieltext",
    "catalog.ui.preview.review_tab": "Dateiänderungen",
    "catalog.ui.preview.open_current": "Aktuelle Datei in einem Tab öffnen",
    "catalog.ui.preview.open_desired": "Gewünschte Datei in einem Tab öffnen",
    "catalog.ui.preview.snapshot_copy": "Angezeigt wird der für diese Vorschau erfasste Dateiinhalt.",
    "catalog.ui.preview.bounded_diff":
        "Diese Dateien unterscheiden sich erheblich. Änderungen werden deshalb abschnittsweise angezeigt. Öffnen Sie eine Datei, um den vollständigen Inhalt zu lesen.",
    "catalog.ui.reconciliation_required":
        "OAAM hat das Endergebnis einer Änderung verloren. Laden Sie den zuletzt gespeicherten Zustand; wiederholen Sie die Aktion nicht blind.",
    "catalog.ui.reverse.finish_recovery":
        "Wählen Sie Wiederherstellen, um diesen Vorgang abzuschließen. OAAM prüft das gespeicherte Ergebnis vor einer weiteren Änderung.",
    "catalog.ui.reverse.confirm_promotion": "Dieser Werkzeugeinstellung die Auswahl genau dieser neuen Asset-Version erlauben",
    "catalog.ui.reverse.expires": "Diese Vorbereitung läuft am {time} ab.",
    "catalog.ui.reverse.preparing": "Die exakt geprüften Änderungen werden zur Überprüfung vorbereitet…",
    "catalog.ui.reverse.result_title": "Speicherergebnis",
    "catalog.ui.reverse.title": "Änderungen aus dem Werkzeug prüfen",
    "catalog.ui.reverse.whole_file_adoption":
        "Änderungen, die eine Übernahme der gesamten Datei erfordern, gehören zum normalen Quelllese- und Importüberprüfungsablauf.",
    "catalog.ui.render.approve_degraded": "Genehmigen Sie diesen beeinträchtigten Rendering einmal",
    "catalog.ui.render.approval.reverse_extract_unsupported":
        "Zukünftige Änderungen in diesem Werkzeug können nicht sicher zurückgeführt werden",
    "catalog.ui.render.approval.semantic_degradation": "Ein Teil des Quellverhaltens geht verloren",
    "catalog.ui.render.blocked": "Dieser Teil kann nicht sicher gerendert werden.",
    "catalog.ui.render.degradation.folder_asset_flattened": "Das Ordner-Asset wird reduziert",
    "catalog.ui.render.degradation.memory_semantics_lost": "Das Gedächtnisverhalten wird zum reinen Inhalt",
    "catalog.ui.render.degradation.permission_or_tool_boundary_lost": "Eine Berechtigung oder Werkzeuggrenze geht verloren",
    "catalog.ui.render.degradation.reverse_extract_pollution_risk":
        "Eine spätere Rückwärtsextraktion kann generierte Inhalte enthalten",
    "catalog.ui.render.degradation.runtime_specific_metadata_lost": "Werkzeugspezifische Metadaten gehen verloren",
    "catalog.ui.render.degradation.target_runtime_missing_asset_kind":
        "Dieses KI-Programmierwerkzeug hat keine native Form für diesen Asset-Typ",
    "catalog.ui.render.degradation.trigger_or_loading_level_lost":
        "Der ursprüngliche Auslöse- oder Belastungspegel geht verloren",
    "catalog.ui.render.degradation.workflow_permission_lost": "Das Verhalten bei Workflow-Berechtigungen geht verloren",
    "catalog.ui.render.degradation.workflow_runtime_lost": "Das Ausführungsverhalten des Workflows geht verloren",
    "catalog.ui.render.degradation.workflow_trigger_lost": "Das Verhalten des Workflow-Triggers geht verloren",
    "catalog.ui.render.degradation.workflow_variable_lost": "Das Verhalten der Workflow-Variablen geht verloren",
    "catalog.ui.render.degradations": "Verhaltensänderungen",
    "catalog.ui.render.executable_suffix": "· ausführbar",
    "catalog.ui.render.managed_directory": "Verwaltetes Verzeichnis: {path}",
    "catalog.ui.render.no_target_file": "Diese Semantik fügt keinen direkten Dateianspruch hinzu.",
    "catalog.ui.render.output_binary": "{path} · binär{executable}",
    "catalog.ui.render.output_text": "{path} · Text{executable}",
    "catalog.ui.render.output_counts": "{count} Dateien · {text} Text · {binary} Binärdateien · {executable} ausführbar",
    "catalog.ui.render.directory_count": "{count} verwaltete Ordner",
    "catalog.ui.render.preview_required":
        "Wählen Sie pro Element eine vollständige Renderoption. OAAM zeigt vor jedem Schreibvorgang eine neue Vorschau des genauen Ziels an.",
    "catalog.ui.render.reverse.can_reconcile": "Zukünftige Änderungen können zugeordnet und überprüft werden",
    "catalog.ui.render.reverse.ignore_generated_wrapper":
        "Der generierte Wrapper-Text wird ignoriert, wenn Änderungen zurückgenommen werden",
    "catalog.ui.render.reverse.unsupported": "Zukünftige Änderungen können nicht sicher wiederhergestellt werden",
    "catalog.ui.render.reverse_label": "Zukünftige Bearbeitung: {policy}",
    "catalog.ui.render.runtime": "KI-Programmierwerkzeug: {runtime}",
    "catalog.ui.render.semantic.asset_file_inventory": "Enthaltene Dateien",
    "catalog.ui.render.semantic.guidance_base_context": "Projektkontext",
    "catalog.ui.render.semantic.guidance_content": "Anweisungen",
    "catalog.ui.render.semantic.memory_content": "Speicherinhalte",
    "catalog.ui.render.semantic.memory_support": "Speicherunterstützung",
    "catalog.ui.render.semantic.rule_activation": "Regelaktivierung",
    "catalog.ui.render.semantic.rule_content": "Regelinhalt",
    "catalog.ui.render.semantic.skill_body": "Fertigkeitsanweisungen",
    "catalog.ui.render.semantic.skill_discovery_metadata": "Metadaten zur Fähigkeitserkennung",
    "catalog.ui.render.semantic.skill_resource": "Fähigkeitsressource",
    "catalog.ui.render.semantic.subagent_delegation_metadata": "Metadaten der Subagentendelegierung",
    "catalog.ui.render.semantic.subagent_invoked_context": "Vom Subagenten aufgerufener Kontext",
    "catalog.ui.render.semantic.subagent_model_hint": "Hinweis zum Subagentenmodell",
    "catalog.ui.render.semantic.subagent_resource": "Subagent-Ressource",
    "catalog.ui.render.semantic.subagent_tool_boundary": "Grenze des Subagenten-Tools",
    "catalog.ui.render.semantic.workflow_activation": "Workflow-Aktivierung",
    "catalog.ui.render.semantic.workflow_content": "Workflow-Inhalte",
    "catalog.ui.render.semantic.workflow_reference": "Workflow-Referenz",
    "catalog.ui.render.strategy.inline": "Inline-Inhalte",
    "catalog.ui.render.strategy.native_directory": "Natives Verzeichnis",
    "catalog.ui.render.strategy.native_graph": "Nativer Dateiverbund",
    "catalog.ui.render.strategy.native_file": "Native Datei",
    "catalog.ui.render.strategy.native_import": "Nativer Import",
    "catalog.ui.render.strategy.reference_with_intro": "Referenz mit einer kurzen Einführung",
    "catalog.ui.support_required":
        "OAAM kann diese Werkzeugdateien nicht automatisch wiederherstellen. Bewahren Sie das Prüfergebnis auf und wenden Sie sich an den Support.",
    "catalog.ui.render.subject": "{asset} · {semantic}",
    "catalog.ui.render.title": "Darstellung der Dateien im Werkzeug auswählen",
    "catalog.ui.render.waiting": "Warten auf Renderanalyse…",
    "catalog.ui.status.external_changes": "Externe Änderungen gefunden",
    "catalog.ui.status.first_deployment": "Erste Bereitstellung verfügbar",
    "catalog.ui.status.needs_checking": "Der Status muss überprüft werden",
    "catalog.ui.status.paused_for_safety": "Aus Sicherheitsgründen pausiert",
    "catalog.ui.status.repair_available": "Einige verwaltete Dateien können wiederhergestellt werden",
    "catalog.ui.status.review_required": "Diese Werkzeugeinstellung muss geprüft werden",
    "catalog.ui.status.support_required": "Unterstützung ist erforderlich",
    "catalog.ui.status.up_to_date": "Auf dem neuesten Stand",
    "catalog.ui.target.choose_project": "Werkzeuge prüfen",
    "catalog.ui.target.copy":
        "Wählen Sie die Werkzeuge und die Systemumgebung für dieses Projekt. Das Herkunftswerkzeug des Assets schränkt das Ziel nicht ein. Diese Prüfung ändert keine Dateien.",
    "catalog.ui.target.discover_global": "Werkzeuge prüfen",
    "catalog.ui.target.environments": "Zu prüfende Systemumgebungen",
    "catalog.ui.target.eyebrow": "Werkzeuge und Speicherorte",
    "catalog.ui.target.loading": "Werkzeuge und Systemumgebungen werden geladen",
    "catalog.ui.target.no_provider": "Kein ausgewähltes KI-Programmierwerkzeug ist verfügbar.",
    "catalog.ui.target.probing": "Werkzeuge werden geprüft…",
    "catalog.ui.target.providers": "Zu verwendende Werkzeuge",
    "catalog.ui.target.select_all": "Alle auswählen",
    "catalog.ui.target.clear_all": "Auswahl löschen",
    "catalog.ui.target.title": "Verfügbare Werkzeuge finden",
    "catalog.ui.target.unavailable": "Verfügbare Werkzeuge können derzeit nicht geprüft werden",
    "catalog.ui.workspace.back": "Zurück zur Bibliothek",
    "catalog.ui.workspace.eyebrow": "Werkzeugorte",
    "catalog.ui.workspace.global": "Globale Assets verwenden",
    "catalog.ui.workspace.project": "Projekt-Assets verwenden",
    "catalog.validation.asset_duplicate": "Eine Werkzeugeinstellung darf dasselbe Asset nicht zweimal umfassen.",
    "catalog.validation.asset_incomplete":
        "{asset} ist unvollständig. Erlauben Sie diese Version ausdrücklich oder entfernen Sie sie.",
    "catalog.validation.asset_missing": "Ein ausgewähltes Asset befindet sich nicht mehr im aktuellen Katalog.",
    "catalog.validation.asset_version_changed":
        "{asset} hat eine andere aktuelle Version. Überprüfen Sie es und wählen Sie es erneut aus.",
    "catalog.validation.choose_asset": "Wählen Sie mindestens ein Asset für ein Werkzeug aus.",
    "catalog.validation.choose_project": "Wählen Sie ein aktuelles OAAM-Projekt.",
    "catalog.validation.choose_runtime":
        "Wählen Sie mindestens ein KI-Programmierwerkzeug, das an diesem genauen Ort verfügbar ist.",
    "catalog.validation.choose_target": "Wählen Sie ein Ziel aus dem aktuellen Erkennungs-Snapshot aus.",
    "catalog.validation.render_approval":
        "Genehmigen Sie ausdrücklich die herabgestufte Option {strategy} oder wählen Sie eine andere Strategie.",
    "catalog.validation.render_approval_evidence": "Die Genehmigung enthält keine Benutzeraktionsnachweise.",
    "catalog.validation.render_duplicate": "Eine semantische Eingabe verfügt über mehr als eine Renderauswahl.",
    "catalog.validation.render_incomplete":
        "OAAM konnte die vollständige Prüfung der Dateiänderungen nicht bestätigen. Aktualisieren Sie die Ansicht, bevor Sie fortfahren.",
    "catalog.validation.render_missing": "Wählen Sie für jede semantische Eingabe genau eine Renderstrategie.",
    "catalog.validation.render_none": "Diese Analyse enthält keine Renderoption, die bereitgestellt werden kann.",
    "session.catalog_unavailable": "Der OAAM-Katalog ist nicht verfügbar.",
    "session.connecting": "Verbindung zu OAAM wird hergestellt…",
    "session.connection_closed": "Die OAAM-Verbindung wurde geschlossen.",
    "session.host_recovering": "OAAM wurde nicht bereit. Ein sauberer Wiederholungsversuch läuft…",
    "session.host_startup_failed": "OAAM konnte nicht gestartet werden. Im Hintergrund wird nicht endlos neu versucht.",
    "session.host_startup_timeout": "OAAM war nach 30 Sekunden noch nicht verfügbar. Sie können es erneut versuchen.",
    "session.initialization_failed": "OAAM konnte die lokalen Daten nicht vorbereiten.",
    "session.restart_failed": "OAAM konnte nicht neu gestartet werden.",
    "session.restarting": "OAAM wird neu gestartet…",
    "session.starting": "OAAM wird gestartet…",
    "workspace.catalog.assets.many": "{count} Vermögenswerte",
    "workspace.catalog.assets.none": "Es wurden noch keine Assets importiert",
    "workspace.catalog.label": "Katalogzusammenfassung",
    "workspace.host.ready": "Gastgeber bereit",
    "workspace.host.warnings.many": "{count} Startwarnungen",
    "workspace.host.warnings.one": "{count} Startwarnung",
    "workspace.overview.copy":
        "Entdecken Sie lokale Quellen, überprüfen Sie die genauen Kandidaten und setzen Sie sie dann nur mit expliziten Entscheidungen ein.",
    "workspace.overview.eyebrow": "Übersicht über den Arbeitsbereich",
    "workspace.overview.title": "Verwalten Sie tragbare Agentenressourcen",
    "library.asset_detail_interrupted": "Das Laden der Asset-Metadaten wurde unterbrochen.",
    "library.asset_detail_unavailable": "OAAM konnte die Details des ausgewählten Assets nicht laden.",
    "library.asset_missing": "Das ausgewählte Asset oder die aktuelle Version ist nicht mehr verfügbar.",
    "library.assets.count": "{count} Vermögenswerte",
    "library.assets.deleted": "Gelöscht",
    "library.assets.empty": "Keine Assets in dieser Sammlung.",
    "library.assets.empty_global_copy":
        "Importieren Sie Assets aus einem KI-Programmierwerkzeug, um Ihre wiederverwendbare globale Bibliothek aufzubauen.",
    "library.assets.empty_global_title": "Die globale Asset-Bibliothek ist leer",
    "library.assets.empty_project_copy":
        "Prüfen Sie die Orte dieses Projekts in Ihren KI-Programmierwerkzeugen und wählen Sie dann die zu importierenden Assets aus.",
    "library.assets.empty_project_title": "Keine Assets in {project}",
    "library.assets.eyebrow": "Asset-Bibliothek",
    "library.assets.global_copy": "In der globalen Bibliothek gespeicherte Assets.",
    "library.assets.global_title": "Globale Bibliothek",
    "library.assets.incomplete": "Unvollständig",
    "library.assets.include_deleted":
        "Assets im OAAM-Papierkorb anzeigen. Sie sind nicht endgültig gelöscht und können wiederhergestellt werden.",
    "library.assets.loading": "Assets werden geladen…",
    "library.assets.loading_page": "Bis zu 50 Assets werden geladen…",
    "library.assets.no_description": "Keine Beschreibung",
    "library.assets.no_match": "Zu dieser Suche passen keine geladenen Assets.",
    "library.assets.project_copy": "Vermögenswerte, die genau diesem Projekt zugeordnet sind.",
    "library.assets.project_title": "Projektvermögenswerte",
    "library.assets.revision": "Version {revision}",
    "library.assets.search": "Durchsuchen Sie geladene Assets",
    "library.assets.search_placeholder": "Durchsuchen Sie diese geladene Bibliothek",
    "library.assets.shared_copy":
        "Globale Assets können später ausgewählt werden, die Zielkompatibilität erfordert jedoch noch eine Renderprüfung.",
    "library.assets.shared_title": "Für dieses Projekt verfügbare globale Vermögenswerte",
    "library.assets.show_more": "{count} weitere {kind} Assets anzeigen",
    "library.assets.title": "Durchsuchen Sie gespeicherte Assets",
    "library.catalog.warnings": "{count} Katalogwarnungen",
    "library.authority_changed":
        "Der Katalog wurde geändert. Aktualisieren Sie die Ansicht, bevor Sie sich auf diese Ansicht verlassen.",
    "library.environments.filter": "Beobachteter Umgebungsfilter",
    "library.environments.sources": "{count} beobachtete Quellen",
    "library.environments.title": "Beobachtete Umgebungen in dieser Ansicht",
    "library.export.action": "OAAM-Versionspaket exportieren",
    "library.export.choose_button": "Paket exportieren",
    "library.export.choose_title": "OAAM-Versionspaket für diese Version speichern",
    "library.export.complete": "Das OAAM-Versionspaket mit {bytes} Byte wurde exportiert.",
    "library.export.failed": "Das OAAM-Versionspaket konnte nicht exportiert werden.",
    "library.export.running": "Das OAAM-Versionspaket wird erstellt…",
    "library.failed_title": "Die Bibliothek konnte nicht geladen werden",
    "library.file_preview_failed": "Die ausgewählte Datei konnte nicht sicher gelesen werden.",
    "library.files.descendants": "{count} untergeordnete Dateien",
    "library.files.more": "50 weitere Einträge laden",
    "library.files.up": "Eine Ebene höher",
    "library.global.navigation": "Globale Bibliothek",
    "library.global.navigation_copy": "Durchsuchen Sie Assets und beobachtete Quellen, die nicht zu einem Projekt gehören.",
    "library.global.title": "Globale Bibliothek",
    "library.host.warnings": "{count} Startwarnungen",
    "library.inspector.bytes": "{count} Bytes",
    "library.inspector.close": "Schließen Sie den Asset-Inspektor",
    "library.inspector.created": "Erstellt",
    "library.inspector.current_version": "Aktuelle Version {revision}",
    "library.inspector.executable": "Ausführbar",
    "library.inspector.eyebrow": "Asset-Details",
    "library.inspector.files": "Dateien",
    "library.inspector.fingerprint": "Fingerabdruck",
    "library.inspector.incomplete":
        "Diese aktuelle Version ist unvollständig und wird nicht als vollständig bereitstellbar dargestellt.",
    "library.inspector.kind": "Typ",
    "library.inspector.label": "Ausgewählte Asset-Metadaten",
    "library.inspector.loading": "Asset-Details werden geladen…",
    "library.inspector.more_versions": "50 weitere Versionen laden",
    "library.inspector.no_files": "Diese Version enthält keine Dateien.",
    "library.inspector.overview": "Übersicht",
    "library.inspector.project": "Projekt",
    "library.inspector.scope": "Umfang",
    "library.inspector.scope_path": "Bereichspfad",
    "library.inspector.status": "Status",
    "library.inspector.title": "Asset-Details",
    "library.inspector.updated": "Aktualisiert",
    "library.inspector.version_id": "Versions-ID",
    "library.inspector.version_select": "Exakte Version",
    "library.inspector.versions": "Versionen",
    "library.compare.action": "Exakte Versionen vergleichen",
    "library.compare.base": "Vergleichen mit",
    "library.compare.file_graph": "Dateiänderungen",
    "library.compare.folded": "{count} unveränderte Zeilen eingeklappt",
    "library.compare.layout": "Diff-Layout",
    "library.compare.metadata_only": "Der Vergleich enthält Dateiänderungen, aber keinen darstellbaren Text-Diff.",
    "library.compare.no_text_changes": "Der ausgewählte Text ist in beiden Versionen identisch.",
    "library.compare.progress": "{stage}: {completed} von {total}",
    "library.compare.selected_file": "Ausgewählte Datei",
    "library.compare.show_more_files": "Weitere Dateien anzeigen ({shown} von {total})",
    "library.compare.show_more_lines": "Weitere Diff-Zeilen anzeigen ({shown} von {total})",
    "library.compare.side_by_side": "Nebeneinander",
    "library.compare.title": "Versionsvergleich",
    "library.compare.unified": "Vereinheitlicht",
    "library.compare_failed": "Der Vergleich der exakten Versionen wurde nicht abgeschlossen.",
    "library.preview.binary": "Diese Datei ist binär und kann nicht in der Vorschau angezeigt werden.",
    "library.preview.loading": "Die ausgewählte Datei wird sicher gelesen…",
    "library.preview.more": "Nächste Textseite laden",
    "library.preview.range": "Bytes {start}–{end} von {total}",
    "library.preview.title": "Dateivorschau",
    "library.layout.cards": "Karten",
    "library.layout.label": "Asset-Layout",
    "library.layout.list": "Liste",
    "library.load_failed": "OAAM konnte die benötigten Projekt- oder Asset-Informationen nicht laden.",
    "library.load_interrupted": "Die Bibliotheksverbindung wurde beendet, bevor eine vertrauenswürdige Ansicht verfügbar war.",
    "library.loading": "Aktuelle Projekt- und Asset-Metadaten werden geladen…",
    "library.loading_title": "Laden Ihrer OAAM-Bibliothek",
    "library.operation_unavailable": "Diese OAAM-Version kann die benötigten Projekte und Assets nicht auflisten.",
    "library.deployments.manage": "Werkzeugorte verwalten",
    "library.deployments.start": "Verwendungsort wählen",
    "library.preference_not_saved":
        "Die Auswahl bleibt für diese Sitzung aktiv, ihre Desktop-Einstellung wurde jedoch nicht gespeichert.",
    "library.project_register_failed": "Der ausgewählte Ordner konnte nicht als Projekt registriert werden.",
    "library.project_register_interrupted":
        "Die Projektregistrierung wurde unterbrochen, bevor ein vertrauenswürdiges Ergebnis zurückgegeben wurde.",
    "library.project_registered": "Registriert {project}.",
    "library.projects.add": "Projekt hinzufügen",
    "library.projects.empty_copy":
        "Fügen Sie Ihren ersten Projektordner hinzu oder importieren Sie Assets aus bereits verwendeten Tools.",
    "library.projects.empty_eyebrow": "Keine verwalteten Projekte",
    "library.projects.empty_title": "Beginnen Sie mit einem Projekt",
    "library.projects.search": "Geladene Projekte durchsuchen",
    "library.projects.search_placeholder": "Durchsuchen Sie aktuelle Projekte",
    "library.projects.open_guided_import": "Geführten Import öffnen",
    "library.projects.title": "Projekte",
    "library.refresh": "Aktualisieren",
    "library.refresh_required": "Geänderte Daten aktualisieren",
    "library.subject.global": "Global",
    "library.subject.label": "Bibliotheksfach",
    "library.subject.projects": "Projekte",
    "library.summary.assets": "Projektvermögenswerte",
    "library.summary.global_assets": "Globale Vermögenswerte",
    "library.summary.label": "Aktuelle Bibliotheksübersicht",
    "library.summary.watched_environments": "Beobachtete Umgebungen werden angezeigt",
    "library.workspace.label": "Project-First-Asset-Arbeitsbereich",
    ...GERMAN_DESKTOP_LIBRARY_SOURCE_MESSAGES,
    ...GERMAN_DESKTOP_PROJECT_LIFECYCLE_MESSAGES,
    "common.back": "Zurück",
    "onboarding.discovery.continue_without_import": "Ohne Import fortfahren",
    "onboarding.navigation.label": "Onboarding-Navigation",
    "onboarding.welcome.choose": "Sie wählen in jedem Schritt Orte, Werkzeuge, Quellen und Assets.",
    "onboarding.welcome.copy":
        "OAAM kann an den gewählten Orten nach wiederverwendbaren Anweisungen und Einstellungen suchen. Bis zum Start wird nichts gescannt.",
    "onboarding.welcome.eyebrow": "Vor dem Scannen",
    "onboarding.welcome.inspect": "OAAM liest nur die Orte, die Sie ausdrücklich auswählen.",
    "onboarding.welcome.later": "Später einrichten",
    "onboarding.welcome.no_write": "Scannen und Importieren ändern keine Dateien Ihrer KI-Programmierwerkzeuge.",
    "onboarding.welcome.start": "Starten Sie die geführte Einrichtung",
    "onboarding.welcome.title": "Wählen Sie aus, wann OAAM Ihren Computer überprüft",
    "state_resilience.backup.copy":
        "Erstellt ein vollständiges, unveränderliches Wiederherstellungsarchiv. Backups enthalten weder andere Backup-Archive noch Dateien Ihrer KI-Coding-Tools.",
    "state_resilience.backup.create": "Verifiziertes Backup erstellen",
    "state_resilience.backup.create_failed": "Das Backup wurde nicht erstellt.",
    "state_resilience.backup.create_interrupted": "Der Backup-Vorgang wurde unterbrochen.",
    "state_resilience.backup.created": "Das verifizierte Backup wurde erstellt.",
    "state_resilience.backup.inspect": "Backup prüfen",
    "state_resilience.backup.inspect_failed": "Das Backup konnte nicht geprüft werden.",
    "state_resilience.backup.inspect_interrupted": "Die Backup-Prüfung wurde unterbrochen.",
    "state_resilience.backup.output": "Erstellt unter {path}",
    "state_resilience.backup.review_ready": "Prüfen Sie Quellgröße und Ziel, bevor Sie das Archiv erstellen.",
    "state_resilience.backup.review_title": "Backup-Prüfung",
    "state_resilience.backup.title": "OAAM-Zustand sichern",
    "state_resilience.copy":
        "Sichern Sie Ihre OAAM-Bibliothek, verwaltete Speicherorte, Wiederherstellungsdateien und Oberflächeneinstellungen und stellen Sie diese wieder her.",
    "state_resilience.destination.choose": "Anderen Ordner wählen…",
    "state_resilience.destination.choose_button": "Diesen Backup-Ordner verwenden",
    "state_resilience.destination.choose_failed": "Der Backup-Ordner konnte nicht ausgewählt werden.",
    "state_resilience.destination.choose_title": "Backup-Ordner wählen",
    "state_resilience.destination.custom": "Ausgewählter eigener Ordner",
    "state_resilience.destination.default": "OAAM-Standardordner für Backups",
    "state_resilience.destination.label": "Ziel",
    "state_resilience.destination.remembered": "Zuletzt erfolgreicher eigener Ordner: {path}",
    "state_resilience.destination.remembered_unavailable":
        "Der gemerkte Ordner ist nicht verfügbar. Wählen Sie einen anderen Ordner oder den OAAM-Standard.",
    "state_resilience.destination.use_remembered": "Letzten eigenen Ordner verwenden",
    "state_resilience.encryption.compatible": "Kompatibles Passwort (schwaches ZipCrypto)",
    "state_resilience.encryption.compatible_warning":
        "Der Kompatibilitätsmodus ist schwach. Verwenden Sie ihn nur, wenn ein anderer Computer die ZIP-Datei ohne OAAM öffnen muss.",
    "state_resilience.encryption.label": "Archivverschlüsselung",
    "state_resilience.encryption.none": "Kein Passwort",
    "state_resilience.encryption.none_warning":
        "Diese normale ZIP-Datei kann private Agent-Assets enthalten. Jeder mit der Datei kann sie lesen.",
    "state_resilience.encryption.short.compatible_password": "kompatibles Passwort",
    "state_resilience.encryption.short.none": "kein Passwort",
    "state_resilience.encryption.short.strong_password": "AES-256-Passwort",
    "state_resilience.encryption.strong": "Starkes Passwort (AES-256)",
    "state_resilience.file.action_failed": "Die Dateimanager-Aktion ist fehlgeschlagen.",
    "state_resilience.file.confirm_trash": "Dieses Backup in den Papierkorb verschieben",
    "state_resilience.file.copied": "Der Backup-Pfad wurde kopiert.",
    "state_resilience.file.copy": "Pfad kopieren",
    "state_resilience.file.copy_failed": "Der Backup-Pfad konnte nicht kopiert werden.",
    "state_resilience.file.reveal": "Im Ordner anzeigen",
    "state_resilience.file.reveal_failed":
        "Der Dateimanager konnte dieses Backup nicht anzeigen. Sie können stattdessen den Pfad kopieren.",
    "state_resilience.file.revealed": "Das Backup wurde im Dateimanager angezeigt.",
    "state_resilience.file.trash": "Entfernen…",
    "state_resilience.file.trash_failed":
        "OAAM konnte den endgültigen Papierkorbstatus nicht bestätigen. Aktualisieren Sie die Liste; es wurde nicht dauerhaft gelöscht.",
    "state_resilience.file.trashed": "Das Backup wurde in den Papierkorb verschoben.",
    "state_resilience.inventory.empty": "Es ist noch kein Backup registriert.",
    "state_resilience.inventory.summary": "{count} registrierte Backups · {bytes} derzeit verfügbar",
    "state_resilience.inventory.title": "Backup-Inventar",
    "state_resilience.load_attention": "Backup-Informationen wurden mit möglicherweise relevanten Details geladen.",
    "state_resilience.load_failed": "Backup- und Wiederherstellungsstatus konnten nicht geladen werden.",
    "state_resilience.observation.available": "Verfügbar",
    "state_resilience.observation.missing": "Fehlt",
    "state_resilience.observation.replaced": "Ersetzt",
    "state_resilience.password.confirm": "Passwort bestätigen",
    "state_resilience.password.label": "Passwort",
    "state_resilience.password_invalid": "Geben Sie zweimal dasselbe nicht leere Passwort ein.",
    "state_resilience.policy.ask": "Jedes Mal fragen",
    "state_resilience.policy.back_up_first": "Zuerst sichern",
    "state_resilience.policy.continue": "Ohne Backup-Hinweis fortfahren",
    "state_resilience.policy.copy":
        "Wählen Sie den Backup-Hinweis vor Änderungen an der Projektverwaltung oder dem dauerhaften Entfernen von Assets.",
    "state_resilience.policy.future_scope":
        "Diese Einstellung überspringt nie die genaue Prüfung der destruktiven Aktion. Bestehendes Deployment-Überschreiben und Reparieren behalten ihre Prüfung.",
    "state_resilience.policy.label": "Backup-Hinweis vor destruktiven Aktionen",
    "state_resilience.policy.latest": "Letztes verfügbares Backup: {time} · {path}",
    "state_resilience.policy.no_backup": "Kein verfügbares Backup ist registriert.",
    "state_resilience.policy.save": "Hinweis-Einstellung speichern",
    "state_resilience.policy.save_failed":
        "Die Hinweis-Einstellung wurde nicht gespeichert. Aktualisieren Sie vor dem erneuten Versuch.",
    "state_resilience.policy.saved": "Die Backup-Hinweis-Einstellung wurde gespeichert.",
    "state_resilience.policy.title": "Vor destruktiven Lebenszyklusaktionen",
    "state_resilience.progress": "{stage}: {completed}/{total}",
    "state_resilience.refresh": "Aktualisieren",
    "state_resilience.restore.activate": "Dieses vollständige Backup wiederherstellen",
    "state_resilience.restore.activate_failed":
        "Das Backup wurde nicht aktiviert. Wählen und prüfen Sie es vor der Wiederherstellung erneut.",
    "state_resilience.restore.activate_interrupted":
        "Die Wiederherstellungsverbindung endete vor einem bestätigten Ergebnis. Öffnen Sie OAAM erneut und prüfen Sie den Wiederherstellungsstatus.",
    "state_resilience.restore.activated": "Das Backup wurde aktiviert. OAAM wird mit den wiederhergestellten Daten neu geöffnet.",
    "state_resilience.restore.choose": "Andere ZIP-Datei wählen…",
    "state_resilience.restore.choose_button": "Dieses Backup prüfen",
    "state_resilience.restore.choose_failed": "Das Backup-Archiv konnte nicht ausgewählt werden.",
    "state_resilience.restore.choose_title": "OAAM-Backup-ZIP wählen",
    "state_resilience.restore.confirm":
        "Ich habe dieses vollständige Backup geprüft und verstehe, dass der aktuelle OAAM-Zustand verschoben und erhalten wird.",
    "state_resilience.restore.copy":
        "Stellt ein vollständiges verifiziertes Backup wieder her. Selektive Tabellen-, Asset- oder Deployment-Wiederherstellung wird nicht unterstützt.",
    "state_resilience.restore.inspect": "Backup prüfen",
    "state_resilience.restore.inspect_failed": "Das gewählte Archiv ist kein gültiges vollständiges OAAM-Backup.",
    "state_resilience.restore.inspect_interrupted": "Die Backup-Prüfung wurde unterbrochen.",
    "state_resilience.restore.no_displaced": "Es gab keinen vorherigen OAAM-Zustand",
    "state_resilience.restore.no_source": "Wählen Sie ein registriertes Backup oder eine andere OAAM-Backup-ZIP-Datei.",
    "state_resilience.restore.password": "Archivpasswort, falls erforderlich",
    "state_resilience.restore.restarting": "Wiederhergestellt. Vorheriger Zustand: {path}. OAAM startet neu.",
    "state_resilience.restore.review_ready": "Das vollständige Backup ist gültig. Prüfen Sie es vor der Aktivierung.",
    "state_resilience.restore.review_title": "Wiederherstellungsprüfung",
    "state_resilience.restore.title": "OAAM-Zustand wiederherstellen",
    "state_resilience.restore.use": "Wiederherstellen…",
    "state_resilience.restore.warning":
        "Die Wiederherstellung ersetzt die vollständige OAAM-Zustandseinheit. Der aktuelle Zustand wird in einem verschobenen Wiederherstellungsordner erhalten.",
    "state_resilience.review.available": "Verfügbare Kapazität",
    "state_resilience.review.created": "Erstellt",
    "state_resilience.review.desktop_preferences": "Desktop-Einstellungen",
    "state_resilience.review.destination": "Ziel",
    "state_resilience.review.destination_existing": "Vorhandener Ordner: {path}",
    "state_resilience.review.destination_planned": "Ordner wird erstellt: {path}",
    "state_resilience.review.files": "Dateien",
    "state_resilience.review.included": "Enthalten",
    "state_resilience.review.logical_size": "Logische Größe",
    "state_resilience.review.not_included": "Nicht enthalten",
    "state_resilience.stage.activation": "Aktivieren",
    "state_resilience.stage.commit": "Festschreiben",
    "state_resilience.stage.encryption": "Verschlüsseln",
    "state_resilience.stage.inspection": "Prüfen",
    "state_resilience.stage.inventory": "Inventarisieren",
    "state_resilience.stage.packing": "Packen",
    "state_resilience.stage.quiescence": "Aktive Arbeit stoppen",
    "state_resilience.stage.restart_required": "Neustart erforderlich",
    "state_resilience.stage.verification": "Verifizieren",
    "state_resilience.title": "Datensicherheit",
    "state_resilience.recovery.eyebrow": "Wiederherstellung erforderlich",
    "state_resilience.recovery.title": "OAAM-Zustand wiederherstellen",
    "state_resilience.recovery.reason.missing_database":
        "Im vorhandenen OAAM-Profil fehlt die Zustandsdatenbank. Normale Vorgänge bleiben gesperrt.",
    "state_resilience.recovery.reason.corrupt_database":
        "Die OAAM-Zustandsdatenbank ist beschädigt oder nicht lesbar. Normale Vorgänge bleiben gesperrt.",
    "state_resilience.recovery.reason.incompatible_database":
        "Die OAAM-Zustandsdatenbank ist mit diesem Build nicht kompatibel. Normale Vorgänge bleiben gesperrt.",
    "state_resilience.recovery.reason.restore_reconciliation":
        "Eine unterbrochene Zustandswiederherstellung muss vor normalen Vorgängen abgeglichen werden.",
    "state_resilience.recovery_only":
        "Im Wiederherstellungsmodus kann OAAM nur eine von Ihnen gewählte vollständige Sicherung prüfen und wiederherstellen. Normale OAAM-Daten bleiben bis zu Ihrer Bestätigung unverändert.",
    "state_resilience.unavailable": "Sicherung und Wiederherstellung sind in dieser OAAM-Sitzung nicht verfügbar.",
    "settings.close": "Einstellungen schließen",
    "settings.back_to_app": "Zurück zur App",
    "settings.eyebrow": "Anwendungseinstellungen",
    "settings.general.copy": "Diese Einstellungen ändern nur das Aussehen und Verhalten der Desktop-App.",
    "settings.general.title": "Allgemein",
    "settings.project_management.copy": "Stellen Sie hier ein gestopptes Projekt wieder her, wenn OAAM es erneut verwalten soll.",
    "settings.project_management.empty": "Es gibt keine gestoppten Projekte.",
    "settings.project_management.title": "Projektverwaltung",
    ...GERMAN_DESKTOP_DIAGNOSTICS_MESSAGES,
    ...GERMAN_DESKTOP_MAINTENANCE_MESSAGES,
    ...GERMAN_DESKTOP_PRESENTATION_MESSAGES,
    ...GERMAN_DESKTOP_SEARCH_MESSAGES,
    "settings.open": "Einstellungen",
    "settings.privacy.copy": "OAAM prüft nur Orte, die Sie freigeben.",
    "settings.privacy.no_session":
        "OAAM erfasst keine Chat-Inhalte, Anmeldedaten, Erweiterungen oder temporären Gesprächsdaten als Assets.",
    "settings.privacy.no_write":
        "Beim Scannen und Importieren werden keine Dateien geändert, die Ihre KI-Coding-Tools verwenden.",
    "settings.privacy.read": "OAAM liest nur Orte, die Sie auswählen oder weiterhin prüfen lassen.",
    "settings.privacy.title": "Datenschutz und Datenzugriff",
    "settings.runtime.copy":
        "Verwalten Sie den Standardbereich und gespeicherte Orte für Scans aus den Einstellungen. Starten Sie zum Importieren einen eigenen geführten Import.",
    "settings.runtime.guided_setup": "Import starten",
    "settings.runtime.title": "Orte und KI-Coding-Tools",
    "tray.host.failed": "OAAM: Nicht verfügbar",
    "tray.host.ready": "OAAM: Wird ausgeführt",
    "tray.host.recovering": "OAAM: Wiederherstellung läuft",
    "tray.host.starting": "OAAM: Wird gestartet",
    "tray.quit": "OAAM beenden",
    "tray.show": "OAAM anzeigen",
    "tray.tooltip": "Open Agent Asset Manager öffnen",
    "settings.title": "Einstellungen",
    "settings.search": "Einstellungen durchsuchen",
    "settings.search_no_results": "Keine passenden Einstellungen gefunden.",
    "window.about.detail":
        "Version {version}. OAAM hält die Portabilität der Agentenressourcen unter Ihrer ausdrücklichen Kontrolle.",
    "window.about.title": "Über OAAM",
    "window.action.failed": "Der Fensterbefehl konnte nicht abgeschlossen werden.",
    "window.chrome.title": "Open Agent Asset Manager",
    "window.menu.edit": "Bearbeiten",
    "window.menu.edit.copy": "Kopieren",
    "window.menu.edit.cut": "Schneiden",
    "window.menu.edit.delete": "Löschen",
    "window.menu.edit.paste": "Einfügen",
    "window.menu.edit.redo": "Wiederholen",
    "window.menu.edit.select_all": "Alles auswählen",
    "window.menu.edit.settings": "Einstellungen…",
    "window.menu.edit.undo": "Rückgängig machen",
    "window.menu.file": "Datei",
    "window.menu.file.add_project": "Projekt hinzufügen…",
    "window.menu.file.exit": "Beenden",
    "window.menu.file.hide_to_tray": "Im Infobereich ausblenden",
    "window.menu.help": "Hilfe",
    "window.menu.help.about": "Über OAAM",
    "window.menu.view": "Ansicht",
    "window.menu.view.back": "Zurück",
    "window.menu.view.forward": "Vorwärts",
    "window.menu.view.full_screen": "Vollbild umschalten",
    "window.menu.view.inspector": "Detailbereich umschalten",
    "window.menu.view.sidebar": "Seitenleiste umschalten",
    "window.menu.view.zoom_in": "Vergrößern",
    "window.menu.view.zoom_out": "Herauszoomen",
    "window.menu.view.zoom_reset": "Tatsächliche Größe",
    "window.navigation.back": "Zurück",
    "window.navigation.forward": "Vorwärts",
    "window.inspector.toggle": "Asset-Detailbereich umschalten",
    "window.sidebar.toggle": "Seitenleiste umschalten",
} as const satisfies Readonly<Record<DesktopMessageId, string>>;
