// Electron main and renderer share this catalog; it contains presentation copy only.

import { ENGLISH_DESKTOP_ASSET_ACTION_MESSAGES } from "./catalog-asset-actions";
import { ENGLISH_DESKTOP_ASSET_INSPECTOR_MESSAGES } from "./catalog-asset-inspector";
import { ENGLISH_DESKTOP_ASSET_AUTHORIZATION_MESSAGES } from "./catalog-asset-authorizations";
import { ENGLISH_DESKTOP_DEPLOYMENT_PRODUCT_LANGUAGE_MESSAGES } from "./catalog-deployment-product-language";
import { ENGLISH_DESKTOP_DIAGNOSTICS_MESSAGES } from "./catalog-diagnostics";
import { ENGLISH_DESKTOP_DIRECTORY_PREVIEW_MESSAGES } from "./catalog-directory-preview";
import { ENGLISH_DESKTOP_DISCOVERY_RESULT_MESSAGES } from "./catalog-discovery-results";
import { ENGLISH_DESKTOP_GUIDED_IMPORT_MESSAGES } from "./catalog-guided-import";
import { ENGLISH_DESKTOP_IMPORT_PREVIEW_MESSAGES } from "./catalog-import-preview";
import { ENGLISH_DESKTOP_LIBRARY_SOURCE_MESSAGES } from "./catalog-library-sources";
import { ENGLISH_DESKTOP_MAINTENANCE_MESSAGES } from "./catalog-maintenance";
import { ENGLISH_DESKTOP_PRESENTATION_MESSAGES } from "./catalog-presentation";
import { ENGLISH_DESKTOP_PROJECT_LIFECYCLE_MESSAGES } from "./catalog-project-lifecycle";
import { ENGLISH_DESKTOP_SEARCH_MESSAGES } from "./catalog-search";

export const ENGLISH_DESKTOP_MESSAGES = {
    "app.brand.subtitle": "Agent asset manager",
    "app.client_unavailable.eyebrow": "Client unavailable",
    "app.client_unavailable.message": "OAAM started, but the local workspace connection is unavailable.",
    "app.client_unavailable.title": "OAAM could not open the local workspace.",
    "app.failed.eyebrow": "OAAM unavailable",
    "app.failed.reason": "Failure code:",
    "app.failed.title": "OAAM could not finish starting.",
    "app.host.running": "Running",
    "app.navigation.catalog": "Catalog & deploy",
    "app.navigation.import": "Import review",
    "app.navigation.label": "Workspace navigation",
    "app.navigation.overview": "Overview",
    "app.navigation.sources": "Sources",
    "app.navigation.workspace": "Workspace",
    "app.ready": "Ready",
    "app.reconnecting.title": "Reconnecting OAAM",
    "app.saved_assets.many": "{count} saved assets",
    "app.saved_assets.one": "{count} saved asset",
    "app.starting.eyebrow": "Open Agent Asset Manager",
    "app.starting.title": "Starting OAAM",
    "app.toolbar.assets": "Agent assets",
    "app.toolbar.workspace": "Local workspace",
    "app.workspace.label": "OAAM workspace",
    "common.cancel": "Cancel",
    "common.close": "Close",
    "common.retry": "Retry",
    "common.save": "Save",
    "discovery.complete_with_warnings": "The scan finished, but some locations could not be checked.",
    "discovery.enable_provider_first": "Choose at least one available AI coding tool before scanning.",
    "discovery.interrupted": "The scan was interrupted. Try again to get current results.",
    "discovery.loading": "Loading your scan choices…",
    "discovery.loading_failed": "OAAM could not load your scan choices.",
    "discovery.no_environment": "Choose at least one available location before scanning.",
    "discovery.provider.save_failed": "Your tool choices were not saved. Refresh them before trying again.",
    "discovery.provider.saved": "Your tool choices were saved. Scan again to see current local assets.",
    "discovery.provider.saving": "Saving tool choices…",
    "discovery.scanning": "Scanning the selected tools and locations…",
    "discovery.settings_unavailable": "Scan choices are unavailable.",
    "discovery.snapshot_refreshed": "The scan results are up to date.",
    "discovery.snapshot_untrustworthy": "The scan did not finish with trustworthy results.",
    "discovery.ui.copy":
        "Disabled providers are visible but cannot probe, read, render or inspect until you save an explicit choice.",
    "discovery.ui.discovery_copy":
        "{environments} available locations · {watched} saved location choices. Scanning never imports files by itself.",
    "discovery.ui.discovery_copy_one_environment":
        "{environments} available location · {watched} saved location choices. Scanning never imports files by itself.",
    "discovery.ui.discovery_copy_one_source":
        "{environments} available locations · {watched} saved location choice. Scanning never imports files by itself.",
    "discovery.ui.discovery_copy_one_each":
        "{environments} available location · {watched} saved location choice. Scanning never imports files by itself.",
    "discovery.ui.eyebrow": "Local asset scan",
    "discovery.ui.environment.current_process": "OAAM will scan this computer only after you continue.",
    "discovery.ui.environment.legend": "Locations to scan",
    "discovery.ui.environment.windows_default": "This Windows computer is selected by default.",
    "discovery.ui.environment.wsl_opt_in": "Select this WSL distribution only if you also keep agent assets there.",
    ...ENGLISH_DESKTOP_DISCOVERY_RESULT_MESSAGES,
    ...ENGLISH_DESKTOP_GUIDED_IMPORT_MESSAGES,
    ...ENGLISH_DESKTOP_IMPORT_PREVIEW_MESSAGES,
    ...ENGLISH_DESKTOP_ASSET_ACTION_MESSAGES,
    ...ENGLISH_DESKTOP_ASSET_INSPECTOR_MESSAGES,
    ...ENGLISH_DESKTOP_ASSET_AUTHORIZATION_MESSAGES,
    ...ENGLISH_DESKTOP_DEPLOYMENT_PRODUCT_LANGUAGE_MESSAGES,
    "discovery.ui.environment_result_providers": "Providers: {providers}",
    "discovery.ui.environment_results": "Scan results by location",
    "discovery.ui.loading_providers": "Loading AI coding tools",
    "discovery.ui.no_runtime_relationship": "No agent-runtime relationship reported",
    "discovery.ui.no_snapshot": "No scan results yet.",
    "discovery.ui.no_sources": "No local asset locations were found for the selected tools.",
    "discovery.ui.unchecked_project_environment_reference":
        "{runtime} references a project in {environment}. It has not been checked. Select {environment} and continue to check it.",
    "discovery.ui.picker.choose_source_button": "Use this source folder",
    "discovery.ui.picker.choose_source_title": "Choose an external source folder",
    "discovery.ui.provider.copy":
        "Disabled providers are visible but cannot probe, read, render or inspect until you save an explicit choice.",
    "discovery.ui.provider.disabled": "Disabled",
    "discovery.ui.provider.disabled_after_save": "Disabled after save",
    "discovery.ui.provider.enabled": "Enabled",
    "discovery.ui.provider.enabled_after_save": "Enabled after save",
    "discovery.ui.provider.entries.many": "{count} runtime entries",
    "discovery.ui.provider.entries.one": "{count} runtime entry",
    "discovery.ui.provider.eyebrow": "Scan setup",
    "discovery.ui.provider.save": "Save provider access",
    "discovery.ui.provider.saving": "Saving…",
    "discovery.ui.provider.title": "Choose which adapters OAAM may run",
    "discovery.ui.provider.unavailable": "This previously saved tool is not available in this OAAM build.",
    "discovery.ui.probe_status.complete": "Complete",
    "discovery.ui.probe_status.failed": "Failed",
    "discovery.ui.probe_status.partial": "Partial",
    "discovery.ui.refresh_settings": "Refresh choices",
    "discovery.ui.review_sources": "Review selected locations",
    "discovery.ui.retry_discovery": "Try scan again",
    "discovery.ui.run": "Scan now",
    "discovery.ui.save_and_run": "Save choices and scan",
    "discovery.ui.save_before_scan": "Your updated tool choices will be saved before the scan starts.",
    "discovery.ui.scanning": "Scanning…",
    "discovery.ui.select_import_source": "Select {path} for import review",
    "discovery.ui.select_source": "Select {path}",
    "discovery.ui.source.eyebrow": "Local assets",
    "discovery.ui.source.moved_from": "Previously: {path}",
    "discovery.ui.source.title": "Find and review asset locations",
    "discovery.ui.status.current": "Current",
    "discovery.ui.status.missing": "Missing",
    "discovery.ui.status.moved": "Moved",
    "discovery.ui.status.new": "New",
    "discovery.ui.status.not_checked": "Not checked",
    "discovery.ui.warnings": "Discovery warnings",
    "discovery.ui.watch.do_not_watch": "Do not include in future scans",
    "discovery.ui.watch.global": "Watch as a global source",
    "discovery.ui.watch.label": "Future scans",
    "discovery.ui.watch.project": "Watch for project: {project}",
    "discovery.ui.watch.project_unavailable": "Retain unavailable project binding: {project}",
    "discovery.ui.watch.save": "Save future-scan choices",
    "discovery.ui.watch.saving": "Saving future-scan choices…",
    "discovery.ui.watch.source_label": "Future-scan choice for {path}",
    "discovery.ui.watch.unavailable": "This source has no stable watch identity.",
    "discovery.watch.saved": "Location choices saved. OAAM will still re-check the real paths next time.",
    "discovery.watch.save_failed": "Location choices were not saved. Refresh the scan before trying again.",
    "discovery.watch.saving": "Saving location choices…",
    "discovery.watch.selection_invalid": "A location choice is out of date. Review the latest scan results.",
    "import.accepting": "Importing selected Assets…",
    "import.batch.complete": "Import finished. Review each Asset below.",
    "import.batch.failed": "The selected Assets were not imported.",
    "import.batch.partial": "Some Assets were imported and some were not. Review each result below.",
    "import.cancel.failed": "This Asset review could not be closed.",
    "import.cancel.interrupted": "Closing the Asset review was interrupted.",
    "import.cancelled": "Asset review closed. Choose sources again if you want to prepare another review.",
    "import.cancelling": "Closing Asset review…",
    "import.choose_candidates": "Choose the Assets you want to save. Nothing is imported until you confirm.",
    "import.choose_compatible_asset": "Choose a current, non-deleted Asset with the same asset kind.",
    "import.choose_compatible_candidate": "Choose another selected Asset that can satisfy this relationship.",
    "import.choose_existing_version": "Choose a current existing Version with a compatible asset kind.",
    "import.connection_ended":
        "The connection ended before OAAM could report the import result. Refresh the library before retrying.",
    "import.detail.interrupted": "File detail loading was interrupted.",
    "import.detail.unavailable": "The selected file detail is unavailable.",
    "import.idle": "Go back to choose a source, or continue without importing.",
    "import.interrupted": "Asset review was interrupted before trustworthy results were available.",
    "import.no_candidates": "The selected sources did not contain any Assets ready to review.",
    "import.catalog.failed": "The Asset library could not be loaded. Retry before choosing where to save these changes.",
    "import.preview.failed": "The Asset review could not be prepared.",
    "import.previewing": "Preparing Asset review…",
    "import.read.failed": "The selected sources could not be read.",
    "import.read.attention": "Some selected locations need attention.",
    "import.reading": "Reading selected sources…",
    "import.ui.action.cancel": "Close Asset review",
    "import.ui.action.cancelling": "Cancelling…",
    "import.ui.action.import": "Import selected Assets",
    "import.ui.action.importing": "Importing…",
    "import.ui.binary_copy":
        "This binary file is not shown. Its exact type, size and hash remain available in technical details.",
    "import.ui.binding.choose_exact": "Choose a related Asset",
    "import.ui.binding.existing_versions": "Assets already in the library",
    "import.ui.binding.leave_unbound": "Do not link an Asset",
    "import.ui.binding.optional": "Optional related Asset for {target}",
    "import.ui.binding.required": "Required related Asset for {target}",
    "import.ui.binding.selected_candidates": "Assets selected in this review",
    "import.ui.binding.target_label": "Related Asset for {candidate}: {target}",
    "import.ui.candidate.file_count.many": "{count} files",
    "import.ui.candidate.file_count.one": "{count} file",
    "import.ui.candidate.select": "Select {candidate}",
    "import.ui.asset.scope.global": "Global library",
    "import.ui.asset.scope.project": "Current project",
    "import.ui.asset.status.blocked": "Cannot import",
    "import.ui.asset.status.duplicate": "Already represented",
    "import.ui.asset.status.incomplete": "Cannot import yet",
    "import.ui.asset.status.ready": "Ready",
    "import.ui.asset.status.requires_refresh": "Scan again",
    "import.ui.asset.status.stale": "Source changed",
    "import.ui.asset.status.unknown": "Source status unknown",
    "import.ui.diagnostics.attribution": "Asset review",
    "onboarding.completion.eyebrow": "Safe completion",
    "onboarding.completion.failed": "OAAM could not save onboarding completion. Nothing was deployed.",
    "onboarding.completion.finish_without_import": "Finish without importing",
    "onboarding.completion.imported_copy":
        "The selected Assets are in the OAAM library. No files used by an AI coding tool were changed.",
    "onboarding.completion.imported_title": "Safe import complete",
    "onboarding.completion.open_workspace": "Open workspace",
    "onboarding.completion.safe_copy":
        "You can finish after a fresh scan without importing. Scanning and keeping a location for later checks do not deploy files.",
    "onboarding.completion.safe_title": "Finish when the source snapshot looks right",
    "onboarding.completion.saving": "Opening workspace…",
    "onboarding.copy": "Choose where OAAM looks, review what it finds, and decide which Assets to keep.",
    "onboarding.eyebrow": "First run",
    "onboarding.steps.label": "First-run progress",
    "onboarding.title": "Set up OAAM without changing files used by your AI coding tools",
    "import.ui.copy": "Review the files when needed, then select only the Assets you want OAAM to save.",
    "import.ui.dependencies_too_many": "This Asset refers to {count} related Assets, which is too many to review safely here.",
    "import.ui.destination.add_version": "Add Version after {asset} revision {revision}",
    "import.ui.destination.create_asset": "Create a new OAAM Asset",
    "import.ui.destination.label": "How to save {candidate}",
    "import.ui.destination.save_as": "Save as",
    "import.ui.detail.binary_label": "Reviewed file detail",
    "import.ui.detail.first_file": "First file",
    "import.ui.detail.loading": "Loading file detail…",
    "import.ui.detail.text_truncated": "This text is truncated; the hash covers the complete file.",
    "import.ui.detail.view": "View {path}",
    "import.ui.detail.view_first": "View first file",
    "import.ui.eyebrow": "Import review",
    "import.ui.failed.refresh_title": "Fresh discovery required",
    "import.ui.failed.title": "Import review unavailable",
    "import.ui.files_omitted": "More files belong to this Asset; open the available files before importing if needed.",
    "import.ui.no_candidates": "The selected sources contain no Assets ready to import.",
    "import.ui.no_preview": "No Assets selected for review",
    "import.ui.preparing": "Preparing Asset review",
    "import.ui.reading": "Reading selected sources",
    "import.ui.read_attention.action_copy":
        "Review the details, then retry. To change the source locations, return to the location selection.",
    "import.ui.read_attention.continue": "Continue with readable locations",
    "import.ui.read_attention.copy":
        "OAAM did not send an incomplete read to Asset review. No Assets from the affected locations will be imported.",
    "import.ui.read_attention.eyebrow": "File access",
    "import.ui.read_attention.status.failed": "This location could not be read",
    "import.ui.read_attention.status.not_found": "This location is no longer available",
    "import.ui.read_attention.status.partial": "Only part of this location could be read",
    "import.ui.read_attention.status.unreported": "This location did not return a trustworthy result",
    "import.ui.read_attention.title": "Some locations could not be read completely",
    "import.ui.refresh_required": "The source files changed or this review expired. Scan again before importing.",
    "import.ui.return_to_sources": "Review scan locations",
    "import.ui.result.batch_outcomes": "Import results",
    "import.ui.result.copy": "{message} A failed Asset does not undo an Asset that was imported successfully.",
    "import.ui.result.no_tool_changes": "Project files and tool configuration were not changed.",
    "import.ui.result.retry_failed": "To retry failed Assets, return to sources and select only those Assets.",
    "import.ui.result.dependency_failed": "Required Asset was not imported",
    "import.ui.result.failed": "Failed",
    "import.ui.result.failed_dependencies": "Required Assets not imported: {assets}",
    "import.ui.result.imported": "Imported",
    "import.ui.result.asset_saved": "New Asset saved in the OAAM library",
    "import.ui.result.version_saved": "New Version saved to the existing Asset",
    "import.ui.result.open": "Open Asset",
    "import.ui.result.open_failed": "The Asset was saved, but could not be opened. Try again or find it in the library.",
    "import.ui.result.title": "Import result",
    "import.ui.result.unknown_asset": "Unnamed Asset",
    "import.ui.safe_import_copy":
        "Each selected Asset must create a new Asset or add a Version to a compatible Asset. Importing does not change any AI coding tool or project file.",
    "import.ui.technical.asset_id": "Asset ID: {assetId}",
    "import.ui.technical.byte_length": "Size in bytes: {byteLength}",
    "import.ui.technical.candidate_id": "Review item ID: {candidateId}",
    "import.ui.technical.content_hash": "Complete-file hash: {contentHash}",
    "import.ui.technical.media_type": "Media type: {mediaType}",
    "import.ui.technical.version_id": "Version ID: {versionId}",
    "import.ui.technical_details": "Technical details",
    "import.ui.title": "Choose Assets and any required related Assets",
    "import.validation.binding_duplicate": "One related-Asset choice was selected more than once.",
    "import.validation.binding_existing_stale": "A selected existing Version is no longer current or compatible.",
    "import.validation.binding_stale": "A related Asset is no longer available, selected or compatible.",
    "import.validation.candidate_dependencies_truncated":
        "{candidate} refers to more related Assets than this review can show safely.",
    "import.validation.candidate_not_importable": "{candidate} cannot be imported from this Asset review.",
    "import.validation.candidate_refresh": "{candidate} needs a fresh scan.",
    "import.validation.destination_choose": "Choose whether {candidate} creates a new Asset or a new Version.",
    "import.validation.destination_duplicate": "One Asset has more than one selected save destination.",
    "import.validation.destination_incompatible": "{candidate} has an outdated or incompatible existing-Asset destination.",
    "import.validation.destination_missing": "A selected save destination is no longer available in this Asset review.",
    "import.validation.destination_stale": "A save destination belongs to an outdated or unselected Asset.",
    "import.validation.missing_binding": "{candidate} still needs a related Asset for {target}.",
    "import.validation.no_selection": "Select at least one Asset that is ready to import.",
    "import.validation.preview_membership": "The selected Assets no longer belong to this Asset review.",
    "import.validation.user_action": "OAAM could not confirm this action. Close and reopen the Asset review before trying again.",
    "catalog.activity.analyze": "Analyzing render options",
    "catalog.version_update.action": "Update selected Version",
    "catalog.version_update.title": "Update the Version used here",
    "catalog.version_update.copy":
        "This location selects another Version. Choose the new Version, review the file changes, then apply them.",
    "catalog.version_update.choose": "Select revision {revision} and review",
    "catalog.version_update.selected": "Previously selected Version: {version}",
    "catalog.version_update.next": "New Version: {version}",
    "catalog.version_update.pending": "Selected inputs need review",
    "catalog.version_update.changed": "The Asset or location changed. Reload before reviewing this update.",
    "catalog.version_update.failed": "The selected Version could not be updated.",
    "catalog.activity.create": "Saving tool setup",
    "catalog.activity.deploy": "Deploying selected render",
    "catalog.activity.preview": "Preparing exact target preview",
    "catalog.activity.inspect": "Inspecting deployed file changes",
    "catalog.activity.recover": "Recovering tool-file state",
    "catalog.activity.register": "Registering project",
    "catalog.activity.repair": "Repairing OAAM-managed files",
    "catalog.activity.reverse_cancel": "Cancelling the prepared review",
    "catalog.activity.reverse_commit": "Saving reviewed changes",
    "catalog.activity.reverse_refresh": "Refreshing the saved Version and managed location",
    "catalog.activity.reverse_prepare": "Preparing reviewed changes",
    "catalog.activity.scan": "Scanning deployed files",
    "catalog.asset.detail_interrupted": "Asset detail loading was interrupted.",
    "catalog.asset.detail_unavailable": "Asset detail is unavailable.",
    "catalog.asset.missing": "The selected Asset or current Version no longer exists.",
    "catalog.authority_changed":
        "The library changed while this page was open. Actions are paused so stale choices cannot be applied. Refresh to review the current state.",
    "catalog.empty": "The library is empty. Import and review Assets before choosing which AI coding tools should use them.",
    "catalog.deployment.created": "This tool setup was saved. Review the file changes before writing anything.",
    "catalog.deployment.creation_failed": "This tool setup could not be saved.",
    "catalog.inspection.conflict": "File conflicts require an explicit restore or a choice to save the reviewed changes.",
    "catalog.inspection.current": "Inspection is current. Review individual details before repairing.",
    "catalog.inspection.detail_interrupted": "Inspection detail was interrupted.",
    "catalog.inspection.detail_unavailable": "Inspection detail is unavailable.",
    "catalog.inspection.interrupted": "Inspection was interrupted.",
    "catalog.inspection.lost_channel": "Inspection lost its terminal channel. Inspect again to obtain fresh evidence.",
    "catalog.inspection.retained_expired":
        "The retained inspection expired or was replaced. Inspect again before a repair or overwrite.",
    "catalog.load.failed": "The OAAM catalog could not be loaded.",
    "catalog.load.interrupted": "The OAAM catalog load was interrupted.",
    "catalog.loading": "Loading OAAM catalog…",
    "catalog.operation.failed": "{operation} failed.",
    "catalog.operation.finished": "The operation finished. Current status: {stage}.",
    "catalog.operation.interrupted": "{operation} was interrupted before a trustworthy result was available.",
    "catalog.operation.lost_terminal":
        "{operation} lost its final result. Do not retry blindly; reload the latest saved state and recover if required.",
    "catalog.project.registered": "Registered {project}.",
    "catalog.project.registration_failed": "The selected project could not be registered.",
    "catalog.preview.failed": "The exact target preview could not be prepared.",
    "catalog.preview.interrupted": "Target preview was interrupted before a trustworthy result was available.",
    "catalog.preview.lost_channel": "Target preview lost its terminal channel. Prepare a fresh preview before writing.",
    "catalog.preview.ready": "Exact current and desired target states are ready for review.",
    "catalog.preview.retained_expired": "The retained target preview expired or was replaced. Prepare a fresh preview.",
    "catalog.render.analysis_failed": "Render analysis failed.",
    "catalog.render.choose_strategies": "Choose one strategy for every semantic input. Required degradation remains unapproved.",
    "catalog.render.interrupted": "Render analysis was interrupted.",
    "catalog.render.lost_channel":
        "Render analysis lost its terminal channel. It is read-only and may be run again after refresh.",
    "catalog.reverse.cancel_failed": "The prepared review could not be cancelled.",
    "catalog.reverse.cancelled": "The prepared review was cancelled without changing the Asset.",
    "catalog.reverse.commit_failed": "The reviewed changes were not saved.",
    "catalog.reverse.not_prepared": "These changes could not be prepared safely for review.",
    "catalog.reverse.prepare_failed": "OAAM could not prepare the exact inspected changes.",
    "catalog.reverse.prepared": "Review how the inspected changes would become an Asset Version.",
    "catalog.reverse.promotion_confirmation_required": "Confirm this exact new Version before saving it.",
    "catalog.reverse.result.committed": "The new Asset Version was published and selected by this tool setup.",
    "catalog.reverse.result.not_published": "No new Asset Version was published.",
    "catalog.reverse.result.outcome_unavailable":
        "OAAM cannot prove whether the changes were saved. Reload the latest saved state.",
    "catalog.reverse.result.published_not_selected":
        "The new Asset Version was published, but this tool setup still selects its previous Version.",
    "catalog.reverse.result.recovery_required": "This save needs recovery before another write can be attempted.",
    "catalog.target.inspection_failed": "Deployed-file inspection failed.",
    "catalog.ui.action.analyze": "Review file changes",
    "catalog.ui.action.apply": "Apply changes",
    "catalog.ui.action.create": "Save this setup",
    "catalog.ui.action.inspect": "Review outside changes",
    "catalog.ui.action.overwrite": "Apply the selected OAAM version",
    "catalog.ui.action.preview": "Review files before applying",
    "catalog.ui.action.recover": "Recover",
    "catalog.ui.action.repair": "Repair from this exact inspection",
    "catalog.ui.action.replace_unmanaged": "Replace existing files",
    "catalog.ui.action.reverse_cancel": "Cancel without saving",
    "catalog.ui.action.reverse_commit": "Keep as a new library version",
    "catalog.ui.action.reverse_prepare": "Review changes from the tool",
    "catalog.ui.action.scan": "Check file status",
    "catalog.ui.asset.bytes": "{count} bytes",
    "catalog.ui.asset.catalog_eyebrow": "Asset and Version catalog",
    "catalog.ui.asset.catalog_title": "Choose exact saved Versions",
    "catalog.ui.asset.current_version": "Current Asset Version",
    "catalog.ui.asset.empty": "No Assets are saved yet. Complete an import review above first.",
    "catalog.ui.asset.loading_detail": "Loading exact Version metadata…",
    "catalog.ui.asset.refresh": "Refresh catalog",
    "catalog.ui.asset.revision_version": "Revision {revision} · Version {versionId}",
    "catalog.ui.asset.view_version": "View current Version",
    "catalog.ui.catalog_eyebrow": "Library and tool use",
    "catalog.ui.catalog_loading": "Loading OAAM catalog",
    "catalog.ui.catalog_unavailable": "Catalog unavailable",
    "catalog.ui.catalog_warnings": "Library and tool-file notices",
    "catalog.ui.create.add_folder": "Add project folder",
    "catalog.ui.create.allow_incomplete": "Explicitly allow this incomplete Version",
    "catalog.ui.create.asset_revision": "{asset} · Version {revision}",
    "catalog.ui.create.assets_legend": "Exact current Asset Versions",
    "catalog.ui.create.consumer_legend": "Tool entry to use at this location",
    "catalog.ui.create.copy": "Choose the exact tool entry. OAAM will show the file changes before anything is written.",
    "catalog.ui.create.eyebrow": "Step 3",
    "catalog.ui.create.fresh_target": "Tool location",
    "catalog.ui.create.no_ready_runtime": "This tool cannot use the selected location.",
    "catalog.ui.create.not_ready": "Unavailable here: {agentRuntimeIds}",
    "catalog.ui.create.project": "OAAM Project",
    "catalog.ui.create.project_choose": "Choose a project",
    "catalog.ui.create.subject_global": "Assets will come from the Global library.",
    "catalog.ui.create.subject_project": "Assets will come from this Project and the Global library.",
    "catalog.ui.create.target_choose": "Choose a discovered tool location",
    "catalog.ui.create.title": "Confirm where to add it",
    "catalog.ui.deployment.asset_count.many": "{count} library items",
    "catalog.ui.deployment.asset_count.one": "{count} library item",
    "catalog.ui.deployment.empty": "No tool setup has been saved yet.",
    "catalog.ui.deployment.eyebrow": "Configured tools",
    "catalog.ui.deployment.select": "Select a tool setup before checking or updating it.",
    "catalog.ui.deployment.title": "Check and update tool files",
    "catalog.ui.freshness.complete": "Last checked {time}",
    "catalog.ui.freshness.failed": "Last check failed {attempt} · last complete {lastComplete}",
    "catalog.ui.freshness.in_progress": "Checking since {attempt} · last complete {lastComplete}",
    "catalog.ui.freshness.never": "Not checked yet",
    "catalog.ui.freshness.no_complete": "not yet completed",
    "catalog.ui.freshness.partial": "Last check was partial {attempt} · last complete {lastComplete}",
    "catalog.ui.inspection.change_count.many": "{count} changes",
    "catalog.ui.inspection.change_count.one": "{count} change",
    "catalog.ui.inspection.conflict_count.many": "{count} conflicts",
    "catalog.ui.inspection.conflict_count.one": "{count} conflict",
    "catalog.ui.inspection.detail_loading": "Loading bounded inspection detail…",
    "catalog.ui.inspection.details_omitted": "Additional inspection selectors were omitted from this bounded summary.",
    "catalog.ui.inspection.inspecting": "Inspecting deployed file changes…",
    "catalog.ui.inspection.title": "Inspection",
    "catalog.ui.inspection.file_detail": "File ownership",
    "catalog.ui.inspection.change_detail": "Content change",
    "discovery.ui.choose_environments": "Choose environments",
    "catalog.ui.picker.cancelled": "Project selection cancelled.",
    "catalog.ui.picker.choose_button": "Use this project folder",
    "catalog.ui.picker.choose_title": "Choose an OAAM project folder",
    "catalog.ui.picker.failed": "The native project-folder selection failed.",
    "catalog.ui.picker.opening": "Opening the native project-folder picker…",
    "catalog.ui.picker.registering": "Registering {path}…",
    "catalog.ui.preview.action.blocked_managed_conflict":
        "Managed content has changed. Review this version and confirm replacement to apply it.",
    "catalog.ui.preview.action.ready_apply": "The exact target state allows an ordinary apply.",
    "catalog.ui.preview.action.requires_unmanaged_replacement":
        "The target already contains different content. Review the file changes, then confirm this replacement.",
    "catalog.ui.preview.change.create": "Create a new file",
    "catalog.ui.preview.change.establish_baseline": "Keep identical content and establish an OAAM baseline",
    "catalog.ui.preview.change.managed_conflict": "Managed target differs from its OAAM baseline",
    "catalog.ui.preview.change.remove_managed": "Remove an OAAM-managed file",
    "catalog.ui.preview.change.replace_unmanaged": "Replace different existing content",
    "catalog.ui.preview.change.remove_unmanaged": "Remove this reviewed existing file",
    "catalog.ui.preview.change.unchanged": "Keep the managed file unchanged",
    "catalog.ui.preview.change.update_managed": "Update the managed file",
    ...ENGLISH_DESKTOP_DIRECTORY_PREVIEW_MESSAGES,
    "catalog.ui.preview.confirm_managed_overwrite":
        "I reviewed the external file changes and choose to restore the exact OAAM output once",
    "catalog.ui.preview.confirm_unmanaged": "I reviewed the existing content and agree to replace it this time",
    "catalog.ui.preview.current_tab": "Current",
    "catalog.ui.preview.desired_tab": "Desired",
    "catalog.ui.preview.current_text": "Current target text",
    "catalog.ui.preview.desired_text": "Desired target text",
    "catalog.ui.preview.review_tab": "File changes",
    "catalog.ui.preview.open_current": "Open current file in a tab",
    "catalog.ui.preview.open_desired": "Open desired file in a tab",
    "catalog.ui.preview.snapshot_copy": "Showing file content captured for this preview.",
    "catalog.ui.preview.bounded_diff":
        "These files differ substantially, so changes are shown as whole sections. Open either file to read its full content.",
    "catalog.ui.reconciliation_required":
        "OAAM lost the final result of a change. Reload the latest saved state; do not repeat the action blindly.",
    "catalog.ui.reverse.finish_recovery":
        "To finish this operation, choose Recover. OAAM will verify the saved result before another change.",
    "catalog.ui.reverse.confirm_promotion": "Allow this tool setup to select this exact new Asset Version",
    "catalog.ui.reverse.expires": "This preparation expires at {time}.",
    "catalog.ui.reverse.preparing": "Preparing the exact inspected changes for review…",
    "catalog.ui.reverse.result_title": "Save result",
    "catalog.ui.reverse.title": "Review changes from the tool",
    "catalog.ui.reverse.whole_file_adoption":
        "Changes that require whole-file adoption belong in the normal source read and import review flow.",
    "catalog.ui.render.approve_degraded": "Approve this degraded render once",
    "catalog.ui.render.approval.reverse_extract_unsupported": "Future edits in this tool cannot be safely brought back",
    "catalog.ui.render.approval.semantic_degradation": "Some source behavior will be lost",
    "catalog.ui.render.blocked": "This part cannot be rendered safely.",
    "catalog.ui.render.degradation.folder_asset_flattened": "The folder asset will be flattened",
    "catalog.ui.render.degradation.memory_semantics_lost": "Memory behavior will become plain content",
    "catalog.ui.render.degradation.permission_or_tool_boundary_lost": "A permission or tool boundary will be lost",
    "catalog.ui.render.degradation.reverse_extract_pollution_risk": "Later reverse extraction may include generated content",
    "catalog.ui.render.degradation.runtime_specific_metadata_lost": "Tool-specific metadata will be lost",
    "catalog.ui.render.degradation.target_runtime_missing_asset_kind":
        "This AI coding tool has no native form for this Asset kind",
    "catalog.ui.render.degradation.trigger_or_loading_level_lost": "The original trigger or loading level will be lost",
    "catalog.ui.render.degradation.workflow_permission_lost": "Workflow permission behavior will be lost",
    "catalog.ui.render.degradation.workflow_runtime_lost": "Workflow execution behavior will be lost",
    "catalog.ui.render.degradation.workflow_trigger_lost": "Workflow trigger behavior will be lost",
    "catalog.ui.render.degradation.workflow_variable_lost": "Workflow variable behavior will be lost",
    "catalog.ui.render.degradations": "Behavior changes",
    "catalog.ui.render.executable_suffix": " · executable",
    "catalog.ui.render.managed_directory": "Managed directory: {path}",
    "catalog.ui.render.no_target_file": "This semantic does not add a direct file claim.",
    "catalog.ui.render.output_binary": "{path} · binary{executable}",
    "catalog.ui.render.output_text": "{path} · text{executable}",
    "catalog.ui.render.output_counts": "{count} files · {text} text · {binary} binary · {executable} executable",
    "catalog.ui.render.directory_count": "{count} managed directories",
    "catalog.ui.render.preview_required":
        "Choose one complete render option per item. OAAM will show a fresh exact target preview before any write.",
    "catalog.ui.render.reverse.can_reconcile": "Future edits can be attributed and reviewed",
    "catalog.ui.render.reverse.ignore_generated_wrapper": "Generated wrapper text is ignored when changes are brought back",
    "catalog.ui.render.reverse.unsupported": "Future edits cannot be safely brought back",
    "catalog.ui.render.reverse_label": "Future edit handling: {policy}",
    "catalog.ui.render.runtime": "AI coding tool: {runtime}",
    "catalog.ui.render.semantic.asset_file_inventory": "Included files",
    "catalog.ui.render.semantic.guidance_base_context": "Project context",
    "catalog.ui.render.semantic.guidance_content": "Instructions",
    "catalog.ui.render.semantic.memory_content": "Memory content",
    "catalog.ui.render.semantic.memory_support": "Memory support",
    "catalog.ui.render.semantic.rule_activation": "Rule activation",
    "catalog.ui.render.semantic.rule_content": "Rule content",
    "catalog.ui.render.semantic.skill_body": "Skill instructions",
    "catalog.ui.render.semantic.skill_discovery_metadata": "Skill discovery metadata",
    "catalog.ui.render.semantic.skill_resource": "Skill resource",
    "catalog.ui.render.semantic.subagent_delegation_metadata": "Subagent delegation metadata",
    "catalog.ui.render.semantic.subagent_invoked_context": "Subagent invoked context",
    "catalog.ui.render.semantic.subagent_model_hint": "Subagent model hint",
    "catalog.ui.render.semantic.subagent_resource": "Subagent resource",
    "catalog.ui.render.semantic.subagent_tool_boundary": "Subagent tool boundary",
    "catalog.ui.render.semantic.workflow_activation": "Workflow activation",
    "catalog.ui.render.semantic.workflow_content": "Workflow content",
    "catalog.ui.render.semantic.workflow_reference": "Workflow reference",
    "catalog.ui.render.strategy.inline": "Inline content",
    "catalog.ui.render.strategy.native_directory": "Native directory",
    "catalog.ui.render.strategy.native_graph": "Native file graph",
    "catalog.ui.render.strategy.native_file": "Native file",
    "catalog.ui.render.strategy.native_import": "Native import",
    "catalog.ui.render.strategy.reference_with_intro": "Reference with a short introduction",
    "catalog.ui.support_required":
        "OAAM cannot recover this tool-file setup automatically. Preserve the inspection result and contact support.",
    "catalog.ui.render.subject": "{asset} · {semantic}",
    "catalog.ui.render.title": "Choose how the files should appear in the tool",
    "catalog.ui.render.waiting": "Waiting for render analysis…",
    "catalog.ui.status.external_changes": "External changes found",
    "catalog.ui.status.first_deployment": "First deployment available",
    "catalog.ui.status.needs_checking": "Status needs checking",
    "catalog.ui.status.paused_for_safety": "Paused for safety",
    "catalog.ui.status.repair_available": "Some managed files can be restored",
    "catalog.ui.status.review_required": "This tool setup needs review",
    "catalog.ui.status.support_required": "Support is required",
    "catalog.ui.status.up_to_date": "Up to date",
    "catalog.ui.target.choose_project": "Check tools",
    "catalog.ui.target.copy":
        "Choose the tools and system environment to check for this Project. The Asset's source tool does not restrict where you can use it. This check does not change files.",
    "catalog.ui.target.discover_global": "Check tools",
    "catalog.ui.target.environments": "System environments to check",
    "catalog.ui.target.eyebrow": "Tools and locations",
    "catalog.ui.target.loading": "Loading tools and system environments",
    "catalog.ui.target.no_provider": "No selected tool is available.",
    "catalog.ui.target.probing": "Checking tools…",
    "catalog.ui.target.providers": "Tools to use",
    "catalog.ui.target.select_all": "Select all",
    "catalog.ui.target.clear_all": "Clear",
    "catalog.ui.target.title": "Find available tools",
    "catalog.ui.target.unavailable": "Available tools cannot be checked right now",
    "catalog.ui.workspace.back": "Back to library",
    "catalog.ui.workspace.eyebrow": "Tool locations",
    "catalog.ui.workspace.global": "Use Global Assets",
    "catalog.ui.workspace.project": "Use Project Assets",
    "catalog.validation.asset_duplicate": "A tool setup cannot include the same Asset twice.",
    "catalog.validation.asset_incomplete": "{asset} is incomplete. Explicitly allow that Version or remove it.",
    "catalog.validation.asset_missing": "A selected Asset is no longer in the current catalog.",
    "catalog.validation.asset_version_changed": "{asset} has a different current Version. Review and select it again.",
    "catalog.validation.choose_asset": "Choose at least one Asset to provide to a tool.",
    "catalog.validation.choose_project": "Choose a current OAAM project.",
    "catalog.validation.choose_runtime": "Choose at least one AI coding tool available for this exact location.",
    "catalog.validation.choose_target": "Choose a target from the current discovery snapshot.",
    "catalog.validation.render_approval": "Explicitly approve the degraded option {strategy} or choose another strategy.",
    "catalog.validation.render_approval_evidence": "The approval has no user-action evidence.",
    "catalog.validation.render_duplicate": "A semantic input has more than one render selection.",
    "catalog.validation.render_incomplete": "OAAM could not verify the complete file-change review. Refresh before continuing.",
    "catalog.validation.render_missing": "Choose exactly one render strategy for every semantic input.",
    "catalog.validation.render_none": "This analysis contains no render option that can be deployed.",
    "session.catalog_unavailable": "OAAM catalog is unavailable.",
    "session.connecting": "Connecting to OAAM…",
    "session.connection_closed": "The OAAM connection closed.",
    "session.host_recovering": "OAAM did not become ready. It is making one clean retry…",
    "session.host_startup_failed": "OAAM could not start. It will not keep retrying in the background.",
    "session.host_startup_timeout": "OAAM was still unavailable after 30 seconds. You can retry explicitly.",
    "session.initialization_failed": "OAAM could not prepare its local data.",
    "session.restart_failed": "OAAM could not restart.",
    "session.restarting": "Restarting OAAM…",
    "session.starting": "Starting OAAM…",
    "workspace.catalog.assets.many": "{count} assets",
    "workspace.catalog.assets.none": "No assets imported yet",
    "workspace.catalog.label": "Catalog summary",
    "workspace.host.ready": "Host ready",
    "workspace.host.warnings.many": "{count} startup warnings",
    "workspace.host.warnings.one": "{count} startup warning",
    "workspace.overview.copy": "Discover local sources, review exact candidates, then deploy only with explicit choices.",
    "workspace.overview.eyebrow": "Workspace overview",
    "workspace.overview.title": "Manage portable agent assets",
    "library.asset_detail_interrupted": "Asset metadata loading was interrupted.",
    "library.asset_detail_unavailable": "OAAM could not load the selected Asset details.",
    "library.asset_missing": "The selected Asset or current Version is no longer available.",
    "library.assets.count": "{count} Assets",
    "library.assets.deleted": "Deleted",
    "library.assets.empty": "No Assets in this collection.",
    "library.assets.empty_global_copy": "Import Assets from an AI coding tool to start your reusable Global library.",
    "library.assets.empty_global_title": "The Global asset library is empty",
    "library.assets.empty_project_copy": "Check this Project's locations in your AI coding tools, then choose what to import.",
    "library.assets.empty_project_title": "No Assets in {project}",
    "library.assets.eyebrow": "Asset library",
    "library.assets.global_copy": "Assets saved in the Global library.",
    "library.assets.global_title": "Global library",
    "library.assets.incomplete": "Incomplete",
    "library.assets.include_deleted":
        "Show Assets in the OAAM Recycle Bin. They are not permanently deleted and can still be restored.",
    "library.assets.loading": "Loading Assets…",
    "library.assets.loading_page": "Loading up to 50 Assets…",
    "library.assets.no_description": "No description",
    "library.assets.no_match": "No loaded Assets match this search.",
    "library.assets.project_copy": "Assets associated with this exact Project.",
    "library.assets.project_title": "Project Assets",
    "library.assets.revision": "Version {revision}",
    "library.assets.search": "Search loaded Assets",
    "library.assets.search_placeholder": "Search this loaded library",
    "library.assets.shared_copy": "Global Assets may be selected later, but target compatibility still requires render review.",
    "library.assets.shared_title": "Global Assets available to this Project",
    "library.assets.show_more": "Show {count} more {kind} Assets",
    "library.assets.title": "Browse saved Assets",
    "library.authority_changed": "The catalog changed. Refresh before relying on this view.",
    "library.catalog.warnings": "{count} catalog warnings",
    "library.environments.filter": "Watched environment filter",
    "library.environments.sources": "{count} watched sources",
    "library.environments.title": "Watched environments in this view",
    "library.export.action": "Export OAAM Version package",
    "library.export.choose_button": "Export package",
    "library.export.choose_title": "Save an OAAM Version package for this Version",
    "library.export.complete": "Exported the {bytes}-byte OAAM Version package.",
    "library.export.failed": "The OAAM Version package could not be exported.",
    "library.export.running": "Building the OAAM Version package…",
    "library.failed_title": "The library could not be loaded",
    "library.file_preview_failed": "The selected file could not be read safely.",
    "library.files.descendants": "{count} descendant files",
    "library.files.more": "Load 50 more entries",
    "library.files.up": "Up one folder",
    "library.global.navigation": "Global library",
    "library.global.navigation_copy": "Browse Assets and watched sources that are not owned by one Project.",
    "library.global.title": "Global library",
    "library.host.warnings": "{count} startup warnings",
    "library.inspector.bytes": "{count} bytes",
    "library.inspector.close": "Close Asset inspector",
    "library.inspector.created": "Created",
    "library.inspector.current_version": "Current Version {revision}",
    "library.inspector.executable": "Executable",
    "library.inspector.eyebrow": "Asset inspector",
    "library.inspector.files": "Files",
    "library.inspector.fingerprint": "Fingerprint",
    "library.inspector.incomplete": "This current Version is incomplete and is not presented as fully deployable.",
    "library.inspector.kind": "Kind",
    "library.inspector.label": "Selected Asset metadata",
    "library.inspector.loading": "Loading Asset details…",
    "library.inspector.more_versions": "Load 50 more Versions",
    "library.inspector.no_files": "This Version contains no files.",
    "library.inspector.overview": "Overview",
    "library.inspector.project": "Project",
    "library.inspector.scope": "Scope",
    "library.inspector.scope_path": "Scope path",
    "library.inspector.status": "Status",
    "library.inspector.title": "Asset details",
    "library.inspector.updated": "Updated",
    "library.inspector.version_id": "Version ID",
    "library.inspector.version_select": "Exact Version",
    "library.inspector.versions": "Versions",
    "library.compare.action": "Compare exact Versions",
    "library.compare.base": "Compare against",
    "library.compare.file_graph": "File changes",
    "library.compare.folded": "{count} unchanged lines folded",
    "library.compare.layout": "Diff layout",
    "library.compare.metadata_only": "The selected comparison contains file-graph changes but no rendered text diff.",
    "library.compare.no_text_changes": "The selected text is identical in both Versions.",
    "library.compare.progress": "{stage}: {completed} of {total}",
    "library.compare.selected_file": "Selected file",
    "library.compare.show_more_files": "Show more files ({shown} of {total})",
    "library.compare.show_more_lines": "Show more diff lines ({shown} of {total})",
    "library.compare.side_by_side": "Side by side",
    "library.compare.title": "Version comparison",
    "library.compare.unified": "Unified",
    "library.compare_failed": "The exact Version comparison did not complete.",
    "library.preview.binary": "This file is binary and cannot be previewed.",
    "library.preview.loading": "Reading the selected file safely…",
    "library.preview.more": "Load the next text page",
    "library.preview.range": "Bytes {start}–{end} of {total}",
    "library.preview.title": "File preview",
    "library.layout.cards": "Cards",
    "library.layout.label": "Asset layout",
    "library.layout.list": "List",
    "library.load_failed": "OAAM could not load the required Project or Asset information.",
    "library.load_interrupted": "The library connection ended before a trustworthy view was available.",
    "library.loading": "Loading current Projects and Asset metadata…",
    "library.loading_title": "Loading your OAAM library",
    "library.operation_unavailable": "This version of OAAM cannot list the required Projects and Assets.",
    "library.deployments.manage": "Manage tool locations",
    "library.deployments.start": "Choose where to use",
    "library.preference_not_saved": "The selection remains active for this session, but its Desktop preference was not saved.",
    "library.project_register_failed": "The selected folder could not be registered as a Project.",
    "library.project_register_interrupted": "Project registration was interrupted before a trustworthy result was returned.",
    "library.project_registered": "Registered {project}.",
    "library.projects.add": "Add Project",
    "library.projects.empty_copy": "Add your first Project folder, or import Assets from tools you already use.",
    "library.projects.empty_eyebrow": "No managed Projects",
    "library.projects.empty_title": "Start with a Project",
    "library.projects.search": "Search loaded Projects",
    "library.projects.search_placeholder": "Search current Projects",
    "library.projects.open_guided_import": "Open guided import",
    "library.projects.title": "Projects",
    "library.refresh": "Refresh",
    "library.refresh_required": "Refresh changed data",
    "library.subject.global": "Global",
    "library.subject.label": "Library subject",
    "library.subject.projects": "Projects",
    "library.summary.assets": "Project Assets",
    "library.summary.global_assets": "Global Assets",
    "library.summary.label": "Current library summary",
    "library.summary.watched_environments": "Watched environments shown",
    "library.workspace.label": "Project-first Asset workspace",
    ...ENGLISH_DESKTOP_LIBRARY_SOURCE_MESSAGES,
    ...ENGLISH_DESKTOP_PROJECT_LIFECYCLE_MESSAGES,
    "common.back": "Back",
    "onboarding.discovery.continue_without_import": "Continue without importing",
    "onboarding.navigation.label": "Onboarding navigation",
    "onboarding.welcome.choose": "You choose the locations, tools, sources and Assets at every step.",
    "onboarding.welcome.copy":
        "OAAM can look for reusable instructions and settings in the locations you choose. Nothing is scanned until you start.",
    "onboarding.welcome.eyebrow": "Before scanning",
    "onboarding.welcome.inspect": "OAAM reads only the locations you explicitly select.",
    "onboarding.welcome.later": "Set up later",
    "onboarding.welcome.no_write": "Scanning and importing do not modify files used by your AI coding tools.",
    "onboarding.welcome.start": "Start guided setup",
    "onboarding.welcome.title": "Choose when OAAM inspects your computer",
    "state_resilience.backup.copy":
        "Create one complete immutable recovery archive. Backups never include other backup archives or files used by your AI coding tools.",
    "state_resilience.backup.create": "Create verified backup",
    "state_resilience.backup.create_failed": "The backup was not created.",
    "state_resilience.backup.create_interrupted": "The backup operation was interrupted.",
    "state_resilience.backup.created": "The verified backup was created.",
    "state_resilience.backup.inspect": "Review backup",
    "state_resilience.backup.inspect_failed": "The backup could not be reviewed.",
    "state_resilience.backup.inspect_interrupted": "Backup review was interrupted.",
    "state_resilience.backup.output": "Created at {path}",
    "state_resilience.backup.review_ready": "Review the exact source size and destination before creating the archive.",
    "state_resilience.backup.review_title": "Backup review",
    "state_resilience.backup.title": "Back up OAAM state",
    "state_resilience.copy":
        "Back up and restore your OAAM library, managed-location records, recovery files, and interface settings.",
    "state_resilience.destination.choose": "Choose another folder…",
    "state_resilience.destination.choose_button": "Use this backup folder",
    "state_resilience.destination.choose_failed": "The backup folder could not be selected.",
    "state_resilience.destination.choose_title": "Choose a backup folder",
    "state_resilience.destination.custom": "Selected custom folder",
    "state_resilience.destination.default": "OAAM default backup folder",
    "state_resilience.destination.label": "Destination",
    "state_resilience.destination.remembered": "Last successful custom folder: {path}",
    "state_resilience.destination.remembered_unavailable":
        "The remembered folder is unavailable. Choose another folder or use the OAAM default.",
    "state_resilience.destination.use_remembered": "Use last custom folder",
    "state_resilience.encryption.compatible": "Compatible password (weak ZipCrypto)",
    "state_resilience.encryption.compatible_warning":
        "Compatibility mode is weak. Use it only when another computer must open the ZIP without OAAM.",
    "state_resilience.encryption.label": "Archive encryption",
    "state_resilience.encryption.none": "No password",
    "state_resilience.encryption.none_warning":
        "This ordinary ZIP can contain private agent assets. Anyone with the file can read it.",
    "state_resilience.encryption.short.compatible_password": "compatible password",
    "state_resilience.encryption.short.none": "no password",
    "state_resilience.encryption.short.strong_password": "AES-256 password",
    "state_resilience.encryption.strong": "Strong password (AES-256)",
    "state_resilience.file.action_failed": "The file-manager action failed.",
    "state_resilience.file.confirm_trash": "Move this backup to Trash",
    "state_resilience.file.copied": "The backup path was copied.",
    "state_resilience.file.copy": "Copy path",
    "state_resilience.file.copy_failed": "The backup path could not be copied.",
    "state_resilience.file.reveal": "Show in folder",
    "state_resilience.file.reveal_failed": "The file manager could not reveal this backup. You can copy its path instead.",
    "state_resilience.file.revealed": "The backup was shown in the file manager.",
    "state_resilience.file.trash": "Remove…",
    "state_resilience.file.trash_failed":
        "OAAM could not confirm the final Trash state. Refresh the inventory; no permanent-delete fallback was used.",
    "state_resilience.file.trashed": "The backup was moved to Trash.",
    "state_resilience.inventory.empty": "No registered backup exists yet.",
    "state_resilience.inventory.summary": "{count} registered backups · {bytes} currently available",
    "state_resilience.inventory.title": "Backup inventory",
    "state_resilience.load_attention": "Backup information loaded with details that may need attention.",
    "state_resilience.load_failed": "Backup and restore state could not be loaded.",
    "state_resilience.observation.available": "Available",
    "state_resilience.observation.missing": "Missing",
    "state_resilience.observation.replaced": "Replaced",
    "state_resilience.password.confirm": "Confirm password",
    "state_resilience.password.label": "Password",
    "state_resilience.password_invalid": "Enter the same non-empty password twice.",
    "state_resilience.policy.ask": "Ask every time",
    "state_resilience.policy.back_up_first": "Back up first",
    "state_resilience.policy.continue": "Continue without the backup prompt",
    "state_resilience.policy.copy":
        "Choose the backup prompt shown before changing Project management or permanently removing Assets.",
    "state_resilience.policy.future_scope":
        "This preference never skips the destructive action's own exact review. Current Deployment overwrite and repair retain their existing review.",
    "state_resilience.policy.label": "Pre-destructive backup prompt",
    "state_resilience.policy.latest": "Latest available backup: {time} · {path}",
    "state_resilience.policy.no_backup": "No available backup is registered.",
    "state_resilience.policy.save": "Save prompt preference",
    "state_resilience.policy.save_failed": "The prompt preference was not saved. Refresh before retrying.",
    "state_resilience.policy.saved": "The backup prompt preference was saved.",
    "state_resilience.policy.title": "Before destructive lifecycle actions",
    "state_resilience.progress": "{stage}: {completed}/{total}",
    "state_resilience.refresh": "Refresh",
    "state_resilience.restore.activate": "Restore this complete backup",
    "state_resilience.restore.activate_failed": "The backup was not activated. Select and inspect it again before restoring.",
    "state_resilience.restore.activate_interrupted":
        "The restore connection ended before a confirmed result. Reopen OAAM and inspect recovery state.",
    "state_resilience.restore.activated": "The backup was activated. OAAM is reopening with the restored data.",
    "state_resilience.restore.choose": "Choose another ZIP…",
    "state_resilience.restore.choose_button": "Review this backup",
    "state_resilience.restore.choose_failed": "The backup archive could not be selected.",
    "state_resilience.restore.choose_title": "Choose an OAAM backup ZIP",
    "state_resilience.restore.confirm":
        "I reviewed this complete backup and understand that current OAAM state will be displaced and preserved.",
    "state_resilience.restore.copy":
        "Restore one complete verified backup. Selective table, Asset, or Deployment restoration is not supported.",
    "state_resilience.restore.inspect": "Inspect backup",
    "state_resilience.restore.inspect_failed": "The selected archive is not a valid complete OAAM backup.",
    "state_resilience.restore.inspect_interrupted": "Backup inspection was interrupted.",
    "state_resilience.restore.no_displaced": "No prior OAAM state existed",
    "state_resilience.restore.no_source": "Choose a registered backup or another OAAM backup ZIP.",
    "state_resilience.restore.password": "Archive password, if required",
    "state_resilience.restore.restarting": "Restored. Previous state: {path}. OAAM is restarting.",
    "state_resilience.restore.review_ready": "The complete backup is valid. Review its contents before activation.",
    "state_resilience.restore.review_title": "Restore review",
    "state_resilience.restore.title": "Restore OAAM state",
    "state_resilience.restore.use": "Restore…",
    "state_resilience.restore.warning":
        "Restore replaces the complete OAAM state unit. Current state is preserved in a displaced recovery directory.",
    "state_resilience.review.available": "Available capacity",
    "state_resilience.review.created": "Created",
    "state_resilience.review.desktop_preferences": "Desktop preferences",
    "state_resilience.review.destination": "Destination",
    "state_resilience.review.destination_existing": "Existing folder: {path}",
    "state_resilience.review.destination_planned": "Folder will be created: {path}",
    "state_resilience.review.files": "Files",
    "state_resilience.review.included": "Included",
    "state_resilience.review.logical_size": "Logical size",
    "state_resilience.review.not_included": "Not included",
    "state_resilience.stage.activation": "Activating",
    "state_resilience.stage.commit": "Committing",
    "state_resilience.stage.encryption": "Encrypting",
    "state_resilience.stage.inspection": "Inspecting",
    "state_resilience.stage.inventory": "Inventory",
    "state_resilience.stage.packing": "Packing",
    "state_resilience.stage.quiescence": "Stopping active work",
    "state_resilience.stage.restart_required": "Restart required",
    "state_resilience.stage.verification": "Verifying",
    "state_resilience.title": "Data safety",
    "state_resilience.recovery.eyebrow": "Recovery required",
    "state_resilience.recovery.title": "Restore OAAM state",
    "state_resilience.recovery.reason.missing_database":
        "The established OAAM profile no longer has its State database. Ordinary operations remain blocked.",
    "state_resilience.recovery.reason.corrupt_database":
        "The OAAM State database is corrupt or unreadable. Ordinary operations remain blocked.",
    "state_resilience.recovery.reason.incompatible_database":
        "The OAAM State database is not compatible with this build. Ordinary operations remain blocked.",
    "state_resilience.recovery.reason.restore_reconciliation":
        "An interrupted State restore must be reconciled before ordinary operations can resume.",
    "state_resilience.recovery_only":
        "In recovery mode, OAAM can only inspect and restore a complete backup you select. Your ordinary OAAM data remains untouched until you approve restoration.",
    "state_resilience.unavailable": "Backup and restore are unavailable in the current OAAM session.",
    "settings.close": "Close settings",
    "settings.back_to_app": "Back to app",
    "settings.eyebrow": "Application settings",
    "settings.general.copy": "These preferences change only how the Desktop app looks and behaves.",
    "settings.general.title": "General",
    "settings.project_management.copy": "Restore a stopped Project here when you want OAAM to manage it again.",
    "settings.project_management.empty": "There are no stopped Projects.",
    "settings.project_management.title": "Project management",
    ...ENGLISH_DESKTOP_DIAGNOSTICS_MESSAGES,
    ...ENGLISH_DESKTOP_MAINTENANCE_MESSAGES,
    ...ENGLISH_DESKTOP_PRESENTATION_MESSAGES,
    ...ENGLISH_DESKTOP_SEARCH_MESSAGES,
    "settings.open": "Settings",
    "settings.privacy.copy": "OAAM looks only in locations you approve.",
    "settings.privacy.no_session":
        "OAAM does not collect chat content, credentials, extensions, or temporary conversation data as Assets.",
    "settings.privacy.no_write": "Scanning and importing never change files used by your AI coding tools.",
    "settings.privacy.read": "OAAM reads only locations you select or ask it to keep checking.",
    "settings.privacy.title": "Privacy and data access",
    "settings.runtime.copy":
        "Manage the default scope and saved locations used by scans started from Settings. To import Assets, start a separate import.",
    "settings.runtime.guided_setup": "Start an import",
    "settings.runtime.title": "Locations and AI coding tools",
    "tray.host.failed": "OAAM: Unavailable",
    "tray.host.ready": "OAAM: Running",
    "tray.host.recovering": "OAAM: Recovering",
    "tray.host.starting": "OAAM: Starting",
    "tray.quit": "Quit OAAM",
    "tray.show": "Show OAAM",
    "tray.tooltip": "Open Agent Asset Manager",
    "settings.title": "Settings",
    "settings.search": "Search settings",
    "settings.search_no_results": "No settings match this search.",
    "window.about.detail": "Version {version}. OAAM keeps agent assets portable under your explicit control.",
    "window.about.title": "About OAAM",
    "window.action.failed": "The window command could not be completed.",
    "window.chrome.title": "Open Agent Asset Manager",
    "window.menu.edit": "Edit",
    "window.menu.edit.copy": "Copy",
    "window.menu.edit.cut": "Cut",
    "window.menu.edit.delete": "Delete",
    "window.menu.edit.paste": "Paste",
    "window.menu.edit.redo": "Redo",
    "window.menu.edit.select_all": "Select All",
    "window.menu.edit.settings": "Settings…",
    "window.menu.edit.undo": "Undo",
    "window.menu.file": "File",
    "window.menu.file.add_project": "Add Project…",
    "window.menu.file.exit": "Exit",
    "window.menu.file.hide_to_tray": "Hide to Tray",
    "window.menu.help": "Help",
    "window.menu.help.about": "About OAAM",
    "window.menu.view": "View",
    "window.menu.view.back": "Back",
    "window.menu.view.forward": "Forward",
    "window.menu.view.full_screen": "Toggle Full Screen",
    "window.menu.view.inspector": "Toggle Inspector",
    "window.menu.view.sidebar": "Toggle Sidebar",
    "window.menu.view.zoom_in": "Zoom In",
    "window.menu.view.zoom_out": "Zoom Out",
    "window.menu.view.zoom_reset": "Actual Size",
    "window.navigation.back": "Back",
    "window.navigation.forward": "Forward",
    "window.inspector.toggle": "Toggle Asset inspector",
    "window.sidebar.toggle": "Toggle sidebar",
} as const;

export type DesktopMessageId = keyof typeof ENGLISH_DESKTOP_MESSAGES;
