import {
    DESKTOP_DEPLOYMENT_CONFIRMATION_MESSAGE_IDS,
    ENGLISH_DESKTOP_DEPLOYMENT_CONFIRMATION_MESSAGES,
    GERMAN_DESKTOP_DEPLOYMENT_CONFIRMATION_MESSAGES,
    JAPANESE_DESKTOP_DEPLOYMENT_CONFIRMATION_MESSAGES,
    SIMPLIFIED_CHINESE_DESKTOP_DEPLOYMENT_CONFIRMATION_MESSAGES,
} from "./catalog-deployment-confirmation-language";
import {
    DESKTOP_DEPLOYMENT_OUTCOME_MESSAGE_IDS,
    ENGLISH_DESKTOP_DEPLOYMENT_OUTCOME_MESSAGES,
    GERMAN_DESKTOP_DEPLOYMENT_OUTCOME_MESSAGES,
    JAPANESE_DESKTOP_DEPLOYMENT_OUTCOME_MESSAGES,
    SIMPLIFIED_CHINESE_DESKTOP_DEPLOYMENT_OUTCOME_MESSAGES,
} from "./catalog-deployment-outcome-language";

export const DESKTOP_DEPLOYMENT_PRODUCT_LANGUAGE_MESSAGE_IDS = [
    ...DESKTOP_DEPLOYMENT_CONFIRMATION_MESSAGE_IDS,
    "catalog.asset_usage.failed",
    "catalog.asset_usage.interrupted",
    "catalog.authorization.allow_current_project",
    "catalog.authorization.allowed",
    "catalog.authorization.create_failed",
    "catalog.authorization.check_failed",
    "catalog.authorization.required",
    "catalog.authorization.target_changed",
    "catalog.authorization.target_check_required",
    "catalog.compatibility.newer_build",
    "catalog.product.asset.revision",
    "catalog.product.asset.summary",
    "catalog.product.action.check_files",
    "catalog.product.apply.waiting",
    "catalog.product.analysis.failed",
    "catalog.product.inspection.attribution.conflict",
    "catalog.product.inspection.attribution.unique",
    "catalog.product.inspection.attribution.whole_file",
    "catalog.product.inspection.binary",
    "catalog.product.inspection.change.added",
    "catalog.product.inspection.change.content",
    "catalog.product.inspection.change.deleted",
    "catalog.product.inspection.change.executable",
    "catalog.product.inspection.change.metadata",
    "catalog.product.inspection.file",
    "catalog.product.inspection.text",
    "catalog.product.inspection.text_truncated",
    "catalog.product.runtime_version",
    "catalog.product.review.preview_required",
    "catalog.product.review.passive_preview",
    "catalog.product.review.waiting",
    "catalog.product.target_option",
    "catalog.product.technical.attribution_state",
    "catalog.product.technical.change_fingerprint",
    "catalog.product.technical.deployment_id",
    "catalog.product.technical.environment",
    "catalog.product.technical.inspection_token",
    "catalog.product.technical.operation_id",
    "catalog.product.technical.progress_stage",
    "catalog.product.technical.reason",
    "catalog.product.technical.runtime_ids",
    "catalog.product.technical.selector",
    "catalog.product.technical.target",
    "catalog.ui.create.asset_step_eyebrow",
    "catalog.ui.create.selected_asset_version",
    "catalog.ui.asset.imported_from",
    "catalog.ui.asset.source_details",
    "catalog.ui.asset.source_files",
    "catalog.ui.asset.source_locations",
    "catalog.ui.asset.view_source",
    "catalog.ui.create.asset_unavailable",
    "catalog.ui.create.asset_unavailable_copy",
    "catalog.ui.create.no_target.available_global",
    "catalog.ui.create.no_target.available_project",
    "catalog.ui.create.no_target.copy_global",
    "catalog.ui.create.no_target.copy_project",
    "catalog.ui.create.no_target.no_result",
    "catalog.ui.create.no_target.title",
    "catalog.ui.create.review_copy",
    "catalog.ui.create.review_eyebrow",
    "catalog.ui.create.review_title",
    "catalog.ui.create.applied_title",
    "catalog.ui.action.apply_to_tool",
    "catalog.ui.target.choose_installation",
    "catalog.ui.target.enable_selected",
    "catalog.ui.target.enablement_persists",
    "catalog.ui.target.installation_picker_button",
    "catalog.ui.target.installation_picker_failed",
    "catalog.ui.target.installation_picker_title",
    "catalog.ui.target.open_project",
    "catalog.ui.target.path",
    "catalog.ui.target.picker_failed",
    "catalog.ui.target.project_load_failed",
    "catalog.ui.target.project_loading",
    "catalog.ui.target.project_unavailable",
    "catalog.ui.target.progress",
    "catalog.ui.target.copy_global",
    "catalog.ui.target.partial",
    "catalog.ui.target.notes_copy",
    "catalog.ui.inspection.actions_title",
    "catalog.ui.inspection.details_title",
    "catalog.ui.inspection.repair_copy",
    "catalog.ui.inspection.reverse_copy",
    "catalog.ui.render.outputs_copy",
    "catalog.ui.render.outputs_title",
    "catalog.ui.usage.checked_path",
    "catalog.ui.usage.copy",
    "catalog.ui.usage.detail.analysis_failed",
    "catalog.ui.usage.detail.already_usable",
    "catalog.ui.usage.detail.applied",
    "catalog.ui.usage.detail.checking",
    "catalog.ui.usage.detail.current_observation_failed",
    "catalog.ui.usage.detail.configured",
    "catalog.ui.usage.detail.direct",
    "catalog.ui.usage.detail.direct_absent",
    "catalog.ui.usage.detail.direct_different",
    "catalog.ui.usage.detail.interrupted",
    "catalog.ui.usage.detail.managed_absent",
    "catalog.ui.usage.detail.managed_different",
    "catalog.ui.usage.detail.managed_unknown",
    "catalog.ui.usage.detail.not_installed",
    "catalog.ui.usage.detail.permission_denied",
    "catalog.ui.usage.detail.substitute_absent",
    "catalog.ui.usage.detail.substitute_different",
    "catalog.ui.usage.detail.tool_changed",
    "catalog.ui.usage.detail.transformed",
    "catalog.ui.usage.detail.transformed_absent",
    "catalog.ui.usage.detail.transformed_different",
    "catalog.ui.usage.detail.unavailable",
    "catalog.ui.usage.detail.unsupported",
    "catalog.ui.usage.detail.unknown",
    "catalog.ui.usage.detail.verification_failed",
    "catalog.ui.usage.detail.workflow_to_skill",
    "catalog.ui.usage.empty",
    "catalog.ui.usage.eyebrow",
    "catalog.ui.usage.failure_stage",
    "catalog.ui.usage.loading",
    "catalog.ui.usage.loading_progress",
    "catalog.ui.usage.group_available",
    "catalog.ui.usage.group_checking",
    "catalog.ui.usage.other_checks",
    "catalog.ui.usage.ready_checks",
    "catalog.ui.usage.review_saved_version",
    "catalog.ui.usage.open",
    "catalog.ui.usage.prepare",
    "catalog.ui.usage.preview_write",
    "catalog.ui.usage.review_conversion",
    "catalog.ui.usage.review_difference",
    "catalog.ui.usage.review_note",
    "catalog.ui.usage.status.absent",
    "catalog.ui.usage.status.already_usable",
    "catalog.ui.usage.status.applied",
    "catalog.ui.usage.status.analysis_failed",
    "catalog.ui.usage.status.checking",
    "catalog.ui.usage.status.current_observation_failed",
    "catalog.ui.usage.status.configured",
    "catalog.ui.usage.status.different",
    "catalog.ui.usage.status.direct",
    "catalog.ui.usage.status.managed_absent",
    "catalog.ui.usage.status.managed_different",
    "catalog.ui.usage.status.managed_unknown",
    "catalog.ui.usage.status.not_installed",
    "catalog.ui.usage.status.transformed",
    "catalog.ui.usage.status.unavailable",
    "catalog.ui.usage.status.unsupported",
    "catalog.ui.usage.status.unknown",
    "catalog.ui.usage.title",
    "catalog.ui.usage.view_adapter",
    "catalog.ui.usage.view_label",
    "catalog.ui.usage.view_project",
    ...DESKTOP_DEPLOYMENT_OUTCOME_MESSAGE_IDS,
    "catalog.ui.workspace.create",
    "catalog.ui.workspace.create_asset",
    "catalog.ui.workspace.applied_asset",
    "catalog.ui.workspace.manage",
    "catalog.ui.workspace.review_asset",
    "catalog.ui.workspace.reverse_asset",
    "catalog.ui.render.claude.blocked.skill",
    "catalog.ui.render.claude.blocked.subagent",
    "catalog.ui.render.claude.blocked.workflow",
    "catalog.ui.render.claude.no_silent_degradation",
    "catalog.ui.render.claude.preserved.skill",
    "catalog.ui.render.claude.preserved.subagent",
    "catalog.ui.render.claude.preserved.workflow",
    "catalog.ui.render.claude.title.blocked",
    "catalog.ui.render.claude.title.preserved",
] as const;

export type DesktopDeploymentProductLanguageMessageId = (typeof DESKTOP_DEPLOYMENT_PRODUCT_LANGUAGE_MESSAGE_IDS)[number];
type DesktopDeploymentProductLanguageMessages = Readonly<Record<DesktopDeploymentProductLanguageMessageId, string>>;

export const ENGLISH_DESKTOP_DEPLOYMENT_PRODUCT_LANGUAGE_MESSAGES = {
    ...ENGLISH_DESKTOP_DEPLOYMENT_CONFIRMATION_MESSAGES,
    "catalog.ui.target.notes_copy": "Notes apply to the listed tools and environments. Confirmed results remain available.",
    "catalog.asset_usage.failed": "OAAM could not determine how the currently found tools can use this Asset.",
    "catalog.asset_usage.interrupted": "The tool-compatibility check was interrupted. Find available tools again.",
    "catalog.authorization.allow_current_project": "Allow this Version for the current Project",
    "catalog.authorization.allowed": "This Version is allowed for the current Project.",
    "catalog.authorization.create_failed": "OAAM could not save this permission. Review the current Project and try again.",
    "catalog.authorization.check_failed": "OAAM could not check whether this Version is allowed. Try again before continuing.",
    "catalog.authorization.required": "Allow this Version for the current Project before previewing the files.",
    "catalog.authorization.target_changed": "The selected tool location changed. Find available tools again before continuing.",
    "catalog.authorization.target_check_required":
        "This saved tool setup is available. Check the current tool location before changing or writing files.",
    "catalog.compatibility.newer_build":
        "{runtime} is newer than the build OAAM directly verified. OAAM checked it using the nearest compatible version rules.",
    "catalog.product.action.check_files": "Check file choices",
    "catalog.product.apply.waiting": "Applying the selected files…",
    "catalog.product.analysis.failed": "OAAM could not prepare the file choices.",
    "catalog.product.asset.revision": "Version {revision}",
    "catalog.product.asset.summary": "{kind} · {scope}",
    "catalog.product.inspection.attribution.conflict": "This file cannot be attributed safely",
    "catalog.product.inspection.attribution.unique": "This change belongs to this saved tool setup",
    "catalog.product.inspection.attribution.whole_file": "The whole file must be reviewed before importing it",
    "catalog.product.inspection.binary": "Binary content · {bytes} bytes",
    "catalog.product.inspection.change.added": "File added",
    "catalog.product.inspection.change.content": "File content changed",
    "catalog.product.inspection.change.deleted": "File deleted",
    "catalog.product.inspection.change.executable": "Executable setting changed",
    "catalog.product.inspection.change.metadata": "Asset metadata changed",
    "catalog.product.inspection.file": "File: {path}",
    "catalog.product.inspection.text": "Reviewed text",
    "catalog.product.inspection.text_truncated": "Only the bounded beginning of this text is shown.",
    "catalog.product.runtime_version": "{runtime} {version}",
    "catalog.product.review.preview_required":
        "Choose how each item should be added. OAAM will show the latest target files before writing anything.",
    "catalog.product.review.waiting": "Checking the available file choices…",
    "catalog.product.target_option": "{target} · {tool} · {environment}",
    "catalog.product.technical.attribution_state": "Internal attribution state: {state}",
    "catalog.product.technical.change_fingerprint": "Change fingerprint: {fingerprint}",
    "catalog.product.technical.deployment_id": "Tool setup ID: {id}",
    "catalog.product.technical.environment": "Internal environment: {identity}",
    "catalog.product.technical.inspection_token": "Inspection token: {token}",
    "catalog.product.technical.operation_id": "Operation ID: {id}",
    "catalog.product.technical.progress_stage": "Internal progress stage: {stage}",
    "catalog.product.technical.reason": "Internal reason: {reason}",
    "catalog.product.technical.runtime_ids": "Internal tool entries: {ids}",
    "catalog.product.technical.selector": "Inspection selector: {selector}",
    "catalog.product.technical.target": "Internal target owner: {id}",
    "catalog.ui.create.asset_step_eyebrow": "Selected Asset",
    "catalog.ui.create.selected_asset_version": "{asset} · selected Version",
    "catalog.ui.asset.imported_from": "Imported from {tool}",
    "catalog.ui.asset.source_details": "Asset source",
    "catalog.ui.asset.source_files": "Imported files",
    "catalog.ui.asset.source_locations": "Source locations",
    "catalog.ui.asset.view_source": "View source",
    "catalog.ui.create.asset_unavailable": "This Asset is no longer available",
    "catalog.ui.create.asset_unavailable_copy": "Return to the library and choose a current Asset before adding it to a tool.",
    "catalog.ui.create.no_target.available_global":
        "The tool was found, but it has no compatible Global location for this Asset.",
    "catalog.ui.create.no_target.available_project":
        "The tool was found, but it has no compatible location in this Project for this Asset.",
    "catalog.ui.create.no_target.copy_global":
        "The check finished, but none of the selected tools provided a Global location that can use this Asset.",
    "catalog.ui.create.no_target.copy_project":
        "The check finished, but none of the selected tools provided a compatible location in this Project.",
    "catalog.ui.create.no_target.no_result": "No tool returned an installation or location result for this environment.",
    "catalog.ui.create.no_target.title": "No usable tool location was found",
    "catalog.ui.target.choose_installation": "Choose installation folder",
    "catalog.ui.target.enable_selected": "Enable selected tools",
    "catalog.ui.target.enablement_persists": "Enabled tools stay enabled in OAAM. You can change this in Settings.",
    "catalog.ui.target.installation_picker_button": "Use this installation folder",
    "catalog.ui.target.installation_picker_failed":
        "OAAM could not verify this folder as the selected tool's installation. Choose the folder that directly contains the tool.",
    "catalog.ui.target.installation_picker_title": "Choose the tool's installation folder",
    "catalog.ui.target.open_project": "Open Project folder",
    "catalog.ui.target.path": "Current Project: {name} · {path}",
    "catalog.ui.target.picker_failed":
        "OAAM could not use this Project's registered folder. Return to Project settings to check the location.",
    "catalog.ui.target.project_load_failed": "OAAM could not load this Project. Try again before checking tool locations.",
    "catalog.ui.target.project_loading": "Loading this Project's registered folder…",
    "catalog.ui.target.project_unavailable": "This Project no longer exists or is no longer managed, so it cannot be checked.",
    "catalog.ui.target.progress": "Checked {completed} of {total} tool/environment combinations",
    "catalog.product.review.passive_preview": "The file plan is ready. Review the current and proposed files before applying it.",
    "catalog.ui.create.applied_title": "Application result",
    "catalog.ui.target.copy_global":
        "Choose tools and environments to check for this Global asset. Its source tool does not restrict where it can be used. This check does not change files.",
    "catalog.ui.target.partial":
        "This check is incomplete, but no specific cause was returned. Confirmed results remain available; run the check again if a result is missing.",
    "catalog.ui.inspection.actions_title": "Choose the next step",
    "catalog.ui.inspection.details_title": "Changes to review",
    "catalog.ui.inspection.repair_copy": "Restore OAAM-managed files from this exact inspection.",
    "catalog.ui.inspection.reverse_copy": "Review attributable tool changes before deciding whether to save a new Asset Version.",
    "catalog.ui.render.outputs_copy":
        "Each physical output is listed once. The roles below explain how the same files are used and how future edits are handled.",
    "catalog.ui.render.outputs_title": "Planned files",
    "catalog.ui.create.review_copy":
        "Check the exact conversion and files for this one location. Nothing is written until you approve the preview.",
    "catalog.ui.create.review_eyebrow": "Selected tool location",
    "catalog.ui.create.review_title": "Review file changes",
    "catalog.ui.action.apply_to_tool": "Apply to {tool}",
    "catalog.ui.usage.copy":
        "OAAM compares this exact Asset Version with each tool found in the selected environment. This check does not write files.",
    "catalog.ui.usage.checked_path": "Checked location: {path}",
    "catalog.ui.usage.detail.analysis_failed": "OAAM could not verify this exact tool location.",
    "catalog.ui.usage.detail.already_usable":
        "The files needed for the current Version are already in place. No change is needed.",
    "catalog.ui.usage.detail.applied": "Matches the current Version. OAAM manages the files here.",
    "catalog.ui.usage.detail.checking": "OAAM is checking this exact tool location.",
    "catalog.ui.usage.detail.current_observation_failed":
        "This check could not confirm the tool's current state. Check the tools again to refresh this result.",
    "catalog.ui.usage.detail.configured": "A file-change review is already prepared here, but nothing has been written yet.",
    "catalog.ui.usage.detail.direct": "This tool can use the Asset without changing its Asset type.",
    "catalog.ui.usage.detail.direct_absent":
        "The files for the current Version are not here yet. Preview the files OAAM would add.",
    "catalog.ui.usage.detail.direct_different":
        "This location already contains different content. Review the existing content and the differences first.",
    "catalog.ui.usage.detail.interrupted": "The check was interrupted. Try checking the available tools again.",
    "catalog.ui.usage.detail.managed_absent":
        "Files previously managed by OAAM are now missing. Open the existing usage to review recovery options.",
    "catalog.ui.usage.detail.managed_different":
        "Files managed by OAAM have changed outside OAAM. Open the existing usage before deciding whether to repair, accept, or restore them.",
    "catalog.ui.usage.detail.managed_unknown":
        "OAAM still has a management record here, but cannot confirm the current files. Open the existing usage to inspect it.",
    "catalog.ui.usage.detail.not_installed": "This tool is not installed in the selected system environment.",
    "catalog.ui.usage.detail.permission_denied":
        "OAAM cannot read this tool location. Check its access permissions, then try again.",
    "catalog.ui.usage.detail.tool_changed": "This tool moved or changed after it was found. Check the available tools again.",
    "catalog.ui.usage.detail.substitute_absent":
        "This tool has no native support for this Asset type, but it can use it as {kind}. Review the conversion first.",
    "catalog.ui.usage.detail.substitute_different":
        "This tool can use it as {kind}, but the target already contains different content. Review the conversion and differences first.",
    "catalog.ui.usage.detail.transformed": "This tool can use the content after a reviewed format conversion.",
    "catalog.ui.usage.detail.transformed_absent":
        "This tool needs a format conversion. Review the converted result and the files OAAM would add.",
    "catalog.ui.usage.detail.transformed_different":
        "This tool needs a format conversion, and the target already contains different content. Review the result and differences first.",
    "catalog.ui.usage.detail.unavailable": "This tool location cannot use the Asset in its current form.",
    "catalog.ui.usage.detail.unsupported": "This tool does not support this Asset at the selected location.",
    "catalog.ui.usage.detail.unknown":
        "OAAM cannot confirm whether this tool is already using the current Version. No write review was created from this result.",
    "catalog.ui.usage.detail.verification_failed":
        "OAAM could not verify how this Asset can be used here. Review the check details before retrying or choosing another location.",
    "catalog.ui.usage.detail.workflow_to_skill":
        "Codex can use this Workflow as a Skill. OAAM will show the conversion and any lost behavior before writing.",
    "catalog.ui.usage.empty": "Find available tools to see where this Asset can be used.",
    "catalog.ui.usage.eyebrow": "Asset relationships",
    "catalog.ui.usage.failure_stage": "Failure stage: {stage}",
    "catalog.ui.usage.loading": "Checking how each found tool can use this Asset…",
    "catalog.ui.usage.loading_progress": "Checking found tools ({completed}/{total})…",
    "catalog.ui.usage.group_available": "{total} tool entries checked · {available} available",
    "catalog.ui.usage.group_checking": "{checking}/{total} checking",
    "catalog.ui.usage.other_checks": "Unavailable or unconfirmed entries ({count})",
    "catalog.ui.usage.ready_checks": "Already usable ({count})",
    "catalog.ui.usage.review_saved_version": "Review saved Version",
    "catalog.ui.usage.open": "View usage",
    "catalog.ui.usage.prepare": "Review file changes",
    "catalog.ui.usage.preview_write": "Preview files to add",
    "catalog.ui.usage.review_conversion": "Review converted result",
    "catalog.ui.usage.review_difference": "Review existing content and differences",
    "catalog.ui.usage.review_note": "You will review the exact conversion and file changes before anything is written.",
    "catalog.ui.usage.status.absent": "Not added yet",
    "catalog.ui.usage.status.already_usable": "Already available",
    "catalog.ui.usage.status.applied": "Applied",
    "catalog.ui.usage.status.analysis_failed": "Could not verify",
    "catalog.ui.usage.status.checking": "Checking",
    "catalog.ui.usage.status.current_observation_failed": "Current check unavailable",
    "catalog.ui.usage.status.configured": "Review prepared",
    "catalog.ui.usage.status.different": "Content differs",
    "catalog.ui.usage.status.direct": "Can use directly",
    "catalog.ui.usage.status.managed_absent": "Managed files missing",
    "catalog.ui.usage.status.managed_different": "Managed files changed",
    "catalog.ui.usage.status.managed_unknown": "Managed state unconfirmed",
    "catalog.ui.usage.status.not_installed": "Not installed",
    "catalog.ui.usage.status.transformed": "Can use after conversion",
    "catalog.ui.usage.status.unavailable": "Unavailable here",
    "catalog.ui.usage.status.unsupported": "Not supported here",
    "catalog.ui.usage.status.unknown": "Could not confirm",
    "catalog.ui.usage.title": "Where this Asset can be used",
    "catalog.ui.usage.view_adapter": "By tool",
    "catalog.ui.usage.view_label": "Group Asset usage relationships",
    "catalog.ui.usage.view_project": "By location",
    ...ENGLISH_DESKTOP_DEPLOYMENT_OUTCOME_MESSAGES,
    "catalog.ui.workspace.create": "Apply this Asset to a tool",
    "catalog.ui.workspace.create_asset": "Apply {asset} to a tool",
    "catalog.ui.workspace.applied_asset": "{asset} is applied",
    "catalog.ui.workspace.manage": "Manage Asset usage",
    "catalog.ui.workspace.review_asset": "Review changes for {asset}",
    "catalog.ui.workspace.reverse_asset": "Save tool changes to {asset}",
    "catalog.ui.render.claude.blocked.skill":
        "OAAM could not prove that this Skill still fits the retained Claude Code settings and one-file SKILL.md format, so no file will be written.",
    "catalog.ui.render.claude.blocked.subagent":
        "OAAM could not prove that this Subagent still fits the retained Claude Code settings and one-file agent format, so no file will be written.",
    "catalog.ui.render.claude.blocked.workflow":
        "OAAM could not prove that this Workflow still fits the retained Claude Code command settings and one-file command format, so no file will be written.",
    "catalog.ui.render.claude.no_silent_degradation":
        "Only portable instructions may be updated. If they no longer agree with the retained Claude Code settings, OAAM stops before the file preview instead of silently dropping behavior.",
    "catalog.ui.render.claude.preserved.skill":
        "OAAM keeps the existing Claude Code Skill settings, comments, key order, quoting, spacing, and SKILL.md location.",
    "catalog.ui.render.claude.preserved.subagent":
        "OAAM keeps the existing Claude Code Subagent settings, aliases, comments, key order, quoting, spacing, and agent-file location.",
    "catalog.ui.render.claude.preserved.workflow":
        "OAAM keeps the existing Claude Code command settings, comments, key order, quoting, spacing, and project file location.",
    "catalog.ui.render.claude.title.blocked": "Claude Code settings cannot be kept safely",
    "catalog.ui.render.claude.title.preserved": "Claude Code settings kept",
} as const satisfies DesktopDeploymentProductLanguageMessages;

export const GERMAN_DESKTOP_DEPLOYMENT_PRODUCT_LANGUAGE_MESSAGES = {
    ...GERMAN_DESKTOP_DEPLOYMENT_CONFIRMATION_MESSAGES,
    "catalog.ui.target.notes_copy":
        "Hinweise gelten für die aufgeführten Tools und Umgebungen. Bestätigte Ergebnisse bleiben verfügbar.",
    "catalog.asset_usage.failed": "OAAM konnte nicht bestimmen, wie die gefundenen Werkzeuge dieses Asset verwenden können.",
    "catalog.asset_usage.interrupted": "Die Kompatibilitätsprüfung wurde unterbrochen. Suchen Sie erneut nach Werkzeugen.",
    "catalog.authorization.allow_current_project": "Diese Version für das aktuelle Projekt erlauben",
    "catalog.authorization.allowed": "Diese Version ist für das aktuelle Projekt erlaubt.",
    "catalog.authorization.create_failed":
        "OAAM konnte diese Erlaubnis nicht speichern. Prüfen Sie das aktuelle Projekt und versuchen Sie es erneut.",
    "catalog.authorization.check_failed": "OAAM konnte die Erlaubnis dieser Version nicht prüfen. Versuchen Sie es erneut.",
    "catalog.authorization.required": "Erlauben Sie diese Version für das aktuelle Projekt, bevor Sie die Dateien ansehen.",
    "catalog.authorization.target_changed": "Der ausgewählte Werkzeugort hat sich geändert. Suchen Sie erneut nach Werkzeugen.",
    "catalog.authorization.target_check_required":
        "Diese gespeicherte Werkzeugeinrichtung ist verfügbar. Prüfen Sie den aktuellen Werkzeugort, bevor Sie Dateien ändern oder schreiben.",
    "catalog.compatibility.newer_build":
        "{runtime} ist neuer als die direkt geprüfte Version. OAAM hat sie mit den Regeln der nächstgelegenen kompatiblen Version geprüft.",
    "catalog.product.action.check_files": "Dateiformen prüfen",
    "catalog.product.apply.waiting": "Ausgewählte Dateien werden angewendet…",
    "catalog.product.analysis.failed": "OAAM konnte die Dateiauswahl nicht vorbereiten.",
    "catalog.product.asset.revision": "Version {revision}",
    "catalog.product.asset.summary": "{kind} · {scope}",
    "catalog.product.inspection.attribution.conflict": "Diese Datei kann nicht sicher zugeordnet werden",
    "catalog.product.inspection.attribution.unique": "Diese Änderung gehört zu dieser gespeicherten Werkzeugeinstellung",
    "catalog.product.inspection.attribution.whole_file": "Die gesamte Datei muss vor dem Import überprüft werden",
    "catalog.product.inspection.binary": "Binärinhalt · {bytes} Bytes",
    "catalog.product.inspection.change.added": "Datei hinzugefügt",
    "catalog.product.inspection.change.content": "Dateiinhalt geändert",
    "catalog.product.inspection.change.deleted": "Datei gelöscht",
    "catalog.product.inspection.change.executable": "Ausführbarkeit geändert",
    "catalog.product.inspection.change.metadata": "Asset-Metadaten geändert",
    "catalog.product.inspection.file": "Datei: {path}",
    "catalog.product.inspection.text": "Überprüfter Text",
    "catalog.product.inspection.text_truncated": "Nur der begrenzte Anfang dieses Textes wird angezeigt.",
    "catalog.product.runtime_version": "{runtime} {version}",
    "catalog.product.review.preview_required":
        "Wählen Sie, wie jedes Element hinzugefügt werden soll. OAAM zeigt vor dem Schreiben die aktuellen Zieldateien an.",
    "catalog.product.review.waiting": "Verfügbare Dateiformen werden geprüft…",
    "catalog.product.target_option": "{target} · {tool} · {environment}",
    "catalog.product.technical.attribution_state": "Interner Zuordnungsstatus: {state}",
    "catalog.product.technical.change_fingerprint": "Änderungs-Fingerabdruck: {fingerprint}",
    "catalog.product.technical.deployment_id": "Werkzeugeinstellungs-ID: {id}",
    "catalog.product.technical.environment": "Interne Umgebung: {identity}",
    "catalog.product.technical.inspection_token": "Prüftoken: {token}",
    "catalog.product.technical.operation_id": "Vorgangs-ID: {id}",
    "catalog.product.technical.progress_stage": "Interne Fortschrittsstufe: {stage}",
    "catalog.product.technical.reason": "Interner Grund: {reason}",
    "catalog.product.technical.runtime_ids": "Interne Tool-Einträge: {ids}",
    "catalog.product.technical.selector": "Prüfselektor: {selector}",
    "catalog.product.technical.target": "Interner Zieleigentümer: {id}",
    "catalog.ui.create.asset_step_eyebrow": "Ausgewähltes Asset",
    "catalog.ui.create.selected_asset_version": "{asset} · ausgewählte Version",
    "catalog.ui.asset.imported_from": "Importiert aus {tool}",
    "catalog.ui.asset.source_details": "Asset-Quelle",
    "catalog.ui.asset.source_files": "Importierte Dateien",
    "catalog.ui.asset.source_locations": "Quellorte",
    "catalog.ui.asset.view_source": "Quelle anzeigen",
    "catalog.ui.create.asset_unavailable": "Dieses Asset ist nicht mehr verfügbar",
    "catalog.ui.create.asset_unavailable_copy": "Kehren Sie zur Bibliothek zurück und wählen Sie ein aktuelles Asset aus.",
    "catalog.ui.create.no_target.available_global":
        "Das Werkzeug wurde gefunden, bietet aber keinen kompatiblen globalen Ort für dieses Asset.",
    "catalog.ui.create.no_target.available_project":
        "Das Werkzeug wurde gefunden, bietet aber keinen kompatiblen Ort in diesem Projekt für dieses Asset.",
    "catalog.ui.create.no_target.copy_global":
        "Die Prüfung ist abgeschlossen, aber keines der ausgewählten Werkzeuge bietet einen passenden globalen Ort.",
    "catalog.ui.create.no_target.copy_project":
        "Die Prüfung ist abgeschlossen, aber keines der ausgewählten Werkzeuge bietet einen passenden Ort in diesem Projekt.",
    "catalog.ui.create.no_target.no_result":
        "Kein Werkzeug hat für diese Umgebung ein Installations- oder Ortsergebnis geliefert.",
    "catalog.ui.create.no_target.title": "Kein verwendbarer Werkzeugort gefunden",
    "catalog.ui.target.choose_installation": "Installationsordner auswählen",
    "catalog.ui.target.enable_selected": "Ausgewählte Werkzeuge aktivieren",
    "catalog.ui.target.enablement_persists":
        "Die Werkzeuge bleiben in OAAM aktiviert. Sie können dies in den Einstellungen ändern.",
    "catalog.ui.target.installation_picker_button": "Diesen Installationsordner verwenden",
    "catalog.ui.target.installation_picker_failed":
        "OAAM konnte diesen Ordner nicht als Installation des ausgewählten Werkzeugs bestätigen. Wählen Sie den Ordner, der das Werkzeug direkt enthält.",
    "catalog.ui.target.installation_picker_title": "Installationsordner des Werkzeugs auswählen",
    "catalog.ui.target.open_project": "Projektordner öffnen",
    "catalog.ui.target.path": "Aktuelles Projekt: {name} · {path}",
    "catalog.ui.target.picker_failed":
        "OAAM konnte den registrierten Projektordner nicht verwenden. Prüfen Sie den Ort in den Projekteinstellungen.",
    "catalog.ui.target.project_load_failed":
        "OAAM konnte dieses Projekt nicht laden. Versuchen Sie es erneut, bevor Sie Werkzeugorte prüfen.",
    "catalog.ui.target.project_loading": "Der registrierte Projektordner wird geladen…",
    "catalog.ui.target.project_unavailable": "Dieses Projekt existiert nicht mehr oder wird nicht mehr verwaltet.",
    "catalog.ui.target.progress": "{completed} von {total} Werkzeug-Umgebungs-Kombinationen geprüft",
    "catalog.product.review.passive_preview":
        "Der Dateiplan ist bereit. Prüfen Sie die aktuellen und vorgesehenen Dateien vor dem Anwenden.",
    "catalog.ui.create.applied_title": "Ergebnis der Anwendung",
    "catalog.ui.target.copy_global":
        "Wählen Sie Werkzeuge und Umgebungen für dieses globale Asset. Das Quellwerkzeug schränkt die Verwendung nicht ein. Diese Prüfung ändert keine Dateien.",
    "catalog.ui.target.partial":
        "Diese Prüfung ist unvollständig; ein genauer Grund wurde nicht gemeldet. Bestätigte Ergebnisse bleiben verfügbar. Prüfen Sie erneut, falls ein Ergebnis fehlt.",
    "catalog.ui.inspection.actions_title": "Nächsten Schritt auswählen",
    "catalog.ui.inspection.details_title": "Zu prüfende Änderungen",
    "catalog.ui.inspection.repair_copy": "OAAM-verwaltete Dateien anhand genau dieser Inspektion wiederherstellen.",
    "catalog.ui.inspection.reverse_copy":
        "Zurechenbare Werkzeugänderungen prüfen, bevor sie als neue Asset-Version gespeichert werden.",
    "catalog.ui.render.outputs_copy":
        "Jede physische Ausgabe wird einmal aufgeführt. Die Rollen unten erklären ihre Verwendung und den Umgang mit künftigen Änderungen.",
    "catalog.ui.render.outputs_title": "Geplante Dateien",
    "catalog.ui.create.review_copy":
        "Prüfen Sie die genaue Umwandlung und die Dateien für diesen Ort. Erst nach Ihrer Freigabe wird geschrieben.",
    "catalog.ui.create.review_eyebrow": "Ausgewählter Werkzeugspeicherort",
    "catalog.ui.create.review_title": "Dateiänderungen prüfen",
    "catalog.ui.action.apply_to_tool": "Auf {tool} anwenden",
    "catalog.ui.usage.copy":
        "OAAM vergleicht diese genaue Asset-Version mit jedem gefundenen Werkzeug. Dabei werden keine Dateien geschrieben.",
    "catalog.ui.usage.checked_path": "Geprüfter Ort: {path}",
    "catalog.ui.usage.detail.analysis_failed": "OAAM konnte diesen genauen Werkzeugort nicht bestätigen.",
    "catalog.ui.usage.detail.already_usable":
        "Die Dateien für die aktuelle Version sind bereits vorhanden. Es ist keine Änderung nötig.",
    "catalog.ui.usage.detail.applied": "Entspricht der aktuellen Version. OAAM verwaltet die Dateien hier.",
    "catalog.ui.usage.detail.checking": "OAAM prüft diesen genauen Werkzeugort.",
    "catalog.ui.usage.detail.current_observation_failed":
        "Der aktuelle Zustand des Werkzeugs konnte nicht bestätigt werden. Prüfen Sie die Werkzeuge erneut, um das Ergebnis zu aktualisieren.",
    "catalog.ui.usage.detail.configured": "Eine Prüfung der Dateiänderungen ist vorbereitet, aber noch nichts wurde geschrieben.",
    "catalog.ui.usage.detail.direct": "Dieses Werkzeug kann das Asset ohne Änderung des Asset-Typs verwenden.",
    "catalog.ui.usage.detail.direct_absent":
        "Die Dateien der aktuellen Version fehlen hier noch. Zeigen Sie zuerst die Dateien an, die OAAM hinzufügen würde.",
    "catalog.ui.usage.detail.direct_different":
        "Dieser Ort enthält bereits andere Inhalte. Prüfen Sie zuerst den vorhandenen Inhalt und die Unterschiede.",
    "catalog.ui.usage.detail.interrupted": "Die Prüfung wurde unterbrochen. Prüfen Sie die verfügbaren Werkzeuge erneut.",
    "catalog.ui.usage.detail.managed_absent":
        "Zuvor von OAAM verwaltete Dateien fehlen jetzt. Öffnen Sie die bestehende Verwendung, um die Wiederherstellung zu prüfen.",
    "catalog.ui.usage.detail.managed_different":
        "Von OAAM verwaltete Dateien wurden außerhalb von OAAM geändert. Öffnen Sie die bestehende Verwendung, bevor Sie sie reparieren, übernehmen oder wiederherstellen.",
    "catalog.ui.usage.detail.managed_unknown":
        "OAAM hat hier weiterhin einen Verwaltungseintrag, kann die aktuellen Dateien aber nicht bestätigen. Öffnen Sie die bestehende Verwendung zur Prüfung.",
    "catalog.ui.usage.detail.not_installed": "Dieses Werkzeug ist in der ausgewählten Systemumgebung nicht installiert.",
    "catalog.ui.usage.detail.permission_denied":
        "OAAM kann diesen Werkzeugort nicht lesen. Prüfen Sie die Zugriffsrechte und versuchen Sie es erneut.",
    "catalog.ui.usage.detail.tool_changed":
        "Dieses Werkzeug wurde nach dem Auffinden verschoben oder geändert. Prüfen Sie die verfügbaren Werkzeuge erneut.",
    "catalog.ui.usage.detail.substitute_absent":
        "Dieses Werkzeug unterstützt diesen Asset-Typ nicht nativ, kann ihn aber als {kind} verwenden. Prüfen Sie zuerst die Umwandlung.",
    "catalog.ui.usage.detail.substitute_different":
        "Dieses Werkzeug kann ihn als {kind} verwenden, am Ziel sind aber bereits andere Inhalte vorhanden. Prüfen Sie zuerst Umwandlung und Unterschiede.",
    "catalog.ui.usage.detail.transformed": "Nach einer geprüften Formatumwandlung kann dieses Werkzeug den Inhalt verwenden.",
    "catalog.ui.usage.detail.transformed_absent":
        "Dieses Werkzeug benötigt eine Formatumwandlung. Prüfen Sie das Ergebnis und die Dateien, die OAAM hinzufügen würde.",
    "catalog.ui.usage.detail.transformed_different":
        "Dieses Werkzeug benötigt eine Formatumwandlung und das Ziel enthält bereits andere Inhalte. Prüfen Sie zuerst Ergebnis und Unterschiede.",
    "catalog.ui.usage.detail.unavailable": "Dieser Werkzeugort kann das Asset derzeit nicht verwenden.",
    "catalog.ui.usage.detail.unsupported": "Dieses Werkzeug unterstützt das Asset am ausgewählten Speicherort nicht.",
    "catalog.ui.usage.detail.unknown":
        "OAAM kann nicht bestätigen, ob dieses Werkzeug bereits die aktuelle Version verwendet. Aus diesem Ergebnis wurde keine Schreibprüfung erstellt.",
    "catalog.ui.usage.detail.verification_failed":
        "OAAM konnte nicht bestätigen, wie dieses Asset hier verwendet werden kann. Prüfen Sie die Details, bevor Sie es erneut versuchen oder einen anderen Speicherort wählen.",
    "catalog.ui.usage.detail.workflow_to_skill":
        "Codex kann diesen Workflow als Skill verwenden. OAAM zeigt Umwandlung und mögliche Verluste vor dem Schreiben.",
    "catalog.ui.usage.empty": "Suchen Sie nach verfügbaren Werkzeugen, um mögliche Verwendungen anzuzeigen.",
    "catalog.ui.usage.eyebrow": "Asset-Beziehungen",
    "catalog.ui.usage.failure_stage": "Fehlerphase: {stage}",
    "catalog.ui.usage.loading": "Verwendungsmöglichkeiten werden geprüft…",
    "catalog.ui.usage.loading_progress": "Gefundene Werkzeuge werden geprüft ({completed}/{total})…",
    "catalog.ui.usage.group_available": "{total} Werkzeugeinträge geprüft · {available} verfügbar",
    "catalog.ui.usage.group_checking": "{checking}/{total} werden geprüft",
    "catalog.ui.usage.other_checks": "Nicht verfügbare oder unbestätigte Einträge ({count})",
    "catalog.ui.usage.ready_checks": "Bereits nutzbar ({count})",
    "catalog.ui.usage.review_saved_version": "Gespeicherte Version prüfen",
    "catalog.ui.usage.open": "Verwendung anzeigen",
    "catalog.ui.usage.prepare": "Dateiänderungen prüfen",
    "catalog.ui.usage.preview_write": "Hinzuzufügende Dateien anzeigen",
    "catalog.ui.usage.review_conversion": "Umwandlungsergebnis prüfen",
    "catalog.ui.usage.review_difference": "Vorhandenen Inhalt und Unterschiede prüfen",
    "catalog.ui.usage.review_note": "Vor dem Schreiben prüfen Sie die genaue Umwandlung und die Dateiänderungen.",
    "catalog.ui.usage.status.absent": "Noch nicht hinzugefügt",
    "catalog.ui.usage.status.already_usable": "Bereits verfügbar",
    "catalog.ui.usage.status.applied": "Angewendet",
    "catalog.ui.usage.status.analysis_failed": "Nicht bestätigt",
    "catalog.ui.usage.status.checking": "Wird geprüft",
    "catalog.ui.usage.status.current_observation_failed": "Aktuelle Prüfung nicht möglich",
    "catalog.ui.usage.status.configured": "Prüfung vorbereitet",
    "catalog.ui.usage.status.different": "Inhalt ist anders",
    "catalog.ui.usage.status.direct": "Direkt verwendbar",
    "catalog.ui.usage.status.managed_absent": "Verwaltete Dateien fehlen",
    "catalog.ui.usage.status.managed_different": "Verwaltete Dateien geändert",
    "catalog.ui.usage.status.managed_unknown": "Verwaltungszustand unbestätigt",
    "catalog.ui.usage.status.not_installed": "Nicht installiert",
    "catalog.ui.usage.status.transformed": "Nach Umwandlung verwendbar",
    "catalog.ui.usage.status.unavailable": "Hier nicht verfügbar",
    "catalog.ui.usage.status.unsupported": "Hier nicht unterstützt",
    "catalog.ui.usage.status.unknown": "Nicht bestätigt",
    "catalog.ui.usage.title": "Wo dieses Asset verwendet werden kann",
    "catalog.ui.usage.view_adapter": "Nach Werkzeug",
    "catalog.ui.usage.view_label": "Asset-Verwendungen gruppieren",
    "catalog.ui.usage.view_project": "Nach Speicherort",
    ...GERMAN_DESKTOP_DEPLOYMENT_OUTCOME_MESSAGES,
    "catalog.ui.workspace.create": "Dieses Asset auf ein Werkzeug anwenden",
    "catalog.ui.workspace.create_asset": "{asset} auf ein Werkzeug anwenden",
    "catalog.ui.workspace.applied_asset": "{asset} ist angewendet",
    "catalog.ui.workspace.manage": "Asset-Nutzung verwalten",
    "catalog.ui.workspace.review_asset": "Änderungen für {asset} prüfen",
    "catalog.ui.workspace.reverse_asset": "Werkzeugänderungen in {asset} speichern",
    "catalog.ui.render.claude.blocked.skill":
        "OAAM kann nicht nachweisen, dass dieser Skill weiterhin zu den beibehaltenen Claude-Code-Einstellungen und dem einteiligen SKILL.md-Format passt. Daher wird keine Datei geschrieben.",
    "catalog.ui.render.claude.blocked.subagent":
        "OAAM kann nicht nachweisen, dass dieser Subagent weiterhin zu den beibehaltenen Claude-Code-Einstellungen und dem einteiligen Agentenformat passt. Daher wird keine Datei geschrieben.",
    "catalog.ui.render.claude.blocked.workflow":
        "OAAM kann nicht nachweisen, dass dieser Workflow weiterhin zu den beibehaltenen Claude-Code-Befehlseinstellungen und dem einteiligen Befehlsformat passt. Daher wird keine Datei geschrieben.",
    "catalog.ui.render.claude.no_silent_degradation":
        "Nur die portablen Anweisungen dürfen aktualisiert werden. Passen sie nicht mehr zu den beibehaltenen Claude-Code-Einstellungen, stoppt OAAM vor der Dateivorschau, statt Verhalten unbemerkt zu verwerfen.",
    "catalog.ui.render.claude.preserved.skill":
        "OAAM behält die vorhandenen Claude-Code-Skill-Einstellungen, Kommentare, Schlüsselreihenfolge, Anführungszeichen, Abstände und den SKILL.md-Pfad bei.",
    "catalog.ui.render.claude.preserved.subagent":
        "OAAM behält die vorhandenen Claude-Code-Subagent-Einstellungen, Aliase, Kommentare, Schlüsselreihenfolge, Anführungszeichen, Abstände und den Pfad der Agentendatei bei.",
    "catalog.ui.render.claude.preserved.workflow":
        "OAAM behält die vorhandenen Claude-Code-Befehlseinstellungen, Kommentare, Schlüsselreihenfolge, Anführungszeichen, Abstände und den Projektdateipfad bei.",
    "catalog.ui.render.claude.title.blocked": "Claude-Code-Einstellungen können nicht sicher beibehalten werden",
    "catalog.ui.render.claude.title.preserved": "Claude-Code-Einstellungen werden beibehalten",
} as const satisfies DesktopDeploymentProductLanguageMessages;

export const JAPANESE_DESKTOP_DEPLOYMENT_PRODUCT_LANGUAGE_MESSAGES = {
    ...JAPANESE_DESKTOP_DEPLOYMENT_CONFIRMATION_MESSAGES,
    "catalog.ui.target.notes_copy": "補足は記載されたツールと環境に関するものです。確認済みの結果は引き続き利用できます。",
    "catalog.asset_usage.failed": "見つかったツールでこの Asset を使用できるか確認できませんでした。",
    "catalog.asset_usage.interrupted": "互換性の確認が中断されました。利用可能なツールを再検索してください。",
    "catalog.authorization.allow_current_project": "この Version を現在の Project で許可",
    "catalog.authorization.allowed": "この Version は現在の Project で許可されています。",
    "catalog.authorization.create_failed": "この許可を保存できませんでした。現在の Project を確認して再試行してください。",
    "catalog.authorization.check_failed": "この Version の許可状態を確認できませんでした。続行する前に再試行してください。",
    "catalog.authorization.required": "ファイルを確認する前に、この Version を現在の Project で許可してください。",
    "catalog.authorization.target_changed": "選択したツールの場所が変わりました。利用可能なツールを再検索してください。",
    "catalog.authorization.target_check_required":
        "保存済みのツール設定を利用できます。ファイルを変更または書き込む前に、現在のツールの場所を確認してください。",
    "catalog.compatibility.newer_build": "{runtime} は直接確認済みの版より新しいため、最も近い互換版のルールで確認しました。",
    "catalog.product.action.check_files": "ファイル形式を確認",
    "catalog.product.apply.waiting": "選択したファイルを適用中…",
    "catalog.product.analysis.failed": "ファイルの選択肢を準備できませんでした。",
    "catalog.product.asset.revision": "バージョン {revision}",
    "catalog.product.asset.summary": "{kind} · {scope}",
    "catalog.product.inspection.attribution.conflict": "このファイルを安全に関連付けられません",
    "catalog.product.inspection.attribution.unique": "この変更は保存済みのツール設定に属します",
    "catalog.product.inspection.attribution.whole_file": "Import の前にファイル全体の確認が必要です",
    "catalog.product.inspection.binary": "バイナリ内容 · {bytes} バイト",
    "catalog.product.inspection.change.added": "ファイルが追加されました",
    "catalog.product.inspection.change.content": "ファイル内容が変更されました",
    "catalog.product.inspection.change.deleted": "ファイルが削除されました",
    "catalog.product.inspection.change.executable": "実行可能設定が変更されました",
    "catalog.product.inspection.change.metadata": "Asset メタデータが変更されました",
    "catalog.product.inspection.file": "ファイル：{path}",
    "catalog.product.inspection.text": "確認対象のテキスト",
    "catalog.product.inspection.text_truncated": "このテキストは先頭の制限範囲だけを表示しています。",
    "catalog.product.runtime_version": "{runtime} {version}",
    "catalog.product.review.preview_required":
        "各項目の追加方法を選択してください。OAAM は書き込み前に最新の対象ファイルを表示します。",
    "catalog.product.review.waiting": "利用可能なファイル形式を確認中…",
    "catalog.product.target_option": "{target} · {tool} · {environment}",
    "catalog.product.technical.attribution_state": "内部の帰属状態：{state}",
    "catalog.product.technical.change_fingerprint": "変更フィンガープリント：{fingerprint}",
    "catalog.product.technical.deployment_id": "ツール設定 ID：{id}",
    "catalog.product.technical.environment": "内部環境：{identity}",
    "catalog.product.technical.inspection_token": "Inspection token：{token}",
    "catalog.product.technical.operation_id": "操作 ID：{id}",
    "catalog.product.technical.progress_stage": "内部進行ステージ：{stage}",
    "catalog.product.technical.reason": "内部理由：{reason}",
    "catalog.product.technical.runtime_ids": "内部ツールエントリ：{ids}",
    "catalog.product.technical.selector": "Inspection selector：{selector}",
    "catalog.product.technical.target": "内部ターゲット所有者：{id}",
    "catalog.ui.create.asset_step_eyebrow": "選択中の Asset",
    "catalog.ui.create.selected_asset_version": "{asset} · 選択中のバージョン",
    "catalog.ui.asset.imported_from": "{tool} からインポート",
    "catalog.ui.asset.source_details": "Asset のソース",
    "catalog.ui.asset.source_files": "インポートしたファイル",
    "catalog.ui.asset.source_locations": "ソースの場所",
    "catalog.ui.asset.view_source": "ソースを表示",
    "catalog.ui.create.asset_unavailable": "この Asset は利用できません",
    "catalog.ui.create.asset_unavailable_copy": "ライブラリに戻り、現在利用できる Asset を選択してください。",
    "catalog.ui.create.no_target.available_global": "ツールは見つかりましたが、この Asset に対応する Global の場所がありません。",
    "catalog.ui.create.no_target.available_project":
        "ツールは見つかりましたが、この Project 内にこの Asset に対応する場所がありません。",
    "catalog.ui.create.no_target.copy_global":
        "確認は完了しましたが、この Asset を使用できる Global の場所を選択したツールから見つけられませんでした。",
    "catalog.ui.create.no_target.copy_project":
        "確認は完了しましたが、この Project 内で使用できる場所を選択したツールから見つけられませんでした。",
    "catalog.ui.create.no_target.no_result": "この環境では、インストール状況または場所の結果が返されませんでした。",
    "catalog.ui.create.no_target.title": "使用できるツールの場所が見つかりません",
    "catalog.ui.target.choose_installation": "インストールフォルダーを選択",
    "catalog.ui.target.enable_selected": "選択したツールを有効にする",
    "catalog.ui.target.enablement_persists": "有効化したツールは OAAM で有効のままになります。設定から変更できます。",
    "catalog.ui.target.installation_picker_button": "このインストールフォルダーを使用",
    "catalog.ui.target.installation_picker_failed":
        "このフォルダーを選択したツールのインストールとして確認できませんでした。ツールを直接含むフォルダーを選択してください。",
    "catalog.ui.target.installation_picker_title": "ツールのインストールフォルダーを選択",
    "catalog.ui.target.open_project": "Project フォルダーを開く",
    "catalog.ui.target.path": "現在の Project: {name} · {path}",
    "catalog.ui.target.picker_failed":
        "登録済みの Project フォルダーを使用できませんでした。Project 設定で場所を確認してください。",
    "catalog.ui.target.project_load_failed":
        "この Project を読み込めませんでした。ツールの場所を確認する前に再試行してください。",
    "catalog.ui.target.project_loading": "登録済みの Project フォルダーを読み込み中…",
    "catalog.ui.target.project_unavailable": "この Project は存在しないか、管理が停止されています。",
    "catalog.ui.target.progress": "ツールと環境の組み合わせを {completed}/{total} 件確認しました",
    "catalog.product.review.passive_preview":
        "ファイルの構成が決まりました。適用前に現在のファイルと変更後のファイルを確認してください。",
    "catalog.ui.create.applied_title": "適用結果",
    "catalog.ui.target.copy_global":
        "このグローバル資産で確認するツールと環境を選択します。元のツールによる使用先の制限はなく、この確認でファイルは変更されません。",
    "catalog.ui.target.partial":
        "確認は一部未完了ですが、具体的な理由は返されていません。確認済みの結果は利用できます。結果が不足している場合は再確認してください。",
    "catalog.ui.inspection.actions_title": "次の操作を選択",
    "catalog.ui.inspection.details_title": "確認する変更",
    "catalog.ui.inspection.repair_copy": "この検査結果に基づいて OAAM 管理ファイルを復元します。",
    "catalog.ui.inspection.reverse_copy": "ツールによる変更を確認してから、新しい Asset Version として保存するか判断します。",
    "catalog.ui.render.outputs_copy":
        "物理的な出力は一度だけ表示されます。下の役割では、同じファイルの用途と今後の編集方法を説明します。",
    "catalog.ui.render.outputs_title": "予定するファイル",
    "catalog.ui.create.review_copy": "この場所への変換内容とファイルを確認します。プレビューを承認するまで書き込みません。",
    "catalog.ui.create.review_eyebrow": "選択中のツールの場所",
    "catalog.ui.create.review_title": "ファイル変更を確認",
    "catalog.ui.action.apply_to_tool": "{tool} に適用",
    "catalog.ui.usage.copy":
        "OAAM はこの正確な Asset Version と見つかった各ツールを比較します。この確認ではファイルを書き込みません。",
    "catalog.ui.usage.checked_path": "確認した場所: {path}",
    "catalog.ui.usage.detail.analysis_failed": "この正確なツール位置を確認できませんでした。",
    "catalog.ui.usage.detail.already_usable": "現在のバージョンに必要なファイルは配置済みです。変更は不要です。",
    "catalog.ui.usage.detail.applied": "現在の Version と一致しています。OAAM がここにあるファイルを管理しています。",
    "catalog.ui.usage.detail.checking": "このツール位置を確認しています。",
    "catalog.ui.usage.detail.current_observation_failed":
        "ツールの現在の状態を確認できませんでした。ツールを再確認して結果を更新してください。",
    "catalog.ui.usage.detail.configured": "ファイル変更の確認が準備されていますが、まだ書き込まれていません。",
    "catalog.ui.usage.detail.direct": "Asset の種類を変えずに、このツールで直接使用できます。",
    "catalog.ui.usage.detail.direct_absent":
        "現在の Version に必要なファイルはまだありません。OAAM が追加するファイルを先に確認してください。",
    "catalog.ui.usage.detail.direct_different": "この場所には異なる内容があります。既存の内容と差分を先に確認してください。",
    "catalog.ui.usage.detail.interrupted": "確認が中断されました。利用可能なツールをもう一度確認してください。",
    "catalog.ui.usage.detail.managed_absent":
        "以前 OAAM が管理していたファイルが見つかりません。既存の使用状態を開いて復元方法を確認してください。",
    "catalog.ui.usage.detail.managed_different":
        "OAAM が管理するファイルが外部で変更されました。修復、取り込み、復元を選ぶ前に既存の使用状態を開いてください。",
    "catalog.ui.usage.detail.managed_unknown":
        "OAAM の管理記録はありますが、現在のファイルを確認できません。既存の使用状態を開いて確認してください。",
    "catalog.ui.usage.detail.not_installed": "選択したシステム環境にこのツールはインストールされていません。",
    "catalog.ui.usage.detail.permission_denied":
        "このツール位置を読み取れません。アクセス権を確認してから、もう一度お試しください。",
    "catalog.ui.usage.detail.tool_changed":
        "検出後にツールの場所または内容が変わりました。利用可能なツールをもう一度確認してください。",
    "catalog.ui.usage.detail.substitute_absent":
        "このツールはこの Asset 種類を直接サポートしませんが、{kind} として使用できます。変換結果を先に確認してください。",
    "catalog.ui.usage.detail.substitute_different":
        "このツールでは {kind} として使用できますが、対象には異なる内容があります。変換結果と差分を先に確認してください。",
    "catalog.ui.usage.detail.transformed": "確認済みの形式変換後、このツールで内容を使用できます。",
    "catalog.ui.usage.detail.transformed_absent":
        "このツールでは形式変換が必要です。変換結果と追加されるファイルを先に確認してください。",
    "catalog.ui.usage.detail.transformed_different":
        "このツールでは形式変換が必要で、対象には異なる内容があります。変換結果と差分を先に確認してください。",
    "catalog.ui.usage.detail.unavailable": "現在、このツール位置ではこの Asset を使用できません。",
    "catalog.ui.usage.detail.unsupported": "このツールは選択した場所でこの Asset をサポートしていません。",
    "catalog.ui.usage.detail.unknown":
        "このツールが現在の Version をすでに使用しているか確認できません。この結果から書き込み確認は作成されません。",
    "catalog.ui.usage.detail.verification_failed":
        "この Asset をここでどのように使用できるか確認できませんでした。確認の詳細を読んでから、再試行するか別の場所を選んでください。",
    "catalog.ui.usage.detail.workflow_to_skill":
        "Codex ではこの Workflow を Skill として使用できます。書き込み前に変換内容と失われる可能性のある動作を表示します。",
    "catalog.ui.usage.empty": "利用可能なツールを検索すると、この Asset を使用できる場所が表示されます。",
    "catalog.ui.usage.eyebrow": "Asset の使用関係",
    "catalog.ui.usage.failure_stage": "失敗した段階: {stage}",
    "catalog.ui.usage.loading": "各ツールでの使用方法を確認しています…",
    "catalog.ui.usage.loading_progress": "検出したツールを確認しています（{completed}/{total}）…",
    "catalog.ui.usage.group_available": "{total} 個のツールエントリを確認 · {available} 個が利用可能",
    "catalog.ui.usage.group_checking": "{checking}/{total} 件を確認中",
    "catalog.ui.usage.other_checks": "利用できない・未確認の項目（{count}）",
    "catalog.ui.usage.ready_checks": "そのまま利用可能（{count}）",
    "catalog.ui.usage.review_saved_version": "保存済み Version を確認",
    "catalog.ui.usage.open": "使用状況を表示",
    "catalog.ui.usage.prepare": "ファイル変更を確認",
    "catalog.ui.usage.preview_write": "追加するファイルをプレビュー",
    "catalog.ui.usage.review_conversion": "変換結果を確認",
    "catalog.ui.usage.review_difference": "既存の内容と差分を確認",
    "catalog.ui.usage.review_note": "書き込み前に、正確な変換とファイル変更を確認します。",
    "catalog.ui.usage.status.absent": "未追加",
    "catalog.ui.usage.status.already_usable": "すでに利用可能",
    "catalog.ui.usage.status.applied": "適用済み",
    "catalog.ui.usage.status.analysis_failed": "確認できませんでした",
    "catalog.ui.usage.status.checking": "確認中",
    "catalog.ui.usage.status.current_observation_failed": "現在の確認ができません",
    "catalog.ui.usage.status.configured": "確認準備済み",
    "catalog.ui.usage.status.different": "内容が異なります",
    "catalog.ui.usage.status.direct": "直接使用可能",
    "catalog.ui.usage.status.managed_absent": "管理中のファイルがありません",
    "catalog.ui.usage.status.managed_different": "管理中のファイルが変更済み",
    "catalog.ui.usage.status.managed_unknown": "管理状態を確認できません",
    "catalog.ui.usage.status.not_installed": "未インストール",
    "catalog.ui.usage.status.transformed": "変換後に使用可能",
    "catalog.ui.usage.status.unavailable": "この場所では使用不可",
    "catalog.ui.usage.status.unsupported": "この場所では未対応",
    "catalog.ui.usage.status.unknown": "確認できません",
    "catalog.ui.usage.title": "この Asset を使用できる場所",
    "catalog.ui.usage.view_adapter": "ツール別",
    "catalog.ui.usage.view_label": "Asset の使用関係をグループ化",
    "catalog.ui.usage.view_project": "場所別",
    ...JAPANESE_DESKTOP_DEPLOYMENT_OUTCOME_MESSAGES,
    "catalog.ui.workspace.create": "この Asset をツールに適用",
    "catalog.ui.workspace.create_asset": "{asset} をツールに適用",
    "catalog.ui.workspace.applied_asset": "{asset} は適用済みです",
    "catalog.ui.workspace.manage": "Asset の利用を管理",
    "catalog.ui.workspace.review_asset": "{asset} の変更を確認",
    "catalog.ui.workspace.reverse_asset": "ツールの変更を {asset} に保存",
    "catalog.ui.render.claude.blocked.skill":
        "この Skill が保持対象の Claude Code 設定と単一ファイルの SKILL.md 形式に引き続き適合することを確認できないため、OAAM はファイルを書き込みません。",
    "catalog.ui.render.claude.blocked.subagent":
        "この Subagent が保持対象の Claude Code 設定と単一ファイルの agent 形式に引き続き適合することを確認できないため、OAAM はファイルを書き込みません。",
    "catalog.ui.render.claude.blocked.workflow":
        "この Workflow が保持対象の Claude Code コマンド設定と単一ファイルのコマンド形式に引き続き適合することを確認できないため、OAAM はファイルを書き込みません。",
    "catalog.ui.render.claude.no_silent_degradation":
        "更新できるのは移植可能な指示内容だけです。保持する Claude Code 設定と一致しなくなった場合、OAAM は動作を黙って削除せず、ファイルプレビューの前に停止します。",
    "catalog.ui.render.claude.preserved.skill":
        "OAAM は既存の Claude Code Skill 設定、コメント、キー順序、引用符、空白、SKILL.md の場所を保持します。",
    "catalog.ui.render.claude.preserved.subagent":
        "OAAM は既存の Claude Code Subagent 設定、別名、コメント、キー順序、引用符、空白、agent ファイルの場所を保持します。",
    "catalog.ui.render.claude.preserved.workflow":
        "OAAM は既存の Claude Code コマンド設定、コメント、キー順序、引用符、空白、プロジェクト内のファイル位置を保持します。",
    "catalog.ui.render.claude.title.blocked": "Claude Code の設定を安全に保持できません",
    "catalog.ui.render.claude.title.preserved": "Claude Code の設定を保持します",
} as const satisfies DesktopDeploymentProductLanguageMessages;

export const SIMPLIFIED_CHINESE_DESKTOP_DEPLOYMENT_PRODUCT_LANGUAGE_MESSAGES = {
    ...SIMPLIFIED_CHINESE_DESKTOP_DEPLOYMENT_CONFIRMATION_MESSAGES,
    "catalog.ui.target.notes_copy": "说明仅涉及列出的工具与系统环境；已确认的结果仍可使用。",
    "catalog.asset_usage.failed": "OAAM 暂时无法判断当前找到的工具如何使用这个资产。",
    "catalog.asset_usage.interrupted": "工具兼容性检查已中断，请重新查找可用工具。",
    "catalog.authorization.allow_current_project": "允许此版本用于当前项目",
    "catalog.authorization.allowed": "已允许当前项目使用此版本。",
    "catalog.authorization.create_failed": "无法保存这项允许设置。请确认当前项目后重试。",
    "catalog.authorization.check_failed": "暂时无法确认此版本的允许状态，请重试后再继续。",
    "catalog.authorization.required": "预览文件前，需要先允许当前项目使用此版本。",
    "catalog.authorization.target_changed": "所选工具位置已经变化。请重新查找可用工具后再继续。",
    "catalog.authorization.target_check_required": "已找到保存的工具配置。修改或写入文件前，请先检查当前工具位置。",
    "catalog.compatibility.newer_build": "{runtime} 比 OAAM 直接实证的版本更新；已按最接近的兼容版本规则完成检查。",
    "catalog.product.action.check_files": "检查文件形式",
    "catalog.product.apply.waiting": "正在应用所选文件…",
    "catalog.product.analysis.failed": "OAAM 无法准备可用的文件形式。",
    "catalog.product.asset.revision": "第 {revision} 版",
    "catalog.product.asset.summary": "{kind} · {scope}",
    "catalog.product.inspection.attribution.conflict": "无法安全确认这个文件属于哪一方",
    "catalog.product.inspection.attribution.unique": "这个变更属于当前保存的工具设置",
    "catalog.product.inspection.attribution.whole_file": "导入前需要审查整个文件",
    "catalog.product.inspection.binary": "二进制内容 · {bytes} 字节",
    "catalog.product.inspection.change.added": "新增文件",
    "catalog.product.inspection.change.content": "文件内容已变化",
    "catalog.product.inspection.change.deleted": "文件已删除",
    "catalog.product.inspection.change.executable": "可执行属性已变化",
    "catalog.product.inspection.change.metadata": "Asset 元数据已变化",
    "catalog.product.inspection.file": "文件：{path}",
    "catalog.product.inspection.text": "待审查文本",
    "catalog.product.inspection.text_truncated": "这里只展示了这段文本开头的有限内容。",
    "catalog.product.runtime_version": "{runtime} {version}",
    "catalog.product.review.preview_required": "请选择每项内容要如何添加。写入前，OAAM 会展示最新的目标文件。",
    "catalog.product.review.waiting": "正在检查可用的文件形式…",
    "catalog.product.target_option": "{target} · {tool} · {environment}",
    "catalog.product.technical.attribution_state": "内部归因状态：{state}",
    "catalog.product.technical.change_fingerprint": "变更指纹：{fingerprint}",
    "catalog.product.technical.deployment_id": "工具使用设置 ID：{id}",
    "catalog.product.technical.environment": "内部环境：{identity}",
    "catalog.product.technical.inspection_token": "检查令牌：{token}",
    "catalog.product.technical.operation_id": "操作 ID：{id}",
    "catalog.product.technical.progress_stage": "内部进度阶段：{stage}",
    "catalog.product.technical.reason": "内部原因：{reason}",
    "catalog.product.technical.runtime_ids": "内部工具入口：{ids}",
    "catalog.product.technical.selector": "检查选择器：{selector}",
    "catalog.product.technical.target": "内部目标归属：{id}",
    "catalog.ui.create.asset_step_eyebrow": "已选资产",
    "catalog.ui.create.selected_asset_version": "{asset} · 已选版本",
    "catalog.ui.asset.imported_from": "导入自 {tool}",
    "catalog.ui.asset.source_details": "资产来源",
    "catalog.ui.asset.source_files": "已导入文件",
    "catalog.ui.asset.source_locations": "来源位置",
    "catalog.ui.asset.view_source": "查看来源",
    "catalog.ui.create.asset_unavailable": "这个资产已不可用",
    "catalog.ui.create.asset_unavailable_copy": "请返回资产库，重新选择一个当前可用的资产。",
    "catalog.ui.create.no_target.available_global": "已找到这个工具，但它没有可用于这项资产的全局位置。",
    "catalog.ui.create.no_target.available_project": "已找到这个工具，但它在当前项目中没有可用于这项资产的位置。",
    "catalog.ui.create.no_target.copy_global": "检查已完成，但所选工具都没有提供可用于这项资产的全局位置。",
    "catalog.ui.create.no_target.copy_project": "检查已完成，但所选工具在当前项目中都没有提供可用位置。",
    "catalog.ui.create.no_target.no_result": "这些工具没有返回当前系统环境中的安装或位置信息。",
    "catalog.ui.create.no_target.title": "没有找到可用的工具位置",
    "catalog.ui.target.choose_installation": "选择安装文件夹",
    "catalog.ui.target.enable_selected": "启用所选工具",
    "catalog.ui.target.enablement_persists": "启用状态会保留，可在设置中调整。",
    "catalog.ui.target.installation_picker_button": "使用这个安装文件夹",
    "catalog.ui.target.installation_picker_failed": "无法确认这里是所选工具的安装文件夹。请选择直接包含该工具的文件夹。",
    "catalog.ui.target.installation_picker_title": "选择工具的安装文件夹",
    "catalog.ui.target.open_project": "打开项目文件夹",
    "catalog.ui.target.path": "当前项目：{name} · {path}",
    "catalog.ui.target.picker_failed": "无法使用这个项目当前登记的文件夹。请返回项目设置检查该位置。",
    "catalog.ui.target.project_load_failed": "暂时无法读取这个项目。请重试后再检查工具位置。",
    "catalog.ui.target.project_loading": "正在读取这个项目已登记的文件夹…",
    "catalog.ui.target.project_unavailable": "这个项目已不存在或已停止管理，无法继续检查。",
    "catalog.ui.target.progress": "已检查 {completed}/{total} 组工具与系统环境",
    "catalog.product.review.passive_preview": "文件方案已准备好。请先查看现有文件与预期文件，再决定是否应用。",
    "catalog.ui.create.applied_title": "应用结果",
    "catalog.ui.target.copy_global":
        "选择要为此全局资产检查的工具和系统环境。资产的来源工具不会限制使用位置；此次检查不会修改文件。",
    "catalog.ui.target.partial": "本次检查未完全完成，但未返回具体原因。已确认的结果仍可使用；如果缺少预期结果，可重新检查。",
    "catalog.ui.inspection.actions_title": "选择后续操作",
    "catalog.ui.inspection.details_title": "可查看的变更",
    "catalog.ui.inspection.repair_copy": "依据此次精确检查恢复 OAAM 管理的文件。",
    "catalog.ui.inspection.reverse_copy": "先审查可归因的工具修改，再决定是否保存为新的资产版本。",
    "catalog.ui.render.outputs_copy": "每个实际输出只列一次。下方各项说明同一组文件的用途以及后续编辑的处理方式。",
    "catalog.ui.render.outputs_title": "文件方案",
    "catalog.ui.create.review_copy": "只审查这个位置将发生的转换和文件变化；确认预览前不会写入任何文件。",
    "catalog.ui.create.review_eyebrow": "已选工具位置",
    "catalog.ui.create.review_title": "确认文件变化",
    "catalog.ui.action.apply_to_tool": "应用到 {tool}",
    "catalog.ui.usage.copy": "OAAM 会用当前这个资产版本逐一检查已找到的工具；这一步不会写入任何文件。",
    "catalog.ui.usage.checked_path": "检查位置：{path}",
    "catalog.ui.usage.detail.analysis_failed": "OAAM 暂时无法确认这个确切的工具位置。",
    "catalog.ui.usage.detail.already_usable": "当前版本需要的文件已经就绪，无需修改。",
    "catalog.ui.usage.detail.applied": "与当前版本一致；OAAM 正在管理这里的文件。",
    "catalog.ui.usage.detail.checking": "正在检查这个工具位置。",
    "catalog.ui.usage.detail.current_observation_failed": "本次未能确认这个工具的当前状态。请再次检查工具以刷新结果。",
    "catalog.ui.usage.detail.configured": "这里已经准备过一项文件变化，但尚未写入。",
    "catalog.ui.usage.detail.direct": "这个工具可以直接使用此资产，不需要改变资产类型。",
    "catalog.ui.usage.detail.direct_absent": "这里还没有当前版本需要的文件。你可以先预览将新增的内容。",
    "catalog.ui.usage.detail.direct_different": "这里已有内容，但与当前版本不同。请先查看现有内容和差异。",
    "catalog.ui.usage.detail.interrupted": "检查过程中连接中断了。请重新查找可用工具。",
    "catalog.ui.usage.detail.managed_absent": "OAAM 此前管理的文件已经缺失。请打开现有使用状态查看恢复方式。",
    "catalog.ui.usage.detail.managed_different":
        "OAAM 管理的文件已在外部发生变化。请先打开现有使用状态，再决定修复、接纳还是恢复。",
    "catalog.ui.usage.detail.managed_unknown": "OAAM 仍保留这里的管理记录，但暂时无法确认当前文件。请打开现有使用状态检查。",
    "catalog.ui.usage.detail.not_installed": "这个工具未安装在所选系统环境中。",
    "catalog.ui.usage.detail.permission_denied": "OAAM 无法读取这个工具位置。请检查访问权限后重试。",
    "catalog.ui.usage.detail.tool_changed": "找到工具后，它的位置或程序文件发生了变化。请重新查找可用工具。",
    "catalog.ui.usage.detail.substitute_absent": "这个工具没有原生支持这类资产，但可以把它作为{kind}使用。请先查看转换结果。",
    "catalog.ui.usage.detail.substitute_different":
        "这个工具可以把它作为{kind}使用，但当前位置已有不同内容。请先查看转换结果和差异。",
    "catalog.ui.usage.detail.transformed": "转换格式后，这个工具可以使用其中的内容。",
    "catalog.ui.usage.detail.transformed_absent": "需要转换成这个工具使用的格式；请先查看转换结果和将新增的文件。",
    "catalog.ui.usage.detail.transformed_different": "需要转换格式，而且这里已有不同内容。请先查看转换结果和文件差异。",
    "catalog.ui.usage.detail.unavailable": "这个工具位置目前不能使用此资产。",
    "catalog.ui.usage.detail.unsupported": "这个工具不支持在所选位置使用这项资产。",
    "catalog.ui.usage.detail.unknown": "暂时无法确认这个工具当前是否已经在使用此版本；OAAM 不会因此创建写入任务。",
    "catalog.ui.usage.detail.verification_failed":
        "OAAM 无法确认这项资产在这里的使用方式。请先查看检查详情，再决定重试或选择其他位置。",
    "catalog.ui.usage.detail.workflow_to_skill":
        "Codex 可以把这个 Workflow 作为 Skill 使用。写入前，OAAM 会展示转换内容和可能缺失的行为。",
    "catalog.ui.usage.empty": "请先查找可用工具，再查看这个资产可以在哪里使用。",
    "catalog.ui.usage.eyebrow": "资产使用关系",
    "catalog.ui.usage.failure_stage": "失败阶段：{stage}",
    "catalog.ui.usage.loading": "正在确认每个已找到的工具如何使用这个资产…",
    "catalog.ui.usage.loading_progress": "正在检查已找到的工具（{completed}/{total}）…",
    "catalog.ui.usage.group_available": "已检查 {total} 个工具入口 · {available} 个可用",
    "catalog.ui.usage.group_checking": "正在检查 {checking}/{total}",
    "catalog.ui.usage.other_checks": "不可用或待确认的入口（{count}）",
    "catalog.ui.usage.ready_checks": "已可使用（{count}）",
    "catalog.ui.usage.review_saved_version": "查看原有版本配置",
    "catalog.ui.usage.open": "查看使用状态",
    "catalog.ui.usage.prepare": "查看文件变化",
    "catalog.ui.usage.preview_write": "预览准备写入的文件",
    "catalog.ui.usage.review_conversion": "查看转换结果",
    "catalog.ui.usage.review_difference": "查看现有内容与差异",
    "catalog.ui.usage.review_note": "写入前，你会先看到并确认确切的转换和文件变化。",
    "catalog.ui.usage.status.absent": "尚未添加",
    "catalog.ui.usage.status.already_usable": "已经可用",
    "catalog.ui.usage.status.applied": "已应用",
    "catalog.ui.usage.status.analysis_failed": "暂时无法确认",
    "catalog.ui.usage.status.checking": "正在检查",
    "catalog.ui.usage.status.current_observation_failed": "本次检查不可用",
    "catalog.ui.usage.status.configured": "已准备审查",
    "catalog.ui.usage.status.different": "内容不同",
    "catalog.ui.usage.status.direct": "可直接使用",
    "catalog.ui.usage.status.managed_absent": "受管文件已缺失",
    "catalog.ui.usage.status.managed_different": "受管文件已变化",
    "catalog.ui.usage.status.managed_unknown": "受管状态待确认",
    "catalog.ui.usage.status.not_installed": "未安装",
    "catalog.ui.usage.status.transformed": "转换后可用",
    "catalog.ui.usage.status.unavailable": "当前位置不可用",
    "catalog.ui.usage.status.unsupported": "当前位置不支持",
    "catalog.ui.usage.status.unknown": "暂时无法确认",
    "catalog.ui.usage.title": "这个资产可以在哪里使用",
    "catalog.ui.usage.view_adapter": "按工具",
    "catalog.ui.usage.view_label": "切换资产使用关系分组",
    "catalog.ui.usage.view_project": "按位置",
    ...SIMPLIFIED_CHINESE_DESKTOP_DEPLOYMENT_OUTCOME_MESSAGES,
    "catalog.ui.workspace.create": "将此资产应用到工具",
    "catalog.ui.workspace.create_asset": "将 {asset} 应用到工具",
    "catalog.ui.workspace.applied_asset": "{asset} 已应用",
    "catalog.ui.workspace.manage": "管理资产使用",
    "catalog.ui.workspace.review_asset": "审查 {asset} 的文件变化",
    "catalog.ui.workspace.reverse_asset": "将工具中的变化保存到 {asset}",
    "catalog.ui.render.claude.blocked.skill":
        "OAAM 无法证明此 Skill 仍与保留的 Claude Code 设置及单文件 SKILL.md 格式一致，因此不会写入文件。",
    "catalog.ui.render.claude.blocked.subagent":
        "OAAM 无法证明此 Subagent 仍与保留的 Claude Code 设置及单文件 agent 格式一致，因此不会写入文件。",
    "catalog.ui.render.claude.blocked.workflow":
        "OAAM 无法证明此 Workflow 仍与保留的 Claude Code 命令设置及单文件命令格式一致，因此不会写入文件。",
    "catalog.ui.render.claude.no_silent_degradation":
        "只会更新可移植的指令内容。若新内容与这些 Claude Code 设置不再一致，OAAM 会在文件预览前停止，不会悄悄丢失行为。",
    "catalog.ui.render.claude.preserved.skill":
        "OAAM 会保留现有的 Claude Code Skill 设置、注释、键顺序、引号、空白格式和 SKILL.md 位置。",
    "catalog.ui.render.claude.preserved.subagent":
        "OAAM 会保留现有的 Claude Code Subagent 设置、别名、注释、键顺序、引号、空白格式和 agent 文件位置。",
    "catalog.ui.render.claude.preserved.workflow":
        "OAAM 会保留现有的 Claude Code 命令设置、注释、键顺序、引号、空白格式和项目内文件位置。",
    "catalog.ui.render.claude.title.blocked": "无法安全保留 Claude Code 设置",
    "catalog.ui.render.claude.title.preserved": "会保留 Claude Code 设置",
} as const satisfies DesktopDeploymentProductLanguageMessages;
