export const DESKTOP_ASSET_ACTION_MESSAGE_IDS = [
    "library.action.running",
    "library.actions.title",
    "library.copy.complete",
    "library.copy.source",
    "library.copy.saved_at",
    "library.copy.open_result",
    "library.copy.confirm",
    "library.copy.advanced",
    "library.copy.destination",
    "library.copy.failed",
    "library.copy.no_authority",
    "library.copy.open",
    "library.copy.project",
    "library.copy.scope_path",
    "library.copy.scope_path_help",
    "library.delete.action",
    "library.delete.complete",
    "library.delete.confirm",
    "library.delete.copy",
    "library.delete.failed",
    "library.delete.open",
    "library.metadata.complete",
    "library.metadata.description",
    "library.metadata.close",
    "library.metadata.discard_changes",
    "library.metadata.failed",
    "library.metadata.keep_editing",
    "library.metadata.name",
    "library.metadata.open",
    "library.metadata.save_changes",
    "library.metadata.unsaved",
    "library.native_export.action",
    "library.native_export.choose_button",
    "library.native_export.choose_title",
    "library.native_export.complete",
    "library.native_export.failed",
    "library.native_export.running",
    "library.purge.action",
    "library.purge.backup_failed",
    "library.purge.backup_remember",
    "library.purge.backup_then_action",
    "library.purge.complete",
    "library.purge.copy",
    "library.purge.failed",
    "library.purge.grants.many",
    "library.purge.grants.one",
    "library.purge.inspect_failed",
    "library.purge.inventory",
    "library.purge.open",
    "library.purge.policy_failed",
    "library.purge.refresh_review",
    "library.purge.review_ready",
    "library.purge.type_name",
    "library.purge.versions.many",
    "library.purge.versions.one",
    "library.purge.without_backup",
    "library.restore.action",
    "library.restore.complete",
    "library.restore.failed",
] as const;

export type DesktopAssetActionMessageId = (typeof DESKTOP_ASSET_ACTION_MESSAGE_IDS)[number];
type DesktopAssetActionMessages = Readonly<Record<DesktopAssetActionMessageId, string>>;

export const ENGLISH_DESKTOP_ASSET_ACTION_MESSAGES = {
    "library.action.running": "Completing the authorized Asset operation…",
    "library.actions.title": "Asset actions",
    "library.copy.advanced": "Advanced options",
    "library.copy.complete": "The copy was created.",
    "library.copy.source": "Source: {name} · Version {revision}",
    "library.copy.saved_at": "Saved in {location} · Version {revision}",
    "library.copy.open_result": "Open copy",
    "library.copy.confirm": "Create copy",
    "library.copy.destination": "Copy to",
    "library.copy.failed": "The exact Version could not be copied.",
    "library.copy.no_authority": "The copy receives no deployment or promotion authority from the source Asset.",
    "library.copy.open": "Copy version",
    "library.copy.project": "Project",
    "library.copy.scope_path": "Location inside the Project",
    "library.copy.scope_path_help":
        "Leave this blank for the Project root. Enter a relative folder such as .agents/skills only when the copy belongs deeper inside this Project.",
    "library.delete.action": "Move Asset to Deleted",
    "library.delete.complete": "The Asset was moved to Deleted.",
    "library.delete.confirm": "I understand that this Asset will move from the current list to Deleted.",
    "library.delete.copy":
        "This Asset moves to Deleted and can be restored later. Existing files in Project folders and tool configuration are not deleted.",
    "library.delete.failed": "The Asset could not be moved to Deleted.",
    "library.delete.open": "Delete",
    "library.metadata.complete": "The Asset display metadata was saved.",
    "library.metadata.close": "Close editor",
    "library.metadata.description": "Description",
    "library.metadata.discard_changes": "Discard changes",
    "library.metadata.failed": "The Asset display metadata could not be saved.",
    "library.metadata.keep_editing": "Keep editing",
    "library.metadata.name": "Display name",
    "library.metadata.open": "Edit name and description",
    "library.metadata.save_changes": "Save changes",
    "library.metadata.unsaved": "The name or description changed. Choose what to do before closing this editor.",
    "library.native_export.action": "Export original files",
    "library.native_export.choose_button": "Export files",
    "library.native_export.choose_title": "Save this Version's original files as a ZIP",
    "library.native_export.complete": "Exported {bytes} bytes of original files.",
    "library.native_export.failed":
        "The original files could not be exported. This Version may not have one unambiguous, directly restorable original format; you can still export the OAAM Version package.",
    "library.native_export.running": "Collecting the original files…",
    "library.purge.action": "Permanently purge from OAAM",
    "library.purge.backup_failed": "The required State backup could not be created.",
    "library.purge.backup_remember": "Remember only my backup choice",
    "library.purge.backup_then_action": "Create a State backup, then purge",
    "library.purge.complete": "The Asset was permanently purged from OAAM.",
    "library.purge.copy":
        "Permanent purge removes this Asset, every Version and the content OAAM stores for them. Existing files in Project folders and tool configuration are not deleted.",
    "library.purge.failed": "OAAM could not confirm that the purge completed. Refresh the review before trying again.",
    "library.purge.grants.many": "{count} Promotion Grants",
    "library.purge.grants.one": "{count} Promotion Grant",
    "library.purge.inspect_failed": "OAAM could not prepare an exact purge inventory.",
    "library.purge.inventory": "Exact inventory: {versions} and {grants}.",
    "library.purge.open": "Permanent purge",
    "library.purge.policy_failed": "The State-backup policy could not be read or saved.",
    "library.purge.refresh_review": "Refresh purge review",
    "library.purge.review_ready": "The exact purge inventory is ready for review.",
    "library.purge.type_name": "Type the exact Asset display name to confirm",
    "library.purge.versions.many": "{count} Versions",
    "library.purge.versions.one": "{count} Version",
    "library.purge.without_backup": "Purge without creating a new backup",
    "library.restore.action": "Restore Asset",
    "library.restore.complete": "The Asset was restored.",
    "library.restore.failed": "The deleted Asset could not be restored.",
} as const satisfies DesktopAssetActionMessages;

export const GERMAN_DESKTOP_ASSET_ACTION_MESSAGES = {
    "library.action.running": "Der autorisierte Asset-Vorgang wird abgeschlossen…",
    "library.actions.title": "Asset-Aktionen",
    "library.copy.advanced": "Erweiterte Optionen",
    "library.copy.complete": "Die Kopie wurde erstellt.",
    "library.copy.source": "Quelle: {name} · Version {revision}",
    "library.copy.saved_at": "Gespeichert in {location} · Version {revision}",
    "library.copy.open_result": "Kopie öffnen",
    "library.copy.confirm": "Kopie erstellen",
    "library.copy.destination": "Kopieren nach",
    "library.copy.failed": "Die exakte Version konnte nicht kopiert werden.",
    "library.copy.no_authority": "Die Kopie übernimmt keine Bereitstellungs- oder Freigabeberechtigung des Quell-Assets.",
    "library.copy.open": "Version kopieren",
    "library.copy.project": "Projekt",
    "library.copy.scope_path": "Ort innerhalb des Projekts",
    "library.copy.scope_path_help":
        "Leer lassen für den Projektstamm. Einen relativen Ordner wie .agents/skills nur angeben, wenn die Kopie tiefer in diesem Projekt liegen soll.",
    "library.delete.action": "Asset in „Gelöscht“ verschieben",
    "library.delete.complete": "Das Asset wurde in „Gelöscht“ verschoben.",
    "library.delete.confirm": "Ich verstehe, dass dieses Asset aus der aktuellen Liste nach „Gelöscht“ verschoben wird.",
    "library.delete.copy":
        "Das Asset wird nach „Gelöscht“ verschoben und kann später wiederhergestellt werden. Vorhandene Projekt- und Werkzeugkonfigurationsdateien werden nicht gelöscht.",
    "library.delete.failed": "Das Asset konnte nicht in „Gelöscht“ verschoben werden.",
    "library.delete.open": "Löschen",
    "library.metadata.complete": "Die Anzeige-Metadaten des Assets wurden gespeichert.",
    "library.metadata.close": "Editor schließen",
    "library.metadata.description": "Beschreibung",
    "library.metadata.discard_changes": "Änderungen verwerfen",
    "library.metadata.failed": "Die Anzeige-Metadaten des Assets konnten nicht gespeichert werden.",
    "library.metadata.keep_editing": "Weiter bearbeiten",
    "library.metadata.name": "Anzeigename",
    "library.metadata.open": "Name und Beschreibung bearbeiten",
    "library.metadata.save_changes": "Änderungen speichern",
    "library.metadata.unsaved": "Name oder Beschreibung wurden geändert. Wählen Sie vor dem Schließen, was damit geschehen soll.",
    "library.native_export.action": "Originaldateien exportieren",
    "library.native_export.choose_button": "Dateien exportieren",
    "library.native_export.choose_title": "Originaldateien dieser Version als ZIP speichern",
    "library.native_export.complete": "{bytes} Byte Originaldateien wurden exportiert.",
    "library.native_export.failed":
        "Die Originaldateien konnten nicht exportiert werden. Diese Version hat möglicherweise kein eindeutiges, direkt wiederherstellbares Originalformat; das OAAM-Versionspaket kann weiterhin exportiert werden.",
    "library.native_export.running": "Originaldateien werden zusammengestellt…",
    "library.purge.action": "Dauerhaft aus OAAM entfernen",
    "library.purge.backup_failed": "Das erforderliche State-Backup konnte nicht erstellt werden.",
    "library.purge.backup_remember": "Nur meine Backup-Auswahl merken",
    "library.purge.backup_then_action": "State-Backup erstellen, dann entfernen",
    "library.purge.complete": "Das Asset wurde dauerhaft aus OAAM entfernt.",
    "library.purge.copy":
        "Das dauerhafte Entfernen löscht dieses Asset, alle Versionen und die dafür von OAAM gespeicherten Inhalte. Dateien Ihrer KI-Coding-Tools werden nicht gelöscht.",
    "library.purge.failed":
        "OAAM konnte den Abschluss des Entfernens nicht bestätigen. Aktualisieren Sie die Prüfung vor einem neuen Versuch.",
    "library.purge.grants.many": "{count} Promotion Grants",
    "library.purge.grants.one": "{count} Promotion Grant",
    "library.purge.inspect_failed": "OAAM konnte kein exaktes Löschinventar erstellen.",
    "library.purge.inventory": "Exaktes Inventar: {versions} und {grants}.",
    "library.purge.open": "Dauerhaft entfernen",
    "library.purge.policy_failed": "Die State-Backup-Richtlinie konnte nicht gelesen oder gespeichert werden.",
    "library.purge.refresh_review": "Löschprüfung aktualisieren",
    "library.purge.review_ready": "Das exakte Löschinventar kann jetzt geprüft werden.",
    "library.purge.type_name": "Zur Bestätigung den exakten Asset-Anzeigenamen eingeben",
    "library.purge.versions.many": "{count} Versionen",
    "library.purge.versions.one": "{count} Version",
    "library.purge.without_backup": "Ohne neues Backup entfernen",
    "library.restore.action": "Asset wiederherstellen",
    "library.restore.complete": "Das Asset wurde wiederhergestellt.",
    "library.restore.failed": "Das gelöschte Asset konnte nicht wiederhergestellt werden.",
} as const satisfies DesktopAssetActionMessages;

export const JAPANESE_DESKTOP_ASSET_ACTION_MESSAGES = {
    "library.action.running": "許可された Asset 操作を完了しています…",
    "library.actions.title": "アセットの操作",
    "library.copy.advanced": "詳細オプション",
    "library.copy.complete": "コピーを作成しました。",
    "library.copy.source": "コピー元：{name} · バージョン {revision}",
    "library.copy.saved_at": "保存先：{location} · バージョン {revision}",
    "library.copy.open_result": "コピーを開く",
    "library.copy.confirm": "コピーを作成",
    "library.copy.destination": "コピー先",
    "library.copy.failed": "正確な Version をコピーできませんでした。",
    "library.copy.no_authority": "コピーは元 Asset のデプロイまたは promotion 権限を継承しません。",
    "library.copy.open": "バージョンをコピー",
    "library.copy.project": "プロジェクト",
    "library.copy.scope_path": "プロジェクト内の場所",
    "library.copy.scope_path_help":
        "プロジェクト直下に置く場合は空欄のままにします。プロジェクト内の別フォルダーに置く場合だけ、.agents/skills のような相対パスを入力します。",
    "library.delete.action": "Asset を削除済みに移動",
    "library.delete.complete": "Asset を削除済みに移動しました。",
    "library.delete.confirm": "この Asset が現在の一覧から削除済みに移動することを理解しています。",
    "library.delete.copy":
        "この Asset は削除済みに移動し、後で復元できます。プロジェクトとツール設定の既存ファイルは削除されません。",
    "library.delete.failed": "Asset を削除済みに移動できませんでした。",
    "library.delete.open": "削除",
    "library.metadata.complete": "Asset の表示メタデータを保存しました。",
    "library.metadata.close": "編集を閉じる",
    "library.metadata.description": "説明",
    "library.metadata.discard_changes": "変更を破棄",
    "library.metadata.failed": "Asset の表示メタデータを保存できませんでした。",
    "library.metadata.keep_editing": "編集を続ける",
    "library.metadata.name": "表示名",
    "library.metadata.open": "名前と説明を編集",
    "library.metadata.save_changes": "変更を保存",
    "library.metadata.unsaved": "名前または説明が変更されています。編集を閉じる前に保存するか破棄してください。",
    "library.native_export.action": "元のファイルをエクスポート",
    "library.native_export.choose_button": "ファイルをエクスポート",
    "library.native_export.choose_title": "この Version の元のファイルを ZIP として保存",
    "library.native_export.complete": "元のファイル {bytes} バイトをエクスポートしました。",
    "library.native_export.failed":
        "元のファイルをエクスポートできませんでした。この Version には一意で直接復元できる元形式がない可能性があります。OAAM Version パッケージは引き続きエクスポートできます。",
    "library.native_export.running": "元のファイルをまとめています…",
    "library.purge.action": "OAAM から完全に消去",
    "library.purge.backup_failed": "必要な State バックアップを作成できませんでした。",
    "library.purge.backup_remember": "バックアップの選択だけを記憶する",
    "library.purge.backup_then_action": "State バックアップを作成してから消去",
    "library.purge.complete": "Asset を OAAM から完全に消去しました。",
    "library.purge.copy":
        "完全消去すると、この Asset、全 Version、OAAM が保存した内容が削除されます。AI コーディングツールが使用するファイルは削除しません。",
    "library.purge.failed": "OAAM は消去の完了を確認できませんでした。再試行する前に消去内容を再確認してください。",
    "library.purge.grants.many": "{count} 個の Promotion Grant",
    "library.purge.grants.one": "{count} 個の Promotion Grant",
    "library.purge.inspect_failed": "OAAM は正確な消去一覧を作成できませんでした。",
    "library.purge.inventory": "正確な対象: {versions} と {grants}。",
    "library.purge.open": "完全消去",
    "library.purge.policy_failed": "State バックアップポリシーを読み取りまたは保存できませんでした。",
    "library.purge.refresh_review": "消去内容を再確認",
    "library.purge.review_ready": "正確な消去一覧を確認できます。",
    "library.purge.type_name": "確認のため正確な Asset 表示名を入力",
    "library.purge.versions.many": "{count} 個の Version",
    "library.purge.versions.one": "{count} 個の Version",
    "library.purge.without_backup": "新しいバックアップを作成せず消去",
    "library.restore.action": "Asset を復元",
    "library.restore.complete": "Asset を復元しました。",
    "library.restore.failed": "削除済み Asset を復元できませんでした。",
} as const satisfies DesktopAssetActionMessages;

export const SIMPLIFIED_CHINESE_DESKTOP_ASSET_ACTION_MESSAGES = {
    "library.action.running": "正在完成已授权的 Asset 操作…",
    "library.actions.title": "资产操作",
    "library.copy.advanced": "更多选项",
    "library.copy.complete": "副本已创建。",
    "library.copy.source": "来源：{name} · 第 {revision} 版",
    "library.copy.saved_at": "已保存至{location} · 第 {revision} 版",
    "library.copy.open_result": "打开副本",
    "library.copy.confirm": "创建副本",
    "library.copy.destination": "复制到",
    "library.copy.failed": "无法复制这个版本。",
    "library.copy.no_authority": "副本不会继承原资产的部署或发布权限。",
    "library.copy.open": "复制此版本",
    "library.copy.project": "项目",
    "library.copy.scope_path": "项目内位置",
    "library.copy.scope_path_help": "留空表示放在项目根目录；只有需要按文件夹整理时，才填写如 .agents/skills 这样的相对路径。",
    "library.delete.action": "移入已删除",
    "library.delete.complete": "Asset 已移入已删除。",
    "library.delete.confirm": "我明白这个资产会从当前列表移到“已删除”。",
    "library.delete.copy": "这个资产会移到“已删除”，以后仍可恢复。项目文件夹和工具配置中的现有文件不会被删除。",
    "library.delete.failed": "无法把 Asset 移入已删除。",
    "library.delete.open": "删除",
    "library.metadata.complete": "已保存 Asset 展示元数据。",
    "library.metadata.close": "收起编辑",
    "library.metadata.description": "描述",
    "library.metadata.discard_changes": "放弃修改",
    "library.metadata.failed": "无法保存 Asset 展示元数据。",
    "library.metadata.keep_editing": "继续编辑",
    "library.metadata.name": "显示名称",
    "library.metadata.open": "编辑名称和简介",
    "library.metadata.save_changes": "保存修改",
    "library.metadata.unsaved": "名称或描述已经修改。收起编辑前，请选择保存还是放弃这些修改。",
    "library.native_export.action": "导出原始文件",
    "library.native_export.choose_button": "导出文件",
    "library.native_export.choose_title": "将这个版本的原始文件保存为 ZIP",
    "library.native_export.complete": "原始文件已导出（{bytes} 字节）。",
    "library.native_export.failed": "无法导出原始文件。这个版本可能没有唯一且可直接还原的原始格式；你仍可导出 OAAM 版本包。",
    "library.native_export.running": "正在整理原始文件…",
    "library.purge.action": "从 OAAM 永久清除",
    "library.purge.backup_failed": "无法创建所需的 State 备份。",
    "library.purge.backup_remember": "仅记住我的备份选择",
    "library.purge.backup_then_action": "先创建 State 备份，再永久清除",
    "library.purge.complete": "已从 OAAM 永久清除这个 Asset。",
    "library.purge.copy":
        "永久清除会移除这个 Asset、全部 Version，以及 OAAM 为其保存的内容；项目文件夹和工具配置中的现有文件不会被删除。",
    "library.purge.failed": "OAAM 无法确认清除已完成。请刷新审查后再试。",
    "library.purge.grants.many": "{count} 个 Promotion Grant",
    "library.purge.grants.one": "{count} 个 Promotion Grant",
    "library.purge.inspect_failed": "OAAM 无法生成精确清除清单。",
    "library.purge.inventory": "精确清单：{versions} 与 {grants}。",
    "library.purge.open": "永久清除",
    "library.purge.policy_failed": "无法读取或保存 State 备份策略。",
    "library.purge.refresh_review": "刷新清除审查",
    "library.purge.review_ready": "精确清除清单已就绪，请先审查。",
    "library.purge.type_name": "输入精确的 Asset 显示名称以确认",
    "library.purge.versions.many": "{count} 个 Version",
    "library.purge.versions.one": "{count} 个 Version",
    "library.purge.without_backup": "不创建新备份，直接清除",
    "library.restore.action": "恢复 Asset",
    "library.restore.complete": "Asset 已恢复。",
    "library.restore.failed": "无法恢复已删除的 Asset。",
} as const satisfies DesktopAssetActionMessages;
