// Project lifecycle copy is shared by the main process and renderer; keys remain locale-exact.

export const ENGLISH_DESKTOP_PROJECT_LIFECYCLE_MESSAGES = {
    "project_lifecycle.action.rebind": "Rebind Project root",
    "project_lifecycle.action.rename": "Rename Project",
    "project_lifecycle.action.restore": "Restore Project",
    "project_lifecycle.action.stop_managing": "Stop managing Project",
    "project_lifecycle.backup.latest": "Latest verified backup: {time} at {path}.",
    "project_lifecycle.backup.none": "No available verified backup is recorded.",
    "project_lifecycle.backup.policy_continue": "Your saved policy continues without creating a backup.",
    "project_lifecycle.backup.policy_first": "Your saved policy creates a verified backup before continuing.",
    "project_lifecycle.backup.remember": "Remember this choice and do not ask next time",
    "project_lifecycle.backup.title": "Pre-change State backup",
    "project_lifecycle.backup_failed": "The required State backup failed. The Project change was not committed.",
    "project_lifecycle.backup_gate_unavailable": "The required State backup policy or inventory is unavailable.",
    "project_lifecycle.backup_then_continue": "Back up, then continue",
    "project_lifecycle.busy.backup": "Creating and verifying the State backup…",
    "project_lifecycle.busy.commit": "Committing the exact Project change…",
    "project_lifecycle.busy.policy": "Saving the backup prompt choice…",
    "project_lifecycle.close": "Close Project management",
    "project_lifecycle.restore.completed": "Project restored: {name}",
    "project_lifecycle.commit_failed": "The Project authority changed or the requested operation was rejected.",
    "project_lifecycle.commit_interrupted": "The Project operation was interrupted before a trustworthy result returned.",
    "project_lifecycle.confirm": "Confirm exact Project change",
    "project_lifecycle.continue_without_backup": "Continue without backup",
    "project_lifecycle.deployment_attention_unavailable":
        "Existing Deployment targets could not be reviewed, so the Project root was not changed.",
    "project_lifecycle.deployments.attention":
        "{count} existing Deployment target(s) were retained and need separate review after this rebind.",
    "project_lifecycle.deployments.copy":
        "These targets are not retargeted by Project rebind. Review or migrate each Deployment separately.",
    "project_lifecycle.deployments.title": "{count} retained Deployment target(s)",
    "project_lifecycle.eyebrow": "Exact Project authority",
    "project_lifecycle.inspect_failed": "The Project change could not be prepared. Choose a review action above to try again.",
    "project_lifecycle.inspect_interrupted": "Project review was interrupted.",
    "project_lifecycle.inspecting": "Preparing the exact Project review…",
    "project_lifecycle.manage.open": "Manage Project",
    "project_lifecycle.manage.title": "Manage this Project",
    "project_lifecycle.policy_failed": "The backup prompt choice was not saved. The Project change was not committed.",
    "project_lifecycle.project": "Project",
    "project_lifecycle.rebind.choose": "Choose new root and review",
    "project_lifecycle.rebind.copy":
        "Keep this Project UUID and history, but make one different existing folder its current root.",
    "project_lifecycle.rebind.title": "Rebind root",
    "project_lifecycle.rebind_selection_interrupted": "The Project-root picker was interrupted.",
    "project_lifecycle.rebind_selection_unavailable": "The selected environment cannot provide a Project-root selection.",
    "project_lifecycle.rename.copy": "Change only the label shown by OAAM. No directory is renamed.",
    "project_lifecycle.rename.label": "Project display name",
    "project_lifecycle.rename.review": "Review rename",
    "project_lifecycle.rename.title": "Rename",
    "project_lifecycle.restore.copy":
        "Reactivate this retained Project UUID and its history. Current directory bytes are not imported.",
    "project_lifecycle.restore.open": "Restore",
    "project_lifecycle.restore.review": "Review restore",
    "project_lifecycle.restore.root_attention":
        "The retained root {path} was unavailable when this Project was restored. Rebind explicitly before using it.",
    "project_lifecycle.restore.title": "Restore retained Project",
    "project_lifecycle.restore.unavailable":
        "The retained root is currently unavailable. Restore keeps that fact visible and does not create or import the directory.",
    "project_lifecycle.retained.copy":
        "Restore one only when you need it. Its Assets, Deployments, and original Project identity remain available.",
    "project_lifecycle.retained.title": "Stopped Projects",
    "project_lifecycle.review.current_name": "Current name",
    "project_lifecycle.review.current_root": "Current root",
    "project_lifecycle.review.next_name": "New name",
    "project_lifecycle.review.next_root": "New root",
    "project_lifecycle.review.title": "Review: {action}",
    "project_lifecycle.root": "Root",
    "project_lifecycle.stop.copy":
        "Soft-delete OAAM Project authority while retaining Assets and Deployments. External files are never deleted.",
    "project_lifecycle.stop.no_external_delete":
        "This stops OAAM management only. It does not delete the Project folder, Assets, Deployments, or files used by your AI coding tools.",
    "project_lifecycle.stop.review": "Review stop managing",
    "project_lifecycle.stop.title": "Stop managing",
    "project_lifecycle.unavailable": "This version of OAAM cannot complete this Project review.",
} as const;

export const GERMAN_DESKTOP_PROJECT_LIFECYCLE_MESSAGES = {
    "project_lifecycle.action.rebind": "Projektstamm neu binden",
    "project_lifecycle.action.rename": "Projekt umbenennen",
    "project_lifecycle.action.restore": "Projekt wiederherstellen",
    "project_lifecycle.action.stop_managing": "Projektverwaltung beenden",
    "project_lifecycle.backup.latest": "Letzte verifizierte Sicherung: {time} unter {path}.",
    "project_lifecycle.backup.none": "Es ist keine verfügbare verifizierte Sicherung erfasst.",
    "project_lifecycle.backup.policy_continue": "Die gespeicherte Richtlinie fährt ohne neue Sicherung fort.",
    "project_lifecycle.backup.policy_first":
        "Die gespeicherte Richtlinie erstellt vor dem Fortfahren eine verifizierte Sicherung.",
    "project_lifecycle.backup.remember": "Auswahl merken und beim nächsten Mal nicht fragen",
    "project_lifecycle.backup.title": "State-Sicherung vor der Änderung",
    "project_lifecycle.backup_failed":
        "Die erforderliche State-Sicherung ist fehlgeschlagen. Die Projektänderung wurde nicht übernommen.",
    "project_lifecycle.backup_gate_unavailable":
        "Die erforderliche State-Sicherungsrichtlinie oder das Inventar ist nicht verfügbar.",
    "project_lifecycle.backup_then_continue": "Sichern und dann fortfahren",
    "project_lifecycle.busy.backup": "State-Sicherung wird erstellt und verifiziert…",
    "project_lifecycle.busy.commit": "Die genaue Projektänderung wird übernommen…",
    "project_lifecycle.busy.policy": "Auswahl für Sicherungshinweise wird gespeichert…",
    "project_lifecycle.close": "Projektverwaltung schließen",
    "project_lifecycle.restore.completed": "Projekt wiederhergestellt: {name}",
    "project_lifecycle.commit_failed": "Die Projektautorität hat sich geändert oder der Vorgang wurde abgelehnt.",
    "project_lifecycle.commit_interrupted": "Der Projektvorgang wurde vor einem verlässlichen Ergebnis unterbrochen.",
    "project_lifecycle.confirm": "Genaue Projektänderung bestätigen",
    "project_lifecycle.continue_without_backup": "Ohne Sicherung fortfahren",
    "project_lifecycle.deployment_attention_unavailable":
        "Vorhandene Deployment-Ziele konnten nicht geprüft werden; der Projektstamm wurde nicht geändert.",
    "project_lifecycle.deployments.attention":
        "{count} vorhandene Deployment-Ziele wurden beibehalten und müssen nach dieser Neubindung separat geprüft werden.",
    "project_lifecycle.deployments.copy":
        "Die Neubindung ändert diese Ziele nicht. Prüfen oder migrieren Sie jedes Deployment separat.",
    "project_lifecycle.deployments.title": "{count} beibehaltene Deployment-Ziele",
    "project_lifecycle.eyebrow": "Genaue Projektautorität",
    "project_lifecycle.inspect_failed":
        "Die Projektänderung konnte nicht vorbereitet werden. Wählen Sie oben eine Prüfaktion, um es erneut zu versuchen.",
    "project_lifecycle.inspect_interrupted": "Die Projektprüfung wurde unterbrochen.",
    "project_lifecycle.inspecting": "Genaue Projektprüfung wird vorbereitet…",
    "project_lifecycle.manage.open": "Projekt verwalten",
    "project_lifecycle.manage.title": "Dieses Projekt verwalten",
    "project_lifecycle.policy_failed":
        "Die Auswahl für Sicherungshinweise wurde nicht gespeichert. Die Projektänderung wurde nicht übernommen.",
    "project_lifecycle.project": "Projekt",
    "project_lifecycle.rebind.choose": "Neuen Stamm wählen und prüfen",
    "project_lifecycle.rebind.copy":
        "Projekt-UUID und Verlauf bleiben erhalten; ein anderer vorhandener Ordner wird zum aktuellen Stamm.",
    "project_lifecycle.rebind.title": "Stamm neu binden",
    "project_lifecycle.rebind_selection_interrupted": "Die Auswahl des Projektstamms wurde unterbrochen.",
    "project_lifecycle.rebind_selection_unavailable": "Die ausgewählte Umgebung kann keinen Projektstamm auswählen.",
    "project_lifecycle.rename.copy": "Nur die in OAAM angezeigte Bezeichnung wird geändert. Kein Ordner wird umbenannt.",
    "project_lifecycle.rename.label": "Projektanzeigename",
    "project_lifecycle.rename.review": "Umbenennung prüfen",
    "project_lifecycle.rename.title": "Umbenennen",
    "project_lifecycle.restore.copy":
        "Diese beibehaltene Projekt-UUID und ihr Verlauf werden reaktiviert. Aktuelle Ordnerdaten werden nicht importiert.",
    "project_lifecycle.restore.open": "Wiederherstellen",
    "project_lifecycle.restore.review": "Wiederherstellung prüfen",
    "project_lifecycle.restore.root_attention":
        "Der beibehaltene Stamm {path} war bei der Wiederherstellung nicht verfügbar. Binden Sie ihn vor der Nutzung ausdrücklich neu.",
    "project_lifecycle.restore.title": "Beibehaltenes Projekt wiederherstellen",
    "project_lifecycle.restore.unavailable":
        "Der beibehaltene Stamm ist derzeit nicht verfügbar. Die Wiederherstellung zeigt diesen Zustand, ohne den Ordner zu erstellen oder zu importieren.",
    "project_lifecycle.retained.copy":
        "Stellen Sie ein Projekt nur bei Bedarf wieder her. Assets, Deployments und die ursprüngliche Projektidentität bleiben erhalten.",
    "project_lifecycle.retained.title": "Nicht mehr verwaltete Projekte",
    "project_lifecycle.review.current_name": "Aktueller Name",
    "project_lifecycle.review.current_root": "Aktueller Stamm",
    "project_lifecycle.review.next_name": "Neuer Name",
    "project_lifecycle.review.next_root": "Neuer Stamm",
    "project_lifecycle.review.title": "Prüfen: {action}",
    "project_lifecycle.root": "Stamm",
    "project_lifecycle.stop.copy":
        "OAAM-Projektautorität wird weich gelöscht; Assets und Deployments bleiben erhalten. Externe Dateien werden nie gelöscht.",
    "project_lifecycle.stop.no_external_delete":
        "Nur die OAAM-Verwaltung endet. Projektordner, Assets, Deployments und Dateien Ihrer KI-Coding-Tools werden nicht gelöscht.",
    "project_lifecycle.stop.review": "Beenden der Verwaltung prüfen",
    "project_lifecycle.stop.title": "Verwaltung beenden",
    "project_lifecycle.unavailable": "Diese OAAM-Version kann diese Projektprüfung nicht abschließen.",
} as const satisfies Readonly<Record<keyof typeof ENGLISH_DESKTOP_PROJECT_LIFECYCLE_MESSAGES, string>>;

export const JAPANESE_DESKTOP_PROJECT_LIFECYCLE_MESSAGES = {
    "project_lifecycle.action.rebind": "プロジェクトルートを再バインド",
    "project_lifecycle.action.rename": "プロジェクト名を変更",
    "project_lifecycle.action.restore": "プロジェクトを復元",
    "project_lifecycle.action.stop_managing": "プロジェクト管理を停止",
    "project_lifecycle.backup.latest": "最新の検証済みバックアップ：{time}、{path}。",
    "project_lifecycle.backup.none": "利用可能な検証済みバックアップは記録されていません。",
    "project_lifecycle.backup.policy_continue": "保存済みポリシーにより、バックアップを作成せず続行します。",
    "project_lifecycle.backup.policy_first": "保存済みポリシーにより、続行前に検証済みバックアップを作成します。",
    "project_lifecycle.backup.remember": "この選択を記憶し、次回から確認しない",
    "project_lifecycle.backup.title": "変更前の State バックアップ",
    "project_lifecycle.backup_failed": "必要な State バックアップに失敗しました。プロジェクト変更は確定されていません。",
    "project_lifecycle.backup_gate_unavailable": "必要な State バックアップポリシーまたはインベントリを利用できません。",
    "project_lifecycle.backup_then_continue": "バックアップして続行",
    "project_lifecycle.busy.backup": "State バックアップを作成して検証しています…",
    "project_lifecycle.busy.commit": "正確なプロジェクト変更を確定しています…",
    "project_lifecycle.busy.policy": "バックアップ確認の選択を保存しています…",
    "project_lifecycle.close": "プロジェクト管理を閉じる",
    "project_lifecycle.restore.completed": "プロジェクトを復元しました：{name}",
    "project_lifecycle.commit_failed": "プロジェクト権限が変更されたか、要求した操作が拒否されました。",
    "project_lifecycle.commit_interrupted": "信頼できる結果が返る前にプロジェクト操作が中断されました。",
    "project_lifecycle.confirm": "正確なプロジェクト変更を確認",
    "project_lifecycle.continue_without_backup": "バックアップせず続行",
    "project_lifecycle.deployment_attention_unavailable":
        "既存の Deployment ターゲットを確認できなかったため、プロジェクトルートは変更されませんでした。",
    "project_lifecycle.deployments.attention":
        "この再バインドでは既存の Deployment ターゲット {count} 件が保持され、個別の確認が必要です。",
    "project_lifecycle.deployments.copy":
        "プロジェクト再バインドではこれらのターゲットを変更しません。各 Deployment を個別に確認または移行してください。",
    "project_lifecycle.deployments.title": "保持される Deployment ターゲット {count} 件",
    "project_lifecycle.eyebrow": "正確なプロジェクト権限",
    "project_lifecycle.inspect_failed": "プロジェクト変更を準備できませんでした。上の確認ボタンからやり直してください。",
    "project_lifecycle.inspect_interrupted": "プロジェクト確認が中断されました。",
    "project_lifecycle.inspecting": "正確なプロジェクト確認を準備しています…",
    "project_lifecycle.manage.open": "プロジェクトを管理",
    "project_lifecycle.manage.title": "このプロジェクトを管理",
    "project_lifecycle.policy_failed": "バックアップ確認の選択を保存できませんでした。プロジェクト変更は確定されていません。",
    "project_lifecycle.project": "プロジェクト",
    "project_lifecycle.rebind.choose": "新しいルートを選択して確認",
    "project_lifecycle.rebind.copy": "このプロジェクトの UUID と履歴を保持し、別の既存フォルダーを唯一の現在ルートにします。",
    "project_lifecycle.rebind.title": "ルートを再バインド",
    "project_lifecycle.rebind_selection_interrupted": "プロジェクトルートの選択が中断されました。",
    "project_lifecycle.rebind_selection_unavailable": "選択した環境ではプロジェクトルートを選択できません。",
    "project_lifecycle.rename.copy": "OAAM に表示される名前だけを変更します。ディレクトリ名は変更しません。",
    "project_lifecycle.rename.label": "プロジェクト表示名",
    "project_lifecycle.rename.review": "名前変更を確認",
    "project_lifecycle.rename.title": "名前を変更",
    "project_lifecycle.restore.copy":
        "保持されているプロジェクト UUID と履歴を再有効化します。現在のディレクトリ内容は取り込みません。",
    "project_lifecycle.restore.open": "復元",
    "project_lifecycle.restore.review": "復元を確認",
    "project_lifecycle.restore.root_attention":
        "このプロジェクトの復元時、保持されたルート {path} は利用できませんでした。使用前に明示的に再バインドしてください。",
    "project_lifecycle.restore.title": "保持されたプロジェクトを復元",
    "project_lifecycle.restore.unavailable":
        "保持されたルートは現在利用できません。復元ではこの状態を表示し、ディレクトリの作成や取り込みは行いません。",
    "project_lifecycle.retained.copy":
        "必要なときだけここから復元できます。既存のアセット、デプロイ、元のプロジェクト ID は保持されます。",
    "project_lifecycle.retained.title": "管理を停止したプロジェクト",
    "project_lifecycle.review.current_name": "現在の名前",
    "project_lifecycle.review.current_root": "現在のルート",
    "project_lifecycle.review.next_name": "新しい名前",
    "project_lifecycle.review.next_root": "新しいルート",
    "project_lifecycle.review.title": "確認：{action}",
    "project_lifecycle.root": "ルート",
    "project_lifecycle.stop.copy":
        "OAAM のプロジェクト権限をソフト削除し、Asset と Deployment は保持します。外部ファイルは削除しません。",
    "project_lifecycle.stop.no_external_delete":
        "OAAM の管理だけを停止します。プロジェクトフォルダー、Asset、Deployment、AI コーディングツールが使用するファイルは削除しません。",
    "project_lifecycle.stop.review": "管理停止を確認",
    "project_lifecycle.stop.title": "管理を停止",
    "project_lifecycle.unavailable": "このバージョンの OAAM では、この Project の確認を完了できません。",
} as const satisfies Readonly<Record<keyof typeof ENGLISH_DESKTOP_PROJECT_LIFECYCLE_MESSAGES, string>>;

export const SIMPLIFIED_CHINESE_DESKTOP_PROJECT_LIFECYCLE_MESSAGES = {
    "project_lifecycle.action.rebind": "更改项目文件夹",
    "project_lifecycle.action.rename": "更改项目名称",
    "project_lifecycle.action.restore": "恢复项目",
    "project_lifecycle.action.stop_managing": "停止管理项目",
    "project_lifecycle.backup.latest": "最近一次已验证备份：{time}，位于 {path}。",
    "project_lifecycle.backup.none": "没有可用的已验证备份记录。",
    "project_lifecycle.backup.policy_continue": "已保存的策略会直接继续，不创建备份。",
    "project_lifecycle.backup.policy_first": "已保存的策略会先创建并验证备份，再继续。",
    "project_lifecycle.backup.remember": "记住本次选择，下次不再询问",
    "project_lifecycle.backup.title": "变更前备份",
    "project_lifecycle.backup_failed": "未能完成所需备份，项目没有更改。",
    "project_lifecycle.backup_gate_unavailable": "暂时无法确认备份设置或可用备份。",
    "project_lifecycle.backup_then_continue": "先备份，再继续",
    "project_lifecycle.busy.backup": "正在创建并检查备份…",
    "project_lifecycle.busy.commit": "正在保存项目变更…",
    "project_lifecycle.busy.policy": "正在保存备份提示选择…",
    "project_lifecycle.close": "关闭项目管理",
    "project_lifecycle.restore.completed": "已恢复项目：{name}",
    "project_lifecycle.commit_failed": "项目信息已经变化，或这次操作未获允许。请刷新后重试。",
    "project_lifecycle.commit_interrupted": "没有确认操作结果，项目未继续更改。",
    "project_lifecycle.confirm": "确认项目变更",
    "project_lifecycle.continue_without_backup": "不备份并继续",
    "project_lifecycle.deployment_attention_unavailable": "无法检查这个项目已有的部署位置，因此项目文件夹没有更改。",
    "project_lifecycle.deployments.attention": "有 {count} 个部署位置仍会保留，需要分别检查。",
    "project_lifecycle.deployments.copy": "更改项目文件夹不会自动更新这些部署位置。请逐一检查或迁移。",
    "project_lifecycle.deployments.title": "{count} 个仍保留的部署位置",
    "project_lifecycle.eyebrow": "项目变更",
    "project_lifecycle.inspect_failed": "暂时无法准备这项项目变更。请使用上方对应的检查按钮重试。",
    "project_lifecycle.inspect_interrupted": "项目检查已中断，没有进行变更。",
    "project_lifecycle.inspecting": "正在准备项目变更…",
    "project_lifecycle.manage.open": "管理项目",
    "project_lifecycle.manage.title": "管理此项目",
    "project_lifecycle.policy_failed": "未能保存备份选择，项目没有更改。",
    "project_lifecycle.project": "项目",
    "project_lifecycle.rebind.choose": "选择新根目录并审查",
    "project_lifecycle.rebind.copy": "保留这个项目在 OAAM 中的记录和历史，只把项目文件夹更换为另一个已存在的文件夹。",
    "project_lifecycle.rebind.title": "更改项目文件夹",
    "project_lifecycle.rebind_selection_interrupted": "没有确认新的项目文件夹，项目未更改。",
    "project_lifecycle.rebind_selection_unavailable": "当前环境无法选择新的项目文件夹。",
    "project_lifecycle.rename.copy": "只变更 OAAM 显示的名称，不会重命名任何目录。",
    "project_lifecycle.rename.label": "项目名称",
    "project_lifecycle.rename.review": "检查新名称",
    "project_lifecycle.rename.title": "更改名称",
    "project_lifecycle.restore.copy": "重新启用这个已停止管理的项目及其历史，不会自动导入当前文件夹内容。",
    "project_lifecycle.restore.open": "恢复",
    "project_lifecycle.restore.review": "检查并恢复",
    "project_lifecycle.restore.root_attention": "恢复后仍无法找到原项目文件夹 {path}。使用前请先更改项目文件夹。",
    "project_lifecycle.restore.title": "恢复项目",
    "project_lifecycle.restore.unavailable": "目前找不到原项目文件夹。恢复项目不会创建文件夹，也不会导入其中的内容。",
    "project_lifecycle.retained.copy": "需要时可在这里恢复。原有资产、部署记录和项目身份仍会保留。",
    "project_lifecycle.retained.title": "已停止管理的项目",
    "project_lifecycle.review.current_name": "当前名称",
    "project_lifecycle.review.current_root": "当前根目录",
    "project_lifecycle.review.next_name": "新名称",
    "project_lifecycle.review.next_root": "新根目录",
    "project_lifecycle.review.title": "确认：{action}",
    "project_lifecycle.root": "项目文件夹",
    "project_lifecycle.stop.copy": "OAAM 会停止管理这个项目，但保留其中的资产和部署记录；不会删除磁盘上的任何文件。",
    "project_lifecycle.stop.no_external_delete": "这只会停止 OAAM 管理，不会删除项目文件夹、资产、使用记录或工具配置文件。",
    "project_lifecycle.stop.review": "检查并停止管理",
    "project_lifecycle.stop.title": "停止管理",
    "project_lifecycle.unavailable": "当前版本的 OAAM 无法完成这项项目操作。",
} as const satisfies Readonly<Record<keyof typeof ENGLISH_DESKTOP_PROJECT_LIFECYCLE_MESSAGES, string>>;
