import { SIMPLIFIED_CHINESE_DESKTOP_ASSET_ACTION_MESSAGES } from "./catalog-asset-actions";
import { SIMPLIFIED_CHINESE_DESKTOP_ASSET_INSPECTOR_MESSAGES } from "./catalog-asset-inspector";
import { SIMPLIFIED_CHINESE_DESKTOP_ASSET_AUTHORIZATION_MESSAGES } from "./catalog-asset-authorizations";
import { SIMPLIFIED_CHINESE_DESKTOP_DEPLOYMENT_PRODUCT_LANGUAGE_MESSAGES } from "./catalog-deployment-product-language";
import { SIMPLIFIED_CHINESE_DESKTOP_DIAGNOSTICS_MESSAGES } from "./catalog-diagnostics";
import { SIMPLIFIED_CHINESE_DESKTOP_DIRECTORY_PREVIEW_MESSAGES } from "./catalog-directory-preview";
import { SIMPLIFIED_CHINESE_DESKTOP_DISCOVERY_RESULT_MESSAGES } from "./catalog-discovery-results";
import type { DesktopMessageId } from "./catalog-en";
import { SIMPLIFIED_CHINESE_DESKTOP_GUIDED_IMPORT_MESSAGES } from "./catalog-guided-import";
import { SIMPLIFIED_CHINESE_DESKTOP_IMPORT_PREVIEW_MESSAGES } from "./catalog-import-preview";
import { SIMPLIFIED_CHINESE_DESKTOP_LIBRARY_SOURCE_MESSAGES } from "./catalog-library-sources";
import { SIMPLIFIED_CHINESE_DESKTOP_MAINTENANCE_MESSAGES } from "./catalog-maintenance";
import { SIMPLIFIED_CHINESE_DESKTOP_PRESENTATION_MESSAGES } from "./catalog-presentation";
import { SIMPLIFIED_CHINESE_DESKTOP_PROJECT_LIFECYCLE_MESSAGES } from "./catalog-project-lifecycle";
import { SIMPLIFIED_CHINESE_DESKTOP_SEARCH_MESSAGES } from "./catalog-search";

// Keep exact key parity with the English authority; runtime tests defend the pair.

export const SIMPLIFIED_CHINESE_DESKTOP_MESSAGES: Readonly<Record<DesktopMessageId, string>> = Object.freeze({
    "app.brand.subtitle": "智能体资产管理器",
    "app.client_unavailable.eyebrow": "客户端不可用",
    "app.client_unavailable.message": "OAAM 已启动，但无法连接本地工作区。",
    "app.client_unavailable.title": "OAAM 无法打开本地工作区。",
    "app.failed.eyebrow": "OAAM 不可用",
    "app.failed.reason": "失败代码：",
    "app.failed.title": "OAAM 未能完成启动。",
    "app.host.running": "运行中",
    "app.navigation.catalog": "资产库与部署",
    "app.navigation.import": "导入审查",
    "app.navigation.label": "工作区导航",
    "app.navigation.overview": "概览",
    "app.navigation.sources": "来源",
    "app.navigation.workspace": "工作区",
    "app.ready": "就绪",
    "app.reconnecting.title": "正在重新连接 OAAM",
    "app.saved_assets.many": "已保存 {count} 个资产",
    "app.saved_assets.one": "已保存 {count} 个资产",
    "app.starting.eyebrow": "Open Agent Asset Manager",
    "app.starting.title": "正在启动 OAAM",
    "app.toolbar.assets": "Agent 资产",
    "app.toolbar.workspace": "本地工作区",
    "app.workspace.label": "OAAM 工作区",
    "common.cancel": "取消",
    "common.close": "关闭",
    "common.retry": "重试",
    "common.save": "保存",
    "discovery.complete_with_warnings": "扫描已经完成，但有些位置未能检查。",
    "discovery.enable_provider_first": "请至少选择一个可用工具后再扫描。",
    "discovery.interrupted": "扫描已中断，请重试以获取当前结果。",
    "discovery.loading": "正在加载扫描选择…",
    "discovery.loading_failed": "OAAM 无法加载扫描选择。",
    "discovery.no_environment": "请至少选择一个可用位置后再扫描。",
    "discovery.provider.save_failed": "工具选择未保存，请刷新后重试。",
    "discovery.provider.saved": "工具选择已保存。请重新扫描以查看当前本机资产。",
    "discovery.provider.saving": "正在保存工具选择…",
    "discovery.scanning": "正在扫描所选工具和位置…",
    "discovery.settings_unavailable": "扫描选择当前不可用。",
    "discovery.snapshot_refreshed": "扫描结果已更新。",
    "discovery.snapshot_untrustworthy": "扫描未能生成可信结果。",
    "discovery.ui.copy": "停用的 Provider 仍会显示，但在保存明确选择前不能执行 probe、read、render 或 inspect。",
    "discovery.ui.discovery_copy": "{environments} 个可用位置 · {watched} 个已保存的位置选择。扫描本身不会导入文件。",
    "discovery.ui.discovery_copy_one_environment":
        "{environments} 个可用位置 · {watched} 个已保存的位置选择。扫描本身不会导入文件。",
    "discovery.ui.discovery_copy_one_source": "{environments} 个可用位置 · {watched} 个已保存的位置选择。扫描本身不会导入文件。",
    "discovery.ui.discovery_copy_one_each": "{environments} 个可用位置 · {watched} 个已保存的位置选择。扫描本身不会导入文件。",
    "discovery.ui.eyebrow": "本机资产扫描",
    "discovery.ui.environment.current_process": "只有继续后，OAAM 才会扫描这台电脑。",
    "discovery.ui.environment.legend": "要扫描的位置",
    "discovery.ui.environment.windows_default": "默认选择这台 Windows 电脑。",
    "discovery.ui.environment.wsl_opt_in": "只有同时把 agent 资产放在这个 WSL 发行版中时才需要选择它。",
    ...SIMPLIFIED_CHINESE_DESKTOP_DISCOVERY_RESULT_MESSAGES,
    ...SIMPLIFIED_CHINESE_DESKTOP_GUIDED_IMPORT_MESSAGES,
    ...SIMPLIFIED_CHINESE_DESKTOP_IMPORT_PREVIEW_MESSAGES,
    ...SIMPLIFIED_CHINESE_DESKTOP_ASSET_ACTION_MESSAGES,
    ...SIMPLIFIED_CHINESE_DESKTOP_ASSET_INSPECTOR_MESSAGES,
    ...SIMPLIFIED_CHINESE_DESKTOP_ASSET_AUTHORIZATION_MESSAGES,
    ...SIMPLIFIED_CHINESE_DESKTOP_DEPLOYMENT_PRODUCT_LANGUAGE_MESSAGES,
    "discovery.ui.environment_result_providers": "Provider：{providers}",
    "discovery.ui.environment_results": "各位置扫描结果",
    "discovery.ui.loading_providers": "正在加载工具",
    "discovery.ui.no_runtime_relationship": "未报告关联的 agent runtime",
    "discovery.ui.no_snapshot": "尚无扫描结果。",
    "discovery.ui.no_sources": "没有找到所选工具的本机资产位置。",
    "discovery.ui.unchecked_project_environment_reference":
        "{runtime} 引用了 {environment} 中的一个项目，但尚未检查。请选择 {environment}，然后继续检查。",
    "discovery.ui.picker.choose_source_button": "使用此来源文件夹",
    "discovery.ui.picker.choose_source_title": "选择外部来源文件夹",
    "discovery.ui.provider.copy": "停用的 Provider 仍会显示，但在保存明确选择前不能执行 probe、read、render 或 inspect。",
    "discovery.ui.provider.disabled": "已停用",
    "discovery.ui.provider.disabled_after_save": "保存后停用",
    "discovery.ui.provider.enabled": "已启用",
    "discovery.ui.provider.enabled_after_save": "保存后启用",
    "discovery.ui.provider.entries.many": "{count} 个 runtime 入口",
    "discovery.ui.provider.entries.one": "{count} 个 runtime 入口",
    "discovery.ui.provider.eyebrow": "扫描设置",
    "discovery.ui.provider.save": "保存 Provider 访问设置",
    "discovery.ui.provider.saving": "正在保存…",
    "discovery.ui.provider.title": "选择允许 OAAM 运行的 adapter",
    "discovery.ui.provider.unavailable": "当前版本的 OAAM 无法使用这个以前保存的工具。",
    "discovery.ui.probe_status.complete": "完整",
    "discovery.ui.probe_status.failed": "失败",
    "discovery.ui.probe_status.partial": "部分完成",
    "discovery.ui.refresh_settings": "刷新选择",
    "discovery.ui.review_sources": "审查所选位置",
    "discovery.ui.retry_discovery": "重新扫描",
    "discovery.ui.run": "开始扫描",
    "discovery.ui.save_and_run": "保存选择并扫描",
    "discovery.ui.save_before_scan": "扫描开始前会先保存更新后的工具选择。",
    "discovery.ui.scanning": "正在扫描…",
    "discovery.ui.select_import_source": "选择 {path} 进入导入审查",
    "discovery.ui.select_source": "选择 {path}",
    "discovery.ui.source.eyebrow": "本机资产",
    "discovery.ui.source.moved_from": "原位置：{path}",
    "discovery.ui.source.title": "查找并审查资产位置",
    "discovery.ui.status.current": "当前",
    "discovery.ui.status.missing": "缺失",
    "discovery.ui.status.moved": "已移动",
    "discovery.ui.status.new": "新发现",
    "discovery.ui.status.not_checked": "未检查",
    "discovery.ui.warnings": "发现警告",
    "discovery.ui.watch.do_not_watch": "不纳入后续扫描",
    "discovery.ui.watch.global": "作为全局来源关注",
    "discovery.ui.watch.label": "后续扫描",
    "discovery.ui.watch.project": "为项目关注：{project}",
    "discovery.ui.watch.project_unavailable": "保留不可用的项目绑定：{project}",
    "discovery.ui.watch.save": "保存后续扫描选择",
    "discovery.ui.watch.saving": "正在保存后续扫描选择…",
    "discovery.ui.watch.source_label": "{path} 的后续扫描选择",
    "discovery.ui.watch.unavailable": "此来源没有稳定的关注标识。",
    "discovery.watch.saved": "位置选择已保存。OAAM 下次仍会重新检查真实路径。",
    "discovery.watch.save_failed": "位置选择未保存，请刷新扫描结果后重试。",
    "discovery.watch.saving": "正在保存位置选择…",
    "discovery.watch.selection_invalid": "位置选择已经过期，请审查最新扫描结果。",
    "import.accepting": "正在导入所选资产…",
    "import.batch.complete": "导入已完成，请逐项查看下方资产。",
    "import.batch.failed": "未能导入所选资产。",
    "import.batch.partial": "部分资产已导入，部分未能导入。请逐项查看下方结果。",
    "import.cancel.failed": "无法关闭本次资产审查。",
    "import.cancel.interrupted": "关闭资产审查的过程已中断。",
    "import.cancelled": "资产审查已关闭。如需再次审查，请重新选择来源。",
    "import.cancelling": "正在关闭资产审查…",
    "import.choose_candidates": "请选择希望保存的资产。确认之前不会导入任何内容。",
    "import.choose_compatible_asset": "请选择同类、当前有效且未删除的资产。",
    "import.choose_compatible_candidate": "请选择另一个能够满足此关联关系的已选资产。",
    "import.choose_existing_version": "请选择资产类型兼容的当前已有 Version。",
    "import.connection_ended": "OAAM 报告导入结果之前连接已结束。请先刷新资产库再重试。",
    "import.detail.interrupted": "加载文件详情的过程已中断。",
    "import.detail.unavailable": "所选文件详情不可用。",
    "import.idle": "可以返回来源选择，或者跳过本次导入。",
    "import.interrupted": "生成可信结果之前资产审查已中断。",
    "import.no_candidates": "所选来源中没有可供审查的资产。",
    "import.catalog.failed": "无法读取资产库。请重试后选择将这些更改保存到哪个资产。",
    "import.preview.failed": "无法准备资产审查。",
    "import.previewing": "正在准备资产审查…",
    "import.read.failed": "无法读取所选来源。",
    "import.read.attention": "部分所选位置需要处理。",
    "import.reading": "正在读取所选来源…",
    "import.ui.action.cancel": "关闭资产审查",
    "import.ui.action.cancelling": "正在取消…",
    "import.ui.action.import": "导入所选资产",
    "import.ui.action.importing": "正在导入…",
    "import.ui.binary_copy": "此二进制文件不直接显示；准确类型、大小和哈希仍可在技术详情中查看。",
    "import.ui.binding.choose_exact": "选择关联资产",
    "import.ui.binding.existing_versions": "资产库中已有的资产",
    "import.ui.binding.leave_unbound": "不关联资产",
    "import.ui.binding.optional": "{target} 的可选关联资产",
    "import.ui.binding.required": "{target} 的必需关联资产",
    "import.ui.binding.selected_candidates": "本次审查中已选的资产",
    "import.ui.binding.target_label": "{candidate} 的关联资产：{target}",
    "import.ui.candidate.file_count.many": "{count} 个文件",
    "import.ui.candidate.file_count.one": "{count} 个文件",
    "import.ui.candidate.select": "选择 {candidate}",
    "import.ui.asset.scope.global": "全局资产库",
    "import.ui.asset.scope.project": "当前项目",
    "import.ui.asset.status.blocked": "无法导入",
    "import.ui.asset.status.duplicate": "已有对应资产",
    "import.ui.asset.status.incomplete": "暂不能导入",
    "import.ui.asset.status.ready": "就绪",
    "import.ui.asset.status.requires_refresh": "需要重新扫描",
    "import.ui.asset.status.stale": "来源已变化",
    "import.ui.asset.status.unknown": "来源状态未知",
    "import.ui.diagnostics.attribution": "资产审查",
    "onboarding.completion.eyebrow": "安全完成",
    "onboarding.completion.failed": "OAAM 无法保存引导完成状态；没有部署任何内容。",
    "onboarding.completion.finish_without_import": "完成设置",
    "onboarding.completion.imported_copy": "所选资产已进入 OAAM 资产库；没有改动项目文件或工具配置文件。",
    "onboarding.completion.imported_title": "安全导入完成",
    "onboarding.completion.open_workspace": "打开工作区",
    "onboarding.completion.safe_copy": "完成一次新扫描后可以不导入直接结束；扫描和保留位置供以后检查都不会部署文件。",
    "onboarding.completion.safe_title": "确认来源快照无误后完成",
    "onboarding.completion.saving": "正在打开工作区…",
    "onboarding.copy": "选择 OAAM 可以查看的位置，核对发现内容，并决定保留哪些资产。",
    "onboarding.eyebrow": "首次使用",
    "onboarding.steps.label": "首次引导进度",
    "onboarding.title": "设置 OAAM，并保留现有项目与工具配置",
    "import.ui.copy": "需要时请打开文件查看，然后只选择希望 OAAM 保存的资产。",
    "import.ui.dependencies_too_many": "此资产引用了 {count} 个关联资产，数量过多，无法在这里安全审查。",
    "import.ui.destination.add_version": "在 {asset} 第 {revision} 版之后添加 Version",
    "import.ui.destination.create_asset": "创建新资产",
    "import.ui.destination.label": "如何保存 {candidate}",
    "import.ui.destination.save_as": "保存为",
    "import.ui.detail.binary_label": "已审查文件详情",
    "import.ui.detail.first_file": "第一个文件",
    "import.ui.detail.loading": "正在加载文件详情…",
    "import.ui.detail.text_truncated": "此文本已截断；哈希覆盖完整文件。",
    "import.ui.detail.view": "查看 {path}",
    "import.ui.detail.view_first": "查看第一个文件",
    "import.ui.eyebrow": "导入审查",
    "import.ui.failed.refresh_title": "需要重新执行发现",
    "import.ui.failed.title": "导入审查不可用",
    "import.ui.files_omitted": "此资产还包含其他文件；如有需要，请在导入前查看当前可用文件。",
    "import.ui.no_candidates": "所选来源中没有可供导入的资产。",
    "import.ui.no_preview": "没有选择要审查的资产",
    "import.ui.preparing": "正在准备资产审查",
    "import.ui.reading": "正在读取所选来源",
    "import.ui.read_attention.action_copy": "请查看具体原因后重试。如需调整来源，请返回选择位置。",
    "import.ui.read_attention.continue": "只继续处理可读取的位置",
    "import.ui.read_attention.copy": "OAAM 没有把不完整的读取结果交给资产审查；受影响位置中的资产不会被导入。",
    "import.ui.read_attention.eyebrow": "文件访问",
    "import.ui.read_attention.status.failed": "无法读取此位置",
    "import.ui.read_attention.status.not_found": "此位置已不可用",
    "import.ui.read_attention.status.partial": "只能读取此位置中的部分内容",
    "import.ui.read_attention.status.unreported": "此位置没有返回可信的读取结果",
    "import.ui.read_attention.title": "部分位置未能完整读取",
    "import.ui.refresh_required": "来源文件已经变化或本次审查已过期，请重新扫描后再导入。",
    "import.ui.return_to_sources": "返回扫描位置",
    "import.ui.result.batch_outcomes": "导入结果",
    "import.ui.result.copy": "{message} 某项失败不会撤销已经成功导入的资产。",
    "import.ui.result.no_tool_changes": "项目文件和工具配置文件没有被改动。",
    "import.ui.result.retry_failed": "如需重试失败的资产，请返回来源，并只选择这些资产重新导入。",
    "import.ui.result.dependency_failed": "所需资产未能导入",
    "import.ui.result.failed": "失败",
    "import.ui.result.failed_dependencies": "未能导入的所需资产：{assets}",
    "import.ui.result.imported": "已导入",
    "import.ui.result.asset_saved": "新资产已保存到 OAAM 资产库",
    "import.ui.result.version_saved": "新版本已保存到原有资产",
    "import.ui.result.open": "打开资产",
    "import.ui.result.open_failed": "资产已保存，但未能打开。请重试或在资产库中查找。",
    "import.ui.result.title": "导入结果",
    "import.ui.result.unknown_asset": "未命名资产",
    "import.ui.safe_import_copy": "每个已选资产都会创建为新资产，或作为新版本加入同类资产。导入不会改动项目文件或工具配置文件。",
    "import.ui.technical.asset_id": "Asset ID：{assetId}",
    "import.ui.technical.byte_length": "字节数：{byteLength}",
    "import.ui.technical.candidate_id": "审查项 ID：{candidateId}",
    "import.ui.technical.content_hash": "完整文件哈希：{contentHash}",
    "import.ui.technical.media_type": "媒体类型：{mediaType}",
    "import.ui.technical.version_id": "Version ID：{versionId}",
    "import.ui.technical_details": "技术详情",
    "import.ui.title": "选择资产及其必需的关联资产",
    "import.validation.binding_duplicate": "同一个关联资产被重复选择。",
    "import.validation.binding_existing_stale": "所选现有 Version 已不再是当前版本或不再兼容。",
    "import.validation.binding_stale": "关联资产已不可用、未被选中或不兼容。",
    "import.validation.candidate_dependencies_truncated": "{candidate} 关联的资产过多，当前页面无法安全展示。",
    "import.validation.candidate_not_importable": "无法从本次资产审查中导入 {candidate}。",
    "import.validation.candidate_refresh": "{candidate} 需要重新扫描。",
    "import.validation.destination_choose": "请选择 {candidate} 创建新 Asset 还是新 Version。",
    "import.validation.destination_duplicate": "一个资产选择了多个保存位置。",
    "import.validation.destination_incompatible": "{candidate} 选择的现有 Asset 已陈旧或不兼容。",
    "import.validation.destination_missing": "所选保存位置已不再属于本次资产审查。",
    "import.validation.destination_stale": "保存位置属于已陈旧或未选择的资产。",
    "import.validation.missing_binding": "{candidate} 仍需为 {target} 选择关联资产。",
    "import.validation.no_selection": "请至少选择一个可以导入的资产。",
    "import.validation.preview_membership": "所选资产已不再属于本次资产审查。",
    "import.validation.user_action": "OAAM 无法确认本次操作。请关闭并重新打开资产审查后重试。",
    "catalog.activity.analyze": "正在分析渲染选项",
    "catalog.version_update.action": "更新所选版本",
    "catalog.version_update.title": "更新此位置使用的版本",
    "catalog.version_update.copy": "此位置仍选用其他版本。选择新版本后，先审查文件差异，再应用。",
    "catalog.version_update.choose": "选择第 {revision} 版并审查",
    "catalog.version_update.selected": "此前所选版本：{version}",
    "catalog.version_update.next": "新版本：{version}",
    "catalog.version_update.pending": "所选内容待审查",
    "catalog.version_update.changed": "资产或使用位置已变化，请重新加载后审查本次更新。",
    "catalog.version_update.failed": "无法更新所选版本。",
    "catalog.activity.create": "正在保存工具使用设置",
    "catalog.activity.deploy": "正在部署所选渲染",
    "catalog.activity.preview": "正在准备精确目标预览",
    "catalog.activity.inspect": "正在检查已部署文件的变更",
    "catalog.activity.recover": "正在恢复工具文件状态",
    "catalog.activity.register": "正在注册项目",
    "catalog.activity.repair": "正在修复 OAAM 管理的文件",
    "catalog.activity.reverse_cancel": "正在取消已准备的审查",
    "catalog.activity.reverse_commit": "正在保存已审查的变更",
    "catalog.activity.reverse_refresh": "正在更新已保存版本和应用位置",
    "catalog.activity.reverse_prepare": "正在准备已审查的变更",
    "catalog.activity.scan": "正在扫描已部署文件",
    "catalog.asset.detail_interrupted": "加载 Asset 详情的过程已中断。",
    "catalog.asset.detail_unavailable": "Asset 详情不可用。",
    "catalog.asset.missing": "所选 Asset 或当前 Version 已不存在。",
    "catalog.authority_changed": "此页面打开期间资产库发生了变化。为避免应用过期选择，相关操作已暂停；请刷新后确认当前状态。",
    "catalog.empty": "资产库为空。请先导入并审查资产，再选择要添加到的工具。",
    "catalog.deployment.created": "这组工具使用设置已保存。写入任何文件前，请先审查将要发生的变化。",
    "catalog.deployment.creation_failed": "无法保存这组工具使用设置。",
    "catalog.inspection.conflict": "文件冲突需要明确恢复，或选择保存已审查的变更。",
    "catalog.inspection.current": "检查结果仍是当前事实。修复前请逐项审查详情。",
    "catalog.inspection.detail_interrupted": "加载检查详情的过程已中断。",
    "catalog.inspection.detail_unavailable": "检查详情不可用。",
    "catalog.inspection.interrupted": "检查过程已中断。",
    "catalog.inspection.lost_channel": "检查结果通道已丢失。请重新检查以获得新鲜证据。",
    "catalog.inspection.retained_expired": "保留的检查结果已过期或被替换。修复或覆盖前请重新检查。",
    "catalog.load.failed": "无法加载 OAAM 资产库。",
    "catalog.load.interrupted": "加载 OAAM 资产库的过程已中断。",
    "catalog.loading": "正在加载 OAAM 资产库…",
    "catalog.operation.failed": "{operation}失败。",
    "catalog.operation.finished": "操作已完成。当前状态：{stage}。",
    "catalog.operation.interrupted": "{operation}在获得可信结果前已中断。",
    "catalog.operation.lost_terminal": "{operation}的最终结果已丢失。请勿盲目重试；请重新加载最新保存状态并按需恢复。",
    "catalog.project.registered": "已注册 {project}。",
    "catalog.project.registration_failed": "无法注册所选项目。",
    "catalog.preview.failed": "无法准备精确目标预览。",
    "catalog.preview.interrupted": "目标预览在获得可信结果前已中断。",
    "catalog.preview.lost_channel": "目标预览的最终结果通道已丢失。写入前请重新准备预览。",
    "catalog.preview.ready": "当前目标状态和预期目标状态已可供精确审查。",
    "catalog.preview.retained_expired": "保留的目标预览已过期或被替换。请重新准备预览。",
    "catalog.render.analysis_failed": "渲染分析失败。",
    "catalog.render.choose_strategies": "请为每个语义输入选择一个策略。必需的降级仍未获得批准。",
    "catalog.render.interrupted": "渲染分析已中断。",
    "catalog.render.lost_channel": "渲染分析的结果通道已丢失。该操作只读，刷新后可以再次运行。",
    "catalog.reverse.cancel_failed": "无法取消已准备的审查。",
    "catalog.reverse.cancelled": "已取消准备好的审查，没有改动资产。",
    "catalog.reverse.commit_failed": "未能保存已审查的变更。",
    "catalog.reverse.not_prepared": "无法安全地准备这些变更以供审查。",
    "catalog.reverse.prepare_failed": "OAAM 无法准备此次精确检查到的变更。",
    "catalog.reverse.prepared": "请审查这些变更将如何成为新的资产版本。",
    "catalog.reverse.promotion_confirmation_required": "保存前请确认此次精确的新版本。",
    "catalog.reverse.result.committed": "新的资产版本已保存，且这组工具设置已选择它。",
    "catalog.reverse.result.not_published": "没有保存新的资产版本。",
    "catalog.reverse.result.outcome_unavailable": "OAAM 无法证明这些变更是否已保存，请重新加载最新保存状态。",
    "catalog.reverse.result.published_not_selected": "新的资产版本已保存，但这组工具设置仍选择此前的版本。",
    "catalog.reverse.result.recovery_required": "再次写入前，本次保存需要先执行恢复。",
    "catalog.target.inspection_failed": "已部署文件检查失败。",
    "catalog.ui.action.analyze": "查看计划变更",
    "catalog.ui.action.apply": "应用变化",
    "catalog.ui.action.create": "保存这组设置",
    "catalog.ui.action.inspect": "查看外部修改",
    "catalog.ui.action.overwrite": "应用所选 OAAM 版本",
    "catalog.ui.action.preview": "应用前查看文件",
    "catalog.ui.action.recover": "恢复",
    "catalog.ui.action.repair": "依据此次精确检查进行修复",
    "catalog.ui.action.replace_unmanaged": "替换现有文件",
    "catalog.ui.action.reverse_cancel": "取消且不保存",
    "catalog.ui.action.reverse_commit": "保留为资产库新版本",
    "catalog.ui.action.reverse_prepare": "查看工具中的变更",
    "catalog.ui.action.scan": "检查文件状态",
    "catalog.ui.asset.bytes": "{count} 字节",
    "catalog.ui.asset.catalog_eyebrow": "Asset 与 Version 资产库",
    "catalog.ui.asset.catalog_title": "选择精确保存的 Version",
    "catalog.ui.asset.current_version": "当前版本",
    "catalog.ui.asset.empty": "尚未保存 Asset。请先在上方完成导入审查。",
    "catalog.ui.asset.loading_detail": "正在加载精确 Version 元数据…",
    "catalog.ui.asset.refresh": "刷新资产库",
    "catalog.ui.asset.revision_version": "第 {revision} 版 · Version {versionId}",
    "catalog.ui.asset.view_version": "查看当前 Version",
    "catalog.ui.catalog_eyebrow": "资产库与工具使用",
    "catalog.ui.catalog_loading": "正在加载 OAAM 资产库",
    "catalog.ui.catalog_unavailable": "资产库不可用",
    "catalog.ui.catalog_warnings": "资产库与工具文件提醒",
    "catalog.ui.create.add_folder": "添加项目文件夹",
    "catalog.ui.create.allow_incomplete": "明确允许此不完整 Version",
    "catalog.ui.create.asset_revision": "{asset} · 第 {revision} 版",
    "catalog.ui.create.assets_legend": "精确的当前 Asset Version",
    "catalog.ui.create.consumer_legend": "在这个位置使用的工具入口",
    "catalog.ui.create.copy": "选择具体的工具入口。OAAM 会先展示文件变化，确认后才会写入。",
    "catalog.ui.create.eyebrow": "第 3 步",
    "catalog.ui.create.fresh_target": "工具位置",
    "catalog.ui.create.no_ready_runtime": "这个工具无法使用所选位置。",
    "catalog.ui.create.not_ready": "此处不可用：{agentRuntimeIds}",
    "catalog.ui.create.project": "OAAM 项目",
    "catalog.ui.create.project_choose": "选择项目",
    "catalog.ui.create.subject_global": "将使用全局资产库中的资产。",
    "catalog.ui.create.subject_project": "将使用当前项目及全局资产库中的资产。",
    "catalog.ui.create.target_choose": "选择已找到的工具位置",
    "catalog.ui.create.title": "确认添加位置",
    "catalog.ui.deployment.asset_count.many": "{count} 个资产库项目",
    "catalog.ui.deployment.asset_count.one": "{count} 个资产库项目",
    "catalog.ui.deployment.empty": "尚未保存任何工具使用设置。",
    "catalog.ui.deployment.eyebrow": "已设置的工具",
    "catalog.ui.deployment.select": "请先选择一组工具设置，再执行检查或更新。",
    "catalog.ui.deployment.title": "检查和更新工具文件",
    "catalog.ui.freshness.complete": "上次检查：{time}",
    "catalog.ui.freshness.failed": "上次检查于 {attempt} 失败 · 上次完整检查：{lastComplete}",
    "catalog.ui.freshness.in_progress": "自 {attempt} 起正在检查 · 上次完整检查：{lastComplete}",
    "catalog.ui.freshness.never": "尚未检查",
    "catalog.ui.freshness.no_complete": "尚无完整检查",
    "catalog.ui.freshness.partial": "上次检查于 {attempt} 部分完成 · 上次完整检查：{lastComplete}",
    "catalog.ui.inspection.change_count.many": "{count} 项变更",
    "catalog.ui.inspection.change_count.one": "{count} 项变更",
    "catalog.ui.inspection.conflict_count.many": "{count} 项冲突",
    "catalog.ui.inspection.conflict_count.one": "{count} 项冲突",
    "catalog.ui.inspection.detail_loading": "正在加载有界检查详情…",
    "catalog.ui.inspection.details_omitted": "有界摘要省略了其他检查选择器。",
    "catalog.ui.inspection.inspecting": "正在检查已部署文件的变更…",
    "catalog.ui.inspection.title": "检查",
    "catalog.ui.inspection.file_detail": "文件归属",
    "catalog.ui.inspection.change_detail": "内容变更",
    "discovery.ui.choose_environments": "选择环境",
    "catalog.ui.picker.cancelled": "已取消项目选择。",
    "catalog.ui.picker.choose_button": "使用此项目文件夹",
    "catalog.ui.picker.choose_title": "选择 OAAM 项目文件夹",
    "catalog.ui.picker.failed": "原生项目文件夹选择失败。",
    "catalog.ui.picker.opening": "正在打开原生项目文件夹选择器…",
    "catalog.ui.picker.registering": "正在注册 {path}…",
    "catalog.ui.preview.action.blocked_managed_conflict": "受管内容已发生变化。请审查此版本并确认替换。",
    "catalog.ui.preview.action.ready_apply": "当前精确目标状态允许普通应用。",
    "catalog.ui.preview.action.requires_unmanaged_replacement": "目标中已有不同内容。请核对本次文件变化，再确认替换。",
    "catalog.ui.preview.change.create": "创建新文件",
    "catalog.ui.preview.change.establish_baseline": "保留相同内容并建立 OAAM 基线",
    "catalog.ui.preview.change.managed_conflict": "受管目标与 OAAM 基线不一致",
    "catalog.ui.preview.change.remove_managed": "移除 OAAM 管理的文件",
    "catalog.ui.preview.change.replace_unmanaged": "替换现有的不同内容",
    "catalog.ui.preview.change.remove_unmanaged": "删除本次审查的现有文件",
    "catalog.ui.preview.change.unchanged": "保持受管文件不变",
    "catalog.ui.preview.change.update_managed": "更新受管文件",
    ...SIMPLIFIED_CHINESE_DESKTOP_DIRECTORY_PREVIEW_MESSAGES,
    "catalog.ui.preview.confirm_managed_overwrite": "我已审查外部文件变更，并选择仅本次恢复精确的 OAAM 输出",
    "catalog.ui.preview.confirm_unmanaged": "我已核对现有内容，同意仅本次替换",
    "catalog.ui.preview.current_tab": "当前",
    "catalog.ui.preview.desired_tab": "预期",
    "catalog.ui.preview.current_text": "当前目标文本",
    "catalog.ui.preview.desired_text": "预期目标文本",
    "catalog.ui.preview.review_tab": "文件变化",
    "catalog.ui.preview.open_current": "在页签中打开当前文件",
    "catalog.ui.preview.open_desired": "在页签中打开预期文件",
    "catalog.ui.preview.snapshot_copy": "显示生成此次预览时的文件内容。",
    "catalog.ui.preview.bounded_diff": "文件差异较多，修改按整段展示。可打开两份文件查看完整内容。",
    "catalog.ui.reconciliation_required": "OAAM 丢失了变更的最终结果。请重新加载最新保存状态；不要盲目重复操作。",
    "catalog.ui.reverse.finish_recovery": "请点击“恢复”完成本次操作；OAAM 会先核对已保存的结果，再允许下一次修改。",
    "catalog.ui.reverse.confirm_promotion": "允许这组工具设置选择此次生成的新资产版本",
    "catalog.ui.reverse.expires": "此次准备将于 {time} 过期。",
    "catalog.ui.reverse.preparing": "正在准备此次精确检查到的变更以供审查…",
    "catalog.ui.reverse.result_title": "保存结果",
    "catalog.ui.reverse.title": "查看工具中的变更",
    "catalog.ui.reverse.whole_file_adoption": "需要整文件接纳的变更应进入普通来源读取和导入审查流程。",
    "catalog.ui.render.approve_degraded": "仅本次批准此降级渲染",
    "catalog.ui.render.approval.reverse_extract_unsupported": "无法安全回收此工具中的后续修改",
    "catalog.ui.render.approval.semantic_degradation": "会丢失部分源行为",
    "catalog.ui.render.blocked": "这部分无法安全地转换。",
    "catalog.ui.render.degradation.folder_asset_flattened": "文件夹资产将被拍平",
    "catalog.ui.render.degradation.memory_semantics_lost": "Memory 行为将退化为普通内容",
    "catalog.ui.render.degradation.permission_or_tool_boundary_lost": "会丢失权限或工具边界",
    "catalog.ui.render.degradation.reverse_extract_pollution_risk": "后续回溯抽取可能夹带生成内容",
    "catalog.ui.render.degradation.runtime_specific_metadata_lost": "会丢失工具专有元数据",
    "catalog.ui.render.degradation.target_runtime_missing_asset_kind": "这个工具不支持这类 Asset 的原生形式",
    "catalog.ui.render.degradation.trigger_or_loading_level_lost": "会丢失原有触发或加载级别",
    "catalog.ui.render.degradation.workflow_permission_lost": "会丢失 Workflow 权限行为",
    "catalog.ui.render.degradation.workflow_runtime_lost": "会丢失 Workflow 执行行为",
    "catalog.ui.render.degradation.workflow_trigger_lost": "会丢失 Workflow 触发行为",
    "catalog.ui.render.degradation.workflow_variable_lost": "会丢失 Workflow 变量行为",
    "catalog.ui.render.degradations": "行为变化",
    "catalog.ui.render.executable_suffix": " · 可执行",
    "catalog.ui.render.managed_directory": "受管目录：{path}",
    "catalog.ui.render.no_target_file": "该语义不会直接声明新文件。",
    "catalog.ui.render.output_binary": "{path} · 二进制{executable}",
    "catalog.ui.render.output_text": "{path} · 文本{executable}",
    "catalog.ui.render.output_counts": "{count} 个文件 · {text} 个文本 · {binary} 个二进制 · {executable} 个可执行文件",
    "catalog.ui.render.directory_count": "{count} 个受管目录",
    "catalog.ui.render.preview_required": "请为每项选择完整渲染方案。任何写入前，OAAM 都会展示新鲜的精确目标预览。",
    "catalog.ui.render.reverse.can_reconcile": "可归属并审查后续修改",
    "catalog.ui.render.reverse.ignore_generated_wrapper": "回收修改时忽略生成的包装内容",
    "catalog.ui.render.reverse.unsupported": "无法安全回收后续修改",
    "catalog.ui.render.reverse_label": "后续修改处理：{policy}",
    "catalog.ui.render.runtime": "工具：{runtime}",
    "catalog.ui.render.semantic.asset_file_inventory": "包含的文件",
    "catalog.ui.render.semantic.guidance_base_context": "项目上下文",
    "catalog.ui.render.semantic.guidance_content": "指令内容",
    "catalog.ui.render.semantic.memory_content": "Memory 内容",
    "catalog.ui.render.semantic.memory_support": "Memory 支持",
    "catalog.ui.render.semantic.rule_activation": "Rule 触发",
    "catalog.ui.render.semantic.rule_content": "Rule 内容",
    "catalog.ui.render.semantic.skill_body": "Skill 指令",
    "catalog.ui.render.semantic.skill_discovery_metadata": "Skill 发现元数据",
    "catalog.ui.render.semantic.skill_resource": "Skill 资源",
    "catalog.ui.render.semantic.subagent_delegation_metadata": "Subagent 委派元数据",
    "catalog.ui.render.semantic.subagent_invoked_context": "Subagent 调用上下文",
    "catalog.ui.render.semantic.subagent_model_hint": "Subagent 模型提示",
    "catalog.ui.render.semantic.subagent_resource": "Subagent 资源",
    "catalog.ui.render.semantic.subagent_tool_boundary": "Subagent 工具边界",
    "catalog.ui.render.semantic.workflow_activation": "Workflow 触发",
    "catalog.ui.render.semantic.workflow_content": "Workflow 内容",
    "catalog.ui.render.semantic.workflow_reference": "Workflow 引用",
    "catalog.ui.render.strategy.inline": "内联内容",
    "catalog.ui.render.strategy.native_directory": "原生目录",
    "catalog.ui.render.strategy.native_graph": "原生文件图",
    "catalog.ui.render.strategy.native_file": "原生文件",
    "catalog.ui.render.strategy.native_import": "原生导入",
    "catalog.ui.render.strategy.reference_with_intro": "引用并附带简短说明",
    "catalog.ui.support_required": "OAAM 无法自动恢复这组工具文件。请保留检查结果并联系支持。",
    "catalog.ui.render.subject": "{asset} · {semantic}",
    "catalog.ui.render.title": "选择文件在工具中的呈现方式",
    "catalog.ui.render.waiting": "正在等待渲染分析…",
    "catalog.ui.status.external_changes": "发现外部变更",
    "catalog.ui.status.first_deployment": "尚未应用",
    "catalog.ui.status.needs_checking": "状态需要检查",
    "catalog.ui.status.paused_for_safety": "已为安全暂停",
    "catalog.ui.status.repair_available": "可以恢复部分受管文件",
    "catalog.ui.status.review_required": "这组工具设置需要审查",
    "catalog.ui.status.support_required": "需要支持介入",
    "catalog.ui.status.up_to_date": "已是最新",
    "catalog.ui.target.choose_project": "检查工具",
    "catalog.ui.target.copy": "选择要为此项目检查的工具和系统环境。资产的来源工具不会限制使用位置；此次检查不会修改文件。",
    "catalog.ui.target.discover_global": "检查工具",
    "catalog.ui.target.environments": "要检查的系统环境",
    "catalog.ui.target.eyebrow": "工具与使用位置",
    "catalog.ui.target.loading": "正在加载工具和系统环境",
    "catalog.ui.target.no_provider": "没有已选择且可用的工具。",
    "catalog.ui.target.probing": "正在检查工具…",
    "catalog.ui.target.providers": "要使用的工具",
    "catalog.ui.target.select_all": "全选",
    "catalog.ui.target.clear_all": "清除",
    "catalog.ui.target.title": "查找可用工具",
    "catalog.ui.target.unavailable": "暂时无法查找可用工具",
    "catalog.ui.workspace.back": "返回资产库",
    "catalog.ui.workspace.eyebrow": "工具使用位置",
    "catalog.ui.workspace.global": "使用全局资产",
    "catalog.ui.workspace.project": "使用项目资产",
    "catalog.validation.asset_duplicate": "同一组工具设置不能重复包含同一 Asset。",
    "catalog.validation.asset_incomplete": "{asset} 不完整。请明确允许该 Version 或移除它。",
    "catalog.validation.asset_missing": "所选 Asset 已不在当前资产库中。",
    "catalog.validation.asset_version_changed": "{asset} 的当前 Version 已变化。请重新审查并选择。",
    "catalog.validation.choose_asset": "请至少选择一个要提供给工具的 Asset。",
    "catalog.validation.choose_project": "请选择当前有效的 OAAM 项目。",
    "catalog.validation.choose_runtime": "请至少选择一个可在这个位置使用的工具入口。",
    "catalog.validation.choose_target": "请从当前发现快照中选择目标。",
    "catalog.validation.render_approval": "请明确批准降级选项 {strategy}，或选择其他策略。",
    "catalog.validation.render_approval_evidence": "此次批准缺少用户操作证据。",
    "catalog.validation.render_duplicate": "一个语义输入选择了多个渲染方案。",
    "catalog.validation.render_incomplete": "OAAM 无法确认完整的文件变化审查，请刷新后再继续。",
    "catalog.validation.render_missing": "请为每个语义输入精确选择一个渲染策略。",
    "catalog.validation.render_none": "此次分析没有可部署的渲染选项。",
    "session.catalog_unavailable": "OAAM 资产库不可用。",
    "session.connecting": "正在连接 OAAM…",
    "session.connection_closed": "OAAM 连接已关闭。",
    "session.host_recovering": "OAAM 未能就绪，正在进行唯一一次干净重试…",
    "session.host_startup_failed": "OAAM 无法启动，后台不会继续循环重试。",
    "session.host_startup_timeout": "OAAM 在 30 秒后仍不可用。你可以明确选择重试。",
    "session.initialization_failed": "OAAM 无法准备本地数据。",
    "session.restart_failed": "OAAM 无法重新启动。",
    "session.restarting": "正在重新启动 OAAM…",
    "session.starting": "正在启动 OAAM…",
    "workspace.catalog.assets.many": "{count} 个资产",
    "workspace.catalog.assets.none": "尚未导入资产",
    "workspace.catalog.label": "资产库摘要",
    "workspace.host.ready": "Host 已就绪",
    "workspace.host.warnings.many": "{count} 条启动警告",
    "workspace.host.warnings.one": "{count} 条启动警告",
    "workspace.overview.copy": "发现本地来源，审查精确候选项，并且只在明确选择后执行部署。",
    "workspace.overview.eyebrow": "工作区概览",
    "workspace.overview.title": "管理可移植的智能体资产",
    "library.asset_detail_interrupted": "资产信息加载中断。",
    "library.asset_detail_unavailable": "OAAM 无法加载所选资产的详情。",
    "library.asset_missing": "所选资产或当前版本已不可用。",
    "library.assets.count": "{count} 个资产",
    "library.assets.deleted": "已删除",
    "library.assets.empty": "此分类中没有资产。",
    "library.assets.empty_global_copy": "从现有工具导入资产，开始建立可复用的全局资产库。",
    "library.assets.empty_global_title": "全局资产库中没有资产",
    "library.assets.empty_project_copy": "查看这个项目在各工具中的位置，然后选择要导入的资产。",
    "library.assets.empty_project_title": "{project}中没有资产",
    "library.assets.eyebrow": "资产库",
    "library.assets.global_copy": "保存在全局资产库中的资产。",
    "library.assets.global_title": "全局资产库",
    "library.assets.incomplete": "不完整",
    "library.assets.include_deleted": "显示 OAAM 回收站中的资产。这些资产尚未永久删除，仍可恢复。",
    "library.assets.loading": "正在加载资产数量…",
    "library.assets.loading_page": "正在加载最多 50 个资产…",
    "library.assets.no_description": "无描述",
    "library.assets.no_match": "当前已加载的资产中没有匹配项。",
    "library.assets.project_copy": "与当前项目关联的资产。",
    "library.assets.project_title": "项目资产",
    "library.assets.revision": "第 {revision} 版",
    "library.assets.search": "搜索已加载的资产",
    "library.assets.search_placeholder": "搜索当前资产库",
    "library.assets.shared_copy": "以后可以选择全局资产；添加到工具前仍会检查兼容性。",
    "library.assets.shared_title": "此项目可用的全局资产",
    "library.assets.show_more": "再显示 {count} 个{kind}资产",
    "library.assets.title": "浏览已保存的资产",
    "library.authority_changed": "资产库已变化。依赖当前视图前请先刷新。",
    "library.catalog.warnings": "{count} 条目录警告",
    "library.environments.filter": "已关注环境筛选",
    "library.environments.sources": "{count} 个已关注来源",
    "library.environments.title": "当前视图中的已关注环境",
    "library.export.action": "导出 OAAM 版本包",
    "library.export.choose_button": "导出版本包",
    "library.export.choose_title": "为此版本保存 OAAM 版本包",
    "library.export.complete": "OAAM 版本包已导出（{bytes} 字节）。",
    "library.export.failed": "无法导出 OAAM 版本包。",
    "library.export.running": "正在生成 OAAM 版本包…",
    "library.failed_title": "无法加载资产库",
    "library.file_preview_failed": "无法安全读取所选文件。",
    "library.files.descendants": "{count} 个下级文件",
    "library.files.more": "再加载 50 项",
    "library.files.up": "返回上一级",
    "library.global.navigation": "全局资产库",
    "library.global.navigation_copy": "浏览不属于某个项目的资产。",
    "library.global.title": "全局资产库",
    "library.host.warnings": "{count} 条启动警告",
    "library.inspector.bytes": "{count} 字节",
    "library.inspector.close": "关闭资产详情",
    "library.inspector.created": "创建时间",
    "library.inspector.current_version": "当前第 {revision} 版",
    "library.inspector.executable": "可执行",
    "library.inspector.eyebrow": "资产详情",
    "library.inspector.files": "文件",
    "library.inspector.fingerprint": "指纹",
    "library.inspector.incomplete": "当前版本不完整，不能直接添加到工具。",
    "library.inspector.kind": "类型",
    "library.inspector.label": "所选资产信息",
    "library.inspector.loading": "正在加载资产与版本信息…",
    "library.inspector.more_versions": "再加载 50 个版本",
    "library.inspector.no_files": "此版本不包含文件。",
    "library.inspector.overview": "概览",
    "library.inspector.project": "项目",
    "library.inspector.scope": "适用范围",
    "library.inspector.scope_path": "适用路径",
    "library.inspector.status": "状态",
    "library.inspector.title": "资产详情",
    "library.inspector.updated": "更新时间",
    "library.inspector.version_id": "版本 ID",
    "library.inspector.version_select": "选择版本",
    "library.inspector.versions": "版本",
    "library.compare.action": "比较版本",
    "library.compare.base": "比较对象",
    "library.compare.file_graph": "文件变化",
    "library.compare.folded": "已折叠 {count} 行未变化内容",
    "library.compare.layout": "差异布局",
    "library.compare.metadata_only": "文件结构发生了变化，但没有可显示的文本差异。",
    "library.compare.no_text_changes": "所选文本在两个版本中完全相同。",
    "library.compare.progress": "{stage}：{completed}/{total}",
    "library.compare.selected_file": "所选文件",
    "library.compare.show_more_files": "显示更多文件（已显示 {shown}/{total}）",
    "library.compare.show_more_lines": "显示更多差异行（已显示 {shown}/{total}）",
    "library.compare.side_by_side": "左右对照",
    "library.compare.title": "版本比较",
    "library.compare.unified": "统一视图",
    "library.compare_failed": "版本比较未能完成。",
    "library.preview.binary": "此文件为二进制格式，无法预览。",
    "library.preview.loading": "正在安全读取所选文件…",
    "library.preview.more": "加载下一页文本",
    "library.preview.range": "第 {start}–{end} 字节，共 {total} 字节",
    "library.preview.title": "文件预览",
    "library.layout.cards": "卡片",
    "library.layout.label": "资产布局",
    "library.layout.list": "列表",
    "library.load_failed": "OAAM 无法加载所需的项目或资产信息。",
    "library.load_interrupted": "建立可信视图之前，资产库连接已中断。",
    "library.loading": "正在加载当前项目与资产信息…",
    "library.loading_title": "正在加载 OAAM 资产库",
    "library.operation_unavailable": "当前版本的 OAAM 无法列出所需的项目与资产。",
    "library.deployments.manage": "管理使用位置",
    "library.deployments.start": "选择使用位置",
    "library.preference_not_saved": "本次会话仍保留当前选择，但没有保存对应的 Desktop 偏好。",
    "library.project_register_failed": "无法添加所选项目文件夹。",
    "library.project_register_interrupted": "项目添加完成前连接已中断。",
    "library.project_registered": "已注册 {project}。",
    "library.projects.add": "添加项目",
    "library.projects.empty_copy": "添加第一个项目文件夹，或从现有工具导入资产。",
    "library.projects.empty_eyebrow": "还没有项目",
    "library.projects.empty_title": "添加第一个项目",
    "library.projects.search": "搜索已加载的项目",
    "library.projects.search_placeholder": "搜索当前项目",
    "library.projects.open_guided_import": "从现有工具导入资产",
    "library.projects.title": "项目",
    "library.refresh": "刷新",
    "library.refresh_required": "刷新已变化的数据",
    "library.subject.global": "全局",
    "library.subject.label": "资产库主语",
    "library.subject.projects": "项目",
    "library.summary.assets": "项目资产",
    "library.summary.global_assets": "全局资产",
    "library.summary.label": "当前资产库摘要",
    "library.summary.watched_environments": "显示的已关注环境",
    "library.workspace.label": "资产库工作区",
    ...SIMPLIFIED_CHINESE_DESKTOP_LIBRARY_SOURCE_MESSAGES,
    ...SIMPLIFIED_CHINESE_DESKTOP_PROJECT_LIFECYCLE_MESSAGES,
    "common.back": "返回",
    "onboarding.discovery.continue_without_import": "跳过本次导入",
    "onboarding.navigation.label": "引导流程导航",
    "onboarding.welcome.choose": "每一步都由你选择位置、工具、来源和资产。",
    "onboarding.welcome.copy": "OAAM 可以在你选择的位置查找可复用的说明和设置。开始之前不会扫描任何内容。",
    "onboarding.welcome.eyebrow": "扫描之前",
    "onboarding.welcome.inspect": "OAAM 只读取你明确选择的位置。",
    "onboarding.welcome.later": "稍后设置",
    "onboarding.welcome.no_write": "扫描和导入不会修改项目文件或工具配置文件。",
    "onboarding.welcome.start": "开始引导设置",
    "onboarding.welcome.title": "由你决定 OAAM 何时检查电脑",
    "state_resilience.backup.copy": "创建一个完整且不可变的恢复归档。备份不会包含其他备份归档、项目文件或工具配置文件。",
    "state_resilience.backup.create": "创建已验证备份",
    "state_resilience.backup.create_failed": "未能创建备份。",
    "state_resilience.backup.create_interrupted": "备份操作已中断。",
    "state_resilience.backup.created": "已创建并验证备份。",
    "state_resilience.backup.inspect": "检查备份",
    "state_resilience.backup.inspect_failed": "无法检查备份。",
    "state_resilience.backup.inspect_interrupted": "备份检查已中断。",
    "state_resilience.backup.output": "已创建于 {path}",
    "state_resilience.backup.review_ready": "创建归档前，请检查精确的来源大小和目标位置。",
    "state_resilience.backup.review_title": "备份检查",
    "state_resilience.backup.title": "备份 OAAM 状态",
    "state_resilience.copy": "备份和恢复 OAAM 资产库、托管位置记录、恢复文件及界面设置。",
    "state_resilience.destination.choose": "选择其他文件夹…",
    "state_resilience.destination.choose_button": "使用此备份文件夹",
    "state_resilience.destination.choose_failed": "无法选择备份文件夹。",
    "state_resilience.destination.choose_title": "选择备份文件夹",
    "state_resilience.destination.custom": "已选择的自定义文件夹",
    "state_resilience.destination.default": "OAAM 默认备份文件夹",
    "state_resilience.destination.label": "目标位置",
    "state_resilience.destination.remembered": "上次成功使用的自定义文件夹：{path}",
    "state_resilience.destination.remembered_unavailable": "记住的文件夹当前不可用。请选择其他文件夹或使用 OAAM 默认位置。",
    "state_resilience.destination.use_remembered": "使用上次的自定义文件夹",
    "state_resilience.encryption.compatible": "兼容密码（弱 ZipCrypto）",
    "state_resilience.encryption.compatible_warning": "兼容模式较弱。仅在其他电脑需要脱离 OAAM 打开 ZIP 时使用。",
    "state_resilience.encryption.label": "归档加密",
    "state_resilience.encryption.none": "无密码",
    "state_resilience.encryption.none_warning": "此普通 ZIP 可能包含私有 Agent 资产。任何拿到文件的人都可以读取。",
    "state_resilience.encryption.short.compatible_password": "兼容密码",
    "state_resilience.encryption.short.none": "无密码",
    "state_resilience.encryption.short.strong_password": "AES-256 密码",
    "state_resilience.encryption.strong": "强密码（AES-256）",
    "state_resilience.file.action_failed": "文件管理器操作失败。",
    "state_resilience.file.confirm_trash": "将此备份移入回收站",
    "state_resilience.file.copied": "已复制备份路径。",
    "state_resilience.file.copy": "复制路径",
    "state_resilience.file.copy_failed": "无法复制备份路径。",
    "state_resilience.file.reveal": "在文件夹中显示",
    "state_resilience.file.reveal_failed": "文件管理器无法显示此备份。你仍可复制路径。",
    "state_resilience.file.revealed": "已在文件管理器中显示备份。",
    "state_resilience.file.trash": "移除…",
    "state_resilience.file.trash_failed": "OAAM 无法确认最终回收站状态。请刷新备份清单；系统没有改用永久删除。",
    "state_resilience.file.trashed": "备份已移入回收站。",
    "state_resilience.inventory.empty": "尚无已登记的备份。",
    "state_resilience.inventory.summary": "{count} 个已登记备份 · 当前可用 {bytes}",
    "state_resilience.inventory.title": "备份清单",
    "state_resilience.load_attention": "备份信息已加载，其中有一些可能需要注意的详情。",
    "state_resilience.load_failed": "无法加载备份与恢复状态。",
    "state_resilience.observation.available": "可用",
    "state_resilience.observation.missing": "缺失",
    "state_resilience.observation.replaced": "已被替换",
    "state_resilience.password.confirm": "确认密码",
    "state_resilience.password.label": "密码",
    "state_resilience.password_invalid": "请两次输入相同且非空的密码。",
    "state_resilience.policy.ask": "每次询问",
    "state_resilience.policy.back_up_first": "先备份",
    "state_resilience.policy.continue": "继续且不显示备份提示",
    "state_resilience.policy.copy": "选择更改项目管理状态或永久移除资产前的默认备份提示。",
    "state_resilience.policy.future_scope":
        "此偏好绝不会跳过破坏性操作自身的精确检查。现有 Deployment 覆盖和修复仍保留原有检查。",
    "state_resilience.policy.label": "破坏性操作前的备份提示",
    "state_resilience.policy.latest": "最近可用备份：{time} · {path}",
    "state_resilience.policy.no_backup": "没有已登记的可用备份。",
    "state_resilience.policy.save": "保存提示偏好",
    "state_resilience.policy.save_failed": "未能保存提示偏好。请刷新后重试。",
    "state_resilience.policy.saved": "已保存备份提示偏好。",
    "state_resilience.policy.title": "执行破坏性生命周期操作前",
    "state_resilience.progress": "{stage}：{completed}/{total}",
    "state_resilience.refresh": "刷新",
    "state_resilience.restore.activate": "恢复此完整备份",
    "state_resilience.restore.activate_failed": "备份未激活。请重新选择并检查备份，再确认恢复。",
    "state_resilience.restore.activate_interrupted": "恢复连接在确认结果前中断。请重新打开 OAAM 并检查恢复状态。",
    "state_resilience.restore.activated": "备份已激活，OAAM 将使用恢复后的数据重新打开。",
    "state_resilience.restore.choose": "选择其他 ZIP…",
    "state_resilience.restore.choose_button": "检查此备份",
    "state_resilience.restore.choose_failed": "无法选择备份归档。",
    "state_resilience.restore.choose_title": "选择 OAAM 备份 ZIP",
    "state_resilience.restore.confirm": "我已检查此完整备份，并理解当前 OAAM 状态将被移出且保留。",
    "state_resilience.restore.copy": "恢复一个完整且已验证的备份。不支持选择性恢复表、Asset 或 Deployment。",
    "state_resilience.restore.inspect": "检查备份",
    "state_resilience.restore.inspect_failed": "所选归档不是有效且完整的 OAAM 备份。",
    "state_resilience.restore.inspect_interrupted": "备份检查已中断。",
    "state_resilience.restore.no_displaced": "此前不存在 OAAM 状态",
    "state_resilience.restore.no_source": "请选择已登记的备份或另一个 OAAM 备份 ZIP。",
    "state_resilience.restore.password": "归档密码（如需要）",
    "state_resilience.restore.restarting": "恢复完成。此前状态：{path}。OAAM 正在重新启动。",
    "state_resilience.restore.review_ready": "完整备份有效。激活前请检查内容。",
    "state_resilience.restore.review_title": "恢复检查",
    "state_resilience.restore.title": "恢复 OAAM 状态",
    "state_resilience.restore.use": "恢复…",
    "state_resilience.restore.warning": "恢复会替换完整 OAAM 状态单元。当前状态会保存在移出的恢复目录中。",
    "state_resilience.review.available": "可用容量",
    "state_resilience.review.created": "创建时间",
    "state_resilience.review.desktop_preferences": "桌面偏好",
    "state_resilience.review.destination": "目标位置",
    "state_resilience.review.destination_existing": "现有文件夹：{path}",
    "state_resilience.review.destination_planned": "将创建文件夹：{path}",
    "state_resilience.review.files": "文件数",
    "state_resilience.review.included": "已包含",
    "state_resilience.review.logical_size": "逻辑大小",
    "state_resilience.review.not_included": "未包含",
    "state_resilience.stage.activation": "正在激活",
    "state_resilience.stage.commit": "正在提交",
    "state_resilience.stage.encryption": "正在加密",
    "state_resilience.stage.inspection": "正在检查",
    "state_resilience.stage.inventory": "正在清点",
    "state_resilience.stage.packing": "正在打包",
    "state_resilience.stage.quiescence": "正在停止活动工作",
    "state_resilience.stage.restart_required": "需要重启",
    "state_resilience.stage.verification": "正在验证",
    "state_resilience.title": "数据安全",
    "state_resilience.recovery.eyebrow": "需要恢复",
    "state_resilience.recovery.title": "恢复 OAAM 状态",
    "state_resilience.recovery.reason.missing_database": "已建立的 OAAM 配置中缺少 State 数据库。恢复完成前，普通操作保持阻塞。",
    "state_resilience.recovery.reason.corrupt_database": "OAAM State 数据库已损坏或无法读取。恢复完成前，普通操作保持阻塞。",
    "state_resilience.recovery.reason.incompatible_database": "OAAM State 数据库与当前版本不兼容。恢复完成前，普通操作保持阻塞。",
    "state_resilience.recovery.reason.restore_reconciliation": "上一次 State 恢复被中断，必须先完成核对，普通操作才能继续。",
    "state_resilience.recovery_only":
        "在恢复模式下，OAAM 只能检查并恢复由你选择的完整备份。在你确认恢复前，普通 OAAM 数据不会被修改。",
    "state_resilience.unavailable": "当前 OAAM 会话无法使用备份与恢复功能。",
    "settings.close": "关闭设置",
    "settings.back_to_app": "返回应用",
    "settings.eyebrow": "应用设置",
    "settings.general.copy": "这些设置只会改变桌面应用的外观和使用方式。",
    "settings.general.title": "通用",
    "settings.project_management.copy": "需要让 OAAM 重新管理某个已停止的项目时，可以在这里恢复。",
    "settings.project_management.empty": "没有已停止管理的项目。",
    "settings.project_management.title": "项目管理",
    ...SIMPLIFIED_CHINESE_DESKTOP_DIAGNOSTICS_MESSAGES,
    ...SIMPLIFIED_CHINESE_DESKTOP_MAINTENANCE_MESSAGES,
    ...SIMPLIFIED_CHINESE_DESKTOP_PRESENTATION_MESSAGES,
    ...SIMPLIFIED_CHINESE_DESKTOP_SEARCH_MESSAGES,
    "settings.open": "设置",
    "settings.privacy.copy": "OAAM 只会查看你允许的位置。",
    "settings.privacy.no_session": "OAAM 不会把聊天内容、凭据、扩展或单次对话的临时数据收集为资产。",
    "settings.privacy.no_write": "扫描和导入不会改动项目文件或工具配置文件。",
    "settings.privacy.read": "OAAM 只读取你选择或要求它继续检查的位置。",
    "settings.privacy.title": "隐私与数据访问",
    "settings.runtime.copy": "这里管理从设置页扫描时使用的默认范围和已保存位置；需要导入资产时，请另行开始引导导入。",
    "settings.runtime.guided_setup": "开始一次导入",
    "settings.runtime.title": "位置与工具",
    "tray.host.failed": "OAAM：不可用",
    "tray.host.ready": "OAAM：运行中",
    "tray.host.recovering": "OAAM：正在恢复",
    "tray.host.starting": "OAAM：正在启动",
    "tray.quit": "退出 OAAM",
    "tray.show": "显示 OAAM",
    "tray.tooltip": "打开 Open Agent Asset Manager",
    "settings.title": "设置",
    "settings.search": "搜索设置",
    "settings.search_no_results": "没有匹配的设置。",
    "window.about.detail": "版本 {version}。OAAM 只在你的明确控制下管理可移植的 Agent 资产。",
    "window.about.title": "关于 OAAM",
    "window.action.failed": "无法完成窗口命令。",
    "window.chrome.title": "Open Agent Asset Manager",
    "window.menu.edit": "编辑",
    "window.menu.edit.copy": "复制",
    "window.menu.edit.cut": "剪切",
    "window.menu.edit.delete": "删除",
    "window.menu.edit.paste": "粘贴",
    "window.menu.edit.redo": "重做",
    "window.menu.edit.select_all": "全选",
    "window.menu.edit.settings": "设置…",
    "window.menu.edit.undo": "撤销",
    "window.menu.file": "文件",
    "window.menu.file.add_project": "添加项目…",
    "window.menu.file.exit": "退出",
    "window.menu.file.hide_to_tray": "隐藏到托盘",
    "window.menu.help": "帮助",
    "window.menu.help.about": "关于 OAAM",
    "window.menu.view": "视图",
    "window.menu.view.back": "后退",
    "window.menu.view.forward": "前进",
    "window.menu.view.full_screen": "切换全屏",
    "window.menu.view.inspector": "切换详情栏",
    "window.menu.view.sidebar": "切换侧栏",
    "window.menu.view.zoom_in": "放大",
    "window.menu.view.zoom_out": "缩小",
    "window.menu.view.zoom_reset": "实际大小",
    "window.navigation.back": "后退",
    "window.navigation.forward": "前进",
    "window.inspector.toggle": "切换 Asset 详情栏",
    "window.sidebar.toggle": "切换侧栏",
});
