export const DESKTOP_PRESENTATION_MESSAGE_IDS = [
    "preferences.language.de",
    "preferences.language.en",
    "preferences.language.ja",
    "preferences.language.label",
    "preferences.language.system",
    "preferences.language.zh-CN",
    "preferences.left_pane.label",
    "preferences.palette.cool",
    "preferences.palette.label",
    "preferences.palette.neutral",
    "preferences.palette.warm",
    "preferences.right_pane.label",
    "preferences.save_failed",
    "preferences.text_size.default",
    "preferences.text_size.label",
    "preferences.text_size.large",
    "preferences.text_size.small",
    "preferences.theme.dark",
    "preferences.theme.label",
    "preferences.theme.light",
    "preferences.theme.system",
    "renderer.failure.action",
    "renderer.failure.copy",
    "renderer.failure.eyebrow",
    "renderer.failure.restarting",
    "renderer.failure.retry_failed",
    "renderer.failure.title",
] as const;

export type DesktopPresentationMessageId = (typeof DESKTOP_PRESENTATION_MESSAGE_IDS)[number];
type DesktopPresentationMessages = Readonly<Record<DesktopPresentationMessageId, string>>;

export const ENGLISH_DESKTOP_PRESENTATION_MESSAGES = {
    "preferences.language.de": "Deutsch",
    "preferences.language.en": "English",
    "preferences.language.ja": "日本語",
    "preferences.language.label": "Language",
    "preferences.language.system": "System",
    "preferences.language.zh-CN": "简体中文",
    "preferences.left_pane.label": "Left pane width",
    "preferences.palette.cool": "Cool",
    "preferences.palette.label": "Surface palette",
    "preferences.palette.neutral": "Neutral",
    "preferences.palette.warm": "Warm",
    "preferences.right_pane.label": "Right pane width",
    "preferences.save_failed": "The presentation preference could not be saved. Your previous choice remains active.",
    "preferences.text_size.default": "Default",
    "preferences.text_size.label": "Text size",
    "preferences.text_size.large": "Large",
    "preferences.text_size.small": "Small",
    "preferences.theme.dark": "Dark",
    "preferences.theme.label": "Appearance",
    "preferences.theme.light": "Light",
    "preferences.theme.system": "System",
    "renderer.failure.action": "Reload interface",
    "renderer.failure.copy":
        "The current page stopped working. Reloading the interface will not repeat the last operation; unsaved input may need to be entered again.",
    "renderer.failure.eyebrow": "OAAM needs attention",
    "renderer.failure.restarting": "Reloading…",
    "renderer.failure.retry_failed": "The interface could not reload yet. You can try again.",
    "renderer.failure.title": "This page could not continue",
} as const satisfies DesktopPresentationMessages;

export const GERMAN_DESKTOP_PRESENTATION_MESSAGES = {
    "preferences.language.de": "Deutsch",
    "preferences.language.en": "Englisch",
    "preferences.language.ja": "日本語",
    "preferences.language.label": "Sprache",
    "preferences.language.system": "System",
    "preferences.language.zh-CN": "简体中文",
    "preferences.left_pane.label": "Breite des linken Bereichs",
    "preferences.palette.cool": "Kühl",
    "preferences.palette.label": "Oberflächenpalette",
    "preferences.palette.neutral": "Neutral",
    "preferences.palette.warm": "Warm",
    "preferences.right_pane.label": "Breite des rechten Bereichs",
    "preferences.save_failed":
        "Die Präsentationseinstellung konnte nicht gespeichert werden. Ihre bisherige Auswahl bleibt aktiv.",
    "preferences.text_size.default": "Standard",
    "preferences.text_size.label": "Textgröße",
    "preferences.text_size.large": "Groß",
    "preferences.text_size.small": "Klein",
    "preferences.theme.dark": "Dunkel",
    "preferences.theme.label": "Aussehen",
    "preferences.theme.light": "Hell",
    "preferences.theme.system": "System",
    "renderer.failure.action": "Oberfläche neu laden",
    "renderer.failure.copy":
        "Die aktuelle Seite funktioniert nicht mehr. Das Neuladen wiederholt den letzten Vorgang nicht; ungespeicherte Eingaben müssen eventuell erneut eingegeben werden.",
    "renderer.failure.eyebrow": "OAAM benötigt Aufmerksamkeit",
    "renderer.failure.restarting": "Wird neu geladen…",
    "renderer.failure.retry_failed": "Die Oberfläche konnte noch nicht neu geladen werden. Sie können es erneut versuchen.",
    "renderer.failure.title": "Diese Seite konnte nicht fortfahren",
} as const satisfies DesktopPresentationMessages;

export const JAPANESE_DESKTOP_PRESENTATION_MESSAGES = {
    "preferences.language.de": "Deutsch",
    "preferences.language.en": "英語",
    "preferences.language.ja": "日本語",
    "preferences.language.label": "言語",
    "preferences.language.system": "システム",
    "preferences.language.zh-CN": "简体中文",
    "preferences.left_pane.label": "左ペインの幅",
    "preferences.palette.cool": "クール",
    "preferences.palette.label": "サーフェス配色",
    "preferences.palette.neutral": "ニュートラル",
    "preferences.palette.warm": "ウォーム",
    "preferences.right_pane.label": "右ペインの幅",
    "preferences.save_failed": "プレゼンテーション設定を保存できませんでした。以前の選択は有効のままです。",
    "preferences.text_size.default": "標準",
    "preferences.text_size.label": "文字サイズ",
    "preferences.text_size.large": "大",
    "preferences.text_size.small": "小",
    "preferences.theme.dark": "暗い",
    "preferences.theme.label": "外観",
    "preferences.theme.light": "ライト",
    "preferences.theme.system": "システム",
    "renderer.failure.action": "画面を再読み込み",
    "renderer.failure.copy":
        "現在のページを続行できません。画面を再読み込みしても直前の操作は繰り返されません。未保存の入力は再入力が必要な場合があります。",
    "renderer.failure.eyebrow": "OAAM の確認が必要です",
    "renderer.failure.restarting": "再読み込みしています…",
    "renderer.failure.retry_failed": "画面をまだ再読み込みできません。もう一度試せます。",
    "renderer.failure.title": "このページを続行できませんでした",
} as const satisfies DesktopPresentationMessages;

export const SIMPLIFIED_CHINESE_DESKTOP_PRESENTATION_MESSAGES = {
    "preferences.language.de": "Deutsch",
    "preferences.language.en": "English",
    "preferences.language.ja": "日本語",
    "preferences.language.label": "语言",
    "preferences.language.system": "跟随系统",
    "preferences.language.zh-CN": "简体中文",
    "preferences.left_pane.label": "左侧栏宽度",
    "preferences.palette.cool": "冷色",
    "preferences.palette.label": "界面色调",
    "preferences.palette.neutral": "中性",
    "preferences.palette.warm": "暖色",
    "preferences.right_pane.label": "右侧栏宽度",
    "preferences.save_failed": "无法保存界面偏好；之前的选择仍然有效。",
    "preferences.text_size.default": "默认",
    "preferences.text_size.label": "文字大小",
    "preferences.text_size.large": "大",
    "preferences.text_size.small": "小",
    "preferences.theme.dark": "深色",
    "preferences.theme.label": "外观",
    "preferences.theme.light": "浅色",
    "preferences.theme.system": "跟随系统",
    "renderer.failure.action": "重新加载界面",
    "renderer.failure.copy": "当前页面已无法继续。重新加载界面不会重复执行刚才的操作；未保存的输入可能需要重新填写。",
    "renderer.failure.eyebrow": "OAAM 需要处理",
    "renderer.failure.restarting": "正在重新加载…",
    "renderer.failure.retry_failed": "界面暂时无法重新加载，你可以再试一次。",
    "renderer.failure.title": "当前页面无法继续",
} as const satisfies DesktopPresentationMessages;
