export const ENGLISH_DESKTOP_GUIDED_IMPORT_MESSAGES = {
    "discovery.ui.environment.project_choose":
        "Choose the one location that contains this Project; only one can be used for this import.",
    "discovery.ui.environment.project_match": "This Project is here, so this is the only location used for this import.",
    "discovery.ui.environment.project_mismatch": "This Project is not in this location, so it cannot be selected here.",
    "discovery.ui.environment.project_mismatch_tooltip":
        "To avoid reading or writing Assets in the wrong system location, this environment is unavailable for this Project.",
    "guided_import.back_to_sources": "Back to sources",
    "guided_import.close": "Skip guided import",
    "guided_import.close_failed": "The retained import preview could not be closed. Retry before leaving this journey.",
    "guided_import.completion.done": "Return to workspace",
    "guided_import.completion.eyebrow": "Guided import complete",
    "guided_import.completion.imported_copy":
        "The selected Assets are in the OAAM library. No files used by an AI coding tool were changed.",
    "guided_import.completion.imported_title": "Selected Assets were imported",
    "guided_import.completion.no_content_copy":
        "OAAM did not find any supported Assets in the selected locations. No files were changed.",
    "guided_import.completion.no_content_title": "No Assets ready to import",
    "guided_import.completion.no_selection_title": "No sources selected",
    "guided_import.completion.no_selection_copy": "No source locations were selected for this import. Nothing was imported.",
    "guided_import.completion.safe_copy": "The fresh source snapshot was reviewed without importing or deploying any files.",
    "guided_import.completion.safe_title": "Scan review complete",
    "guided_import.copy": "Choose where OAAM looks, review what it found, then import only the Assets you select.",
    "guided_import.project_copy":
        "OAAM checks your selected tools, but this import shows and reads only locations that the current scan links exactly to this Project.",
    "guided_import.project_fallback": "this Project",
    "guided_import.project_missing_copy": "The Project list changed. Return to the Asset library and open the import again.",
    "guided_import.project_missing_title": "This Project is no longer available",
    "guided_import.project_scope": "This import is limited to locations linked to Project “{project}”.",
    "guided_import.project_title": "Find and import Assets for “{project}”",
    "guided_import.change_selection": "Change selections",
    "guided_import.eyebrow": "Asset import",
    "guided_import.finish_without_import": "Finish without importing",
    "guided_import.navigation.label": "Guided import navigation",
    "guided_import.steps.label": "Guided import progress",
    "guided_import.title": "Find and import Assets from your AI coding tools",
    "import_journey.action.continue": "Continue",
    "import_journey.action.review_assets": "Scan selected locations",
    "import_journey.action.review_sources": "Choose folders",
    "import_journey.action.scan": "Start scan",
    "import_journey.locations.copy": "Choose the places OAAM may inspect. Nothing is scanned on this step.",
    "import_journey.locations.eyebrow": "Step 1",
    "import_journey.locations.title": "Where should OAAM look?",
    "import_journey.projects.add": "Register as Project",
    "import_journey.projects.add_failed": "OAAM could not register this exact Project folder.",
    "import_journey.projects.adding": "Registering…",
    "import_journey.projects.dialog.close": "Close Project registration",
    "import_journey.projects.dialog.copy":
        "Give this Project the name you want to see in OAAM. The folder below came from this scan.",
    "import_journey.projects.dialog.name": "Project name",
    "import_journey.projects.dialog.path": "Project folder",
    "import_journey.projects.dialog.register": "Register Project",
    "import_journey.projects.dialog.reveal": "View in file manager",
    "import_journey.projects.dialog.reveal_failed": "The Project folder could not be opened in the file manager.",
    "import_journey.projects.dialog.revealing": "Opening…",
    "import_journey.projects.dialog.title": "Register this Project",
    "import_journey.projects.copy":
        "These folders were not shown in the source cards above. Register the ones you want to use as Projects, or leave them out for now.",
    "import_journey.projects.matched": "Already registered in OAAM",
    "import_journey.projects.pending": "Register this folder to keep the Assets found here with this Project.",
    "import_journey.projects.retained_pending":
        "This folder belongs to a stopped OAAM Project. Restore that Project to keep its existing history.",
    "import_journey.projects.restore": "Restore Project",
    "import_journey.projects.restore_failed": "OAAM could not restore the stopped Project for this exact folder.",
    "import_journey.projects.restoring": "Restoring…",
    "import_journey.projects.not_now": "Do not register now",
    "import_journey.projects.observation_unavailable":
        "This scan result is no longer current. Scan again before registering the Project.",
    "import_journey.projects.skipped": "Not registered for this import",
    "import_journey.projects.skipped_effect": "Project Assets in this folder will not be used in this import.",
    "import_journey.projects.title": "Other Project folders",
    "import_journey.projects.wait_for_other": "Finish registering the other Project first.",
    "import_journey.projects.wrong_folder": "Choose this exact folder: {path}",
    "import_journey.results.copy": "See what each selected tool reported before deciding which exact sources to review.",
    "import_journey.results.eyebrow": "Step 3",
    "import_journey.results.refresh": "Scan again",
    "import_journey.results.title": "Scan results",
    "import_journey.sources.copy": "Select the locations to scan now. Assets found there will appear below for review.",
    "import_journey.sources.eyebrow": "Step 4",
    "import_journey.sources.persistence": "Selected locations are used for this scan and saved for future manual scans.",
    "import_journey.sources.review_copy":
        "Review the locations found in this scan. Choose where OAAM should keep each source, or ignore locations you do not want to use.",
    "import_journey.sources.review_title": "Review found locations",
    "import_journey.sources.title": "Choose locations to scan",
    "import_journey.steps.assets": "Review Assets",
    "import_journey.steps.complete": "Complete",
    "import_journey.steps.content": "Choose content",
    "import_journey.steps.locations": "Locations",
    "import_journey.steps.results": "Results",
    "import_journey.steps.sources": "Sources",
    "import_journey.steps.tools": "AI coding tools",
    "import_journey.tools.copy": "Select the AI coding tools whose files OAAM may inspect in the chosen locations.",
    "import_journey.tools.eyebrow": "Step 2",
    "import_journey.tools.title": "Which tools do you use?",
} as const;

export const GERMAN_DESKTOP_GUIDED_IMPORT_MESSAGES = {
    "discovery.ui.environment.project_choose":
        "Wählen Sie den einen Ort aus, der dieses Projekt enthält; für diesen Import kann nur einer verwendet werden.",
    "discovery.ui.environment.project_match":
        "Dieses Projekt befindet sich hier. Für diesen Import wird daher nur dieser Ort verwendet.",
    "discovery.ui.environment.project_mismatch":
        "Dieses Projekt befindet sich nicht an diesem Ort; er kann hier nicht ausgewählt werden.",
    "discovery.ui.environment.project_mismatch_tooltip":
        "Damit Assets nicht am falschen Systemort gelesen oder geschrieben werden, ist diese Umgebung für dieses Projekt nicht verfügbar.",
    "guided_import.back_to_sources": "Zurück zu den Quellen",
    "guided_import.close": "Geführten Import überspringen",
    "guided_import.close_failed":
        "Die beibehaltene Importvorschau konnte nicht geschlossen werden. Versuchen Sie es erneut, bevor Sie diesen Ablauf verlassen.",
    "guided_import.completion.done": "Zurück zum Arbeitsbereich",
    "guided_import.completion.eyebrow": "Geführter Import abgeschlossen",
    "guided_import.completion.imported_copy":
        "Die ausgewählten Assets befinden sich in der OAAM-Bibliothek. Dateien von KI-Programmierwerkzeugen wurden nicht geändert.",
    "guided_import.completion.imported_title": "Ausgewählte Assets wurden importiert",
    "guided_import.completion.no_content_copy":
        "OAAM hat an den ausgewählten Orten keine unterstützten Assets gefunden. Es wurden keine Dateien geändert.",
    "guided_import.completion.no_content_title": "Keine Assets zum Importieren gefunden",
    "guided_import.completion.no_selection_title": "Keine Quellen ausgewählt",
    "guided_import.completion.no_selection_copy":
        "Für diesen Import wurden keine Quellorte ausgewählt. Es wurde nichts importiert.",
    "guided_import.completion.safe_copy":
        "Der aktuelle Quellensnapshot wurde geprüft, ohne Dateien zu importieren oder bereitzustellen.",
    "guided_import.completion.safe_title": "Scanprüfung abgeschlossen",
    "guided_import.copy":
        "Wählen Sie, wo OAAM suchen darf, prüfen Sie die Funde und importieren Sie nur die ausgewählten Assets.",
    "guided_import.project_copy":
        "OAAM prüft die ausgewählten Werkzeuge, zeigt und liest in diesem Import aber nur Orte, die der aktuelle Scan exakt diesem Projekt zuordnet.",
    "guided_import.project_fallback": "dieses Projekt",
    "guided_import.project_missing_copy":
        "Die Projektliste hat sich geändert. Kehren Sie zur Asset-Bibliothek zurück und öffnen Sie den Import erneut.",
    "guided_import.project_missing_title": "Dieses Projekt ist nicht mehr verfügbar",
    "guided_import.project_scope": "Dieser Import ist auf Orte beschränkt, die dem Projekt „{project}“ zugeordnet sind.",
    "guided_import.project_title": "Assets für „{project}“ finden und importieren",
    "guided_import.change_selection": "Auswahl ändern",
    "guided_import.eyebrow": "Asset-Import",
    "guided_import.finish_without_import": "Ohne Import abschließen",
    "guided_import.navigation.label": "Navigation des geführten Imports",
    "guided_import.steps.label": "Fortschritt des geführten Imports",
    "guided_import.title": "Assets Ihrer KI-Programmierwerkzeuge finden und importieren",
    "import_journey.action.continue": "Weiter",
    "import_journey.action.review_assets": "Ausgewählte Orte scannen",
    "import_journey.action.review_sources": "Ordner auswählen",
    "import_journey.action.scan": "Scan starten",
    "import_journey.locations.copy": "Wählen Sie die Orte, die OAAM prüfen darf. In diesem Schritt wird noch nichts gescannt.",
    "import_journey.locations.eyebrow": "Schritt 1",
    "import_journey.locations.title": "Wo soll OAAM suchen?",
    "import_journey.projects.add": "Als Projekt registrieren",
    "import_journey.projects.add_failed": "OAAM konnte diesen genauen Projektordner nicht registrieren.",
    "import_journey.projects.adding": "Wird registriert…",
    "import_journey.projects.dialog.close": "Projektregistrierung schließen",
    "import_journey.projects.dialog.copy":
        "Geben Sie diesem Projekt den Namen, der in OAAM erscheinen soll. Der Ordner unten stammt aus diesem Scan.",
    "import_journey.projects.dialog.name": "Projektname",
    "import_journey.projects.dialog.path": "Projektordner",
    "import_journey.projects.dialog.register": "Projekt registrieren",
    "import_journey.projects.dialog.reveal": "Im Dateimanager anzeigen",
    "import_journey.projects.dialog.reveal_failed": "Der Projektordner konnte im Dateimanager nicht geöffnet werden.",
    "import_journey.projects.dialog.revealing": "Wird geöffnet…",
    "import_journey.projects.dialog.title": "Dieses Projekt registrieren",
    "import_journey.projects.copy":
        "Diese Ordner wurden nicht in den Quellkarten oben angezeigt. Registrieren Sie die gewünschten Projektordner oder lassen Sie sie vorerst aus.",
    "import_journey.projects.matched": "Bereits in OAAM registriert",
    "import_journey.projects.pending":
        "Registrieren Sie diesen Ordner, damit die hier gefundenen Assets zu diesem Projekt gehören.",
    "import_journey.projects.retained_pending":
        "Dieser Ordner gehört zu einem gestoppten OAAM-Projekt. Stellen Sie das Projekt wieder her, um seinen bisherigen Verlauf beizubehalten.",
    "import_journey.projects.restore": "Projekt wiederherstellen",
    "import_journey.projects.restore_failed":
        "OAAM konnte das gestoppte Projekt für diesen exakten Ordner nicht wiederherstellen.",
    "import_journey.projects.restoring": "Wird wiederhergestellt…",
    "import_journey.projects.not_now": "Jetzt nicht registrieren",
    "import_journey.projects.observation_unavailable":
        "Dieses Scanergebnis ist nicht mehr aktuell. Scannen Sie erneut, bevor Sie das Projekt registrieren.",
    "import_journey.projects.skipped": "Für diesen Import nicht registriert",
    "import_journey.projects.skipped_effect": "Projekt-Assets in diesem Ordner werden in diesem Import nicht verwendet.",
    "import_journey.projects.title": "Weitere Projektordner",
    "import_journey.projects.wait_for_other": "Schließen Sie zuerst die Registrierung des anderen Projekts ab.",
    "import_journey.projects.wrong_folder": "Wählen Sie genau diesen Ordner: {path}",
    "import_journey.results.copy":
        "Prüfen Sie die Ergebnisse der gewählten Werkzeuge, bevor Sie genaue Quellen zur Prüfung auswählen.",
    "import_journey.results.eyebrow": "Schritt 3",
    "import_journey.results.refresh": "Erneut scannen",
    "import_journey.results.title": "Scanergebnisse",
    "import_journey.sources.copy":
        "Wählen Sie die Orte für den aktuellen Scan. Gefundene Assets werden darunter zur Prüfung angezeigt.",
    "import_journey.sources.eyebrow": "Schritt 4",
    "import_journey.sources.persistence":
        "Ausgewählte Orte werden für diesen Scan verwendet und für spätere manuelle Scans gespeichert.",
    "import_journey.sources.review_copy":
        "Prüfen Sie die in diesem Scan gefundenen Orte. Wählen Sie für jede Quelle ein Ziel oder ignorieren Sie Orte, die Sie nicht verwenden möchten.",
    "import_journey.sources.review_title": "Gefundene Orte prüfen",
    "import_journey.sources.title": "Orte zum Scannen auswählen",
    "import_journey.steps.assets": "Assets prüfen",
    "import_journey.steps.complete": "Fertig",
    "import_journey.steps.content": "Inhalte auswählen",
    "import_journey.steps.locations": "Orte",
    "import_journey.steps.results": "Ergebnisse",
    "import_journey.steps.sources": "Quellen",
    "import_journey.steps.tools": "KI-Programmierwerkzeuge",
    "import_journey.tools.copy": "Wählen Sie die KI-Programmierwerkzeuge, deren Dateien OAAM an den gewählten Orten prüfen darf.",
    "import_journey.tools.eyebrow": "Schritt 2",
    "import_journey.tools.title": "Welche Werkzeuge verwenden Sie?",
} as const;

export const JAPANESE_DESKTOP_GUIDED_IMPORT_MESSAGES = {
    "discovery.ui.environment.project_choose":
        "このプロジェクトがある場所を 1 つ選択してください。今回のインポートで使用できるのは 1 つだけです。",
    "discovery.ui.environment.project_match": "このプロジェクトはここにあるため、今回のインポートではこの場所だけを使用します。",
    "discovery.ui.environment.project_mismatch": "このプロジェクトはこの場所にないため、ここでは選択できません。",
    "discovery.ui.environment.project_mismatch_tooltip":
        "別のシステム上の場所でアセットを読み書きしないよう、このプロジェクトではこの環境を選択できません。",
    "guided_import.back_to_sources": "ソースに戻る",
    "guided_import.close": "ガイド付きインポートをスキップ",
    "guided_import.close_failed": "保持中のインポートプレビューを閉じられませんでした。この手順を離れる前に再試行してください。",
    "guided_import.completion.done": "ワークスペースに戻る",
    "guided_import.completion.eyebrow": "ガイド付きインポート完了",
    "guided_import.completion.imported_copy":
        "選択した Asset は OAAM ライブラリに保存されました。AI コーディングツールが使用するファイルは変更されていません。",
    "guided_import.completion.imported_title": "選択した Asset をインポートしました",
    "guided_import.completion.no_content_copy":
        "選択した場所に、OAAM が対応している Asset は見つかりませんでした。ファイルは変更されていません。",
    "guided_import.completion.no_content_title": "インポートできる Asset はありません",
    "guided_import.completion.no_selection_title": "ソースが選択されていません",
    "guided_import.completion.no_selection_copy":
        "今回のインポートではソースの場所が選択されていません。何もインポートされていません。",
    "guided_import.completion.safe_copy":
        "ファイルをインポートまたはデプロイせずに、新しいソーススナップショットを確認しました。",
    "guided_import.completion.safe_title": "スキャン結果の確認が完了しました",
    "guided_import.copy": "OAAM が確認する場所を選び、見つかった内容を確認して、選択した Asset だけをインポートします。",
    "guided_import.project_copy":
        "OAAM は選択したツールを確認しますが、このインポートで表示・読み取りするのは、現在のスキャンでこのプロジェクトに正確に関連付けられた場所だけです。",
    "guided_import.project_fallback": "このプロジェクト",
    "guided_import.project_missing_copy":
        "プロジェクト一覧が変更されました。Asset ライブラリに戻り、もう一度インポートを開いてください。",
    "guided_import.project_missing_title": "このプロジェクトは利用できません",
    "guided_import.project_scope": "このインポートはプロジェクト「{project}」に関連付けられた場所だけを対象にします。",
    "guided_import.project_title": "「{project}」の Asset を検索してインポート",
    "guided_import.change_selection": "選択を変更",
    "guided_import.eyebrow": "Asset のインポート",
    "guided_import.finish_without_import": "インポートせずに終了",
    "guided_import.navigation.label": "ガイド付きインポートのナビゲーション",
    "guided_import.steps.label": "ガイド付きインポートの進行状況",
    "guided_import.title": "AI コーディングツールから Asset を検索してインポート",
    "import_journey.action.continue": "続ける",
    "import_journey.action.review_assets": "選択した場所をスキャン",
    "import_journey.action.review_sources": "フォルダーを選択",
    "import_journey.action.scan": "スキャンを開始",
    "import_journey.locations.copy": "OAAM が確認できる場所を選択します。この手順ではまだスキャンしません。",
    "import_journey.locations.eyebrow": "ステップ 1",
    "import_journey.locations.title": "OAAM はどこを確認しますか？",
    "import_journey.projects.add": "プロジェクトとして登録",
    "import_journey.projects.add_failed": "この正確なプロジェクトフォルダーを登録できませんでした。",
    "import_journey.projects.adding": "登録中…",
    "import_journey.projects.dialog.close": "プロジェクト登録を閉じる",
    "import_journey.projects.dialog.copy":
        "OAAM に表示するプロジェクト名を付けてください。下のフォルダーは今回のスキャンで見つかりました。",
    "import_journey.projects.dialog.name": "プロジェクト名",
    "import_journey.projects.dialog.path": "プロジェクトフォルダー",
    "import_journey.projects.dialog.register": "プロジェクトを登録",
    "import_journey.projects.dialog.reveal": "ファイルマネージャーで表示",
    "import_journey.projects.dialog.reveal_failed": "ファイルマネージャーでプロジェクトフォルダーを開けませんでした。",
    "import_journey.projects.dialog.revealing": "開いています…",
    "import_journey.projects.dialog.title": "このプロジェクトを登録",
    "import_journey.projects.copy":
        "上のソースカードに表示されなかったフォルダーです。必要なものをプロジェクトとして登録するか、今回は登録せずに進めます。",
    "import_journey.projects.matched": "OAAM に登録済み",
    "import_journey.projects.pending": "このフォルダーを登録すると、ここで見つかった Asset がこのプロジェクトに入ります。",
    "import_journey.projects.retained_pending":
        "このフォルダーは管理を停止した OAAM プロジェクトに属しています。既存の履歴を保つには、そのプロジェクトを復元してください。",
    "import_journey.projects.restore": "プロジェクトを復元",
    "import_journey.projects.restore_failed": "この正確なフォルダーの停止済みプロジェクトを復元できませんでした。",
    "import_journey.projects.restoring": "復元しています…",
    "import_journey.projects.not_now": "今回は登録しない",
    "import_journey.projects.observation_unavailable":
        "このスキャン結果は最新ではありません。プロジェクトを登録する前に再スキャンしてください。",
    "import_journey.projects.skipped": "今回は未登録",
    "import_journey.projects.skipped_effect": "このフォルダーのプロジェクト用 Asset は今回のインポートでは使用しません。",
    "import_journey.projects.title": "その他のプロジェクトフォルダー",
    "import_journey.projects.wait_for_other": "先に別のプロジェクトの登録を完了してください。",
    "import_journey.projects.wrong_folder": "この正確なフォルダーを選択してください: {path}",
    "import_journey.results.copy": "確認するソースを選ぶ前に、選択した各ツールの結果を確認します。",
    "import_journey.results.eyebrow": "ステップ 3",
    "import_journey.results.refresh": "もう一度スキャン",
    "import_journey.results.title": "スキャン結果",
    "import_journey.sources.copy": "今回スキャンする場所を選択します。見つかった Asset は下に表示され、続けて確認できます。",
    "import_journey.sources.eyebrow": "ステップ 4",
    "import_journey.sources.persistence": "選択した場所は今回のスキャンに使用され、今後の手動スキャン用に保存されます。",
    "import_journey.sources.review_copy":
        "今回のスキャンで見つかった場所を確認します。各ソースの保存先を選ぶか、使用しない場所を無視してください。",
    "import_journey.sources.review_title": "見つかった場所を確認",
    "import_journey.sources.title": "スキャンする場所を選択",
    "import_journey.steps.assets": "Asset を確認",
    "import_journey.steps.complete": "完了",
    "import_journey.steps.content": "内容を選択",
    "import_journey.steps.locations": "場所",
    "import_journey.steps.results": "結果",
    "import_journey.steps.sources": "ソース",
    "import_journey.steps.tools": "AI コーディングツール",
    "import_journey.tools.copy": "選択した場所で OAAM がファイルを確認できる AI コーディングツールを選びます。",
    "import_journey.tools.eyebrow": "ステップ 2",
    "import_journey.tools.title": "どのツールを使用していますか？",
} as const;

export const SIMPLIFIED_CHINESE_DESKTOP_GUIDED_IMPORT_MESSAGES = {
    "discovery.ui.environment.project_choose": "请选择实际包含这个项目的一个位置；本次只能选择一个。",
    "discovery.ui.environment.project_match": "这个项目在这里，本次只从这个位置查找。",
    "discovery.ui.environment.project_mismatch": "这个项目不在这里，因此不能选择这个位置。",
    "discovery.ui.environment.project_mismatch_tooltip": "为避免在错误的系统位置读取或写入资产，这个项目不能使用此环境。",
    "guided_import.back_to_sources": "返回来源",
    "guided_import.close": "跳过引导",
    "guided_import.close_failed": "无法关闭当前保留的导入预览。请重试后再离开此流程。",
    "guided_import.completion.done": "返回工作区",
    "guided_import.completion.eyebrow": "引导导入已完成",
    "guided_import.completion.imported_copy": "所选资产已进入 OAAM 资产库，没有改动项目文件或工具配置文件。",
    "guided_import.completion.imported_title": "已导入所选资产",
    "guided_import.completion.no_content_copy": "在所选位置中没有找到 OAAM 支持的资产，任何文件都没有被改动。",
    "guided_import.completion.no_content_title": "没有可导入的资产",
    "guided_import.completion.no_selection_title": "本次未选择导入来源",
    "guided_import.completion.no_selection_copy": "本次没有选择要导入的来源位置，未导入任何资产。",
    "guided_import.completion.safe_copy": "已检查最新来源快照，没有导入或部署任何文件。",
    "guided_import.completion.safe_title": "来源检查已完成",
    "guided_import.copy": "选择 OAAM 可以查看的位置，核对发现内容，然后只导入你选中的资产。",
    "guided_import.project_copy": "OAAM 会检查你选择的工具，但本次只展示和读取扫描结果中与这个项目精确对应的位置。",
    "guided_import.project_fallback": "当前项目",
    "guided_import.project_missing_copy": "项目列表已经变化。请返回资产库，再从该项目重新打开导入。",
    "guided_import.project_missing_title": "这个项目已不可用",
    "guided_import.project_scope": "本次只处理与“{project}”对应的位置。",
    "guided_import.project_title": "为“{project}”查找并导入资产",
    "guided_import.change_selection": "修改选择",
    "guided_import.eyebrow": "资产导入",
    "guided_import.finish_without_import": "不导入并完成",
    "guided_import.navigation.label": "引导导入导航",
    "guided_import.steps.label": "引导导入进度",
    "guided_import.title": "从 Claude Code、Codex 等工具导入资产",
    "import_journey.action.continue": "继续",
    "import_journey.action.review_assets": "扫描所选位置",
    "import_journey.action.review_sources": "选择文件夹",
    "import_journey.action.scan": "开始扫描",
    "import_journey.locations.copy": "选择 OAAM 可以查看的位置。这一步不会开始扫描。",
    "import_journey.locations.eyebrow": "第 1 步",
    "import_journey.locations.title": "希望 OAAM 在哪里查找？",
    "import_journey.projects.add": "登记为项目",
    "import_journey.projects.add_failed": "无法将这个确切文件夹登记为项目。",
    "import_journey.projects.adding": "正在登记…",
    "import_journey.projects.dialog.close": "关闭项目登记",
    "import_journey.projects.dialog.copy": "为这个项目设置在 OAAM 中显示的名称。下方文件夹来自刚才的扫描。",
    "import_journey.projects.dialog.name": "项目名称",
    "import_journey.projects.dialog.path": "项目文件夹",
    "import_journey.projects.dialog.register": "登记项目",
    "import_journey.projects.dialog.reveal": "在文件管理器中查看",
    "import_journey.projects.dialog.reveal_failed": "无法在文件管理器中打开项目文件夹。",
    "import_journey.projects.dialog.revealing": "正在打开…",
    "import_journey.projects.dialog.title": "登记这个项目",
    "import_journey.projects.copy": "这些文件夹没有显示在上面的来源卡片中。需要的可以登记为项目，这次不处理的可以先跳过。",
    "import_journey.projects.matched": "已在 OAAM 中登记",
    "import_journey.projects.pending": "登记这个文件夹后，这里发现的项目资产会归入该项目。",
    "import_journey.projects.retained_pending": "这个文件夹对应一个已停止管理的项目。恢复原项目即可保留既有历史。",
    "import_journey.projects.restore": "恢复项目",
    "import_journey.projects.restore_failed": "无法恢复与这个确切文件夹对应的已停止项目。",
    "import_journey.projects.restoring": "正在恢复…",
    "import_journey.projects.not_now": "这次不登记",
    "import_journey.projects.observation_unavailable": "这次扫描结果已经失效。请重新扫描后再登记项目。",
    "import_journey.projects.skipped": "本次未登记",
    "import_journey.projects.skipped_effect": "这个文件夹中的项目资产不会在本次导入中使用。",
    "import_journey.projects.title": "其他项目文件夹",
    "import_journey.projects.wait_for_other": "请先完成另一个项目的登记。",
    "import_journey.projects.wrong_folder": "请选择这个确切文件夹：{path}",
    "import_journey.results.copy": "先查看每个所选工具报告的结果，再决定审查哪些具体来源。",
    "import_journey.results.eyebrow": "第 3 步",
    "import_journey.results.refresh": "重新扫描",
    "import_journey.results.title": "扫描结果",
    "import_journey.sources.copy": "选择本次要扫描的位置。扫描后，发现的资产会继续显示在本页供你审查。",
    "import_journey.sources.eyebrow": "第 4 步",
    "import_journey.sources.persistence": "所选位置会用于本次扫描，并保存为以后手动扫描的位置。",
    "import_journey.sources.review_copy": "审查本次扫描发现的位置。为每个来源选择保存位置，或忽略不想使用的位置。",
    "import_journey.sources.review_title": "审查发现的位置",
    "import_journey.sources.title": "选择要扫描的位置",
    "import_journey.steps.assets": "审查资产",
    "import_journey.steps.complete": "完成",
    "import_journey.steps.content": "选择内容",
    "import_journey.steps.locations": "选择位置",
    "import_journey.steps.results": "扫描结果",
    "import_journey.steps.sources": "审查来源",
    "import_journey.steps.tools": "工具",
    "import_journey.tools.copy": "选择你使用的工具，OAAM 只会在刚才选择的位置查看它们的文件。",
    "import_journey.tools.eyebrow": "第 2 步",
    "import_journey.tools.title": "你使用哪些工具？",
} as const;
