export const ENGLISH_DESKTOP_LIBRARY_SOURCE_MESSAGES = {
    "library.import_sources": "Import from existing tools",
    "library.import_project_sources": "Find Assets for this Project",
    "library.assets.search_global_placeholder": "Search Global assets",
    "library.assets.search_project_placeholder": "Search assets in this Project",
    "library.global.help":
        "Saved in OAAM's Global asset library for reuse across Projects. This does not write to any AI coding tool automatically.",
    "library.kind.guidance": "Guidance",
    "library.kind.guidance_help":
        "Instructions that tell AI how to work in a Project. Common files include AGENTS.md and CLAUDE.md.",
    "library.kind.memory": "Memory",
    "library.kind.memory_help": "Facts and context retained for use in later work.",
    "library.kind.rule": "Rules",
    "library.kind.rule_help": "Instructions that apply under specific paths, models, or activation conditions.",
    "library.kind.skill": "Skills",
    "library.kind.skill_help": "Reusable instruction bundles that may include supporting files and resources.",
    "library.kind.subagent": "Subagents",
    "library.kind.subagent_help": "Definitions for specialized helper agents with their own instructions and tools.",
    "library.kind.workflow": "Workflows",
    "library.kind.workflow_help": "Reusable multi-step procedures for completing a task.",
    "library.tree.all_assets": "All assets",
    "library.tree.global_assets": "Global assets",
    "library.tree.label": "Asset library",
    "library.tree.projects": "Projects",
    "library.projects.manage": "Manage {project}",
    "library.projects.more_actions": "More actions",
    "library.targets.help":
        "OAAM can generate and write files for: {targets}. This does not mean the tool is installed or its current path is ready.",
    "library.targets.loading": "Checking write support…",
    "library.targets.less": "Show fewer",
    "library.targets.more": "+{count}",
    "library.targets.none": "Cannot currently write to AI tools",
    "library.targets.prefix": "Can write to",
    "library.targets.unavailable": "Cannot check write support right now",
    "sources.back_to_library": "Back to asset library",
    "sources.changed": "Saved search locations changed. Refresh before using the current information.",
    "sources.clear_search": "Clear search",
    "sources.destination": "Future manual imports",
    "sources.destination_column": "Import to",
    "sources.destination.global": "Global asset library",
    "sources.destination.project": "Project: {project}",
    "sources.destination.unknown_project": "Unavailable project",
    "sources.columns.location": "Location",
    "sources.empty_copy": "Add locations for OAAM to check during future manual searches.",
    "sources.empty_title": "No locations included in searches",
    "sources.environment.local": "This device",
    "sources.environment.linux": "Linux",
    "sources.environment.mac": "macOS",
    "sources.environment.windows": "Windows",
    "sources.environment.wsl": "WSL · {distribution}",
    "sources.environment.count": "Locations: {count}",
    "sources.eyebrow": "Asset search locations",
    "sources.failed_title": "Search locations are unavailable",
    "sources.find_assets": "Find assets",
    "sources.folder": "Search location",
    "sources.load_failed": "OAAM could not load the saved search locations.",
    "sources.load_interrupted": "The search-location connection ended before loading completed.",
    "sources.loading": "Loading search locations…",
    "sources.loading_title": "Loading asset search locations",
    "sources.no_match_copy": "Try another tool name, location, or path.",
    "sources.no_match_title": "No matching locations",
    "sources.open_details": "View details",
    "sources.open_location": "Open {location}, used by {tools}, importing to {destination}",
    "sources.operation_unavailable": "This OAAM build cannot list saved search locations.",
    "sources.path": "Folder",
    "sources.refresh": "Refresh search locations",
    "sources.refresh_required": "Refresh changed search locations",
    "sources.search": "Search locations",
    "sources.search_placeholder": "Tool, location, or path",
    "sources.title": "Asset search locations",
    "sources.tool.unknown": "Unavailable tool",
    "sources.tools": "Used by",
    "sources.tree.all": "All locations",
    "sources.tree.collapse": "Collapse {environment}",
    "sources.tree.expand": "Expand {environment}",
    "sources.tree.label": "Asset search location navigation",
    "sources.workspace.label": "Asset search locations",
} as const;

type DesktopLibrarySourceMessageId = keyof typeof ENGLISH_DESKTOP_LIBRARY_SOURCE_MESSAGES;
type DesktopLibrarySourceMessages = Readonly<Record<DesktopLibrarySourceMessageId, string>>;

export const GERMAN_DESKTOP_LIBRARY_SOURCE_MESSAGES = {
    "library.import_sources": "Aus vorhandenen Tools importieren",
    "library.import_project_sources": "Assets für dieses Projekt suchen",
    "library.assets.search_global_placeholder": "Globale Assets durchsuchen",
    "library.assets.search_project_placeholder": "Assets in diesem Projekt durchsuchen",
    "library.global.help":
        "In OAAMs globaler Asset-Bibliothek gespeichert und projektübergreifend wiederverwendbar. Es wird nichts automatisch in KI-Programmierwerkzeuge geschrieben.",
    "library.kind.guidance": "Anweisungen",
    "library.kind.guidance_help":
        "Anweisungen für die Arbeit der KI in einem Projekt. Häufige Dateien sind AGENTS.md und CLAUDE.md.",
    "library.kind.memory": "Erinnerungen",
    "library.kind.memory_help": "Fakten und Kontext, die für spätere Arbeiten aufbewahrt werden.",
    "library.kind.rule": "Regeln",
    "library.kind.rule_help": "Anweisungen für bestimmte Pfade, Modelle oder Aktivierungsbedingungen.",
    "library.kind.skill": "Skills",
    "library.kind.skill_help": "Wiederverwendbare Anweisungspakete mit möglichen Begleitdateien und Ressourcen.",
    "library.kind.subagent": "Subagents",
    "library.kind.subagent_help": "Definitionen spezialisierter Hilfsagenten mit eigenen Anweisungen und Werkzeugen.",
    "library.kind.workflow": "Workflows",
    "library.kind.workflow_help": "Wiederverwendbare mehrstufige Abläufe zum Erledigen einer Aufgabe.",
    "library.tree.all_assets": "Alle Assets",
    "library.tree.global_assets": "Globale Assets",
    "library.tree.label": "Asset-Bibliothek",
    "library.tree.projects": "Projekte",
    "library.projects.manage": "{project} verwalten",
    "library.projects.more_actions": "Weitere Aktionen",
    "library.targets.help":
        "OAAM kann Dateien erzeugen und schreiben für: {targets}. Dies bedeutet nicht, dass das Tool installiert oder sein aktueller Pfad bereit ist.",
    "library.targets.loading": "Schreibunterstützung wird geprüft…",
    "library.targets.less": "Weniger anzeigen",
    "library.targets.more": "+{count}",
    "library.targets.none": "Derzeit kann nicht in KI-Tools geschrieben werden",
    "library.targets.prefix": "Schreibbar in",
    "library.targets.unavailable": "Schreibunterstützung kann derzeit nicht geprüft werden",
    "sources.back_to_library": "Zurück zur Asset-Bibliothek",
    "sources.changed": "Gespeicherte Suchorte wurden geändert. Aktualisieren Sie die Ansicht.",
    "sources.clear_search": "Suche löschen",
    "sources.destination": "Ziel künftiger manueller Importe",
    "sources.destination_column": "Importieren nach",
    "sources.destination.global": "Globale Asset-Bibliothek",
    "sources.destination.project": "Projekt: {project}",
    "sources.destination.unknown_project": "Nicht verfügbares Projekt",
    "sources.columns.location": "Ort",
    "sources.empty_copy": "Fügen Sie Orte hinzu, die OAAM bei künftigen manuellen Suchen prüfen soll.",
    "sources.empty_title": "Keine Orte für die Suche ausgewählt",
    "sources.environment.local": "Dieses Gerät",
    "sources.environment.linux": "Linux",
    "sources.environment.mac": "macOS",
    "sources.environment.windows": "Windows",
    "sources.environment.wsl": "WSL · {distribution}",
    "sources.environment.count": "Orte: {count}",
    "sources.eyebrow": "Asset-Suchorte",
    "sources.failed_title": "Suchorte sind nicht verfügbar",
    "sources.find_assets": "Assets suchen",
    "sources.folder": "Suchort",
    "sources.load_failed": "OAAM konnte die gespeicherten Suchorte nicht laden.",
    "sources.load_interrupted": "Die Verbindung wurde vor Abschluss des Ladens beendet.",
    "sources.loading": "Suchorte werden geladen…",
    "sources.loading_title": "Asset-Suchorte werden geladen",
    "sources.no_match_copy": "Versuchen Sie einen anderen Toolnamen, Ort oder Pfad.",
    "sources.no_match_title": "Keine passenden Orte",
    "sources.open_details": "Details anzeigen",
    "sources.open_location": "{location} öffnen; verwendet von {tools}; Import nach {destination}",
    "sources.operation_unavailable": "Diese OAAM-Version kann gespeicherte Suchorte nicht auflisten.",
    "sources.path": "Ordner",
    "sources.refresh": "Suchorte aktualisieren",
    "sources.refresh_required": "Geänderte Suchorte aktualisieren",
    "sources.search": "Suchorte durchsuchen",
    "sources.search_placeholder": "Tool, Ort oder Pfad",
    "sources.title": "Asset-Suchorte",
    "sources.tool.unknown": "Nicht verfügbares Tool",
    "sources.tools": "Verwendet von",
    "sources.tree.all": "Alle Orte",
    "sources.tree.collapse": "{environment} einklappen",
    "sources.tree.expand": "{environment} ausklappen",
    "sources.tree.label": "Navigation der Asset-Suchorte",
    "sources.workspace.label": "Asset-Suchorte",
} as const satisfies DesktopLibrarySourceMessages;

export const JAPANESE_DESKTOP_LIBRARY_SOURCE_MESSAGES = {
    "library.import_sources": "既存のツールからアセットをインポート",
    "library.import_project_sources": "このプロジェクトの Asset を検索",
    "library.assets.search_global_placeholder": "グローバルアセットを検索",
    "library.assets.search_project_placeholder": "このプロジェクトのアセットを検索",
    "library.global.help":
        "OAAM のグローバルアセットライブラリに保存され、複数のプロジェクトで再利用できます。AI コーディングツールへ自動的に書き込まれることはありません。",
    "library.kind.guidance": "ガイダンス",
    "library.kind.guidance_help":
        "プロジェクトでの AI の動作を伝える指示です。一般的なファイルには AGENTS.md と CLAUDE.md があります。",
    "library.kind.memory": "メモリ",
    "library.kind.memory_help": "今後の作業で使うために保持される事実とコンテキストです。",
    "library.kind.rule": "ルール",
    "library.kind.rule_help": "特定のパス、モデル、または有効化条件で適用される指示です。",
    "library.kind.skill": "スキル",
    "library.kind.skill_help": "補助ファイルやリソースを含められる再利用可能な指示セットです。",
    "library.kind.subagent": "サブエージェント",
    "library.kind.subagent_help": "独自の指示とツールを持つ専門ヘルパーエージェントの定義です。",
    "library.kind.workflow": "ワークフロー",
    "library.kind.workflow_help": "タスクを完了するための再利用可能な複数手順です。",
    "library.tree.all_assets": "すべてのアセット",
    "library.tree.global_assets": "グローバルアセット",
    "library.tree.label": "アセットライブラリ",
    "library.tree.projects": "プロジェクト",
    "library.projects.manage": "{project} を管理",
    "library.projects.more_actions": "その他の操作",
    "library.targets.help":
        "OAAM は次のツール用ファイルを生成して書き込めます：{targets}。ツールのインストールや現在のパス利用可否は示しません。",
    "library.targets.loading": "書き込み対応を確認中…",
    "library.targets.less": "折りたたむ",
    "library.targets.more": "ほか {count} 件",
    "library.targets.none": "現在は AI ツールへ書き込めません",
    "library.targets.prefix": "書き込み先",
    "library.targets.unavailable": "現在は書き込み対応を確認できません",
    "sources.back_to_library": "アセットライブラリに戻る",
    "sources.changed": "保存済みの検索場所が変更されました。現在の情報を使う前に更新してください。",
    "sources.clear_search": "検索をクリア",
    "sources.destination": "今後の手動インポート先",
    "sources.destination_column": "インポート先",
    "sources.destination.global": "グローバルアセットライブラリ",
    "sources.destination.project": "プロジェクト：{project}",
    "sources.destination.unknown_project": "利用できないプロジェクト",
    "sources.columns.location": "場所",
    "sources.empty_copy": "今後の手動検索で OAAM が確認する場所を追加します。",
    "sources.empty_title": "検索対象に含まれる場所はありません",
    "sources.environment.local": "このデバイス",
    "sources.environment.linux": "Linux",
    "sources.environment.mac": "macOS",
    "sources.environment.windows": "Windows",
    "sources.environment.wsl": "WSL · {distribution}",
    "sources.environment.count": "{count} 個の場所",
    "sources.eyebrow": "アセットの検索場所",
    "sources.failed_title": "検索場所を利用できません",
    "sources.find_assets": "アセットを検索",
    "sources.folder": "検索場所",
    "sources.load_failed": "保存済みの検索場所を読み込めませんでした。",
    "sources.load_interrupted": "検索場所の読み込みが完了する前に接続が終了しました。",
    "sources.loading": "検索場所を読み込み中…",
    "sources.loading_title": "アセットの検索場所を読み込み中",
    "sources.no_match_copy": "別のツール名、場所、またはパスをお試しください。",
    "sources.no_match_title": "一致する場所はありません",
    "sources.open_details": "詳細を表示",
    "sources.open_location": "{location} を開く。使用ツール：{tools}。インポート先：{destination}",
    "sources.operation_unavailable": "この OAAM ビルドでは保存済みの検索場所を一覧表示できません。",
    "sources.path": "フォルダー",
    "sources.refresh": "検索場所を更新",
    "sources.refresh_required": "変更された検索場所を更新",
    "sources.search": "場所を検索",
    "sources.search_placeholder": "ツール、場所、またはパス",
    "sources.title": "アセットの検索場所",
    "sources.tool.unknown": "利用できないツール",
    "sources.tools": "使用するツール",
    "sources.tree.all": "すべての場所",
    "sources.tree.collapse": "{environment} を折りたたむ",
    "sources.tree.expand": "{environment} を展開",
    "sources.tree.label": "アセット検索場所のナビゲーション",
    "sources.workspace.label": "アセットの検索場所",
} as const satisfies DesktopLibrarySourceMessages;

export const SIMPLIFIED_CHINESE_DESKTOP_LIBRARY_SOURCE_MESSAGES = {
    "library.import_sources": "从现有工具导入资产",
    "library.import_project_sources": "查找此项目的资产",
    "library.assets.search_global_placeholder": "搜索全局资产",
    "library.assets.search_project_placeholder": "搜索此项目的资产",
    "library.global.help": "保存在 OAAM 的全局资产库，可供多个项目使用；不会自动写入任何 AI 工具。",
    "library.kind.guidance": "指引",
    "library.kind.guidance_help": "用于告诉 AI 如何在项目中工作的说明，常见文件包括 AGENTS.md、CLAUDE.md。",
    "library.kind.memory": "记忆",
    "library.kind.memory_help": "为以后工作保留的事实和上下文。",
    "library.kind.rule": "规则",
    "library.kind.rule_help": "在特定路径、模型或启用条件下生效的说明。",
    "library.kind.skill": "技能",
    "library.kind.skill_help": "可重复使用的一组说明，也可以包含配套文件和资源。",
    "library.kind.subagent": "子代理",
    "library.kind.subagent_help": "具有独立说明和工具的专用辅助代理定义。",
    "library.kind.workflow": "工作流",
    "library.kind.workflow_help": "用于完成任务、可重复使用的多步骤流程。",
    "library.tree.all_assets": "全部资产",
    "library.tree.global_assets": "全局资产",
    "library.tree.label": "资产库",
    "library.tree.projects": "项目",
    "library.projects.manage": "管理{project}",
    "library.projects.more_actions": "更多操作",
    "library.targets.help": "OAAM 可以为这些工具生成并写入文件：{targets}。这不代表本机已安装或当前路径可用。",
    "library.targets.loading": "正在检查写入支持…",
    "library.targets.less": "收起",
    "library.targets.more": "另有 {count} 个",
    "library.targets.none": "目前不能写入 AI 工具",
    "library.targets.prefix": "可写入",
    "library.targets.unavailable": "暂时无法检查写入支持",
    "sources.back_to_library": "返回资产库",
    "sources.changed": "已保存的查找位置发生变化，请刷新后再使用当前信息。",
    "sources.clear_search": "清除搜索",
    "sources.destination": "以后手动导入到",
    "sources.destination_column": "导入到",
    "sources.destination.global": "全局资产库",
    "sources.destination.project": "项目：{project}",
    "sources.destination.unknown_project": "当前不可用的项目",
    "sources.columns.location": "位置",
    "sources.empty_copy": "添加 OAAM 在以后手动查找时需要检查的位置。",
    "sources.empty_title": "尚未纳入任何查找位置",
    "sources.environment.local": "本机",
    "sources.environment.linux": "Linux",
    "sources.environment.mac": "macOS",
    "sources.environment.windows": "Windows",
    "sources.environment.wsl": "WSL · {distribution}",
    "sources.environment.count": "{count} 个位置",
    "sources.eyebrow": "资产查找位置",
    "sources.failed_title": "无法查看查找位置",
    "sources.find_assets": "查找资产",
    "sources.folder": "查找位置",
    "sources.load_failed": "OAAM 无法加载已保存的查找位置。",
    "sources.load_interrupted": "查找位置加载完成前连接已中断。",
    "sources.loading": "正在加载查找位置…",
    "sources.loading_title": "正在加载资产查找位置",
    "sources.no_match_copy": "请尝试其他工具名称、位置或路径。",
    "sources.no_match_title": "没有匹配的位置",
    "sources.open_details": "查看详情",
    "sources.open_location": "打开{location}，由{tools}使用，导入到{destination}",
    "sources.operation_unavailable": "当前版本的 OAAM 无法列出已保存的查找位置。",
    "sources.path": "文件夹",
    "sources.refresh": "刷新查找位置",
    "sources.refresh_required": "刷新已变化的查找位置",
    "sources.search": "搜索查找位置",
    "sources.search_placeholder": "工具、位置或路径",
    "sources.title": "资产查找位置",
    "sources.tool.unknown": "当前不可用的工具",
    "sources.tools": "使用此文件夹的工具",
    "sources.tree.all": "全部位置",
    "sources.tree.collapse": "折叠{environment}",
    "sources.tree.expand": "展开{environment}",
    "sources.tree.label": "资产查找位置导航",
    "sources.workspace.label": "资产查找位置",
} as const satisfies DesktopLibrarySourceMessages;
